ANP – astro-fortran
ANP Function
7 statements
Source File
public function ANP(a) result(w)
Normalize angle into the range 0 <= A < 2pi.
Status: vector/matrix support routine.
History
IAU SOFA revision: 2000 December 15
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: a
angle (radians)
Return Value real(kind=wp)
angle in range 0-2pi
Called by
Contents
Source Code
ANP
Source Code
    function ANP ( a ) result(w)
    implicit none
    real(wp),intent(in) :: a !! angle (radians)
    real(wp) :: w !! angle in range 0-2pi
    w = mod(a,d2pi)
    if ( w < 0.0_wp ) w = w + d2pi
    end function ANP
Call graph
aticq calls anp
gmst00 calls anp, era00
hfk5z calls anp
gst94 calls anp, gmst82
icrs2g calls anp
atioq calls anp
g2icrs calls anp
atciq calls anp
atciqz calls anp
gst00b calls anp, gmst00
eceq06 calls anp
lteqec calls anp
era00 calls anp
lteceq calls anp
aticqn calls anp
fk524 calls anp
tpsts calls anp
fk54z calls anp, fk524
gst00a calls anp, gmst00
atoiq calls anp
eqec06 calls anp
gmst06 calls anp, era00
fk425 calls anp
pvstar calls anp
tpors calls anp
atciqn calls anp
fk5hz calls anp
fk45z calls anp
gst06 calls anp, era00
gmst82 calls anp
c2t06a calls era00
c2txy calls era00
apco13 calls era00
apio13 calls era00
c2t00b calls era00
c2t00a calls era00
atoi13 calls atoiq, apio13
fk52h calls pvstar
atio13 calls atioq, apio13
h2fk5 calls pvstar
atic13 calls aticq
aper13 calls era00
atco13 calls atioq, atciq, apco13
starpm calls pvstar
ee06a calls gmst06, gst06a
c2tpe calls gmst00
gst06a calls gst06
atoc13 calls aticq, atoiq, apco13
atci13 calls atciq
pmsafe calls starpm