ANPM – astro-fortran
ANPM Function
7 statements
Source File
public function ANPM(a) result(w)
Normalize angle into the range -pi <= A < +pi.
Status: vector/matrix support routine.
History
IAU SOFA revision: 2000 November 25
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: a
angle (radians)
Return Value real(kind=wp)
angle in range +/-pi
Called by
Contents
Source Code
ANPM
Source Code
    function ANPM ( a ) result(w)
    implicit none
    real(wp),intent(in) :: a !! angle (radians)
    real(wp) :: w !! angle in range +/-pi
    w = mod(a,d2pi)
    if ( abs(w) >= dpi ) w = w - sign(d2pi,a)
    end function ANPM
Call graph
nut80 calls anpm
plan94 calls anpm
ee06a calls anpm
eqeq94 calls anpm, nut80
eceq06 calls anpm
lteqec calls anpm
icrs2g calls anpm
lteceq calls anpm
eqec06 calls anpm
g2icrs calls anpm
nutm80 calls nut80
gst94 calls eqeq94
pnm80 calls nutm80