APCI13 – astro-fortran
APCI13 Subroutine
15 statements
Source File
public subroutine APCI13(date1, date2, astrom, eo)
For a terrestrial observer, prepare star-independent astrometry parameters for transformations between ICRS and geocentric CIRS coordinates. The caller supplies the date, and SOFA models are used to predict the Earth ephemeris and CIP/CIO.
The parameters produced by this routine are required in the parallax, light deflection, aberration, and bias-precession-nutation parts of the astrometric transformation chain.
Status: support routine.
Notes
The TDB date DATE1+DATE2 is a Julian Date, apportioned in any convenient way between the two arguments. For example, JD(TDB)=2450123.7 could be expressed in any of these ways, among others:
    DATE1          DATE2
 2450123.7D0        0D0        (JD method)
  2451545D0      -1421.3D0     (J2000 method)
 2400000.5D0     50123.2D0     (MJD method)
 2450123.5D0       0.2D0       (date & time method)
The JD method is the most natural and convenient to use in cases where the loss of several decimal digits of resolution is acceptable. The J2000 method is best matched to the way the argument is handled internally and will deliver the optimum resolution. The MJD method and the date & time methods are both good compromises between resolution and convenience. For most applications of this routine the choice will not be at all critical.
TT can be used instead of TDB without any significant impact on accuracy.
All the vectors are with respect to BCRS axes.
In cases where the caller wishes to supply his own Earth ephemeris and CIP/CIO, the routine APCI can be used instead of the present routine.
This is one of several routines that inserts into the ASTROM array star-independent parameters needed for the chain of astrometric transformations ICRS <-> GCRS <-> CIRS <-> observed.
The various routines support different classes of observer and portions of the transformation chain:
    routines           observer        transformation
APCG APCG13    geocentric      ICRS <-> GCRS
APCI APCI13    terrestrial     ICRS <-> CIRS
APCO APCO13    terrestrial     ICRS <-> observed
APCS APCS13    space           ICRS <-> GCRS
APER APER13    terrestrial     update Earth rotation
APIO APIO13    terrestrial     CIRS <-> observed
Those with names ending in "13" use contemporary SOFA models to compute the various ephemerides. The others accept ephemerides supplied by the caller.
The transformation from ICRS to GCRS covers space motion, parallax, light deflection, and aberration. From GCRS to CIRS comprises frame bias and precession-nutation. From CIRS to observed takes account of Earth rotation, polar motion, diurnal aberration and parallax (unless subsumed into the ICRS <-> GCRS transformation), and atmospheric refraction.
The context array ASTROM produced by this routine is used by ATCIQ and ATICQ.
History
IAU SOFA revision: 2017 March 12
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: date1
TDB as a 2-part...
real(kind=wp), intent(in) :: date2
real(kind=wp), intent(inout), dimension(30) :: astrom
star-independent astrometry parameters:
(1) PM time interval (SSB, Julian years) (2-4) SSB to observer (vector, au) (5-7) Sun to observer (unit vector) (8) distance from Sun to observer (au) (9-11) v: barycentric observer velocity (vector, c) (12) sqrt(1-|v|^2): reciprocal of Lorenz factor (13-21) bias-precession-nutation matrix (22) unchanged (23) unchanged (24) unchanged (25) unchanged (26) unchanged (27) unchanged (28) unchanged (29) unchanged (30) unchanged
real(kind=wp), intent(out) :: eo
equation of the origins (ERA-GST)
Calls
Called by
Contents
Source Code
APCI13
Source Code
    subroutine APCI13 ( date1, date2, astrom, eo )
    implicit none
    real(wp),intent(in) :: date1 !! TDB as a 2-part...
    real(wp),intent(in) :: date2 !! ...Julian Date (Note 1)
    real(wp),dimension(30),intent(inout) :: astrom !! star-independent astrometry parameters:
                                                   !!
                                                   !! (1)      PM time interval (SSB, Julian years)
                                                   !! (2-4)    SSB to observer (vector, au)
                                                   !! (5-7)    Sun to observer (unit vector)
                                                   !! (8)      distance from Sun to observer (au)
                                                   !! (9-11)   v: barycentric observer velocity (vector, c)
                                                   !! (12)     sqrt(1-|v|^2): reciprocal of Lorenz factor
                                                   !! (13-21)  bias-precession-nutation matrix
                                                   !! (22)     unchanged
                                                   !! (23)     unchanged
                                                   !! (24)     unchanged
                                                   !! (25)     unchanged
                                                   !! (26)     unchanged
                                                   !! (27)     unchanged
                                                   !! (28)     unchanged
                                                   !! (29)     unchanged
                                                   !! (30)     unchanged
    real(wp),intent(out) :: eo !! equation of the origins (ERA-GST)
    integer :: j
    real(wp) :: pvh(3,2), pvb(3,2), r(3,3), x, y, s
    !  Earth barycentric & heliocentric position/velocity (au, au/d).
    call EPV00 ( date1, date2, pvh, pvb, j )
    !  Form the equinox based BPN matrix, IAU 2006/2000A.
    call PNM06A ( date1, date2, r )
    !  Extract CIP X,Y.
    call BPN2XY ( r, x, y )
    !  Obtain CIO locator s.
    s = S06 ( date1, date2, x, y )
    !  Compute the star-independent astrometry parameters.
    call APCI ( date1, date2, pvb, pvh, x, y, s, astrom )
    !  Equation of the origins.
    eo = EORS ( r, s )
    end subroutine APCI13
Call graph
apci13 calls s06, pnm06a, eors, apci, epv00, bpn2xy
s06 calls faom03, falp03, fae03, fal03, faf03, fad03, fave03, fapa03
pnm06a calls pfw06, nut06a, fw2m
apci calls c2ixys, apcg
pfw06 calls obl06
c2ixys calls ry, ir, rz
nut06a calls nut00a
fw2m calls rx, ir, rz
apcg calls zpv, apcs
nut00a calls faom03, fae03, fal03, faf03, fave03, fapa03, fame03, fasa03, faju03, fama03, faur03
zpv calls zp
apcs calls ir, pn
pn calls zp, sxp
atci13 calls apci13
atic13 calls apci13