APCO – astro-fortran
APCO Subroutine
37 statements
Source File
public subroutine APCO(date1, date2, ebpv, ehp, x, y, s, theta, elong, phi, hm, xp, yp, sp, refa, refb, astrom)
For a terrestrial observer, prepare star-independent astrometry parameters for transformations between ICRS and observed coordinates. The caller supplies the Earth ephemeris, the Earth rotation information and the refraction constants as well as the site coordinates.
Status: support routine.
Notes
The TDB date DATE1+DATE2 is a Julian Date, apportioned in any convenient way between the two arguments. For example, JD(TDB)=2450123.7 could be expressed in any of these ways, among others:
    DATE1          DATE2
 2450123.7D0        0D0        (JD method)
  2451545D0      -1421.3D0     (J2000 method)
 2400000.5D0     50123.2D0     (MJD method)
 2450123.5D0       0.2D0       (date & time method)
The JD method is the most natural and convenient to use in cases where the loss of several decimal digits of resolution is acceptable. The J2000 method is best matched to the way the argument is handled internally and will deliver the optimum resolution. The MJD method and the date & time methods are both good compromises between resolution and convenience. For most applications of this routine the choice will not be at all critical.
TT can be used instead of TDB without any significant impact on accuracy.
The vectors EB, EH, and all the ASTROM vectors, are with respect to BCRS axes.
The geographical coordinates are with respect to the WGS84 reference ellipsoid. TAKE CARE WITH THE LONGITUDE SIGN CONVENTION: the longitude required by the present routine is right-handed, i.e. east-positive, in accordance with geographical convention.
XP and YP are the coordinates (in radians) of the Celestial Intermediate Pole with respect to the International Terrestrial Reference System (see IERS Conventions), measured along the meridians 0 and 90 deg west respectively. SP is the TIO locator s', in radians, which positions the Terrestrial Intermediate Origin on the equator. For many applications, XP, YP and (especially) SP can be set to zero.
Internally, the polar motion is stored in a form rotated onto the local meridian.
The refraction constants REFA and REFB are for use in a dZ = Atan(Z)+Btan^3(Z) model, where Z is the observed (i.e. refracted) zenith distance and dZ is the amount of refraction.
It is advisable to take great care with units, as even unlikely values of the input parameters are accepted and processed in accordance with the models used.
In cases where the caller does not wish to provide the Earth Ephemeris, the Earth rotation information and refraction constants, the routine APCO13 can be used instead of the present routine. This starts from UTC and weather readings etc. and computes suitable values using other SOFA routines.
This is one of several routines that inserts into the ASTROM array star-independent parameters needed for the chain of astrometric transformations ICRS <-> GCRS <-> CIRS <-> observed.
The various routines support different classes of observer and portions of the transformation chain:
    routines           observer        transformation
APCG APCG13    geocentric      ICRS <-> GCRS
APCI APCI13    terrestrial     ICRS <-> CIRS
APCO APCO13    terrestrial     ICRS <-> observed
APCS APCS13    space           ICRS <-> GCRS
APER APER13    terrestrial     update Earth rotation
APIO APIO13    terrestrial     CIRS <-> observed
Those with names ending in "13" use contemporary SOFA models to compute the various ephemerides. The others accept ephemerides supplied by the caller.
The transformation from ICRS to GCRS covers space motion, parallax, light deflection, and aberration. From GCRS to CIRS comprises frame bias and precession-nutation. From CIRS to observed takes account of Earth rotation, polar motion, diurnal aberration and parallax (unless subsumed into the ICRS <-> GCRS transformation), and atmospheric refraction.
The context array ASTROM produced by this routine is used by ATIOQ, ATOIQ, ATCIQ, and ATICQ.
History
IAU SOFA revision: 2017 March 12
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: date1
TDB as a 2-part...
real(kind=wp), intent(in) :: date2
real(kind=wp), intent(in), dimension(3,2) :: ebpv
Earth barycentric pos/vel (au, au/day, Note 2)
real(kind=wp), intent(in), dimension(3) :: ehp
Earth heliocentric position (au, Note 2)
real(kind=wp), intent(in) :: x
CIP X (component of unit vector)
real(kind=wp), intent(in) :: y
CIP Y (component of unit vector)
real(kind=wp), intent(in) :: s
the CIO locator s (radians)
real(kind=wp), intent(in) :: theta
Earth rotation angle (radians)
real(kind=wp), intent(in) :: elong
longitude (radians, east +ve, Note 3)
real(kind=wp), intent(in) :: phi
latitude (geodetic, radians, Note 3)
real(kind=wp), intent(in) :: hm
height above ellipsoid (m, geodetic, Note 3)
real(kind=wp), intent(in) :: xp
polar motion coordinate (radians, Note 4)
real(kind=wp), intent(in) :: yp
polar motion coordinate (radians, Note 4)
real(kind=wp), intent(in) :: sp
the TIO locator s' (radians, Note 4)
real(kind=wp), intent(in) :: refa
refraction constant A (radians, Note 5)
real(kind=wp), intent(in) :: refb
refraction constant B (radians, Note 5)
real(kind=wp), intent(out), dimension(30) :: astrom
star-independent astrometry parameters:
(1) PM time interval (SSB, Julian years) (2-4) SSB to observer (vector, au) (5-7) Sun to observer (unit vector) (8) distance from Sun to observer (au) (9-11) v: barycentric observer velocity (vector, c) (12) sqrt(1-|v|^2): reciprocal of Lorenz factor (13-21) bias-precession-nutation matrix (22) longitude + s' (radians) (23) polar motion xp wrt local meridian (radians) (24) polar motion yp wrt local meridian (radians) (25) sine of geodetic latitude (26) cosine of geodetic latitude (27) magnitude of diurnal aberration vector (28) "local" Earth rotation angle (radians) (29) refraction constant A (radians) (30) refraction constant B (radians)
Calls
Called by
Contents
Source Code
APCO
Source Code
    subroutine APCO ( date1, date2, ebpv, ehp, x, y, s, &
                      theta, elong, phi, hm, xp, yp, sp, &
                      refa, refb, astrom )
    implicit none
    real(wp),intent(in) :: date1 !! TDB as a 2-part...
    real(wp),intent(in) :: date2 !! ...Julian Date (Note 1)
    real(wp),dimension(3,2),intent(in) :: ebpv !! Earth barycentric pos/vel (au, au/day, Note 2)
    real(wp),dimension(3),intent(in) :: ehp !! Earth heliocentric position (au, Note 2)
    real(wp),intent(in) :: x !! CIP X (component of unit vector)
    real(wp),intent(in) :: y !! CIP Y (component of unit vector)
    real(wp),intent(in) :: s !! the CIO locator s (radians)
    real(wp),intent(in) :: theta !! Earth rotation angle (radians)
    real(wp),intent(in) :: elong !! longitude (radians, east +ve, Note 3)
    real(wp),intent(in) :: phi !! latitude (geodetic, radians, Note 3)
    real(wp),intent(in) :: hm !! height above ellipsoid (m, geodetic, Note 3)
    real(wp),intent(in) :: xp !! polar motion coordinate (radians, Note 4)
    real(wp),intent(in) :: yp !! polar motion coordinate (radians, Note 4)
    real(wp),intent(in) :: sp !! the TIO locator s' (radians, Note 4)
    real(wp),intent(in) :: refa !! refraction constant A (radians, Note 5)
    real(wp),intent(in) :: refb !! refraction constant B (radians, Note 5)
    real(wp),dimension(30),intent(out) :: astrom !! star-independent astrometry parameters:
                                                 !!
                                                 !! (1)      PM time interval (SSB, Julian years)
                                                 !! (2-4)    SSB to observer (vector, au)
                                                 !! (5-7)    Sun to observer (unit vector)
                                                 !! (8)      distance from Sun to observer (au)
                                                 !! (9-11)   v: barycentric observer velocity (vector, c)
                                                 !! (12)     sqrt(1-|v|^2): reciprocal of Lorenz factor
                                                 !! (13-21)  bias-precession-nutation matrix
                                                 !! (22)     longitude + s' (radians)
                                                 !! (23)     polar motion xp wrt local meridian (radians)
                                                 !! (24)     polar motion yp wrt local meridian (radians)
                                                 !! (25)     sine of geodetic latitude
                                                 !! (26)     cosine of geodetic latitude
                                                 !! (27)     magnitude of diurnal aberration vector
                                                 !! (28)     "local" Earth rotation angle (radians)
                                                 !! (29)     refraction constant A (radians)
                                                 !! (30)     refraction constant B (radians)
    real(wp) :: sl, cl, r(3,3), pvc(3,2), pv(3,2)
    !  Longitude with adjustment for TIO locator s'.
    astrom(22) = elong + sp
    !  Polar motion, rotated onto the local meridian.
    sl = sin(astrom(22))
    cl = cos(astrom(22))
    astrom(23) = xp*cl - yp*sl
    astrom(24) = xp*sl + yp*cl
    !  Functions of latitude.
    astrom(25) = sin(phi)
    astrom(26) = cos(phi)
    !  Refraction constants.
    astrom(29) = refa
    astrom(30) = refb
    !  Local Earth rotation angle.
    call APER ( theta, astrom )
    !  Disable the (redundant) diurnal aberration step.
    astrom(27) = 0.0_wp
    !  CIO based BPN matrix.
    call C2IXYS ( x, y, s, r )
    !  Observer's geocentric position and velocity (m, m/s, CIRS).
    call PVTOB ( elong, phi, hm, xp, yp, sp, theta, pvc )
    !  Rotate into GCRS.
    call TRXPV ( r, pvc, pv )
    !  ICRS <-> GCRS parameters.
    call APCS ( date1, date2, pv, ebpv, ehp, astrom )
    !  Store the CIO based BPN matrix.
    call CR ( r, astrom(13) )
    end subroutine APCO
Call graph
apco calls pvtob, cr, c2ixys, aper, trxpv, apcs
pvtob calls gd2gc, pom00, trxp
c2ixys calls ry, ir, rz
trxpv calls rxpv, tr
apcs calls pn, ir
gd2gc calls gd2gce, zp, eform
rxpv calls rxp
pn calls sxp, zp
pom00 calls ry, ir, rz, rx
trxp calls tr, rxp
apco13 calls apco
atco13 calls apco13
atoc13 calls apco13