APCO13 – astro-fortran
APCO13 Subroutine
37 statements
Source File
public subroutine APCO13(utc1, utc2, dut1, elong, phi, hm, xp, yp, phpa, tc, rh, wl, astrom, eo, j)
For a terrestrial observer, prepare star-independent astrometry parameters for transformations between ICRS and observed coordinates. The caller supplies UTC, site coordinates, ambient air conditions and observing wavelength, and SOFA models are used to obtain the Earth ephemeris, CIP/CIO and refraction constants.
The parameters produced by this routine are required in the parallax, light deflection, aberration, and bias-precession-nutation parts of the ICRS/CIRS transformations.
Status: support routine.
Notes
UTC1+UTC2 is quasi Julian Date (see Note 2), apportioned in any convenient way between the two arguments, for example where UTC1 is the Julian Day Number and UTC2 is the fraction of a day.
However, JD cannot unambiguously represent UTC during a leap second unless special measures are taken. The convention in the present routine is that the JD day represents UTC days whether the length is 86399, 86400 or 86401 SI seconds.
Applications should use the routine DTF2D to convert from calendar date and time of day into 2-part quasi Julian Date, as it implements the leap-second-ambiguity convention just described.
The warning status "dubious year" flags UTCs that predate the introduction of the time scale or that are too far in the future to be trusted. See DAT for further details.
UT1-UTC is tabulated in IERS bulletins. It increases by exactly one second at the end of each positive UTC leap second, introduced in order to keep UT1-UTC within +/- 0.9s. n.b. This practice is under review, and in the future UT1-UTC may grow essentially without limit.
The geographical coordinates are with respect to the WGS84 reference ellipsoid. TAKE CARE WITH THE LONGITUDE SIGN: the longitude required by the present routine is east-positive (i.e. right-handed), in accordance with geographical convention.
The polar motion XP,YP can be obtained from IERS bulletins. The values are the coordinates (in radians) of the Celestial Intermediate Pole with respect to the International Terrestrial Reference System (see IERS Conventions 2003), measured along the meridians 0 and 90 deg west respectively. For many applications, XP and YP can be set to zero.
Internally, the polar motion is stored in a form rotated onto the local meridian.
If hm, the height above the ellipsoid of the observing station in meters, is not known but phpa, the pressure in hPa (=mB), is available, an adequate estimate of hm can be obtained from the expression
    hm = -29.3 * tsl * log ( phpa / 1013.25 );
where tsl is the approximate sea-level air temperature in K (See Astrophysical Quantities, C.W.Allen, 3rd edition, section 52). Similarly, if the pressure phpa is not known, it can be estimated from the height of the observing station, hm, as follows:
    phpa = 1013.25 * exp ( -hm / ( 29.3 * tsl ) );
Note, however, that the refraction is nearly proportional to the pressure and that an accurate phpa value is important for precise work.
The argument WL specifies the observing wavelength in micrometers. The transition from optical to radio is assumed to occur at 100 micrometers (about 3000 GHz).
It is advisable to take great care with units, as even unlikely values of the input parameters are accepted and processed in accordance with the models used.
In cases where the caller wishes to supply his own Earth ephemeris, Earth rotation information and refraction constants, the routine APCO can be used instead of the present routine.
This is one of several routines that inserts into the ASTROM array star-independent parameters needed for the chain of astrometric transformations ICRS <-> GCRS <-> CIRS <-> observed.
The various routines support different classes of observer and portions of the transformation chain:
    routines           observer        transformation
APCG APCG13    geocentric      ICRS <-> GCRS
APCI APCI13    terrestrial     ICRS <-> CIRS
APCO APCO13    terrestrial     ICRS <-> observed
APCS APCS13    space           ICRS <-> GCRS
APER APER13    terrestrial     update Earth rotation
APIO APIO13    terrestrial     CIRS <-> observed
Those with names ending in "13" use contemporary SOFA models to compute the various ephemerides. The others accept ephemerides supplied by the caller.
The transformation from ICRS to GCRS covers space motion, parallax, light deflection, and aberration. From GCRS to CIRS comprises frame bias and precession-nutation. From CIRS to observed takes account of Earth rotation, polar motion, diurnal aberration and parallax (unless subsumed into the ICRS <-> GCRS transformation), and atmospheric refraction.
The context array ASTROM produced by this routine is used by ATIOQ, ATOIQ, ATCIQ and ATICQ.
History
IAU SOFA revision: 2013 December 5
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: utc1
UTC as a 2-part...
real(kind=wp), intent(in) :: utc2
real(kind=wp), intent(in) :: dut1
UT1-UTC (seconds, Note 3)
real(kind=wp), intent(in) :: elong
longitude (radians, east +ve, Note 4)
real(kind=wp), intent(in) :: phi
latitude (geodetic, radians, Note 4)
real(kind=wp), intent(in) :: hm
height above ellipsoid (m, geodetic, Notes 4,6)
real(kind=wp), intent(in) :: xp
polar motion coordinate (radians, Note 5)
real(kind=wp), intent(in) :: yp
polar motion coordinate (radians, Note 5)
real(kind=wp), intent(in) :: phpa
pressure at the observer (hPa = mB, Note 6)
real(kind=wp), intent(in) :: tc
ambient temperature at the observer (deg C)
real(kind=wp), intent(in) :: rh
relative humidity at the observer (range 0-1)
real(kind=wp), intent(in) :: wl
wavelength (micrometers, Note 7)
real(kind=wp), intent(out), dimension(30) :: astrom
star-independent astrometry parameters:
(1) PM time interval (SSB, Julian years) (2-4) SSB to observer (vector, au) (5-7) Sun to observer (unit vector) (8) distance from Sun to observer (au) (9-11) v: barycentric observer velocity (vector, c) (12) sqrt(1-|v|^2): reciprocal of Lorenz factor (13-21) bias-precession-nutation matrix (22) longitude + s' (radians) (23) polar motion xp wrt local meridian (radians) (24) polar motion yp wrt local meridian (radians) (25) sine of geodetic latitude (26) cosine of geodetic latitude (27) magnitude of diurnal aberration vector (28) "local" Earth rotation angle (radians) (29) refraction constant A (radians) (30) refraction constant B (radians)
real(kind=wp), intent(out) :: eo
equation of the origins (ERA-GST)
integer, intent(out) :: j
0 = OK -1 = unacceptable date
Calls
Called by
Contents
Source Code
APCO13
Source Code
    subroutine APCO13 ( utc1, utc2, dut1, elong, phi, hm, xp, yp, &
                        phpa, tc, rh, wl, astrom, eo, j )
    implicit none
    real(wp),intent(in) :: utc1 !! UTC as a 2-part...
    real(wp),intent(in) :: utc2 !! ...quasi Julian Date (Notes 1,2)
    real(wp),intent(in) :: dut1 !! UT1-UTC (seconds, Note 3)
    real(wp),intent(in) :: elong !! longitude (radians, east +ve, Note 4)
    real(wp),intent(in) :: phi !! latitude (geodetic, radians, Note 4)
    real(wp),intent(in) :: hm !! height above ellipsoid (m, geodetic, Notes 4,6)
    real(wp),intent(in) :: xp !! polar motion coordinate (radians, Note 5)
    real(wp),intent(in) :: yp !! polar motion coordinate (radians, Note 5)
    real(wp),intent(in) :: phpa !! pressure at the observer (hPa = mB, Note 6)
    real(wp),intent(in) :: tc !! ambient temperature at the observer (deg C)
    real(wp),intent(in) :: rh !! relative humidity at the observer (range 0-1)
    real(wp),intent(in) :: wl !! wavelength (micrometers, Note 7)
    real(wp),dimension(30),intent(out) :: astrom !! star-independent astrometry parameters:
                                                 !!
                                                 !! (1)      PM time interval (SSB, Julian years)
                                                 !! (2-4)    SSB to observer (vector, au)
                                                 !! (5-7)    Sun to observer (unit vector)
                                                 !! (8)      distance from Sun to observer (au)
                                                 !! (9-11)   v: barycentric observer velocity (vector, c)
                                                 !! (12)     sqrt(1-|v|^2): reciprocal of Lorenz factor
                                                 !! (13-21)  bias-precession-nutation matrix
                                                 !! (22)     longitude + s' (radians)
                                                 !! (23)     polar motion xp wrt local meridian (radians)
                                                 !! (24)     polar motion yp wrt local meridian (radians)
                                                 !! (25)     sine of geodetic latitude
                                                 !! (26)     cosine of geodetic latitude
                                                 !! (27)     magnitude of diurnal aberration vector
                                                 !! (28)     "local" Earth rotation angle (radians)
                                                 !! (29)     refraction constant A (radians)
                                                 !! (30)     refraction constant B (radians)
    real(wp),intent(out) :: eo !! equation of the origins (ERA-GST)
    integer,intent(out) :: j !! status: +1 = dubious year (Note 2)
                             !!  0 = OK
                             !! -1 = unacceptable date
    integer :: js, jw
    real(wp) :: tai1, tai2, tt1, tt2, ut11, ut12, &
                ehpv(3,2), ebpv(3,2), r(3,3), x, y, s, theta, &
                sp, refa, refb
    !  UTC to other time scales.
    call UTCTAI ( utc1, utc2, tai1, tai2, js )
    if ( js>=0 ) then
      call TAITT ( tai1, tai2, tt1, tt2, js )
      call UTCUT1 ( utc1, utc2, dut1, ut11, ut12, js )
      if ( js>=0 ) then
        !  Earth barycentric & heliocentric position/velocity (au, au/d).
        call EPV00 ( tt1, tt2, ehpv, ebpv, jw )
        !  Form the equinox based BPN matrix, IAU 2006/2000A.
        call PNM06A ( tt1, tt2, r )
        !  Extract CIP X,Y.
        call BPN2XY ( r, x, y )
        !  Obtain CIO locator s.
        s = S06 ( tt1, tt2, x, y )
        !  Earth rotation angle.
        theta = ERA00 ( ut11, ut12 )
        !  TIO locator s'.
        sp = SP00 ( tt1, tt2 )
        !  Refraction constants A and B.
        call REFCO ( phpa, tc, rh, wl, refa, refb )
        !  Compute the star-independent astrometry parameters.
        call APCO ( tt1, tt2, ebpv, ehpv, x, y, s, theta, &
                        elong, phi, hm, xp, yp, sp, refa, refb, &
                        astrom )
        !  Equation of the origins.
        eo = EORS ( r, s )
      end if
    end if
    !  Return the status.
    j = js
    end subroutine APCO13
Call graph
apco13 calls utctai, refco, utcut1, epv00, s06, eors, apco, sp00, taitt, bpn2xy, pnm06a, era00
utctai calls dat, cal2jd, jd2cal
utcut1 calls utctai, taiut1, dat, jd2cal
s06 calls fad03, fae03, fal03, falp03, faf03, fave03, faom03, fapa03
apco calls trxpv, aper, apcs, pvtob, cr, c2ixys
pnm06a calls nut06a, pfw06, fw2m
era00 calls anp
trxpv calls tr, rxpv
nut06a calls nut00a
pfw06 calls obl06
apcs calls pn, ir
fw2m calls ir, rx, rz
dat calls cal2jd
pvtob calls gd2gc, pom00, trxp
c2ixys calls ir, ry, rz
nut00a calls fae03, fal03, faf03, fave03, faom03, fapa03, faur03, faju03, fasa03, fame03, fama03
gd2gc calls gd2gce, zp, eform
pom00 calls ir, rx, ry, rz
rxpv calls rxp
pn calls sxp, zp
trxp calls tr, rxp
atoc13 calls apco13
atco13 calls apco13