APER13 – astro-fortran
APER13 Subroutine
7 statements
Source File
public subroutine APER13(ut11, ut12, astrom)
In the star-independent astrometry parameters, update only the Earth rotation angle. The caller provides UT1 (n.b. not UTC).
Status: support routine.
Notes
The UT1 date (n.b. not UTC) UT11+UT12 is a Julian Date, apportioned in any convenient way between the arguments UT11 and UT12. For example, JD(UT1)=2450123.7 could be expressed in any of these ways, among others:
    UT11           UT12
 2450123.7D0        0D0        (JD method)
  2451545D0      -1421.3D0     (J2000 method)
 2400000.5D0     50123.2D0     (MJD method)
 2450123.5D0       0.2D0       (date & time method)
The JD method is the most natural and convenient to use in cases where the loss of several decimal digits of resolution is acceptable. The J2000 and MJD methods are good compromises between resolution and convenience. The date & time method is best matched to the algorithm used: maximum precision is delivered when the UT11 argument is for 0hrs UT1 on the day in question and the UT12 argument lies in the range 0 to 1, or vice versa.
If the caller wishes to provide the Earth rotation angle itself, the routine APER can be used instead. One use of this technique is to substitute Greenwich apparent sidereal time and thereby to support equinox based transformations directly.
This is one of several routines that inserts into the ASTROM array star-independent parameters needed for the chain of astrometric transformations ICRS <-> GCRS <-> CIRS <-> observed.
The various routines support different classes of observer and portions of the transformation chain:
    routines           observer        transformation
APCG APCG13    geocentric      ICRS <-> GCRS
APCI APCI13    terrestrial     ICRS <-> CIRS
APCO APCO13    terrestrial     ICRS <-> observed
APCS APCS13    space           ICRS <-> GCRS
APER APER13    terrestrial     update Earth rotation
APIO APIO13    terrestrial     CIRS <-> observed
Those with names ending in "13" use contemporary SOFA models to compute the various ephemerides. The others accept ephemerides supplied by the caller.
The transformation from ICRS to GCRS covers space motion, parallax, light deflection, and aberration. From GCRS to CIRS comprises frame bias and precession-nutation. From CIRS to observed takes account of Earth rotation, polar motion, diurnal aberration and parallax (unless subsumed into the ICRS <-> GCRS transformation), and atmospheric refraction.
History
IAU SOFA revision: 2017 March 12
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: ut11
UT1 as a 2-part...
real(kind=wp), intent(in) :: ut12
real(kind=wp), intent(inout), dimension(30) :: astrom
star-independent astrometry parameters: * In: astrom(22): longitude + s' (radians) * Out: astrom(28): "local" Earth rotation angle (radians)
Calls
Contents
Source Code
APER13
Source Code
    subroutine APER13 ( ut11, ut12, astrom )
    implicit none
    real(wp),intent(in) :: ut11 !! UT1 as a 2-part...
    real(wp),intent(in) :: ut12 !! ...Julian Date (Note 1)
    real(wp),dimension(30),intent(inout) :: astrom !! star-independent astrometry parameters:
                                                   !! * In: astrom(22): longitude + s' (radians)
                                                   !! * Out: astrom(28): "local" Earth rotation angle (radians)
    call APER ( ERA00 ( ut11, ut12 ), astrom )
    end subroutine APER13
Call graph
aper13 calls era00, aper
era00 calls anp