APER – astro-fortran
APER Subroutine
6 statements
Source File
public subroutine APER(theta, astrom)
In the star-independent astrometry parameters, update only the Earth rotation angle, supplied by the caller explicitly.
Status: support routine.
Notes
This routine exists to enable sidereal-tracking applications to avoid wasteful recomputation of the bulk of the astrometry parameters: only the Earth rotation is updated.
For targets expressed as equinox based positions, such as classical geocentric apparent (RA,Dec), the supplied THETA can be Greenwich apparent sidereal time rather than Earth rotation angle.
The routine APER13 can be used instead of the present routine, and starts from UT1 rather than ERA itself.
This is one of several routines that inserts into the ASTROM array star-independent parameters needed for the chain of astrometric transformations ICRS <-> GCRS <-> CIRS <-> observed.
The various routines support different classes of observer and portions of the transformation chain:
    routines           observer        transformation
APCG APCG13    geocentric      ICRS <-> GCRS
APCI APCI13    terrestrial     ICRS <-> CIRS
APCO APCO13    terrestrial     ICRS <-> observed
APCS APCS13    space           ICRS <-> GCRS
APER APER13    terrestrial     update Earth rotation
APIO APIO13    terrestrial     CIRS <-> observed
Those with names ending in "13" use contemporary SOFA models to compute the various ephemerides. The others accept ephemerides supplied by the caller.
The transformation from ICRS to GCRS covers space motion, parallax, light deflection, and aberration. From GCRS to CIRS comprises frame bias and precession-nutation. From CIRS to observed takes account of Earth rotation, polar motion, diurnal aberration and parallax (unless subsumed into the ICRS <-> GCRS transformation), and atmospheric refraction.
History
IAU SOFA revision: 2013 September 25
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: theta
Earth rotation angle (radians, Note 2)
real(kind=wp), intent(inout), dimension(30) :: astrom
star-independent astrometry parameters: * In: astrom(22): longitude + s' (radians) * Out: astrom(28): "local" Earth rotation angle (radians)
Called by
Contents
Source Code
APER
Source Code
    subroutine APER ( theta, astrom )
    implicit none
    real(wp),intent(in) :: theta !! Earth rotation angle (radians, Note 2)
    real(wp),dimension(30),intent(inout) :: astrom !! star-independent astrometry parameters:
                                                   !! * In: astrom(22): longitude + s' (radians)
                                                   !! * Out: astrom(28): "local" Earth rotation angle (radians)
    astrom(28) = theta + astrom(22)
    end subroutine APER
Call graph
apco calls aper
apio calls aper
aper13 calls aper
apio13 calls apio
apco13 calls apco
atoc13 calls apco13
atio13 calls apio13
atoi13 calls apio13
atco13 calls apco13