ATCI13 – astro-fortran
ATCI13 Subroutine
17 statements
Source File
public subroutine ATCI13(rc, dc, pr, pd, px, rv, date1, date2, ri, di, eo)
Transform ICRS star data, epoch J2000.0, to CIRS.
Status: support routine.
Notes
Star data for an epoch other than J2000.0 (for example from the Hipparcos catalog, which has an epoch of J1991.25) will require a preliminary call to PMSAFE before use.
The proper motion in RA is dRA/dt rather than cos(Dec)*dRA/dt.
The TDB date DATE1+DATE2 is a Julian Date, apportioned in any convenient way between the two arguments. For example, JD(TDB)=2450123.7 could be expressed in any of these ways, among others:
    DATE1          DATE2
 2450123.7D0        0D0        (JD method)
  2451545D0      -1421.3D0     (J2000 method)
 2400000.5D0     50123.2D0     (MJD method)
 2450123.5D0       0.2D0       (date & time method)
The JD method is the most natural and convenient to use in cases where the loss of several decimal digits of resolution is acceptable. The J2000 method is best matched to the way the argument is handled internally and will deliver the optimum resolution. The MJD method and the date & time methods are both good compromises between resolution and convenience. For most applications of this routine the choice will not be at all critical.
TT can be used instead of TDB without any significant impact on accuracy.
The available accuracy is better than 1 milliarcsecond, limited mainly by the precession-nutation model that is used, namely IAU 2000A/2006. Very close to solar system bodies, additional errors of up to several milliarcseconds can occur because of unmodeled light deflection; however, the Sun's contribution is taken into account, to first order. The accuracy limitations of the SOFA routine EPV00 (used to compute Earth position and velocity) can contribute aberration errors of up to 5 microarcseconds. Light deflection at the Sun's limb is uncertain at the 0.4 mas level.
Should the transformation to (equinox based) apparent place be required rather than (CIO based) intermediate place, subtract the equation of the origins from the returned right ascension: RA = RI - EO. (The ANP routine can then be applied, as required, to keep the result in the conventional 0-2pi range.)
History
IAU SOFA revision: 2017 March 12
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: rc
ICRS right ascension at J2000.0 (radians, Note 1)
real(kind=wp), intent(in) :: dc
ICRS declination at J2000.0 (radians, Note 1)
real(kind=wp), intent(in) :: pr
RA proper motion (radians/year; Note 2)
real(kind=wp), intent(in) :: pd
Dec proper motion (radians/year)
real(kind=wp), intent(in) :: px
parallax (arcsec)
real(kind=wp), intent(in) :: rv
radial velocity (km/s, +ve if receding)
real(kind=wp), intent(in) :: date1
TDB as a 2-part...
real(kind=wp), intent(in) :: date2
real(kind=wp), intent(out) :: ri
CIRS geocentric RA (radians)
real(kind=wp), intent(out) :: di
CIRS geocentric Dec (radians)
real(kind=wp), intent(out) :: eo
equation of the origins (ERA-GST, Note 5)
Calls
Contents
Source Code
ATCI13
Source Code
    subroutine ATCI13 ( rc, dc, pr, pd, px, rv, date1, date2, &
                        ri, di, eo )
    implicit none
    real(wp),intent(in) :: rc !! ICRS right ascension at J2000.0 (radians, Note 1)
    real(wp),intent(in) :: dc !! ICRS declination at J2000.0 (radians, Note 1)
    real(wp),intent(in) :: pr !! RA proper motion (radians/year; Note 2)
    real(wp),intent(in) :: pd !! Dec proper motion (radians/year)
    real(wp),intent(in) :: px !! parallax (arcsec)
    real(wp),intent(in) :: rv !! radial velocity (km/s, +ve if receding)
    real(wp),intent(in) :: date1 !! TDB as a 2-part...
    real(wp),intent(in) :: date2 !! ...Julian Date (Note 3)
    real(wp),intent(out) :: ri !! CIRS geocentric RA (radians)
    real(wp),intent(out) :: di !! CIRS geocentric Dec (radians)
    real(wp),intent(out) :: eo !! equation of the origins (ERA-GST, Note 5)
    !  Star-independent astrometry parameters
    real(wp) :: astrom(30)
    !  The transformation parameters.
    call APCI13 ( date1, date2, astrom, eo )
    !  ICRS (epoch J2000.0) to CIRS.
    call ATCIQ ( rc, dc, pr, pd, px, rv, astrom, ri, di )
    end subroutine ATCI13
Call graph
atci13 calls apci13, atciq
apci13 calls eors, epv00, s06, bpn2xy, apci, pnm06a
atciq calls c2s, ab, anp, ldsun, rxp, pmpx
s06 calls faom03, fad03, falp03, fae03, fal03, fapa03, faf03, fave03
ab calls pdp
apci calls apcg, c2ixys
ldsun calls ld
pnm06a calls pfw06, nut06a, fw2m
pmpx calls pdp
ld calls pdp, pxp
pfw06 calls obl06
nut06a calls nut00a
apcg calls zpv, apcs
c2ixys calls ir, ry, rz
fw2m calls rx, ir, rz
zpv calls zp
nut00a calls faom03, fae03, fal03, fapa03, faf03, fave03, faur03, faju03, fasa03, fame03, fama03
apcs calls ir, pn
pn calls zp, sxp