ATCO13 – astro-fortran
ATCO13 Subroutine
37 statements
Source File
public subroutine ATCO13(rc, dc, pr, pd, px, rv, utc1, utc2, dut1, elong, phi, hm, xp, yp, phpa, tc, rh, wl, aob, zob, hob, dob, rob, eo, j)
ICRS RA,Dec to observed place. The caller supplies UTC, site coordinates, ambient air conditions and observing wavelength.
Status: support routine.
Notes
Star data for an epoch other than J2000.0 (for example from the Hipparcos catalog, which has an epoch of J1991.25) will require a preliminary call to PMSAFE before use.
The proper motion in RA is dRA/dt rather than cos(Dec)*dRA/dt.
UTC1+UTC2 is quasi Julian Date (see Note 2), apportioned in any convenient way between the two arguments, for example where UTC1 is the Julian Day Number and UTC2 is the fraction of a day.
However, JD cannot unambiguously represent UTC during a leap second unless special measures are taken. The convention in the present routine is that the JD day represents UTC days whether the length is 86399, 86400 or 86401 SI seconds.
Applications should use the routine DTF2D to convert from calendar date and time of day into 2-part quasi Julian Date, as it implements the leap-second-ambiguity convention just described.
The warning status "dubious year" flags UTCs that predate the introduction of the time scale or that are too far in the future to be trusted. See DAT for further details.
UT1-UTC is tabulated in IERS bulletins. It increases by exactly one second at the end of each positive UTC leap second, introduced in order to keep UT1-UTC within +/- 0.9s. n.b. This practice is under review, and in the future UT1-UTC may grow essentially without limit.
The geographical coordinates are with respect to the WGS84 reference ellipsoid. TAKE CARE WITH THE LONGITUDE SIGN: the longitude required by the present routine is east-positive (i.e. right-handed), in accordance with geographical convention.
The polar motion XP,YP can be obtained from IERS bulletins. The values are the coordinates (in radians) of the Celestial Intermediate Pole with respect to the International Terrestrial Reference System (see IERS Conventions 2003), measured along the meridians 0 and 90 deg west respectively. For many applications, XP and YP can be set to zero.
If hm, the height above the ellipsoid of the observing station in meters, is not known but phpa, the pressure in hPa (=mB), is available, an adequate estimate of hm can be obtained from the expression
    hm = -29.3 * tsl * log ( phpa / 1013.25 );
where tsl is the approximate sea-level air temperature in K (See Astrophysical Quantities, C.W.Allen, 3rd edition, section 52). Similarly, if the pressure phpa is not known, it can be estimated from the height of the observing station, hm, as follows:
    phpa = 1013.25 * exp ( -hm / ( 29.3 * tsl ) );
Note, however, that the refraction is nearly proportional to the pressure and that an accurate phpa value is important for precise work.
The argument WL specifies the observing wavelength in micrometers. The transition from optical to radio is assumed to occur at 100 micrometers (about 3000 GHz).
The accuracy of the result is limited by the corrections for refraction, which use a simple Atan(z) + Btan^3(z) model. Providing the meteorological parameters are known accurately and there are no gross local effects, the predicted observed coordinates should be within 0.05 arcsec (optical) or 1 arcsec (radio) for a zenith distance of less than 70 degrees, better than 30 arcsec (optical or radio) at 85 degrees and better than 20 arcmin (optical) or 30 arcmin (radio) at the horizon.
Without refraction, the complementary routines ATCO13 and ATOC13 are self-consistent to better than 1 microarcsecond all over the celestial sphere. With refraction included, consistency falls off at high zenith distances, but is still better than 0.05 arcsec at 85 degrees.
"Observed" Az,ZD means the position that would be seen by a perfect geodetically aligned theodolite. (Zenith distance is used rather than altitude in order to reflect the fact that no allowance is made for depression of the horizon.) This is related to the observed HA,Dec via the standard rotation, using the geodetic latitude (corrected for polar motion), while the observed HA and RA are related simply through the Earth rotation angle and the site longitude. "Observed" RA,Dec or HA,Dec thus means the position that would be seen by a perfect equatorial with its polar axis aligned to the Earth's axis of rotation.
It is advisable to take great care with units, as even unlikely values of the input parameters are accepted and processed in accordance with the models used.
History
IAU SOFA revision: 2016 February 2
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: rc
ICRS right ascension at J2000.0 (radians, Note 1)
real(kind=wp), intent(in) :: dc
ICRS declination at J2000.0 (radians, Note 1)
real(kind=wp), intent(in) :: pr
RA proper motion (radians/year; Note 2)
real(kind=wp), intent(in) :: pd
Dec proper motion (radians/year)
real(kind=wp), intent(in) :: px
parallax (arcsec)
real(kind=wp), intent(in) :: rv
radial velocity (km/s, +ve if receding)
real(kind=wp), intent(in) :: utc1
UTC as a 2-part...
real(kind=wp), intent(in) :: utc2
real(kind=wp), intent(in) :: dut1
UT1-UTC (seconds, Note 5)
real(kind=wp), intent(in) :: elong
longitude (radians, east +ve, Note 6)
real(kind=wp), intent(in) :: phi
latitude (geodetic, radians, Note 6)
real(kind=wp), intent(in) :: hm
height above ellipsoid (m, geodetic, Notes 6,8)
real(kind=wp), intent(in) :: xp
polar motion coordinate (radians, Note 7)
real(kind=wp), intent(in) :: yp
polar motion coordinate (radians, Note 7)
real(kind=wp), intent(in) :: phpa
pressure at the observer (hPa = mB, Note 8)
real(kind=wp), intent(in) :: tc
ambient temperature at the observer (deg C)
real(kind=wp), intent(in) :: rh
relative humidity at the observer (range 0-1)
real(kind=wp), intent(in) :: wl
wavelength (micrometers, Note 9)
real(kind=wp), intent(out) :: aob
observed azimuth (radians: N=0,E=90)
real(kind=wp), intent(out) :: zob
observed zenith distance (radians)
real(kind=wp), intent(out) :: hob
observed hour angle (radians)
real(kind=wp), intent(out) :: dob
observed declination (radians)
real(kind=wp), intent(out) :: rob
observed right ascension (CIO-based, radians)
real(kind=wp), intent(out) :: eo
equation of the origins (ERA-GST)
integer, intent(out) :: j
+1 = dubious year (Note 4)
0 = OK
-1 = unacceptable date
Calls
Contents
Source Code
ATCO13
Source Code
    subroutine ATCO13 ( rc, dc, pr, pd, px, rv, &
                        utc1, utc2, dut1, elong, phi, hm, xp, yp, &
                        phpa, tc, rh, wl, &
                        aob, zob, hob, dob, rob, eo, j )
    implicit none
    real(wp),intent(in) :: rc !! ICRS right ascension at J2000.0 (radians, Note 1)
    real(wp),intent(in) :: dc !! ICRS declination at J2000.0 (radians, Note 1)
    real(wp),intent(in) :: pr !! RA proper motion (radians/year; Note 2)
    real(wp),intent(in) :: pd !! Dec proper motion (radians/year)
    real(wp),intent(in) :: px !! parallax (arcsec)
    real(wp),intent(in) :: rv !! radial velocity (km/s, +ve if receding)
    real(wp),intent(in) :: utc1 !! UTC as a 2-part...
    real(wp),intent(in) :: utc2 !! ...quasi Julian Date (Notes 3-4)
    real(wp),intent(in) :: dut1 !! UT1-UTC (seconds, Note 5)
    real(wp),intent(in) :: elong !! longitude (radians, east +ve, Note 6)
    real(wp),intent(in) :: phi !! latitude (geodetic, radians, Note 6)
    real(wp),intent(in) :: hm !! height above ellipsoid (m, geodetic, Notes 6,8)
    real(wp),intent(in) :: xp !! polar motion coordinate (radians, Note 7)
    real(wp),intent(in) :: yp !! polar motion coordinate (radians, Note 7)
    real(wp),intent(in) :: phpa !! pressure at the observer (hPa = mB, Note 8)
    real(wp),intent(in) :: tc !! ambient temperature at the observer (deg C)
    real(wp),intent(in) :: rh !! relative humidity at the observer (range 0-1)
    real(wp),intent(in) :: wl !! wavelength (micrometers, Note 9)
    real(wp),intent(out) :: aob !! observed azimuth (radians: N=0,E=90)
    real(wp),intent(out) :: zob !! observed zenith distance (radians)
    real(wp),intent(out) :: hob !! observed hour angle (radians)
    real(wp),intent(out) :: dob !! observed declination (radians)
    real(wp),intent(out) :: rob !! observed right ascension (CIO-based, radians)
    real(wp),intent(out) :: eo !! equation of the origins (ERA-GST)
    integer,intent(out) :: j !! status:
                             !! * +1 = dubious year (Note 4)
                             !! *  0 = OK
                             !! * -1 = unacceptable date
    integer :: js
    real(wp) :: astrom(30)
    real(wp) :: ri, di
    !  Star-independent astrometry parameters.
    call APCO13 ( utc1, utc2, dut1, elong, phi, hm, xp, yp, &
                  phpa, tc, rh, wl, astrom, eo, js )
    if ( js>=0 ) then
      !  Transform ICRS to CIRS.
      call ATCIQ ( rc, dc, pr, pd, px, rv, astrom, ri, di )
      !  Transform CIRS to observed.
      call ATIOQ ( ri, di, astrom, aob, zob, hob, dob, rob )
    end if
    !  Return OK/warning status.
    j = js
    end subroutine ATCO13
Call graph
atco13 calls atciq, atioq, apco13
atciq calls ab, rxp, anp, pmpx, c2s, ldsun
atioq calls anp, s2c, c2s
apco13 calls utctai, utcut1, epv00, s06, apco, taitt, bpn2xy, pnm06a, era00, refco, eors, sp00
ab calls pdp
utctai calls dat, cal2jd, jd2cal
utcut1 calls utctai, taiut1, dat, jd2cal
s06 calls fad03, fae03, fal03, falp03, faf03, fave03, faom03, fapa03
apco calls trxpv, aper, apcs, pvtob, cr, c2ixys
pmpx calls pdp
pnm06a calls nut06a, pfw06, fw2m
era00 calls anp
ldsun calls ld
trxpv calls tr, rxpv
nut06a calls nut00a
pfw06 calls obl06
apcs calls pn, ir
fw2m calls ir, rx, rz
dat calls cal2jd
pvtob calls gd2gc, pom00, trxp
ld calls pdp, pxp
c2ixys calls ir, ry, rz
nut00a calls fae03, fal03, faf03, fave03, faom03, fapa03, faur03, faju03, fasa03, fame03, fama03
gd2gc calls gd2gce, zp, eform
pom00 calls ir, rx, ry, rz
rxpv calls rxp
pn calls sxp, zp
trxp calls rxp, tr