ATIC13 – astro-fortran
ATIC13 Subroutine
13 statements
Source File
public subroutine ATIC13(ri, di, date1, date2, rc, dc, eo)
Transform star RA,Dec from geocentric CIRS to ICRS astrometric.
Status: support routine.
Notes
The TDB date DATE1+DATE2 is a Julian Date, apportioned in any convenient way between the two arguments. For example, JD(TDB)=2450123.7 could be expressed in any of these ways, among others:
    DATE1          DATE2
 2450123.7D0        0D0        (JD method)
  2451545D0      -1421.3D0     (J2000 method)
 2400000.5D0     50123.2D0     (MJD method)
 2450123.5D0       0.2D0       (date & time method)
The JD method is the most natural and convenient to use in cases where the loss of several decimal digits of resolution is acceptable. The J2000 method is best matched to the way the argument is handled internally and will deliver the optimum resolution. The MJD method and the date & time methods are both good compromises between resolution and convenience. For most applications of this routine the choice will not be at all critical.
TT can be used instead of TDB without any significant impact on accuracy.
Iterative techniques are used for the aberration and light deflection corrections so that the routines ATIC13 (or ATICQ) and ATCI13 (or ATCIQ) are accurate inverses; even at the edge of the Sun's disk the discrepancy is only about 1 nanoarcsecond.
The available accuracy is better than 1 milliarcsecond, limited mainly by the precession-nutation model that is used, namely IAU 2000A/2006. Very close to solar system bodies, additional errors of up to several milliarcseconds can occur because of unmodeled light deflection; however, the Sun's contribution is taken into account, to first order. The accuracy limitations of the SOFA routine EPV00 (used to compute Earth position and velocity) can contribute aberration errors of up to 5 microarcseconds. Light deflection at the Sun's limb is uncertain at the 0.4 mas level.
Should the transformation to (equinox based) J2000.0 mean place be required rather than (CIO based) ICRS coordinates, subtract the equation of the origins from the returned right ascension: RA = RI - EO. (The ANP routine can then be applied, as required, to keep the result in the conventional 0-2pi range.)
History
IAU SOFA revision: 2017 March 12
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: ri
CIRS geocentric RA (radians)
real(kind=wp), intent(in) :: di
CIRS geocentric Dec (radians)
real(kind=wp), intent(in) :: date1
TDB as a 2-part...
real(kind=wp), intent(in) :: date2
real(kind=wp), intent(out) :: rc
ICRS astrometric RA (radians)
real(kind=wp), intent(out) :: dc
ICRS astrometric Dec (radians)
real(kind=wp), intent(out) :: eo
equation of the origins (ERA-GST, Note 4)
Calls
Contents
Source Code
ATIC13
Source Code
    subroutine ATIC13 ( ri, di, date1, date2, rc, dc, eo )
    implicit none
    real(wp),intent(in) :: ri !! CIRS geocentric RA (radians)
    real(wp),intent(in) :: di !! CIRS geocentric Dec (radians)
    real(wp),intent(in) :: date1 !! TDB as a 2-part...
    real(wp),intent(in) :: date2 !! ...Julian Date (Note 1)
    real(wp),intent(out) :: rc !! ICRS astrometric RA (radians)
    real(wp),intent(out) :: dc !! ICRS astrometric Dec (radians)
    real(wp),intent(out) :: eo !! equation of the origins (ERA-GST, Note 4)
    !  Star-independent astrometry parameters
    real(wp) :: astrom(30)
    !  Star-independent astrometry parameters.
    call APCI13 ( date1, date2, astrom, eo )
    !  CIRS to ICRS astrometric
    call ATICQ ( ri, di, astrom, rc, dc )
    end subroutine ATIC13
Call graph
atic13 calls aticq, apci13
aticq calls ab, anp, zp, c2s, s2c, ldsun, trxp
apci13 calls apci, pnm06a, epv00, s06, eors, bpn2xy
apci calls apcg, c2ixys
pnm06a calls nut06a, pfw06, fw2m
s06 calls faom03, fad03, falp03, fae03, fal03, fapa03, faf03, fave03
ab calls pdp
ldsun calls ld
trxp calls tr, rxp
ld calls pdp, pxp
nut06a calls nut00a
apcg calls zpv, apcs
pfw06 calls obl06
c2ixys calls ir, ry, rz
fw2m calls rx, ir, rz
zpv calls zp
nut00a calls faom03, fae03, fal03, fapa03, faf03, fave03, faur03, faju03, fasa03, fame03, fama03
apcs calls ir, pn
pn calls zp, sxp