BI00 – astro-fortran
BI00 Subroutine
12 statements
Source File
public subroutine BI00(dpsibi, depsbi, dra)
Frame bias components of IAU 2000 precession-nutation models (part of MHB2000 with additions).
Status: canonical model.
Notes
The frame bias corrections in longitude and obliquity (radians) are required in order to correct for the offset between the GCRS pole and the J2000.0 mean pole. They define, with respect to the GCRS frame, a J2000.0 mean pole that is consistent with the rest of the IAU 2000A precession-nutation model.
In addition to the displacement of the pole, the complete description of the frame bias requires also an offset in right ascension. This is not part of the IAU 2000A model, and is from Chapront et al. (2002). It is returned in radians.
This is a supplemented implementation of one aspect of the IAU 2000A nutation model, formally adopted by the IAU General Assembly in 2000, namely MHB2000 (Mathews et al. 2002).
References
Chapront, J., Chapront-Touze, M. & Francou, G., Astron.Astrophys., 387, 700, 2002.
Mathews, P.M., Herring, T.A., Buffet, B.A., "Modeling of nutation and precession New nutation series for nonrigid Earth and insights into the Earth's interior", J.Geophys.Res., 107, B4,
The MHB2000 code itself was obtained on 9th September 2002 from ftp://maia.usno.navy.mil/conv2000/chapter5/IAU2000A.
History
IAU SOFA revision: 2009 December 15
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(out) :: dpsibi
longitude correction
real(kind=wp), intent(out) :: depsbi
obliquity correction
real(kind=wp), intent(out) :: dra
the ICRS RA of the J2000.0 mean equinox
Called by
Contents
Source Code
BI00
Source Code
    subroutine BI00 ( dpsibi, depsbi, dra )
    implicit none
    real(wp),intent(out) :: dpsibi !! longitude correction
    real(wp),intent(out) :: depsbi !! obliquity correction
    real(wp),intent(out) :: dra !! the ICRS RA of the J2000.0 mean equinox
    !  The frame bias corrections in longitude and obliquity
    real(wp),parameter :: dpbias = -0.041775_wp * das2r
    real(wp),parameter :: debias = -0.0068192_wp * das2r
    !  The ICRS RA of the J2000.0 equinox (Chapront et al., 2002)
    real(wp),parameter :: dra0 = -0.0146_wp * das2r
    !  Return the results (which are fixed).
    dpsibi = dpbias
    depsbi = debias
    dra = dra0
    end subroutine BI00
Call graph
bp00 calls bi00
pn00 calls bp00
pmat00 calls bp00
pn00a calls pn00
pn00b calls pn00
c2tpe calls pn00
pnm00a calls pn00a
num00a calls pn00a
num00b calls pn00b
pnm00b calls pn00b
xys00a calls pnm00a
s00a calls pnm00a
c2i00b calls pnm00b
c2i00a calls pnm00a
s00b calls pnm00b
xys00b calls pnm00b
c2t00b calls c2i00b
c2t00a calls c2i00a