BP00 – astro-fortran
BP00 Subroutine
29 statements
Source File
public subroutine BP00(date1, date2, rb, rp, rbp)
Frame bias and precession, IAU 2000.
Status: canonical model.
Notes
The TT date DATE1+DATE2 is a Julian Date, apportioned in any convenient way between the two arguments. For example, JD(TT)=2450123.7 could be expressed in any of these ways, among others:
    DATE1          DATE2
 2450123.7D0        0D0        (JD method)
  2451545D0      -1421.3D0     (J2000 method)
 2400000.5D0     50123.2D0     (MJD method)
 2450123.5D0       0.2D0       (date & time method)
The JD method is the most natural and convenient to use in cases where the loss of several decimal digits of resolution is acceptable. The J2000 method is best matched to the way the argument is handled internally and will deliver the optimum resolution. The MJD method and the date & time methods are both good compromises between resolution and convenience.
The matrix RB transforms vectors from GCRS to mean J2000.0 by applying frame bias.
The matrix RP transforms vectors from J2000.0 mean equator and equinox to mean equator and equinox of date by applying precession.
The matrix RBP transforms vectors from GCRS to mean equator and equinox of date by applying frame bias then precession. It is the product RP x RB.
Reference
Capitaine, N., Chapront, J., Lambert, S. and Wallace, P., "Expressions for the Celestial Intermediate Pole and Celestial Ephemeris Origin consistent with the IAU 2000A precession-nutation model", Astron.Astrophys. 400, 1145-1154 (2003)
n.b. The celestial ephemeris origin (CEO) was renamed "celestial intermediate origin" (CIO) by IAU 2006 Resolution 2.
History
IAU SOFA revision: 2013 August 21
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: date1
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(in) :: date2
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(out), dimension(3,3) :: rb
frame bias matrix (Note 2)
real(kind=wp), intent(out), dimension(3,3) :: rp
precession matrix (Note 3)
real(kind=wp), intent(out), dimension(3,3) :: rbp
bias-precession matrix (Note 4)
Calls
Called by
Contents
Source Code
BP00
Source Code
    subroutine BP00 ( date1, date2, rb, rp, rbp )
    implicit none
    real(wp),intent(in) :: date1 !! TT as a 2-part Julian Date (Note 1)
    real(wp),intent(in) :: date2 !! TT as a 2-part Julian Date (Note 1)
    real(wp),dimension(3,3),intent(out) :: rb !! frame bias matrix (Note 2)
    real(wp),dimension(3,3),intent(out) :: rp !! precession matrix (Note 3)
    real(wp),dimension(3,3),intent(out) :: rbp !! bias-precession matrix (Note 4)
    !  J2000.0 obliquity (Lieske et al. 1977)
    real(wp),parameter :: eps0 = 84381.448_wp * das2r
    real(wp) :: t, dpsibi, depsbi, dra0, psia77, oma77, chia, &
                dpsipr, depspr, psia, oma, rbw(3,3)
    !  Interval between fundamental epoch J2000.0 and current date (JC).
    t = ( ( date1-dj00 ) + date2 ) / djc
    !  Frame bias.
    call BI00 ( dpsibi, depsbi, dra0 )
    !  Precession angles (Lieske et al. 1977)
    psia77 =        ( 5038.7784_wp + &
                    (   -1.07259_wp + &
                    (   -0.001147_wp ) * t ) * t ) * t * das2r
    oma77  = eps0 + ( &
                    (    0.05127_wp + &
                    (   -0.007726_wp ) * t ) * t ) * t * das2r
    chia   =        (   10.5526_wp + &
                    (   -2.38064_wp + &
                    (   -0.001125_wp ) * t ) * t ) * t * das2r
    !  Apply IAU 2000 precession corrections.
    call PR00 ( date1, date2, dpsipr, depspr )
    psia = psia77 + dpsipr
    oma  = oma77  + depspr
    !  Frame bias matrix: GCRS to J2000.0.
    call IR ( rbw )
    call RZ ( dra0, rbw )
    call RY ( dpsibi*sin(eps0), rbw )
    call RX ( -depsbi, rbw )
    call CR ( rbw, rb )
    !  Precession matrix: J2000.0 to mean of date.
    call IR ( rp )
    call RX ( eps0, rp )
    call RZ ( -psia, rp )
    call RX ( -oma, rp )
    call RZ ( chia, rp )
    !  Bias-precession matrix: GCRS to mean of date.
    call RXR ( rp, rbw, rbp )
    end subroutine BP00
Call graph
bp00 calls rx, ir, rxr, bi00, pr00, rz
pn00 calls bp00
pmat00 calls bp00
pn00b calls pn00
pn00a calls pn00
c2tpe calls pn00
pnm00a calls pn00a
num00a calls pn00a
pnm00b calls pn00b
num00b calls pn00b
xys00a calls pnm00a
xys00b calls pnm00b
s00b calls pnm00b
c2i00b calls pnm00b
c2i00a calls pnm00a
s00a calls pnm00a
c2t00b calls c2i00b
c2t00a calls c2i00a