BP06 – astro-fortran
BP06 Subroutine
17 statements
Source File
public subroutine BP06(date1, date2, rb, rp, rbp)
Frame bias and precession, IAU 2006.
Status: support routine.
Notes
The TT date DATE1+DATE2 is a Julian Date, apportioned in any convenient way between the two arguments. For example, JD(TT)=2450123.7 could be expressed in any of these ways, among others:
    DATE1          DATE2
 2450123.7D0        0D0        (JD method)
  2451545D0      -1421.3D0     (J2000 method)
 2400000.5D0     50123.2D0     (MJD method)
 2450123.5D0       0.2D0       (date & time method)
The JD method is the most natural and convenient to use in cases where the loss of several decimal digits of resolution is acceptable. The J2000 method is best matched to the way the argument is handled internally and will deliver the optimum resolution. The MJD method and the date & time methods are both good compromises between resolution and convenience.
The matrix RB transforms vectors from GCRS to mean J2000.0 by applying frame bias.
The matrix RP transforms vectors from mean J2000.0 to mean of date by applying precession.
The matrix RBP transforms vectors from GCRS to mean of date by applying frame bias then precession. It is the product RP x RB.
References
Capitaine, N. & Wallace, P.T., 2006, Astron.Astrophys. 450, 855
Wallace, P.T. & Capitaine, N., 2006, Astron.Astrophys. 459, 981
History
IAU SOFA revision: 2013 August 21
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: date1
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(in) :: date2
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(out), dimension(3,3) :: rb
frame bias matrix (Note 2)
real(kind=wp), intent(out), dimension(3,3) :: rp
precession matrix (Note 3)
real(kind=wp), intent(out), dimension(3,3) :: rbp
bias-precession matrix (Note 4)
Calls
Contents
Source Code
BP06
Source Code
    subroutine BP06 ( date1, date2, rb, rp, rbp )
    implicit none
    real(wp),intent(in) :: date1 !! TT as a 2-part Julian Date (Note 1)
    real(wp),intent(in) :: date2 !! TT as a 2-part Julian Date (Note 1)
    real(wp),dimension(3,3),intent(out) :: rb !! frame bias matrix (Note 2)
    real(wp),dimension(3,3),intent(out) :: rp !! precession matrix (Note 3)
    real(wp),dimension(3,3),intent(out) :: rbp !! bias-precession matrix (Note 4)
    !  JD for MJD 0
    real(wp),parameter :: djm0 = 2400000.5_wp
    !  Reference epoch (J2000.0), MJD
    real(wp),parameter :: djm00 = 51544.5_wp
    real(wp) :: gamb, phib, psib, epsa, rbpw(3,3), rbt(3,3)
    !  B matrix.
    call PFW06 ( djm0, djm00, gamb, phib, psib, epsa )
    call FW2M ( gamb, phib, psib, epsa, rb )
    !  PxB matrix (temporary).
    call PMAT06 ( date1, date2, rbpw )
    !  P matrix.
    call TR ( rb, rbt )
    call RXR ( rbpw, rbt, rp )
    !  PxB matrix.
    call CR ( rbpw, rbp )
    end subroutine BP06
Call graph
bp06 calls pmat06, tr, pfw06, rxr, fw2m
pmat06 calls pfw06, fw2m
pfw06 calls obl06
fw2m calls ir, rz, rx