BPN2XY – astro-fortran
BPN2XY Subroutine
8 statements
Source File
public subroutine BPN2XY(rbpn, x, y)
Extract from the bias-precession-nutation matrix the X,Y coordinates of the Celestial Intermediate Pole.
Status: support routine.
Notes
The matrix RBPN transforms vectors from GCRS to true equator (and CIO or equinox) of date, and therefore the Celestial Intermediate Pole unit vector is the bottom row of the matrix.
X,Y are components of the Celestial Intermediate Pole unit vector in the Geocentric Celestial Reference System.
Reference
Capitaine, N., Chapront, J., Lambert, S. and Wallace, P., "Expressions for the Celestial Intermediate Pole and Celestial Ephemeris Origin consistent with the IAU 2000A precession-nutation model", Astron.Astrophys. 400, 1145-1154 (2003)
n.b. The celestial ephemeris origin (CEO) was renamed "celestial intermediate origin" (CIO) by IAU 2006 Resolution 2.
History
IAU SOFA revision: 2010 January 18
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(3,3) :: rbpn
celestial-to-true matrix (Note 1)
real(kind=wp), intent(out) :: x
Celestial Intermediate Pole (Note 2)
real(kind=wp), intent(out) :: y
Celestial Intermediate Pole (Note 2)
Called by
Contents
Source Code
BPN2XY
Source Code
    subroutine BPN2XY ( rbpn, x, y )
    implicit none
    real(wp),dimension(3,3),intent(in) :: rbpn !! celestial-to-true matrix (Note 1)
    real(wp),intent(out) :: x !! Celestial Intermediate Pole (Note 2)
    real(wp),intent(out) :: y !! Celestial Intermediate Pole (Note 2)
    !  Extract the X,Y coordinates.
    x = rbpn(3,1)
    y = rbpn(3,2)
    end subroutine BPN2XY
Call graph
s06a calls bpn2xy
c2ibpn calls bpn2xy
c2i06a calls bpn2xy
xys00a calls bpn2xy
apco13 calls bpn2xy
xys06a calls bpn2xy
gst06 calls bpn2xy
s00a calls bpn2xy
eo06a calls bpn2xy
s00b calls bpn2xy
apci13 calls bpn2xy
fw2xy calls bpn2xy
xys00b calls bpn2xy
atco13 calls apco13
gst06a calls gst06
atci13 calls apci13
atic13 calls apci13
c2i00a calls c2ibpn
c2i00b calls c2ibpn
c2t06a calls c2i06a
atoc13 calls apco13
ee06a calls gst06a
c2t00a calls c2i00a
c2t00b calls c2i00b