C2I06A – astro-fortran
C2I06A Subroutine
11 statements
Source File
public subroutine C2I06A(date1, date2, rc2i)
Form the celestial-to-intermediate matrix for a given date using the IAU 2006 precession and IAU 2000A nutation models.
Status: support routine.
Notes
The TT date DATE1+DATE2 is a Julian Date, apportioned in any convenient way between the two arguments. For example, JD(TT)=2450123.7 could be expressed in any of these ways, among others:
    DATE1          DATE2
 2450123.7D0        0D0        (JD method)
  2451545D0      -1421.3D0     (J2000 method)
 2400000.5D0     50123.2D0     (MJD method)
 2450123.5D0       0.2D0       (date & time method)
The JD method is the most natural and convenient to use in cases where the loss of several decimal digits of resolution is acceptable. The J2000 method is best matched to the way the argument is handled internally and will deliver the optimum resolution. The MJD method and the date & time methods are both good compromises between resolution and convenience.
The matrix RC2I is the first stage in the transformation from celestial to terrestrial coordinates:
[TRS]  =  RPOM * R_3(ERA) * RC2I * [CRS]
       =  RC2T * [CRS]
where [CRS] is a vector in the Geocentric Celestial Reference System and [TRS] is a vector in the International Terrestrial Reference System (see IERS Conventions 2003), ERA is the Earth Rotation Angle and RPOM is the polar motion matrix.
References
McCarthy, D. D., Petit, G. (eds.), 2004, IERS Conventions (2003), IERS Technical Note No. 32, BKG
Capitaine, N. & Wallace, P.T., 2006, Astron.Astrophys. 450, 855
Wallace, P.T. & Capitaine, N., 2006, Astron.Astrophys. 459, 981
History
IAU SOFA revision: 2007 May 11
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: date1
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(in) :: date2
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(out), dimension(3,3) :: rc2i
celestial-to-intermediate matrix (Note 2)
Calls
Called by
Contents
Source Code
C2I06A
Source Code
    subroutine C2I06A ( date1, date2, rc2i )
    implicit none
    real(wp),intent(in) :: date1 !! TT as a 2-part Julian Date (Note 1)
    real(wp),intent(in) :: date2 !! TT as a 2-part Julian Date (Note 1)
    real(wp),dimension(3,3),intent(out) :: rc2i !! celestial-to-intermediate matrix (Note 2)
    real(wp) :: rbpn(3,3), x, y, s
    !  Obtain the celestial-to-true matrix (IAU 2006/2000A).
    call PNM06A ( date1, date2, rbpn )
    !  Extract the X,Y coordinates.
    call BPN2XY ( rbpn, x, y )
    !  Obtain the CIO locator.
    s = S06 ( date1, date2, x, y )
    !  Form the celestial-to-intermediate matrix.
    call C2IXYS ( x, y, s, rc2i )
    end subroutine C2I06A
Call graph
c2i06a calls s06, bpn2xy, c2ixys, pnm06a
s06 calls fal03, faf03, fad03, faom03, fapa03, falp03, fave03, fae03
c2ixys calls ir, ry, rz
pnm06a calls pfw06, nut06a, fw2m
pfw06 calls obl06
nut06a calls nut00a
fw2m calls ir, rz, rx
nut00a calls fal03, faf03, faom03, fapa03, fave03, fae03, faur03, faju03, fame03, fasa03, fama03
c2t06a calls c2i06a