C2IBPN – astro-fortran
C2IBPN Subroutine
10 statements
Source File
public subroutine C2IBPN(date1, date2, rbpn, rc2i)
Form the celestial-to-intermediate matrix for a given date given the bias-precession-nutation matrix. IAU 2000.
Status: support routine.
Notes
The TT date DATE1+DATE2 is a Julian Date, apportioned in any convenient way between the two arguments. For example, JD(TT)=2450123.7 could be expressed in any of these ways, among others:
    DATE1          DATE2
 2450123.7D0        0D0        (JD method)
  2451545D0      -1421.3D0     (J2000 method)
 2400000.5D0     50123.2D0     (MJD method)
 2450123.5D0       0.2D0       (date & time method)
The JD method is the most natural and convenient to use in cases where the loss of several decimal digits of resolution is acceptable. The J2000 method is best matched to the way the argument is handled internally and will deliver the optimum resolution. The MJD method and the date & time methods are both good compromises between resolution and convenience.
The matrix RBPN transforms vectors from GCRS to true equator (and CIO or equinox) of date. Only the CIP (bottom row) is used.
The matrix RC2I is the first stage in the transformation from celestial to terrestrial coordinates:
[TRS]  =  RPOM * R_3(ERA) * RC2I * [CRS]
       =  RC2T * [CRS]
where [CRS] is a vector in the Geocentric Celestial Reference System and [TRS] is a vector in the International Terrestrial Reference System (see IERS Conventions 2003), ERA is the Earth Rotation Angle and RPOM is the polar motion matrix.
Although its name does not include "00", this routine is in fact specific to the IAU 2000 models.
References
Capitaine, N., Chapront, J., Lambert, S. and Wallace, P., "Expressions for the Celestial Intermediate Pole and Celestial Ephemeris Origin consistent with the IAU 2000A precession-nutation model", Astron.Astrophys. 400, 1145-1154 (2003)
n.b. The celestial ephemeris origin (CEO) was renamed "celestial intermediate origin" (CIO) by IAU 2006 Resolution 2.
McCarthy, D. D., Petit, G. (eds.), IERS Conventions (2003), IERS Technical Note No. 32, BKG (2004)
History
IAU SOFA revision: 2010 January 18
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: date1
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(in) :: date2
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(in), dimension(3,3) :: rbpn
celestial-to-true matrix (Note 2)
real(kind=wp), intent(out), dimension(3,3) :: rc2i
celestial-to-intermediate matrix (Note 3)
Calls
Called by
Contents
Source Code
C2IBPN
Source Code
    subroutine C2IBPN ( date1, date2, rbpn, rc2i )
    implicit none
    real(wp),intent(in) :: date1 !! TT as a 2-part Julian Date (Note 1)
    real(wp),intent(in) :: date2 !! TT as a 2-part Julian Date (Note 1)
    real(wp),dimension(3,3),intent(in) :: rbpn !! celestial-to-true matrix (Note 2)
    real(wp),dimension(3,3),intent(out) :: rc2i !! celestial-to-intermediate matrix (Note 3)
    real(wp) :: x, y
    !  Extract the X,Y coordinates.
    call BPN2XY ( rbpn, x, y )
    !  Form the celestial-to-intermediate matrix (n.b. IAU 2000 specific).
    call C2IXY ( date1, date2, x, y, rc2i )
    end subroutine C2IBPN
Call graph
c2ibpn calls bpn2xy, c2ixy
c2ixy calls s00
s00 calls fal03, faf03, fad03, faom03, fapa03, falp03, fave03, fae03
c2i00b calls c2ibpn
c2i00a calls c2ibpn
c2t00b calls c2i00b
c2t00a calls c2i00a