C2IXY – astro-fortran
C2IXY Subroutine
9 statements
Source File
public subroutine C2IXY(date1, date2, x, y, rc2i)
Form the celestial to intermediate-frame-of-date matrix for a given date when the CIP X,Y coordinates are known. IAU 2000.
Status: support routine.
Notes
The TT date DATE1+DATE2 is a Julian Date, apportioned in any convenient way between the two arguments. For example, JD(TT)=2450123.7 could be expressed in any of these ways, among others:
    DATE1          DATE2
 2450123.7D0        0D0        (JD method)
  2451545D0      -1421.3D0     (J2000 method)
 2400000.5D0     50123.2D0     (MJD method)
 2450123.5D0       0.2D0       (date & time method)
The JD method is the most natural and convenient to use in cases where the loss of several decimal digits of resolution is acceptable. The J2000 method is best matched to the way the argument is handled internally and will deliver the optimum resolution. The MJD method and the date & time methods are both good compromises between resolution and convenience.
The Celestial Intermediate Pole coordinates are the x,y components of the unit vector in the Geocentric Celestial Reference System.
The matrix RC2I is the first stage in the transformation from celestial to terrestrial coordinates:
[TRS]  =  RPOM * R_3(ERA) * RC2I * [CRS]
       =  RC2T * [CRS]
where [CRS] is a vector in the Geocentric Celestial Reference System and [TRS] is a vector in the International Terrestrial Reference System (see IERS Conventions 2003), ERA is the Earth Rotation Angle and RPOM is the polar motion matrix.
Although its name does not include "00", this routine is in fact specific to the IAU 2000 models.
Reference
McCarthy, D. D., Petit, G. (eds.), IERS Conventions (2003), IERS Technical Note No. 32, BKG (2004)
History
IAU SOFA revision: 2007 June 1
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: date1
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(in) :: date2
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(in) :: x
Celestial Intermediate Pole (Note 2)
real(kind=wp), intent(in) :: y
Celestial Intermediate Pole (Note 2)
real(kind=wp), intent(out), dimension(3,3) :: rc2i
celestial-to-intermediate matrix (Note 3)
Calls
Called by
Contents
Source Code
C2IXY
Source Code
    subroutine C2IXY ( date1, date2, x, y, rc2i )
    implicit none
    real(wp),intent(in) :: date1 !! TT as a 2-part Julian Date (Note 1)
    real(wp),intent(in) :: date2 !! TT as a 2-part Julian Date (Note 1)
    real(wp),intent(in) :: x !! Celestial Intermediate Pole (Note 2)
    real(wp),intent(in) :: y !! Celestial Intermediate Pole (Note 2)
    real(wp),dimension(3,3),intent(out) :: rc2i !! celestial-to-intermediate matrix (Note 3)
    !  Compute s and then the matrix.
    call C2IXYS ( x, y, S00 ( date1, date2, x, y ), rc2i )
    end subroutine C2IXY
Call graph
c2ixy calls c2ixys, s00
c2ixys calls ir, ry, rz
s00 calls faom03, fad03, falp03, fae03, fal03, fapa03, faf03, fave03
c2txy calls c2ixy
c2ibpn calls c2ixy
c2i00a calls c2ibpn
c2i00b calls c2ibpn
c2t00a calls c2i00a
c2t00b calls c2i00b