C2IXYS – astro-fortran
C2IXYS Subroutine
19 statements
Source File
public subroutine C2IXYS(x, y, s, rc2i)
Form the celestial to intermediate-frame-of-date matrix given the CIP X,Y and the CIO locator s.
Status: support routine.
Notes
The Celestial Intermediate Pole coordinates are the x,y components of the unit vector in the Geocentric Celestial Reference System.
The CIO locator s (in radians) positions the Celestial Intermediate Origin on the equator of the CIP.
The matrix RC2I is the first stage in the transformation from celestial to terrestrial coordinates:
[TRS]  =  RPOM * R_3(ERA) * RC2I * [CRS]
       =  RC2T * [CRS]
where [CRS] is a vector in the Geocentric Celestial Reference System and [TRS] is a vector in the International Terrestrial Reference System (see IERS Conventions 2003), ERA is the Earth Rotation Angle and RPOM is the polar motion matrix.
Reference
McCarthy, D. D., Petit, G. (eds.), IERS Conventions (2003), IERS Technical Note No. 32, BKG (2004)
History
IAU SOFA revision: 2014 November 7
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: x
Celestial Intermediate Pole (Note 1)
real(kind=wp), intent(in) :: y
Celestial Intermediate Pole (Note 1)
real(kind=wp), intent(in) :: s
the CIO locator s (Note 2)
real(kind=wp), intent(out), dimension(3,3) :: rc2i
celestial-to-intermediate matrix (Note 3)
Calls
Called by
Contents
Source Code
C2IXYS
Source Code
    subroutine C2IXYS ( x, y, s, rc2i )
    implicit none
    real(wp),intent(in) :: x !! Celestial Intermediate Pole (Note 1)
    real(wp),intent(in) :: y !! Celestial Intermediate Pole (Note 1)
    real(wp),intent(in) :: s !! the CIO locator s (Note 2)
    real(wp),dimension(3,3),intent(out) :: rc2i !! celestial-to-intermediate matrix (Note 3)
    real(wp) :: r2, e, d
    !  Obtain the spherical angles E and d.
    r2 = x*x+y*y
    if ( r2>0.0_wp ) then
       e = atan2 ( y, x )
    else
       e = 0.0_wp
    end if
    d = atan ( sqrt ( r2 / (1.0_wp-r2) ) )
    !  Form the matrix.
    call IR ( rc2i )
    call RZ ( e, rc2i )
    call RY ( d, rc2i )
    call RZ ( -(e+s), rc2i )
    end subroutine C2IXYS
Call graph
c2ixys calls ir, rz, ry
apci calls c2ixys
apco calls c2ixys
c2ixy calls c2ixys
c2i06a calls c2ixys
c2txy calls c2ixy
c2ibpn calls c2ixy
apci13 calls apci
apco13 calls apco
c2t06a calls c2i06a
atoc13 calls apco13
c2i00b calls c2ibpn
atci13 calls apci13
atic13 calls apci13
atco13 calls apco13
c2i00a calls c2ibpn
c2t00a calls c2i00a
c2t00b calls c2i00b