C2S – astro-fortran
C2S Subroutine
21 statements
Source File
public subroutine C2S(p, theta, phi)
P-vector to spherical coordinates.
Status: vector/matrix support routine.
Notes
P can have any magnitude; only its direction is used.
If P is null, zero THETA and PHI are returned.
At either pole, zero THETA is returned.
History
IAU SOFA revision: 2007 April 11
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(3) :: p
p-vector
real(kind=wp), intent(out) :: theta
longitude angle (radians)
real(kind=wp), intent(out) :: phi
latitude angle (radians)
Called by
Contents
Source Code
C2S
Source Code
    subroutine C2S ( p, theta, phi )
    implicit none
    real(wp),dimension(3),intent(in) :: p !! p-vector
    real(wp),intent(out) :: theta !! longitude angle (radians)
    real(wp),intent(out) :: phi !! latitude angle (radians)
    real(wp) :: x, y, z, d2
    x = p(1)
    y = p(2)
    z = p(3)
    d2 = x*x + y*y
    if ( d2 == 0.0_wp ) then
       theta = 0.0_wp
    else
       theta = atan2(y,x)
    end if
    if ( z == 0.0_wp ) then
       phi = 0.0_wp
    else
       phi = atan2(z,sqrt(d2))
    end if
    end subroutine C2S
Call graph
lteceq calls c2s
atoiq calls c2s
aticq calls c2s
atioq calls c2s
atciqz calls c2s
fk45z calls c2s
eqec06 calls c2s
fk5hz calls c2s
g2icrs calls c2s
p2s calls c2s
lteqec calls c2s
fk54z calls c2s
icrs2g calls c2s
eceq06 calls c2s
aticqn calls c2s
atciqn calls c2s
atciq calls c2s
atoc13 calls atoiq, aticq
atci13 calls atciq
atic13 calls aticq
atco13 calls atioq, atciq
atio13 calls atioq
atoi13 calls atoiq