C2T00A – astro-fortran
C2T00A Subroutine
16 statements
Source File
public subroutine C2T00A(tta, ttb, uta, utb, xp, yp, rc2t)
Form the celestial to terrestrial matrix given the date, the UT1 and the polar motion, using the IAU 2000A nutation model.
Status: support routine.
Notes
The TT and UT1 dates TTA+TTB and UTA+UTB are Julian Dates, apportioned in any convenient way between the arguments UTA and UTB. For example, JD(UT1)=2450123.7 could be expressed in any of these ways, among others:
     UTA            UTB
 2450123.7D0        0D0        (JD method)
  2451545D0      -1421.3D0     (J2000 method)
 2400000.5D0     50123.2D0     (MJD method)
 2450123.5D0       0.2D0       (date & time method)
The JD method is the most natural and convenient to use in cases where the loss of several decimal digits of resolution is acceptable. The J2000 and MJD methods are good compromises between resolution and convenience. In the case of UTA,UTB, the date & time method is best matched to the Earth rotation angle algorithm used: maximum accuracy (or, at least, minimum noise) is delivered when the UTA argument is for 0hrs UT1 on the day in question and the UTB argument lies in the range 0 to 1, or vice versa.
XP and YP are the coordinates (in radians) of the Celestial Intermediate Pole with respect to the International Terrestrial Reference System (see IERS Conventions 2003), measured along the meridians to 0 and 90 deg west respectively.
The matrix RC2T transforms from celestial to terrestrial coordinates:
[TRS]  =  RPOM * R_3(ERA) * RC2I * [CRS]
       =  RC2T * [CRS]
where [CRS] is a vector in the Geocentric Celestial Reference System and [TRS] is a vector in the International Terrestrial Reference System (see IERS Conventions 2003), RC2I is the celestial-to-intermediate matrix, ERA is the Earth rotation angle and RPOM is the polar motion matrix.
A faster, but slightly less accurate result (about 1 mas), can be obtained by using instead the C2T00B routine.
Reference
McCarthy, D. D., Petit, G. (eds.), IERS Conventions (2003), IERS Technical Note No. 32, BKG (2004)
History
IAU SOFA revision: 2009 April 1
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: tta
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(in) :: ttb
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(in) :: uta
UT1 as a 2-part Julian Date (Note 1)
real(kind=wp), intent(in) :: utb
UT1 as a 2-part Julian Date (Note 1)
real(kind=wp), intent(in) :: xp
coordinates of the pole (radians, Note 2)
real(kind=wp), intent(in) :: yp
coordinates of the pole (radians, Note 2)
real(kind=wp), intent(out), dimension(3,3) :: rc2t
celestial-to-terrestrial matrix (Note 3)
Calls
Contents
Source Code
C2T00A
Source Code
    subroutine C2T00A ( tta, ttb, uta, utb, xp, yp, rc2t )
    implicit none
    real(wp),intent(in) :: tta !! TT as a 2-part Julian Date (Note 1)
    real(wp),intent(in) :: ttb !! TT as a 2-part Julian Date (Note 1)
    real(wp),intent(in) :: uta !! UT1 as a 2-part Julian Date (Note 1)
    real(wp),intent(in) :: utb !! UT1 as a 2-part Julian Date (Note 1)
    real(wp),intent(in) :: xp !! coordinates of the pole (radians, Note 2)
    real(wp),intent(in) :: yp !! coordinates of the pole (radians, Note 2)
    real(wp),dimension(3,3),intent(out) :: rc2t !! celestial-to-terrestrial matrix (Note 3)
    real(wp) :: rc2i(3,3), era, sp, rpom(3,3)
    !  Form the celestial-to-intermediate matrix for this TT (IAU 2000A).
    call C2I00A ( tta, ttb, rc2i )
    !  Predict the Earth rotation angle for this UT1.
    era = ERA00 ( uta, utb )
    !  Estimate s'.
    sp = SP00 ( tta, ttb )
    !  Form the polar motion matrix.
    call POM00 ( xp, yp, sp, rpom )
    !  Combine to form the celestial-to-terrestrial matrix.
    call C2TCIO ( rc2i, era, rpom, rc2t )
    end subroutine C2T00A
Call graph
c2t00a calls c2tcio, pom00, sp00, c2i00a, era00
c2tcio calls rxr, rz
pom00 calls rx, ir, ry, rz
c2i00a calls pnm00a, c2ibpn
era00 calls anp
pnm00a calls pn00a
c2ibpn calls c2ixy, bpn2xy
c2ixy calls c2ixys, s00
pn00a calls pn00, nut00a
c2ixys calls ir, ry, rz
s00 calls faom03, fad03, falp03, fae03, fal03, fapa03, faf03, fave03
pn00 calls rxr, obl80, bp00, numat, pr00
nut00a calls faom03, faur03, faju03, fame03, fasa03, fae03, fal03, fapa03, faf03, fave03, fama03
bp00 calls rx, ir, ry, rxr, rz, pr00, bi00
numat calls rx, ir, rz