C2TCIO – astro-fortran
C2TCIO Subroutine
11 statements
Source File
public subroutine C2TCIO(rc2i, era, rpom, rc2t)
Assemble the celestial to terrestrial matrix from CIO-based components (the celestial-to-intermediate matrix, the Earth Rotation Angle and the polar motion matrix).
Status: support routine.
Notes
This routine constructs the rotation matrix that transforms vectors in the celestial system into vectors in the terrestrial system. It does so starting from precomputed components, namely the matrix which rotates from celestial coordinates to the intermediate frame, the Earth rotation angle and the polar motion matrix. One use of the present routine is when generating a series of celestial-to-terrestrial matrices where only the Earth Rotation Angle changes, avoiding the considerable overhead of recomputing the precession-nutation more often than necessary to achieve given accuracy objectives.
The relationship between the arguments is as follows:
[TRS]  =  RPOM * R_3(ERA) * RC2I * [CRS]
       =  RC2T * [CRS]
where [CRS] is a vector in the Geocentric Celestial Reference System and [TRS] is a vector in the International Terrestrial Reference System (see IERS Conventions 2003).
Reference
McCarthy, D. D., Petit, G. (eds.), 2004, IERS Conventions (2003), IERS Technical Note No. 32, BKG
History
IAU SOFA revision: 2013 August 24
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(3,3) :: rc2i
celestial-to-intermediate matrix
real(kind=wp), intent(in) :: era
Earth rotation angle (radians)
real(kind=wp), intent(in), dimension(3,3) :: rpom
polar-motion matrix
real(kind=wp), intent(out), dimension(3,3) :: rc2t
celestial-to-terrestrial matrix
Calls
Called by
Contents
Source Code
C2TCIO
Source Code
    subroutine C2TCIO ( rc2i, era, rpom, rc2t )
    implicit none
    real(wp),dimension(3,3),intent(in) :: rc2i !! celestial-to-intermediate matrix
    real(wp),intent(in) :: era !! Earth rotation angle (radians)
    real(wp),dimension(3,3),intent(in) :: rpom !! polar-motion matrix
    real(wp),dimension(3,3),intent(out) :: rc2t !! celestial-to-terrestrial matrix
    real(wp) :: r(3,3)
    !  Construct the matrix.
    call CR ( rc2i, r )
    call RZ ( era, r )
    call RXR ( rpom, r, rc2t )
    end subroutine C2TCIO
Call graph
c2tcio calls rz, rxr
c2t00a calls c2tcio
c2txy calls c2tcio
c2tceo calls c2tcio
c2t06a calls c2tcio
c2t00b calls c2tcio