C2TCEO – astro-fortran
C2TCEO Subroutine
8 statements
Source File
public subroutine C2TCEO(rc2i, era, rpom, rc2t)
Assemble the celestial to terrestrial matrix from CIO-based components (the celestial-to-intermediate matrix, the Earth Rotation Angle and the polar motion matrix).
Status: obsolete routine.
Notes
The name of the present routine, C2TCEO, reflects the original name of the celestial intermediate origin (CIO), which before the adoption of IAU 2006 Resolution 2 was called the "celestial ephemeris origin" (CEO).
When the name change from CEO to CIO occurred, a new SOFA routine called C2TCIO was introduced as the successor to the existing C2TCEO. The present routine is merely a front end to the new one.
The present routine is included in the SOFA collection only to support existing applications. It should not be used in new applications.
History
IAU SOFA revision: 2007 May 9
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(3,3) :: rc2i
celestial-to-intermediate matrix
real(kind=wp), intent(in) :: era
Earth rotation angle
real(kind=wp), intent(in), dimension(3,3) :: rpom
polar-motion matrix
real(kind=wp), intent(out), dimension(3,3) :: rc2t
celestial-to-terrestrial matrix
Calls
Contents
Source Code
C2TCEO
Source Code
    subroutine C2TCEO ( rc2i, era, rpom, rc2t )
    implicit none
    real(wp),dimension(3,3),intent(in) :: rc2i !! celestial-to-intermediate matrix
    real(wp),intent(in) :: era !! Earth rotation angle
    real(wp),dimension(3,3),intent(in) :: rpom !! polar-motion matrix
    real(wp),dimension(3,3),intent(out) :: rc2t !! celestial-to-terrestrial matrix
    !  Call the renamed routine.
    call C2TCIO ( rc2i, era, rpom, rc2t )
    end subroutine C2TCEO
Call graph
c2tceo calls c2tcio
c2tcio calls rxr, rz