C2TPE – astro-fortran
C2TPE Subroutine
19 statements
Source File
public subroutine C2TPE(tta, ttb, uta, utb, dpsi, deps, xp, yp, rc2t)
Form the celestial to terrestrial matrix given the date, the UT1, the nutation and the polar motion. IAU 2000.
Status: support routine.
Notes
The TT and UT1 dates TTA+TTB and UTA+UTB are Julian Dates, apportioned in any convenient way between the arguments UTA and UTB. For example, JD(UT1)=2450123.7 could be expressed in any of these ways, among others:
     UTA            UTB
 2450123.7D0        0D0        (JD method)
  2451545D0      -1421.3D0     (J2000 method)
 2400000.5D0     50123.2D0     (MJD method)
 2450123.5D0       0.2D0       (date & time method)
The JD method is the most natural and convenient to use in cases where the loss of several decimal digits of resolution is acceptable. The J2000 and MJD methods are good compromises between resolution and convenience. In the case of UTA,UTB, the date & time method is best matched to the Earth rotation angle algorithm used: maximum accuracy (or, at least, minimum noise) is delivered when the UTA argument is for 0hrs UT1 on the day in question and the UTB argument lies in the range 0 to 1, or vice versa.
The caller is responsible for providing the nutation components; they are in longitude and obliquity, in radians and are with respect to the equinox and ecliptic of date. For high-accuracy applications, free core nutation should be included as well as any other relevant corrections to the position of the CIP.
XP and YP are the coordinates (in radians) of the Celestial Intermediate Pole with respect to the International Terrestrial Reference System (see IERS Conventions 2003), measured along the meridians to 0 and 90 deg west respectively.
The matrix RC2T transforms from celestial to terrestrial coordinates:
[TRS]  =  RPOM * R_3(GST) * RBPN * [CRS]
       =  RC2T * [CRS]
where [CRS] is a vector in the Geocentric Celestial Reference System and [TRS] is a vector in the International Terrestrial Reference System (see IERS Conventions 2003), RBPN is the bias-precession-nutation matrix, GST is the Greenwich (apparent) Sidereal Time and RPOM is the polar motion matrix.
Although its name does not include "00", this routine is in fact specific to the IAU 2000 models.
Reference
McCarthy, D. D., Petit, G. (eds.), IERS Conventions (2003), IERS Technical Note No. 32, BKG (2004)
History
IAU SOFA revision: 2009 April 1
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: tta
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(in) :: ttb
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(in) :: uta
UT1 as a 2-part Julian Date (Note 1)
real(kind=wp), intent(in) :: utb
UT1 as a 2-part Julian Date (Note 1)
real(kind=wp), intent(in) :: dpsi
nutation (Note 2)
real(kind=wp), intent(in) :: deps
nutation (Note 2)
real(kind=wp), intent(in) :: xp
coordinates of the pole (radians, Note 3)
real(kind=wp), intent(in) :: yp
coordinates of the pole (radians, Note 3)
real(kind=wp), intent(out), dimension(3,3) :: rc2t
celestial-to-terrestrial matrix (Note 4)
Calls
Contents
Source Code
C2TPE
Source Code
    subroutine C2TPE ( tta, ttb, uta, utb, dpsi, deps, xp, yp, &
                       rc2t )
    implicit none
    real(wp),intent(in) :: tta !! TT as a 2-part Julian Date (Note 1)
    real(wp),intent(in) :: ttb !! TT as a 2-part Julian Date (Note 1)
    real(wp),intent(in) :: uta !! UT1 as a 2-part Julian Date (Note 1)
    real(wp),intent(in) :: utb !! UT1 as a 2-part Julian Date (Note 1)
    real(wp),intent(in) :: dpsi !! nutation (Note 2)
    real(wp),intent(in) :: deps !! nutation (Note 2)
    real(wp),intent(in) :: xp !! coordinates of the pole (radians, Note 3)
    real(wp),intent(in) :: yp !! coordinates of the pole (radians, Note 3)
    real(wp),dimension(3,3),intent(out) :: rc2t !! celestial-to-terrestrial matrix (Note 4)
    real(wp) :: epsa, rb(3,3), rp(3,3), rbp(3,3), rn(3,3), &
                rbpn(3,3), gmst, ee, sp, rpom(3,3)
    !  Form the celestial-to-true matrix for this TT.
    call PN00 ( tta, ttb, dpsi, deps, &
                    epsa, rb, rp, rbp, rn, rbpn )
    !  Predict the Greenwich Mean Sidereal Time for this UT1 and TT.
    gmst = GMST00 ( uta, utb, tta, ttb )
    !  Predict the equation of the equinoxes given TT and nutation.
    ee = EE00 ( tta, ttb, epsa, dpsi)
    !  Estimate s'.
    sp = SP00 ( tta, ttb)
    !  Form the polar motion matrix.
    call POM00 ( xp, yp, sp, rpom )
    !  Combine to form the celestial-to-terrestrial matrix.
    call C2TEQX ( rbpn, gmst+ee, rpom, rc2t )
    end subroutine C2TPE
Call graph
c2tpe calls gmst00, ee00, pn00, c2teqx, pom00, sp00
gmst00 calls anp, era00
ee00 calls eect00
pn00 calls obl80, bp00, rxr, numat, pr00
c2teqx calls rxr, rz
pom00 calls rx, ir, ry, rz
bp00 calls rx, ir, rxr, ry, rz, pr00, bi00
numat calls rx, ir, rz
eect00 calls faom03, fad03, falp03, fae03, fal03, fapa03, faf03, fave03
era00 calls anp