CAL2JD – astro-fortran
CAL2JD Subroutine
31 statements
Source File
public subroutine CAL2JD(iy, im, id, djm0, djm, j)
Gregorian Calendar to Julian Date.
Status: support routine.
Notes
The algorithm used is valid from -4800 March 1, but this implementation rejects dates before -4799 January 1.
The Julian Date is returned in two pieces, in the usual SOFA manner, which is designed to preserve time resolution. The Julian Date is available as a single number by adding DJM0 and DJM.
In early eras the conversion is from the "Proleptic Gregorian Calendar"; no account is taken of the date(s) of adoption of the Gregorian Calendar, nor is the AD/BC numbering convention observed.
Reference
Explanatory Supplement to the Astronomical Almanac, P. Kenneth Seidelmann (ed), University Science Books (1992), Section 12.92 (p604).
History
IAU SOFA revision: 2014 November 7
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: iy
year in Gregorian calendar (Note 1)
integer, intent(in) :: im
month in Gregorian calendar (Note 1)
integer, intent(in) :: id
day in Gregorian calendar (Note 1)
real(kind=wp), intent(out) :: djm0
MJD zero-point: always 2400000.5
real(kind=wp), intent(out) :: djm
Modified Julian Date for 0 hrs
integer, intent(out) :: j
0 = OK
-1 = bad year (Note 3: JD not computed)
-2 = bad month (JD not computed)
-3 = bad day (JD computed)
Called by
Contents
Source Code
CAL2JD
Source Code
    subroutine CAL2JD ( iy, im, id, djm0, djm, j )
    implicit none
    integer,intent(in) :: iy !! year in Gregorian calendar (Note 1)
    integer,intent(in) :: im !! month in Gregorian calendar (Note 1)
    integer,intent(in) :: id !! day in Gregorian calendar (Note 1)
    real(wp),intent(out) :: djm0 !! MJD zero-point: always 2400000.5
    real(wp),intent(out) :: djm !! Modified Julian Date for 0 hrs
    integer,intent(out) :: j !! status:
                             !! *  0 = OK
                             !! * -1 = bad year   (Note 3: JD not computed)
                             !! * -2 = bad month  (JD not computed)
                             !! * -3 = bad day    (JD computed)
    integer :: ndays, my, iypmy
    !  Earliest year allowed (4800BC)
    integer,parameter :: iymin = -4799
    !  Month lengths in days
    integer,dimension(12),parameter :: mtab = [31,28,31,30,31,30,31,31,30,31,30,31]
    !  Preset status.
    j = 0
    !  Validate year.
    if ( iy<iymin ) then
       j = -1
    else
       !  Validate month.
       if ( im>=1 .and. im<=12 ) then
          !  Days in current month.
          ndays = mtab(im)
          !  Allow for leap year.
          if ( im == 2 ) then
             if ( mod(iy,4) == 0 ) ndays = 29
             if ( mod(iy,100)==0 .and. &
                  mod(iy,400)/=0 ) ndays = 28
          end if
          !  Validate day.
          if ( id<1 .or. id>ndays ) j = -3
          !  Result.
          my = ( im - 14 ) / 12
          iypmy = iy + my
          djm0 = 2400000.5_wp
          djm = real( ( 1461 * ( iypmy + 4800 ) ) / 4 &
                    + (  367 * ( im-2 - 12*my ) ) / 12 &
                    - (    3 * ( ( iypmy + 4900 ) / 100 ) ) / 4 &
                    + id - 2432076, wp)
          !  Bad month
       else
          j = -2
       end if
    end if
    end subroutine CAL2JD
Call graph
utctai calls cal2jd, dat
dat calls cal2jd
dtf2d calls cal2jd, dat
ut1utc calls cal2jd, dat
apio13 calls utctai, utcut1
taiutc calls utctai
utcut1 calls utctai, dat
apco13 calls utctai, utcut1
d2dtf calls dat
atoc13 calls apco13
atio13 calls apio13
atoi13 calls apio13
atco13 calls apco13