ECEQ06 – astro-fortran
ECEQ06 Subroutine
16 statements
Source File
public subroutine ECEQ06(date1, date2, dl, db, dr, dd)
Transformation from ecliptic coordinates (mean equinox and ecliptic of date) to ICRS RA,Dec, using the IAU 2006 precession model.
Status: support routine.
Notes
The TT date DATE1+DATE2 is a Julian Date, apportioned in any convenient way between the two arguments. For example, JD(TT)=2450123.7 could be expressed in any of these ways, among others:
    DATE1          DATE2
 2450123.7D0        0D0        (JD method)
  2451545D0      -1421.3D0     (J2000 method)
 2400000.5D0     50123.2D0     (MJD method)
 2450123.5D0       0.2D0       (date & time method)
The JD method is the most natural and convenient to use in cases where the loss of several decimal digits of resolution is acceptable. The J2000 method is best matched to the way the argument is handled internally and will deliver the optimum resolution. The MJD method and the date & time methods are both good compromises between resolution and convenience.
No assumptions are made about whether the coordinates represent starlight and embody astrometric effects such as parallax or aberration.
The transformation is approximately that from ecliptic longitude and latitude (mean equinox and ecliptic of date) to mean J2000.0 right ascension and declination, with only frame bias (always less than 25 mas) to disturb this classical picture.
History
IAU SOFA revision: 2016 February 9
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: date1
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(in) :: date2
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(in) :: dl
ecliptic longitude and latitude (radians)
real(kind=wp), intent(in) :: db
ecliptic longitude and latitude (radians)
real(kind=wp), intent(out) :: dr
ICRS right ascension and declination (radians)
real(kind=wp), intent(out) :: dd
ICRS right ascension and declination (radians)
Calls
Contents
Source Code
ECEQ06
Source Code
    subroutine ECEQ06 ( date1, date2, dl, db, dr, dd )
    implicit none
    real(wp),intent(in) :: date1 !! TT as a 2-part Julian Date (Note 1)
    real(wp),intent(in) :: date2 !! TT as a 2-part Julian Date (Note 1)
    real(wp),intent(in) :: dl !! ecliptic longitude and latitude (radians)
    real(wp),intent(in) :: db !! ecliptic longitude and latitude (radians)
    real(wp),intent(out) :: dr !! ICRS right ascension and declination (radians)
    real(wp),intent(out) :: dd !! ICRS right ascension and declination (radians)
    real(wp) :: rm(3,3), v1(3), v2(3), a, b
    !  Spherical to Cartesian.
    call S2C ( dl, db, v1 )
    !  Rotation matrix, ICRS equatorial to ecliptic.
    call ECM06 ( date1, date2, rm )
    !  The transformation from ecliptic to ICRS.
    call TRXP ( rm, v1, v2 )
    !  Cartesian to spherical.
    call C2S ( v2, a, b )
    !  Express in conventional ranges.
    dr = ANP ( a )
    dd = ANPM ( b )
    end subroutine ECEQ06
Call graph
eceq06 calls s2c, trxp, anpm, c2s, ecm06, anp
trxp calls rxp, tr
ecm06 calls rx, pmat06, obl06, ir, rxr
pmat06 calls pfw06, fw2m
pfw06 calls obl06
fw2m calls rx, ir, rz