ECM06 – astro-fortran
ECM06 Subroutine
12 statements
Source File
public subroutine ECM06(date1, date2, rm)
ICRS equatorial to ecliptic rotation matrix, IAU 2006.
Status: support routine.
Notes
The TT date DATE1+DATE2 is a Julian Date, apportioned in any convenient way between the two arguments. For example, JD(TT)=2450123.7 could be expressed in any of these ways, among others:
    DATE1          DATE2
 2450123.7D0        0D0        (JD method)
  2451545D0      -1421.3D0     (J2000 method)
 2400000.5D0     50123.2D0     (MJD method)
 2450123.5D0       0.2D0       (date & time method)
The JD method is the most natural and convenient to use in cases where the loss of several decimal digits of resolution is acceptable. The J2000 method is best matched to the way the argument is handled internally and will deliver the optimum resolution. The MJD method and the date & time methods are both good compromises between resolution and convenience.
The matrix is in the sense
E_ep = RM x P_ICRS,
where P_ICRS is a vector with respect to ICRS right ascension and declination axes and E_ep is the same vector with respect to the (inertial) ecliptic and equinox of date.
P_ICRS is a free vector, merely a direction, typically of unit magnitude, and not bound to any particular spatial origin, such as the Earth, Sun or SSB. No assumptions are made about whether it represents starlight and embodies astrometric effects such as parallax or aberration. The transformation is approximately that between mean J2000.0 right ascension and declination and ecliptic longitude and latitude, with only frame bias (always less than 25 mas) to disturb this classical picture.
History
IAU SOFA revision: 2015 December 11
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: date1
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(in) :: date2
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(out), dimension(3,3) :: rm
ICRS to ecliptic rotation matrix
Calls
Called by
Contents
Source Code
ECM06
Source Code
    subroutine ECM06 ( date1, date2, rm )
    implicit none
    real(wp),intent(in) :: date1 !! TT as a 2-part Julian Date (Note 1)
    real(wp),intent(in) :: date2 !! TT as a 2-part Julian Date (Note 1)
    real(wp),dimension(3,3),intent(out) :: rm !! ICRS to ecliptic rotation matrix
    real(wp) :: ob, bp(3,3), e(3,3)
    !  Obliquity, IAU 2006.
    ob = OBL06 ( date1, date2 )
    !  Precession-bias matrix, IAU 2006.
    call PMAT06 ( date1, date2, bp )
    !  Equatorial of date to ecliptic matrix.
    call IR ( e )
    call RX ( ob, e )
    !  ICRS to ecliptic coordinates rotation matrix, IAU 2006.
    call RXR ( e, bp, rm )
    end subroutine ECM06
Call graph
ecm06 calls pmat06, obl06, ir, rx, rxr
pmat06 calls pfw06, fw2m
pfw06 calls obl06
fw2m calls ir, rx, rz
eceq06 calls ecm06
eqec06 calls ecm06