EE00B – astro-fortran
EE00B Function
11 statements
Source File
public function EE00B(date1, date2) result(res)
Equation of the equinoxes, compatible with IAU 2000 resolutions but using the truncated nutation model IAU 2000B.
Status: support routine.
Notes
The TT date DATE1+DATE2 is a Julian Date, apportioned in any convenient way between the two arguments. For example, JD(TT)=2450123.7 could be expressed in any of these ways, among others:
    DATE1          DATE2
 2450123.7D0        0D0        (JD method)
  2451545D0      -1421.3D0     (J2000 method)
 2400000.5D0     50123.2D0     (MJD method)
 2450123.5D0       0.2D0       (date & time method)
The JD method is the most natural and convenient to use in cases where the loss of several decimal digits of resolution is acceptable. The J2000 method is best matched to the way the argument is handled internally and will deliver the optimum resolution. The MJD method and the date & time methods are both good compromises between resolution and convenience.
The result, which is in radians, operates in the following sense:
Greenwich apparent ST = GMST + equation of the equinoxes
The result is compatible with the IAU 2000 resolutions except that accuracy has been compromised for the sake of speed. For further details, see McCarthy & Luzum (2001), IERS Conventions 2003 and Capitaine et al. (2003).
References
Capitaine, N., Wallace, P.T. and McCarthy, D.D., "Expressions to implement the IAU 2000 definition of UT1", Astronomy & Astrophysics, 406, 1135-1149 (2003)
McCarthy, D.D. & Luzum, B.J., "An abridged model of the precession-nutation of the celestial pole", Celestial Mechanics & Dynamical Astronomy, 85, 37-49 (2003)
McCarthy, D. D., Petit, G. (eds.), IERS Conventions (2003), IERS Technical Note No. 32, BKG (2004)
History
IAU SOFA revision: 2006 November 13
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: date1
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(in) :: date2
TT as a 2-part Julian Date (Note 1)
Return Value real(kind=wp)
equation of the equinoxes (Note 2)
Calls
Called by
Contents
Source Code
EE00B
Source Code
    function EE00B ( date1, date2 ) result(res)
    implicit none
    real(wp),intent(in) :: date1 !!  TT as a 2-part Julian Date (Note 1)
    real(wp),intent(in) :: date2 !!  TT as a 2-part Julian Date (Note 1)
    real(wp) :: res !! equation of the equinoxes (Note 2)
    real(wp) :: dpsipr, depspr, epsa, dpsi, deps
    !  IAU 2000 precession-rate adjustments.
    call PR00 ( date1, date2, dpsipr, depspr )
    !  Mean obliquity, consistent with IAU 2000 precession-nutation.
    epsa = OBL80 ( date1, date2 ) + depspr
    !  Nutation in longitude.
    call NUT00B ( date1, date2, dpsi, deps )
    !  Equation of the equinoxes.
    res = EE00 ( date1, date2, epsa, dpsi )
    end function EE00B
Call graph
ee00b calls pr00, obl80, nut00b, ee00
ee00 calls eect00
eect00 calls faom03, falp03, fad03, faf03, fae03, fave03, fapa03, fal03
gst00b calls ee00b