EE06A – astro-fortran
EE06A Function
7 statements
Source File
public function EE06A(date1, date2) result(res)
Equation of the equinoxes, compatible with IAU 2000 resolutions and IAU 2006/2000A precession-nutation.
Status: support routine.
Notes
The TT date DATE1+DATE2 is a Julian Date, apportioned in any convenient way between the two arguments. For example, JD(TT)=2450123.7 could be expressed in any of these ways, among others:
    DATE1          DATE2
 2450123.7D0        0D0        (JD method)
  2451545D0      -1421.3D0     (J2000 method)
 2400000.5D0     50123.2D0     (MJD method)
 2450123.5D0       0.2D0       (date & time method)
The JD method is the most natural and convenient to use in cases where the loss of several decimal digits of resolution is acceptable. The J2000 method is best matched to the way the argument is handled internally and will deliver the optimum resolution. The MJD method and the date & time methods are both good compromises between resolution and convenience.
The result, which is in radians, operates in the following sense:
Greenwich apparent ST = GMST + equation of the equinoxes
Reference
McCarthy, D. D., Petit, G. (eds.), 2004, IERS Conventions (2003), IERS Technical Note No. 32, BKG
History
IAU SOFA revision: 2006 October 31
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: date1
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(in) :: date2
TT as a 2-part Julian Date (Note 1)
Return Value real(kind=wp)
equation of the equinoxes (Note 2)
Calls
Contents
Source Code
EE06A
Source Code
    function EE06A ( date1, date2 ) result(res)
    implicit none
    real(wp),intent(in) :: date1 !! TT as a 2-part Julian Date (Note 1)
    real(wp),intent(in) :: date2 !! TT as a 2-part Julian Date (Note 1)
    real(wp) :: res !! equation of the equinoxes (Note 2)
    !  Equation of the equinoxes.
    res = ANPM ( GST06A ( 0.0_wp, 0.0_wp, date1, date2 ) - &
                 GMST06 ( 0.0_wp, 0.0_wp, date1, date2 ) )
    end function EE06A
Call graph
ee06a calls anpm, gmst06, gst06a
gmst06 calls anp, era00
gst06a calls pnm06a, gst06
pnm06a calls nut06a, pfw06, fw2m
era00 calls anp
gst06 calls anp, era00, eors, s06, bpn2xy
nut06a calls nut00a
s06 calls faom03, fad03, falp03, fae03, fal03, fapa03, faf03, fave03
pfw06 calls obl06
fw2m calls rx, ir, rz
nut00a calls faom03, fae03, fal03, fapa03, faf03, fave03, faur03, faju03, fasa03, fame03, fama03