EO06A – astro-fortran
EO06A Function
11 statements
Source File
public function EO06A(date1, date2) result(res)
Equation of the origins, IAU 2006 precession and IAU 2000A nutation.
Status: support routine.
Notes
The TT date DATE1+DATE2 is a Julian Date, apportioned in any convenient way between the two arguments. For example, JD(TT)=2450123.7 could be expressed in any of these ways, among others:
    DATE1          DATE2
 2450123.7D0        0D0        (JD method)
  2451545D0      -1421.3D0     (J2000 method)
 2400000.5D0     50123.2D0     (MJD method)
 2450123.5D0       0.2D0       (date & time method)
The JD method is the most natural and convenient to use in cases where the loss of several decimal digits of resolution is acceptable. The J2000 method is best matched to the way the argument is handled internally and will deliver the optimum resolution. The MJD method and the date & time methods are both good compromises between resolution and convenience.
The equation of the origins is the distance between the true equinox and the celestial intermediate origin and, equivalently, the difference between Earth rotation angle and Greenwich apparent sidereal time (ERA-GST). It comprises the precession (since J2000.0) in right ascension plus the equation of the equinoxes (including the small correction terms).
References
Capitaine, N. & Wallace, P.T., 2006, Astron.Astrophys. 450, 855
Wallace, P.T. & Capitaine, N., 2006, Astron.Astrophys. 459, 981
History
IAU SOFA revision: 2007 February 13
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: date1
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(in) :: date2
TT as a 2-part Julian Date (Note 1)
Return Value real(kind=wp)
equation of the origins in radians
Calls
Contents
Source Code
EO06A
Source Code
    function EO06A ( date1, date2 ) result(res)
    implicit none
    real(wp),intent(in) :: date1 !! TT as a 2-part Julian Date (Note 1)
    real(wp),intent(in) :: date2 !! TT as a 2-part Julian Date (Note 1)
    real(wp) :: res !! equation of the origins in radians
    real(wp) :: r(3,3), x, y, s
    !  Classical nutation x precession x bias matrix.
    call PNM06A ( date1, date2, r )
    !  Extract CIP coordinates.
    call BPN2XY ( r, x, y )
    !  The CIO locator, s.
    s = S06 ( date1, date2, x, y )
    !  Solve for the EO.
    res = EORS ( r, s )
    end function EO06A
Call graph
eo06a calls s06, pnm06a, bpn2xy, eors
s06 calls faom03, falp03, fad03, faf03, fae03, fave03, fapa03, fal03
pnm06a calls nut06a, fw2m, pfw06
nut06a calls nut00a
fw2m calls ir, rz, rx
pfw06 calls obl06
nut00a calls faom03, faf03, fae03, fave03, fapa03, fal03, fama03, faur03, faju03, fame03, fasa03