EORS – astro-fortran
EORS Function
19 statements
Source File
public function EORS(rnpb, s) result(res)
Equation of the origins, given the classical NPB matrix and the quantity s.
Status: support routine.
Notes
The equation of the origins is the distance between the true equinox and the celestial intermediate origin and, equivalently, the difference between Earth rotation angle and Greenwich apparent sidereal time (ERA-GST). It comprises the precession (since J2000.0) in right ascension plus the equation of the equinoxes (including the small correction terms).
The algorithm is from Wallace & Capitaine (2006).
References
Capitaine, N. & Wallace, P.T., 2006, Astron.Astrophys. 450, 855
Wallace, P. & Capitaine, N., 2006, Astron.Astrophys. 459, 981
History
IAU SOFA revision: 2008 February 24
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(3,3) :: rnpb
classical nutation x precession x bias matrix
real(kind=wp), intent(in) :: s
the quantity s (the CIO locator)
Return Value real(kind=wp)
the equation of the origins in radians.
Called by
Contents
Source Code
EORS
Source Code
    function EORS ( rnpb, s ) result(res)
    implicit none
    real(wp),dimension(3,3),intent(in) :: rnpb !! classical nutation x precession x bias matrix
    real(wp),intent(in) :: s !! the quantity s (the CIO locator)
    real(wp) :: res !! the equation of the origins in radians.
    real(wp) :: x, ax, xs, ys, zs, p, q
    !  Evaluate Wallace & Capitaine (2006) expression (16).
    x = rnpb(3,1)
    ax = x / ( 1.0_wp + rnpb(3,3) )
    xs = 1.0_wp - ax*x
    ys = -ax*rnpb(3,2)
    zs = -x
    p = rnpb(1,1)*xs + rnpb(1,2)*ys + rnpb(1,3)*zs
    q = rnpb(2,1)*xs + rnpb(2,2)*ys + rnpb(2,3)*zs
    if ( p/=0.0_wp .or. q/=0.0_wp ) then
       res = s - atan2 ( q, p )
    else
       res = s
    end if
    end function EORS
Call graph
eo06a calls eors
apci13 calls eors
gst06 calls eors
apco13 calls eors
gst06a calls gst06
atic13 calls apci13
atoc13 calls apco13
atci13 calls apci13
atco13 calls apco13
ee06a calls gst06a