EQEQ94 – astro-fortran
EQEQ94 Function
12 statements
Source File
public function EQEQ94(date1, date2) result(eqe)
Equation of the equinoxes, IAU 1994 model.
Status: canonical model.
Notes
The TDB date DATE1+DATE2 is a Julian Date, apportioned in any convenient way between the two arguments. For example, JD(TDB)=2450123.7 could be expressed in any of these ways, among others:
    DATE1          DATE2
 2450123.7D0        0D0        (JD method)
  2451545D0      -1421.3D0     (J2000 method)
 2400000.5D0     50123.2D0     (MJD method)
 2450123.5D0       0.2D0       (date & time method)
The JD method is the most natural and convenient to use in cases where the loss of several decimal digits of resolution is acceptable. The J2000 method is best matched to the way the argument is handled internally and will deliver the optimum resolution. The MJD method and the date & time methods are both good compromises between resolution and convenience.
The result, which is in radians, operates in the following sense:
Greenwich apparent ST = GMST + equation of the equinoxes
References
IAU Resolution C7, Recommendation 3 (1994)
Capitaine, N. & Gontier, A.-M., Astron.Astrophys., 275, 645-650 (1993)
History
IAU SOFA revision: 2017 October 12
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: date1
TDB date (Note 1)
real(kind=wp), intent(in) :: date2
TDB date (Note 1)
Return Value real(kind=wp)
equation of the equinoxes (Note 2)
Calls
Called by
Contents
Source Code
EQEQ94
Source Code
    function EQEQ94 ( date1, date2 ) result(eqe)
    implicit none
    real(wp),intent(in) :: date1 !! TDB date (Note 1)
    real(wp),intent(in) :: date2 !! TDB date (Note 1)
    real(wp) :: eqe !! equation of the equinoxes (Note 2)
    real(wp) :: t, om, dpsi, deps, eps0
    !  Interval between fundamental epoch J2000.0 and given date (JC).
    t = ( ( date1-dj00 ) + date2 ) / djc
    !  Longitude of the mean ascending node of the lunar orbit on the
    !  ecliptic, measured from the mean equinox of date.
    om = ANPM( ( 450160.280_wp + ( -482890.539_wp + &
               ( 7.455_wp + 0.008_wp * t ) * t ) * t ) * das2r &
                 + mod(-5.0_wp*t,1.0_wp) * d2pi )
    !  Nutation components and mean obliquity.
    call NUT80 ( date1, date2, dpsi, deps )
    eps0 = OBL80 ( date1, date2 )
    !  Equation of the equinoxes.
    eqe = dpsi * cos(eps0) + das2r * ( 0.00264_wp * sin(om) + &
                                       0.000063_wp * sin(om+om))
    end function EQEQ94
Call graph
eqeq94 calls obl80, anpm, nut80
nut80 calls anpm
gst94 calls eqeq94