ERA00 – astro-fortran
ERA00 Function
17 statements
Source File
public function ERA00(dj1, dj2) result(era)
Earth rotation angle (IAU 2000 model).
Status: canonical model.
Notes
The UT1 date DJ1+DJ2 is a Julian Date, apportioned in any convenient way between the arguments DJ1 and DJ2. For example, JD(UT1)=2450123.7 could be expressed in any of these ways, among others:
     DJ1            DJ2
 2450123.7D0        0D0        (JD method)
  2451545D0      -1421.3D0     (J2000 method)
 2400000.5D0     50123.2D0     (MJD method)
 2450123.5D0       0.2D0       (date & time method)
The JD method is the most natural and convenient to use in cases where the loss of several decimal digits of resolution is acceptable. The J2000 and MJD methods are good compromises between resolution and convenience. The date & time method is best matched to the algorithm used: maximum accuracy (or, at least, minimum noise) is delivered when the DJ1 argument is for 0hrs UT1 on the day in question and the DJ2 argument lies in the range 0 to 1, or vice versa.
The algorithm is adapted from Expression 22 of Capitaine et al.
The time argument has been expressed in days directly, and, to retain precision, integer contributions have been eliminated. The same formulation is given in IERS Conventions (2003), Chap. 5, Eq. 14.
References
Capitaine N., Guinot B. and McCarthy D.D, 2000, Astron. Astrophys., 355, 398-405.
McCarthy, D. D., Petit, G. (eds.), IERS Conventions (2003), IERS Technical Note No. 32, BKG (2004)
History
IAU SOFA revision: 2009 December 15
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: dj1
UT1 as a 2-part Julian Date (see note)
real(kind=wp), intent(in) :: dj2
UT1 as a 2-part Julian Date (see note)
Return Value real(kind=wp)
the Earth rotation angle (radians), in the range 0 to 2pi.
Calls
Called by
Contents
Source Code
ERA00
Source Code
    function ERA00 ( dj1, dj2 ) result(era)
    implicit none
    real(wp),intent(in) :: dj1 !! UT1 as a 2-part Julian Date (see note)
    real(wp),intent(in) :: dj2 !! UT1 as a 2-part Julian Date (see note)
    real(wp) :: era !! the Earth rotation angle (radians), in the range 0 to 2pi.
    real(wp) :: d1, d2, t, f
    !  Days since fundamental epoch.
    if ( dj1 < dj2 ) then
       d1 = dj1
       d2 = dj2
    else
       d1 = dj2
       d2 = dj1
    end if
    t = d1 + ( d2-dj00 )
    !  Fractional part of T (days).
    f = mod ( d1, 1.0_wp ) + mod ( d2, 1.0_wp )
    !  Earth rotation angle at this UT1.
    era = ANP ( d2pi * ( f + 0.7790572732640_wp &
                           + 0.00273781191135448_wp * t ) )
    end function ERA00
Call graph
era00 calls anp
apio13 calls era00
gmst00 calls era00
c2t00b calls era00
c2t00a calls era00
apco13 calls era00
aper13 calls era00
c2t06a calls era00
c2txy calls era00
gst06 calls era00
gmst06 calls era00
gst00a calls gmst00
c2tpe calls gmst00
atio13 calls apio13
ee06a calls gmst06, gst06a
gst00b calls gmst00
gst06a calls gst06
atoc13 calls apco13
atoi13 calls apio13
atco13 calls apco13