FAD03 – astro-fortran
FAD03 Function
7 statements
Source File
public function FAD03(t) result(fa)
Fundamental argument, IERS Conventions (2003): mean elongation of the Moon from the Sun.
Status: canonical model.
Notes
Though T is strictly TDB, it is usually more convenient to use TT, which makes no significant difference.
The expression used is as adopted in IERS Conventions (2003) and is from Simon et al. (1994).
References
McCarthy, D. D., Petit, G. (eds.), IERS Conventions (2003), IERS Technical Note No. 32, BKG (2004)
Simon, J.-L., Bretagnon, P., Chapront, J., Chapront-Touze, M., Francou, G., Laskar, J. 1994, Astron.Astrophys. 282, 663-683
History
IAU SOFA revision: 2009 December 15
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: t
TDB, Julian centuries since J2000.0 (Note 1)
Return Value real(kind=wp)
D, radians (Note 2)
Called by
Contents
Source Code
FAD03
Source Code
    function FAD03 ( t ) result(fa)
    implicit none
    real(wp),intent(in) :: t !! TDB, Julian centuries since J2000.0 (Note 1)
    real(wp) :: fa !! D, radians (Note 2)
    !  Arcseconds in a full circle.
    real(wp),parameter :: turnas = 1296000.0_wp
    !  Mean elongation of the Moon from the Sun (IERS Conventions 2003).
    fa = mod (  1072260.703692_wp + &
                t*( 1602961601.2090_wp + &
                t*(        - 6.3706_wp + &
                t*(          0.006593_wp + &
                t*(        - 0.00003169_wp )))), turnas ) * das2r
    end function FAD03
Call graph
eect00 calls fad03
s00 calls fad03
xy06 calls fad03
s06 calls fad03
ee00 calls eect00
xys00a calls s00
s06a calls s06
apco13 calls s06
c2i06a calls s06
xys06a calls s06
c2ixy calls s00
xys00b calls s00
s00a calls s00
s00b calls s00
gst06 calls s06
apci13 calls s06
eo06a calls s06
ee00a calls ee00
ee00b calls ee00
atco13 calls apco13
c2ibpn calls c2ixy
c2txy calls c2ixy
gst06a calls gst06
atci13 calls apci13
atic13 calls apci13
c2tpe calls ee00
atoc13 calls apco13
c2t06a calls c2i06a
gst00a calls ee00a
c2i00b calls c2ibpn
ee06a calls gst06a
c2i00a calls c2ibpn
gst00b calls ee00b
c2t00b calls c2i00b
c2t00a calls c2i00a