FAF03 – astro-fortran
FAF03 Function
7 statements
Source File
public function FAF03(t) result(f)
Fundamental argument, IERS Conventions (2003): mean longitude of the Moon minus mean longitude of the ascending node.
Status: canonical model.
Notes
Though T is strictly TDB, it is usually more convenient to use TT, which makes no significant difference.
The expression used is as adopted in IERS Conventions (2003) and is from Simon et al. (1994).
References
McCarthy, D. D., Petit, G. (eds.), IERS Conventions (2003), IERS Technical Note No. 32, BKG (2004)
Simon, J.-L., Bretagnon, P., Chapront, J., Chapront-Touze, M., Francou, G., Laskar, J. 1994, Astron.Astrophys. 282, 663-683
History
IAU SOFA revision: 2009 December 15
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: t
TDB, Julian centuries since J2000.0 (Note 1)
Return Value real(kind=wp)
F, radians (Note 2)
Called by
Contents
Source Code
FAF03
Source Code
    function FAF03 ( t ) result(f)
    implicit none
    real(wp),intent(in) :: t !! TDB, Julian centuries since J2000.0 (Note 1)
    real(wp) :: f !! F, radians (Note 2)
    !  Arcseconds in a full circle.
    real(wp),parameter :: turnas = 1296000.0_wp
    !  Mean longitude of the Moon minus that of the ascending node
    !  (IERS Conventions 2003).
    f = mod ( 335779.526232_wp + &
               t*( 1739527262.8478_wp + &
               t*(       - 12.7512_wp + &
               t*(       -  0.001037_wp + &
               t*(          0.00000417_wp )))), turnas ) * das2r
    end function FAF03
Call graph
xy06 calls faf03
s00 calls faf03
nut00a calls faf03
eect00 calls faf03
s06 calls faf03
s00b calls s00
ee00 calls eect00
nut06a calls nut00a
s00a calls s00, pnm00a
xys00a calls s00, pnm00a
pn00a calls nut00a
s06a calls s06, pnm06a
xys06a calls s06, pnm06a
ee00a calls nut00a, ee00
gst06 calls s06
apco13 calls s06, pnm06a
xys00b calls s00
c2i06a calls s06, pnm06a
c2ixy calls s00
eo06a calls s06, pnm06a
apci13 calls s06, pnm06a
c2t06a calls c2i06a
num00a calls pn00a
c2txy calls c2ixy
gst00a calls ee00a
gst06a calls gst06, pnm06a
c2ibpn calls c2ixy
atci13 calls apci13
num06a calls nut06a
pnm00a calls pn00a
ee00b calls ee00
c2tpe calls ee00
atic13 calls apci13
atoc13 calls apco13
pn06a calls nut06a
pnm06a calls nut06a
atco13 calls apco13
gst00b calls ee00b
c2i00a calls c2ibpn, pnm00a
ee06a calls gst06a
c2i00b calls c2ibpn
c2t00b calls c2i00b
c2t00a calls c2i00a