FALP03 – astro-fortran
FALP03 Function
7 statements
Source File
public function FALP03(t) result(res)
Fundamental argument, IERS Conventions (2003): mean anomaly of the Sun.
Status: canonical model.
Notes
Though T is strictly TDB, it is usually more convenient to use TT, which makes no significant difference.
The expression used is as adopted in IERS Conventions (2003) and is from Simon et al. (1994).
References
McCarthy, D. D., Petit, G. (eds.), IERS Conventions (2003), IERS Technical Note No. 32, BKG (2004)
Simon, J.-L., Bretagnon, P., Chapront, J., Chapront-Touze, M., Francou, G., Laskar, J. 1994, Astron.Astrophys. 282, 663-683
History
IAU SOFA revision: 2009 December 15
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: t
TDB, Julian centuries since J2000.0 (Note 1)
Return Value real(kind=wp)
l', radians (Note 2)
Called by
Contents
Source Code
FALP03
Source Code
    function FALP03 ( t ) result(res)
    implicit none
    real(wp),intent(in) :: t !! TDB, Julian centuries since J2000.0 (Note 1)
    real(wp) :: res !! l', radians (Note 2)
    !  Arcseconds in a full circle.
    real(wp),parameter :: turnas = 1296000.0_wp
    !  Mean anomaly of the Sun (IERS Conventions 2003).
    res = mod ( 1287104.793048_wp + &
                t*( 129596581.0481_wp + &
                t*(       - 0.5532_wp + &
                t*(         0.000136_wp + &
                t*(       - 0.00001149_wp )))), turnas ) * das2r
    end function FALP03
Call graph
s06 calls falp03
xy06 calls falp03
eect00 calls falp03
s00 calls falp03
s00b calls s00
ee00 calls eect00
xys00a calls s00
s00a calls s00
s06a calls s06
xys06a calls s06
gst06 calls s06
apco13 calls s06
c2i06a calls s06
xys00b calls s00
c2ixy calls s00
eo06a calls s06
apci13 calls s06
c2t06a calls c2i06a
c2txy calls c2ixy
gst06a calls gst06
c2ibpn calls c2ixy
ee00a calls ee00
ee00b calls ee00
c2tpe calls ee00
atic13 calls apci13
atoc13 calls apco13
atci13 calls apci13
atco13 calls apco13
c2i00a calls c2ibpn
ee06a calls gst06a
gst00a calls ee00a
gst00b calls ee00b
c2i00b calls c2ibpn
c2t00b calls c2i00b
c2t00a calls c2i00a