FAME03 – astro-fortran
FAME03 Function
6 statements
Source File
public function FAME03(t) result(res)
Fundamental argument, IERS Conventions (2003): mean longitude of Mercury.
Status: canonical model.
Notes
Though T is strictly TDB, it is usually more convenient to use TT, which makes no significant difference.
The expression used is as adopted in IERS Conventions (2003) and comes from Souchay et al. (1999) after Simon et al. (1994).
References
McCarthy, D. D., Petit, G. (eds.), IERS Conventions (2003), IERS Technical Note No. 32, BKG (2004)
Simon, J.-L., Bretagnon, P., Chapront, J., Chapront-Touze, M., Francou, G., Laskar, J. 1994, Astron.Astrophys. 282, 663-683
Souchay, J., Loysel, B., Kinoshita, H., Folgueira, M. 1999, Astron.Astrophys.Supp.Ser. 135, 111
History
IAU SOFA revision: 2009 December 15
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: t
TDB, Julian centuries since J2000.0 (Note 1)
Return Value real(kind=wp)
mean longitude of Mercury, radians (Note 2)
Called by
Contents
Source Code
FAME03
Source Code
    function FAME03 ( t ) result(res)
    implicit none
    real(wp),intent(in) :: t !! TDB, Julian centuries since J2000.0 (Note 1)
    real(wp) :: res !! mean longitude of Mercury, radians (Note 2)
    !  Mean longitude of Mercury (IERS Conventions 2003).
    res = mod ( 4.402608842_wp + 2608.7903141574_wp * t, d2pi )
    end function FAME03
Call graph
xy06 calls fame03
nut00a calls fame03
pn00a calls nut00a
nut06a calls nut00a
ee00a calls nut00a
pn06a calls nut06a
pnm00a calls pn00a
num06a calls nut06a
gst00a calls ee00a
num00a calls pn00a
pnm06a calls nut06a
s06a calls pnm06a
apci13 calls pnm06a
eo06a calls pnm06a
apco13 calls pnm06a
gst06a calls pnm06a
xys06a calls pnm06a
c2i00a calls pnm00a
s00a calls pnm00a
xys00a calls pnm00a
c2i06a calls pnm06a
atoc13 calls apco13
c2t00a calls c2i00a
atci13 calls apci13
c2t06a calls c2i06a
ee06a calls gst06a
atic13 calls apci13
atco13 calls apco13