FAUR03 – astro-fortran
FAUR03 Function
6 statements
Source File
public function FAUR03(t) result(res)
Fundamental argument, IERS Conventions (2003): mean longitude of Uranus.
Status: canonical model.
Notes
Though T is strictly TDB, it is usually more convenient to use TT, which makes no significant difference.
The expression used is as adopted in IERS Conventions (2003) and is adapted from Simon et al. (1994).
References
McCarthy, D. D., Petit, G. (eds.), IERS Conventions (2003), IERS Technical Note No. 32, BKG (2004)
Simon, J.-L., Bretagnon, P., Chapront, J., Chapront-Touze, M., Francou, G., Laskar, J. 1994, Astron.Astrophys. 282, 663-683
History
IAU SOFA revision: 2009 December 15
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: t
TDB, Julian centuries since J2000.0 (Note 1)
Return Value real(kind=wp)
mean longitude of Uranus, radians (Note 2)
Called by
Contents
Source Code
FAUR03
Source Code
    function FAUR03 ( t ) result(res)
    implicit none
    real(wp),intent(in) :: t !! TDB, Julian centuries since J2000.0 (Note 1)
    real(wp) :: res !! mean longitude of Uranus, radians (Note 2)
    !  Mean longitude of Uranus (IERS Conventions 2003).
    res = mod ( 5.481293872_wp + 7.4781598567_wp * t, d2pi )
    end function FAUR03
Call graph
nut00a calls faur03
xy06 calls faur03
ee00a calls nut00a
nut06a calls nut00a
pn00a calls nut00a
pnm06a calls nut06a
pn06a calls nut06a
num00a calls pn00a
gst00a calls ee00a
num06a calls nut06a
pnm00a calls pn00a
gst06a calls pnm06a
s06a calls pnm06a
xys06a calls pnm06a
c2i06a calls pnm06a
apco13 calls pnm06a
xys00a calls pnm00a
apci13 calls pnm06a
eo06a calls pnm06a
s00a calls pnm00a
c2i00a calls pnm00a
atco13 calls apco13
atci13 calls apci13
atic13 calls apci13
c2t00a calls c2i00a
ee06a calls gst06a
c2t06a calls c2i06a
atoc13 calls apco13