FAVE03 – astro-fortran
FAVE03 Function
6 statements
Source File
public function FAVE03(t) result(res)
Fundamental argument, IERS Conventions (2003): mean longitude of Venus.
Status: canonical model.
Notes
Though T is strictly TDB, it is usually more convenient to use TT, which makes no significant difference.
The expression used is as adopted in IERS Conventions (2003) and comes from Souchay et al. (1999) after Simon et al. (1994).
References
McCarthy, D. D., Petit, G. (eds.), IERS Conventions (2003), IERS Technical Note No. 32, BKG (2004)
Simon, J.-L., Bretagnon, P., Chapront, J., Chapront-Touze, M., Francou, G., Laskar, J. 1994, Astron.Astrophys. 282, 663-683
Souchay, J., Loysel, B., Kinoshita, H., Folgueira, M. 1999, Astron.Astrophys.Supp.Ser. 135, 111
History
IAU SOFA revision: 2009 December 15
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: t
TDB, Julian centuries since J2000.0 (Note 1)
Return Value real(kind=wp)
mean longitude of Venus, radians (Note 2)
Called by
Contents
Source Code
FAVE03
Source Code
    function FAVE03 ( t ) result(res)
    implicit none
    real(wp),intent(in) :: t !! TDB, Julian centuries since J2000.0 (Note 1)
    real(wp) :: res !! mean longitude of Venus, radians (Note 2)
    !  Mean longitude of Venus (IERS Conventions 2003).
    res = mod ( 3.176146697_wp + 1021.3285546211_wp * t, d2pi )
    end function FAVE03
Call graph
nut00a calls fave03
s00 calls fave03
s06 calls fave03
xy06 calls fave03
eect00 calls fave03
ee00a calls nut00a, ee00
pn00a calls nut00a
xys00a calls s00, pnm00a
s06a calls s06, pnm06a
apco13 calls s06, pnm06a
c2i06a calls s06, pnm06a
xys06a calls s06, pnm06a
ee00 calls eect00
s00a calls s00, pnm00a
nut06a calls nut00a
xys00b calls s00
c2ixy calls s00
s00b calls s00
gst06 calls s06
apci13 calls s06, pnm06a
eo06a calls s06, pnm06a
atco13 calls apco13
num00a calls pn00a
ee00b calls ee00
pnm06a calls nut06a
pn06a calls nut06a
c2ibpn calls c2ixy
c2txy calls c2ixy
gst06a calls gst06, pnm06a
atci13 calls apci13
atic13 calls apci13
gst00a calls ee00a
atoc13 calls apco13
pnm00a calls pn00a
c2t06a calls c2i06a
c2tpe calls ee00
num06a calls nut06a
gst00b calls ee00b
c2i00b calls c2ibpn
ee06a calls gst06a
c2i00a calls c2ibpn, pnm00a
c2t00b calls c2i00b
c2t00a calls c2i00a