FK52H – astro-fortran
FK52H Subroutine
27 statements
Source File
public subroutine FK52H(r5, d5, dr5, dd5, px5, rv5, rh, dh, drh, ddh, pxh, rvh)
Transform FK5 (J2000.0) star data into the Hipparcos system.
Status: support routine.
Notes
This routine transforms FK5 star positions and proper motions into the system of the Hipparcos catalog.
The proper motions in RA are dRA/dt rather than cos(Dec)*dRA/dt, and are per year rather than per century.
The FK5 to Hipparcos transformation is modeled as a pure rotation and spin; zonal errors in the FK5 catalog are not taken into account.
See also H2FK5, FK5HZ, HFK5Z.
Reference
F. Mignard & M. Froeschle, Astron.Astrophys., 354, 732-739 (2000).
History
IAU SOFA revision: 2017 October 12
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: r5
RA (radians)
real(kind=wp), intent(in) :: d5
Dec (radians)
real(kind=wp), intent(in) :: dr5
proper motion in RA (dRA/dt, rad/Jyear)
real(kind=wp), intent(in) :: dd5
proper motion in Dec (dDec/dt, rad/Jyear)
real(kind=wp), intent(in) :: px5
parallax (arcsec)
real(kind=wp), intent(in) :: rv5
radial velocity (km/s, positive = receding)
real(kind=wp), intent(out) :: rh
RA (radians)
real(kind=wp), intent(out) :: dh
Dec (radians)
real(kind=wp), intent(out) :: drh
proper motion in RA (dRA/dt, rad/Jyear)
real(kind=wp), intent(out) :: ddh
proper motion in Dec (dDec/dt, rad/Jyear)
real(kind=wp), intent(out) :: pxh
parallax (arcsec)
real(kind=wp), intent(out) :: rvh
radial velocity (km/s, positive = receding)
Calls
Contents
Source Code
FK52H
Source Code
    subroutine FK52H ( r5, d5, dr5, dd5, px5, rv5, &
                       rh, dh, drh, ddh, pxh, rvh )
    implicit none
    real(wp),intent(in) :: r5 !! RA (radians)
    real(wp),intent(in) :: d5 !! Dec (radians)
    real(wp),intent(in) :: dr5 !! proper motion in RA (dRA/dt, rad/Jyear)
    real(wp),intent(in) :: dd5 !! proper motion in Dec (dDec/dt, rad/Jyear)
    real(wp),intent(in) :: px5 !! parallax (arcsec)
    real(wp),intent(in) :: rv5 !! radial velocity (km/s, positive = receding)
    real(wp),intent(out) :: rh !! RA (radians)
    real(wp),intent(out) :: dh !! Dec (radians)
    real(wp),intent(out) :: drh !! proper motion in RA (dRA/dt, rad/Jyear)
    real(wp),intent(out) :: ddh !! proper motion in Dec (dDec/dt, rad/Jyear)
    real(wp),intent(out) :: pxh !! parallax (arcsec)
    real(wp),intent(out) :: rvh !! radial velocity (km/s, positive = receding)
    real(wp) :: pv5(3,2), r5h(3,3), s5h(3), wxp(3), vv(3), &
                pvh(3,2)
    integer :: j, i
    !  FK5 barycentric position/velocity pv-vector (normalized).
    call STARPV ( r5, d5, dr5, dd5, px5, rv5, pv5, j )
    !  FK5 to Hipparcos orientation matrix and spin vector.
    call FK5HIP ( r5h, s5h )
    !  Make spin units per day instead of per year.
    do i=1,3
       s5h(i) = s5h(i) / 365.25_wp
    end do
    !  Orient the FK5 position into the Hipparcos system.
    call RXP ( r5h, pv5(1,1), pvh(1,1) )
    !  Apply spin to the position giving an extra space motion component.
    call PXP ( pv5(1,1), s5h, wxp )
    !  Add this component to the FK5 space motion.
    call PPP ( wxp, pv5(1,2), vv )
    !  Orient the FK5 space motion into the Hipparcos system.
    call RXP ( r5h, vv, pvh(1,2) )
    !  Hipparcos pv-vector to spherical.
    call PVSTAR ( pvh, rh, dh, drh, ddh, pxh, rvh, j )
    end subroutine FK52H
Call graph
fk52h calls starpv, rxp, ppp, fk5hip, pxp, pvstar
starpv calls ppp, pdp, sxp, zp, pmp, s2pv
fk5hip calls rv2m
pvstar calls ppp, pdp, sxp, pv2s, pmp, anp