FK54Z – astro-fortran
FK54Z Subroutine
25 statements
Source File
public subroutine FK54Z(r2000, d2000, bepoch, r1950, d1950, dr1950, dd1950)
Convert a J2000.0 FK5 star position to B1950.0 FK4, assuming zero proper motion in FK5 and parallax.
Status: support routine.
Notes
In contrast to the FK524 routine, here the FK5 proper motions, the parallax and the radial velocity are presumed zero.
This routine converts a star position from the IAU 1976 FK5 (Fricke) system to the former FK4 (Bessel-Newcomb) system, for cases such as distant radio sources where it is presumed there is zero parallax and no proper motion. Because of the E-terms of aberration, such objects have (in general) non-zero proper motion in FK4, and the present routine returns those fictitious proper motions.
Conversion from B1950.0 FK4 to J2000.0 FK5 only is provided for. Conversions involving other equinoxes would require additional treatment for precession.
The position returned by this routine is in the B1950.0 FK4 reference system but at Besselian epoch BEPOCH. For comparison with catalogs the BEPOCH argument will frequently be 1950D0. (In this context the distinction between Besselian and Julian epoch is insignificant.)
The RA component of the returned (fictitious) proper motion is dRA/dt rather than cos(Dec)*dRA/dt.
History
IAU SOFA revision: 2018 January 11
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: r2000
J2000.0 FK5 RA (rad)
real(kind=wp), intent(in) :: d2000
J2000.0 FK5 Dec (rad)
real(kind=wp), intent(in) :: bepoch
Besselian epoch (e.g. 1950D0)
real(kind=wp), intent(out) :: r1950
B1950.0 FK4 RA (rad) at epoch BEPOCH
real(kind=wp), intent(out) :: d1950
B1950.0 FK4 Dec (rad) at epoch BEPOCH
real(kind=wp), intent(out) :: dr1950
B1950.0 FK4 proper motions (rad/trop.yr)
real(kind=wp), intent(out) :: dd1950
B1950.0 FK4 proper motions (rad/trop.yr)
Calls
Contents
Source Code
FK54Z
Source Code
    subroutine FK54Z ( r2000, d2000, bepoch, &
                       r1950, d1950, dr1950, dd1950 )
    implicit none
    real(wp),intent(in) :: r2000 !! J2000.0 FK5 RA (rad)
    real(wp),intent(in) :: d2000 !! J2000.0 FK5 Dec (rad)
    real(wp),intent(in) :: bepoch !! Besselian epoch (e.g. 1950D0)
    real(wp),intent(out) :: r1950 !! B1950.0 FK4 RA (rad) at epoch BEPOCH
    real(wp),intent(out) :: d1950 !! B1950.0 FK4 Dec (rad) at epoch BEPOCH
    real(wp),intent(out) :: dr1950 !! B1950.0 FK4 proper motions (rad/trop.yr)
    real(wp),intent(out) :: dd1950 !! B1950.0 FK4 proper motions (rad/trop.yr)
    real(wp) :: r, d, pr, pd, px, rv, p(3), w, v(3)
    integer :: i
    !  FK5 equinox J2000.0 to FK4 equinox B1950.0.
    call FK524 ( r2000, d2000, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, &
                 r, d, pr, pd, px, rv )
    !  Spherical to Cartesian.
    call S2C ( r, d, p )
    !  Fictitious proper motion (radians per year).
    v(1) = - pr*p(2) - pd*cos(r)*sin(d)
    v(2) =   pr*p(1) - pd*sin(r)*sin(d)
    v(3) =             pd*cos(d)
    !  Apply the motion.
    w = bepoch - 1950.0_wp
    do i=1,3
       p(i) = p(i) + w*v(i)
    end do
    !  Cartesian to spherical.
    call C2S ( p, w, d1950 )
    r1950 = ANP ( w )
    !  Fictitious proper motion.
    dr1950 = pr
    dd1950 = pd
    end subroutine FK54Z
Call graph
fk54z calls c2s, s2c, fk524, anp
fk524 calls anp, sxp, pmp, pm, ppp, pdp, pv2s, s2pv