FK5HZ – astro-fortran
FK5HZ Subroutine
19 statements
Source File
public subroutine FK5HZ(r5, d5, date1, date2, rh, dh)
Transform an FK5 (J2000.0) star position into the system of the Hipparcos catalogue, assuming zero Hipparcos proper motion.
Status: support routine.
Notes
This routine converts a star position from the FK5 system to the Hipparcos system, in such a way that the Hipparcos proper motion is zero. Because such a star has, in general, a non-zero proper motion in the FK5 system, the routine requires the date at which the position in the FK5 system was determined.
The TDB date DATE1+DATE2 is a Julian Date, apportioned in any convenient way between the two arguments. For example, JD(TDB)=2450123.7 could be expressed in any of these ways, among others:
    DATE1          DATE2
 2450123.7D0        0D0        (JD method)
  2451545D0      -1421.3D0     (J2000 method)
 2400000.5D0     50123.2D0     (MJD method)
 2450123.5D0       0.2D0       (date & time method)
The JD method is the most natural and convenient to use in cases where the loss of several decimal digits of resolution is acceptable. The J2000 method is best matched to the way the argument is handled internally and will deliver the optimum resolution. The MJD method and the date & time methods are both good compromises between resolution and convenience.
The FK5 to Hipparcos transformation is modeled as a pure rotation and spin; zonal errors in the FK5 catalogue are not taken into account.
The position returned by this routine is in the Hipparcos reference system but at date DATE1+DATE2.
See also FK52H, H2FK5, HFK5Z.
Reference
F. Mignard & M. Froeschle, Astron. Astrophys. 354, 732-739 (2000).
History
IAU SOFA revision: 2012 September 5
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: r5
FK5 RA (radians), equinox J2000.0, at date
real(kind=wp), intent(in) :: d5
FK5 Dec (radians), equinox J2000.0, at date
real(kind=wp), intent(in) :: date1
TDB date (Notes 1,2)
real(kind=wp), intent(in) :: date2
TDB date (Notes 1,2)
real(kind=wp), intent(out) :: rh
Hipparcos RA (radians)
real(kind=wp), intent(out) :: dh
Hipparcos Dec (radians)
Calls
Contents
Source Code
FK5HZ
Source Code
    subroutine FK5HZ ( r5, d5, date1, date2, rh, dh )
    implicit none
    real(wp),intent(in) :: r5 !! FK5 RA (radians), equinox J2000.0, at date
    real(wp),intent(in) :: d5 !! FK5 Dec (radians), equinox J2000.0, at date
    real(wp),intent(in) :: date1 !! TDB date (Notes 1,2)
    real(wp),intent(in) :: date2 !! TDB date (Notes 1,2)
    real(wp),intent(out) :: rh !! Hipparcos RA (radians)
    real(wp),intent(out) :: dh !! Hipparcos Dec (radians)
    real(wp) :: t, p5e(3), r5h(3,3), s5h(3), vst(3), rst(3,3), &
                p5(3), ph(3), w
    !  Interval from given date to fundamental epoch J2000.0 (JY).
    t = - ( ( date1-dj00 ) + date2 ) / djy
    !  FK5 barycentric position vector.
    call S2C ( r5, d5, p5e )
    !  FK5 to Hipparcos orientation matrix and spin vector.
    call FK5HIP ( r5h, s5h )
    !  Accumulated Hipparcos wrt FK5 spin over that interval.
    call SXP ( t, s5h, vst )
    !  Express the accumulated spin as a rotation matrix.
    call RV2M ( vst, rst )
    !  Derotate the vector's FK5 axes back to date.
    call TRXP ( rst, p5e, p5 )
    !  Rotate the vector into the Hipparcos system.
    call RXP ( r5h, p5, ph )
    !  Hipparcos vector to spherical.
    call C2S ( ph, w, dh )
    rh = ANP ( w )
    end subroutine FK5HZ
Call graph
fk5hz calls rv2m, rxp, sxp, s2c, trxp, c2s, anp, fk5hip
trxp calls rxp, tr
fk5hip calls rv2m