FK5HIP – astro-fortran
FK5HIP Subroutine
19 statements
Source File
public subroutine FK5HIP(r5h, s5h)
FK5 to Hipparcos rotation and spin.
Status: support routine.
Notes
This routine models the FK5 to Hipparcos transformation as a pure rotation and spin; zonal errors in the FK5 catalogue are not taken into account.
The r-matrix R5H operates in the sense:
   P_Hipparcos = R5H x P_FK5
where P_FK5 is a p-vector in the FK5 frame, and P_Hipparcos is the equivalent Hipparcos p-vector.
The r-vector S5H represents the time derivative of the FK5 to Hipparcos rotation. The units are radians per year (Julian, TDB).
Reference
F. Mignard & M. Froeschle, Astron.Astrophys., 354, 732-739 (2000).
History
IAU SOFA revision: 2017 October 12
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(out), dimension(3,3) :: r5h
r-matrix: FK5 rotation wrt Hipparcos (Note 2)
real(kind=wp), intent(out), dimension(3) :: s5h
Calls
Called by
Contents
Source Code
FK5HIP
Source Code
    subroutine FK5HIP ( r5h, s5h )
    implicit none
    real(wp),dimension(3,3),intent(out) :: r5h !! r-matrix: FK5 rotation wrt Hipparcos (Note 2)
    real(wp),dimension(3),intent(out) :: s5h !! r-vector: FK5 spin wrt Hipparcos (Note 3)
    !  FK5 to Hipparcos orientation and spin (radians, radians/year)
    real(wp),parameter :: epx = -19.9e-3_wp * das2r
    real(wp),parameter :: epy =  -9.1e-3_wp * das2r
    real(wp),parameter :: epz = +22.9e-3_wp * das2r
    real(wp),parameter :: omx = -0.30e-3_wp * das2r
    real(wp),parameter :: omy = +0.60e-3_wp * das2r
    real(wp),parameter :: omz = +0.70e-3_wp * das2r
    real(wp) :: v(3)
    !  FK5 to Hipparcos orientation expressed as an r-vector.
    v(1) = epx
    v(2) = epy
    v(3) = epz
    !  Re-express as an r-matrix.
    call RV2M ( v, r5h )
    !  Hipparcos wrt FK5 spin expressed as an r-vector.
    s5h(1) = omx
    s5h(2) = omy
    s5h(3) = omz
    end subroutine FK5HIP
Call graph
fk5hip calls rv2m
fk5hz calls fk5hip
h2fk5 calls fk5hip
fk52h calls fk5hip
hfk5z calls fk5hip