FW2M – astro-fortran
FW2M Subroutine
13 statements
Source File
public subroutine FW2M(gamb, phib, psi, eps, r)
Form rotation matrix given the Fukushima-Williams angles.
Status: support routine.
Notes
Naming the following points:
   e = J2000.0 ecliptic pole,
   p = GCRS pole,
   E = ecliptic pole of date,
and P = CIP,
the four Fukushima-Williams angles are as follows:
GAMB = gamma = epE
PHIB = phi = pE
PSI = psi = pEP
EPS = epsilon = EP
The matrix representing the combined effects of frame bias, precession and nutation is:
NxPxB = R_1(-EPS).R_3(-PSI).R_1(PHIB).R_3(GAMB)
Three different matrices can be constructed, depending on the supplied angles:
To obtain the nutation x precession x frame bias matrix, generate the four precession angles, generate the nutation components and add them to the psi_bar and epsilon_A angles, and call the present routine.
To obtain the precession x frame bias matrix, generate the four precession angles and call the present routine.
To obtain the frame bias matrix, generate the four precession angles for date J2000.0 and call the present routine.
The nutation-only and precession-only matrices can if necessary be obtained by combining these three appropriately.
Reference
Hilton, J. et al., 2006, Celest.Mech.Dyn.Astron. 94, 351
History
IAU SOFA revision: 2009 December 15
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: gamb
F-W angle gamma_bar (radians)
real(kind=wp), intent(in) :: phib
F-W angle phi_bar (radians)
real(kind=wp), intent(in) :: psi
F-W angle psi (radians)
real(kind=wp), intent(in) :: eps
F-W angle epsilon (radians)
real(kind=wp), intent(out), dimension(3,3) :: r
rotation matrix
Calls
Called by
Contents
Source Code
FW2M
Source Code
    subroutine FW2M ( gamb, phib, psi, eps, r )
    implicit none
    real(wp),intent(in) :: gamb !! F-W angle gamma_bar (radians)
    real(wp),intent(in) :: phib !! F-W angle phi_bar (radians)
    real(wp),intent(in) :: psi !! F-W angle psi (radians)
    real(wp),intent(in) :: eps !! F-W angle epsilon (radians)
    real(wp),dimension(3,3),intent(out) :: r !! rotation matrix
    !  Construct the matrix.
    call IR ( r )
    call RZ ( gamb, r )
    call RX ( phib, r )
    call RZ ( -psi, r )
    call RX ( -eps, r )
    end subroutine FW2M
Call graph
fw2m calls ir, rz, rx
pnm06a calls fw2m
bp06 calls fw2m, pmat06
pmat06 calls fw2m
pn06 calls fw2m
fw2xy calls fw2m
gst06a calls pnm06a
s06a calls pnm06a
xys06a calls pnm06a
c2i06a calls pnm06a
apco13 calls pnm06a
pn06a calls pn06
apci13 calls pnm06a
eo06a calls pnm06a
pb06 calls pmat06
ecm06 calls pmat06
atco13 calls apco13
atci13 calls apci13
atic13 calls apci13
eceq06 calls ecm06
ee06a calls gst06a
c2t06a calls c2i06a
atoc13 calls apco13
eqec06 calls ecm06