GD2GC – astro-fortran
GD2GC Subroutine
16 statements
Source File
public subroutine GD2GC(n, elong, phi, height, xyz, j)
Transform geodetic coordinates to geocentric using the specified reference ellipsoid.
Status: canonical transformation.
Notes
The identifier N is a number that specifies the choice of reference ellipsoid. The following are supported:
N   ellipsoid
1    WGS84
2    GRS80
3    WGS72
The number N has no significance outside the SOFA software.
The height (HEIGHT, given) and the geocentric vector (XYZ, returned) are in meters.
No validation is performed on the arguments ELONG, PHI and HEIGHT. An error status J=-1 means that the identifier N is illegal. An error status J=-2 protects against cases that would lead to arithmetic exceptions. In all error cases, XYZ is set to zeros.
The inverse transformation is performed in the routine GC2GD.
History
IAU SOFA revision: 2010 January 18
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
ellipsoid identifier (Note 1)
real(kind=wp), intent(in) :: elong
longitude (radians, east +ve)
real(kind=wp), intent(in) :: phi
latitude (geodetic, radians, Note 3)
real(kind=wp), intent(in) :: height
height above ellipsoid (geodetic, Notes 2,3)
real(kind=wp), intent(out), dimension(3) :: xyz
geocentric vector (Note 2)
integer, intent(out) :: j
0 = OK
-1 = illegal identifier (Note 3)
-2 = illegal case (Note 3)
Calls
Called by
Contents
Source Code
GD2GC
Source Code
    subroutine GD2GC ( n, elong, phi, height, xyz, j )
    implicit none
    integer,intent(in) :: n !! ellipsoid identifier (Note 1)
    real(wp),intent(in) :: elong !! longitude (radians, east +ve)
    real(wp),intent(in) :: phi !! latitude (geodetic, radians, Note 3)
    real(wp),intent(in) :: height !! height above ellipsoid (geodetic, Notes 2,3)
    real(wp),dimension(3),intent(out) :: xyz !! geocentric vector (Note 2)
    integer,intent(out) :: j !! status:
                             !! *  0 = OK
                             !! * -1 = illegal identifier (Note 3)
                             !! * -2 = illegal case (Note 3)
    real(wp) :: a, f
    !  Obtain reference ellipsoid parameters.
    call EFORM ( n, a, f, j )
    !  If OK, transform longitude, geodetic latitude, height to x,y,z.
    if ( j==0 ) then
       call GD2GCE ( a, f, elong, phi, height, xyz, j )
       if ( j/=0 ) j=-2
    end if
    !  Deal with any errors.
    if ( j/=0 ) call ZP ( xyz )
    end subroutine GD2GC
Call graph
gd2gc calls eform, gd2gce, zp
pvtob calls gd2gc
apco calls pvtob
apio calls pvtob
apco13 calls apco
apio13 calls apio
atco13 calls apco13
atoi13 calls apio13
atio13 calls apio13
atoc13 calls apco13