GST06 – astro-fortran
GST06 Function
13 statements
Source File
public function GST06(uta, utb, tta, ttb, rnpb) result(gast)
Greenwich apparent sidereal time, IAU 2006, given the NPB matrix.
Status: support routine.
Notes
The UT1 and TT dates UTA+UTB and TTA+TTB respectively, are both Julian Dates, apportioned in any convenient way between the argument pairs. For example, JD=2450123.7 could be expressed in any of these ways, among others:
    Part A         Part B
 2450123.7D0        0D0        (JD method)
  2451545D0      -1421.3D0     (J2000 method)
 2400000.5D0     50123.2D0     (MJD method)
 2450123.5D0       0.2D0       (date & time method)
The JD method is the most natural and convenient to use in cases where the loss of several decimal digits of resolution is acceptable (in the case of UT; the TT is not at all critical in this respect). The J2000 and MJD methods are good compromises between resolution and convenience. For UT, the date & time method is best matched to the algorithm that is used by the Earth rotation angle routine, called internally: maximum accuracy (or, at least, minimum noise) is delivered when the UTA argument is for 0hrs UT1 on the day in question and the UTB argument lies in the range 0 to 1, or vice versa.
Both UT1 and TT are required, UT1 to predict the Earth rotation and TT to predict the effects of precession-nutation. If UT1 is used for both purposes, errors of order 100 microarcseconds result.
Although the routine uses the IAU 2006 series for s+XY/2, it is otherwise independent of the precession-nutation model and can in practice be used with any equinox-based NPB matrix.
The result is returned in the range 0 to 2pi.
Reference
Wallace, P.T. & Capitaine, N., 2006, Astron.Astrophys. 459, 981
History
IAU SOFA revision: 2008 January 2
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: uta
UT1 as a 2-part Julian Date (Notes 1,2)
real(kind=wp), intent(in) :: utb
UT1 as a 2-part Julian Date (Notes 1,2)
real(kind=wp), intent(in) :: tta
TT as a 2-part Julian Date (Notes 1,2)
real(kind=wp), intent(in) :: ttb
TT as a 2-part Julian Date (Notes 1,2)
real(kind=wp), intent(in), dimension(3,3) :: rnpb
nutation x precession x bias matrix
Return Value real(kind=wp)
Greenwich apparent sidereal time (radians)
Calls
Called by
Contents
Source Code
GST06
Source Code
    function GST06 ( uta, utb, tta, ttb, rnpb ) result(gast)
    implicit none
    real(wp),intent(in) :: uta !! UT1 as a 2-part Julian Date (Notes 1,2)
    real(wp),intent(in) :: utb !! UT1 as a 2-part Julian Date (Notes 1,2)
    real(wp),intent(in) :: tta !! TT as a 2-part Julian Date (Notes 1,2)
    real(wp),intent(in) :: ttb !! TT as a 2-part Julian Date (Notes 1,2)
    real(wp),dimension(3,3),intent(in) :: rnpb !! nutation x precession x bias matrix
    real(wp) :: gast !! Greenwich apparent sidereal time (radians)
    real(wp) :: x, y, s
    !  Extract CIP coordinates.
    call BPN2XY ( rnpb, x, y )
    !  The CIO locator, s.
    s = S06 ( tta, ttb, x, y )
    !  Greenwich apparent sidereal time.
    gast = ANP ( ERA00 ( uta, utb ) - EORS ( rnpb, s ) )
    end function GST06
Call graph
gst06 calls anp, eors, bpn2xy, s06, era00
s06 calls faom03, falp03, fad03, faf03, fae03, fave03, fapa03, fal03
era00 calls anp
gst06a calls gst06
ee06a calls gst06a