GST00B – astro-fortran
GST00B Function
7 statements
Source File
public function GST00B(uta, utb) result(gast)
Greenwich Apparent Sidereal Time (consistent with IAU 2000 resolutions but using the truncated nutation model IAU 2000B).
Status: support routine.
Notes
The UT1 date UTA+UTB is a Julian Date, apportioned in any convenient way between the argument pair. For example, JD=2450123.7 could be expressed in any of these ways, among others:
     UTA            UTB
 2450123.7D0        0D0        (JD method)
  2451545D0      -1421.3D0     (J2000 method)
 2400000.5D0     50123.2D0     (MJD method)
 2450123.5D0       0.2D0       (date & time method)
The JD method is the most natural and convenient to use in cases where the loss of several decimal digits of resolution is acceptable. The J2000 and MJD methods are good compromises between resolution and convenience. For UT, the date & time method is best matched to the algorithm that is used by the Earth Rotation Angle routine, called internally: maximum accuracy (or, at least, minimum noise) is delivered when the UTA argument is for 0hrs UT1 on the day in question and the UTB argument lies in the range 0 to 1, or vice versa.
The result is compatible with the IAU 2000 resolutions, except that accuracy has been compromised for the sake of speed and convenience in two respects:
UT is used instead of TDB (or TT) to compute the precession component of GMST and the equation of the equinoxes. This results in errors of order 0.1 mas at present.
The IAU 2000B abridged nutation model (McCarthy & Luzum, 2001) is used, introducing errors of up to 1 mas.
This GAST is compatible with the IAU 2000 resolutions and must be used only in conjunction with other IAU 2000 compatible components such as precession-nutation.
The result is returned in the range 0 to 2pi.
The algorithm is from Capitaine et al. (2003) and IERS Conventions 2003.
References
Capitaine, N., Wallace, P.T. and McCarthy, D.D., "Expressions to implement the IAU 2000 definition of UT1", Astronomy & Astrophysics, 406, 1135-1149 (2003)
McCarthy, D.D. & Luzum, B.J., "An abridged model of the precession-nutation of the celestial pole", Celestial Mechanics & Dynamical Astronomy, 85, 37-49 (2003)
McCarthy, D. D., Petit, G. (eds.), IERS Conventions (2003), IERS Technical Note No. 32, BKG (2004)
History
IAU SOFA revision: 2007 December 8
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: uta
UT1 as a 2-part Julian Date (Notes 1,2)
real(kind=wp), intent(in) :: utb
UT1 as a 2-part Julian Date (Notes 1,2)
Return Value real(kind=wp)
Greenwich apparent sidereal time (radians)
Calls
Contents
Source Code
GST00B
Source Code
    function GST00B ( uta, utb ) result(gast)
    implicit none
    real(wp),intent(in) :: uta !! UT1 as a 2-part Julian Date (Notes 1,2)
    real(wp),intent(in) :: utb !! UT1 as a 2-part Julian Date (Notes 1,2)
    real(wp) :: gast !! Greenwich apparent sidereal time (radians)
    gast = ANP ( GMST00 ( uta,utb, uta,utb ) + EE00B ( uta,utb ) )
    end function GST00B
Call graph
gst00b calls anp, ee00b, gmst00
ee00b calls nut00b, obl80, ee00, pr00
gmst00 calls anp, era00
ee00 calls eect00
era00 calls anp
eect00 calls faom03, falp03, fae03, fal03, faf03, fad03, fave03, fapa03