GST00A – astro-fortran
GST00A Function
9 statements
Source File
public function GST00A(uta, utb, tta, ttb) result(gast)
Greenwich Apparent Sidereal Time (consistent with IAU 2000 resolutions).
Status: canonical model.
Notes
The UT1 and TT dates UTA+UTB and TTA+TTB respectively, are both Julian Dates, apportioned in any convenient way between the argument pairs. For example, JD=2450123.7 could be expressed in any of these ways, among others:
    Part A         Part B
 2450123.7D0        0D0        (JD method)
  2451545D0      -1421.3D0     (J2000 method)
 2400000.5D0     50123.2D0     (MJD method)
 2450123.5D0       0.2D0       (date & time method)
The JD method is the most natural and convenient to use in cases where the loss of several decimal digits of resolution is acceptable (in the case of UT; the TT is not at all critical in this respect). The J2000 and MJD methods are good compromises between resolution and convenience. For UT, the date & time method is best matched to the algorithm that is used by the Earth Rotation Angle routine, called internally: maximum accuracy (or, at least, minimum noise) is delivered when the UTA argument is for 0hrs UT1 on the day in question and the UTB argument lies in the range 0 to 1, or vice versa.
Both UT1 and TT are required, UT1 to predict the Earth rotation and TT to predict the effects of precession-nutation. If UT1 is used for both purposes, errors of order 100 microarcseconds result.
This GAST is compatible with the IAU 2000 resolutions and must be used only in conjunction with other IAU 2000 compatible components such as precession-nutation.
The result is returned in the range 0 to 2pi.
The algorithm is from Capitaine et al. (2003) and IERS Conventions 2003.
References
Capitaine, N., Wallace, P.T. and McCarthy, D.D., "Expressions to implement the IAU 2000 definition of UT1", Astronomy & Astrophysics, 406, 1135-1149 (2003)
McCarthy, D. D., Petit, G. (eds.), IERS Conventions (2003), IERS Technical Note No. 32, BKG (2004)
History
IAU SOFA revision: 2007 December 8
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: uta
UT1 as a 2-part Julian Date (Notes 1,2)
real(kind=wp), intent(in) :: utb
UT1 as a 2-part Julian Date (Notes 1,2)
real(kind=wp), intent(in) :: tta
TT as a 2-part Julian Date (Notes 1,2)
real(kind=wp), intent(in) :: ttb
TT as a 2-part Julian Date (Notes 1,2)
Return Value real(kind=wp)
Greenwich apparent sidereal time (radians)
Calls
Contents
Source Code
GST00A
Source Code
    function GST00A ( uta, utb, tta, ttb ) result(gast)
    implicit none
    real(wp),intent(in) :: uta !! UT1 as a 2-part Julian Date (Notes 1,2)
    real(wp),intent(in) :: utb !! UT1 as a 2-part Julian Date (Notes 1,2)
    real(wp),intent(in) :: tta !! TT as a 2-part Julian Date (Notes 1,2)
    real(wp),intent(in) :: ttb !! TT as a 2-part Julian Date (Notes 1,2)
    real(wp) :: gast !! Greenwich apparent sidereal time (radians)
    gast = ANP ( GMST00 ( uta,utb, tta,ttb ) + EE00A ( tta,ttb ) )
    end function GST00A
Call graph
gst00a calls anp, gmst00, ee00a
gmst00 calls anp, era00
ee00a calls nut00a, obl80, ee00, pr00
nut00a calls faom03, faju03, fasa03, fae03, fame03, fal03, fapa03, faf03, fave03, fama03, faur03
ee00 calls eect00
era00 calls anp
eect00 calls faom03, fae03, fal03, fapa03, faf03, fave03, falp03, fad03