GST94 – astro-fortran
GST94 Function
7 statements
Source File
public function GST94(uta, utb) result(gast)
Greenwich Apparent Sidereal Time (consistent with IAU 1982/94 resolutions).
Status: support routine.
Notes
The UT1 date UTA+UTB is a Julian Date, apportioned in any convenient way between the argument pair. For example, JD=2450123.7 could be expressed in any of these ways, among others:
     UTA            UTB
 2450123.7D0        0D0        (JD method)
  2451545D0      -1421.3D0     (J2000 method)
 2400000.5D0     50123.2D0     (MJD method)
 2450123.5D0       0.2D0       (date & time method)
The JD method is the most natural and convenient to use in cases where the loss of several decimal digits of resolution is acceptable. The J2000 and MJD methods are good compromises between resolution and convenience. For UT, the date & time method is best matched to the algorithm that is used by the Earth Rotation Angle routine, called internally: maximum accuracy (or, at least, minimum noise) is delivered when the UTA argument is for 0hrs UT1 on the day in question and the UTB argument lies in the range 0 to 1, or vice versa.
The result is compatible with the IAU 1982 and 1994 resolutions, except that accuracy has been compromised for the sake of convenience in that UT is used instead of TDB (or TT) to compute the equation of the equinoxes.
This GAST must be used only in conjunction with contemporaneous IAU standards such as 1976 precession, 1980 obliquity and 1982 nutation. It is not compatible with the IAU 2000 resolutions.
The result is returned in the range 0 to 2pi.
References
Explanatory Supplement to the Astronomical Almanac, P. Kenneth Seidelmann (ed), University Science Books (1992)
IAU Resolution C7, Recommendation 3 (1994)
History
IAU SOFA revision: 2007 December 8
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: uta
UT1 as a 2-part Julian Date (Notes 1,2)
real(kind=wp), intent(in) :: utb
UT1 as a 2-part Julian Date (Notes 1,2)
Return Value real(kind=wp)
Greenwich apparent sidereal time (radians)
Calls
Contents
Source Code
GST94
Source Code
    function GST94 ( uta, utb ) result(gast)
    implicit none
    real(wp),intent(in) :: uta !! UT1 as a 2-part Julian Date (Notes 1,2)
    real(wp),intent(in) :: utb !! UT1 as a 2-part Julian Date (Notes 1,2)
    real(wp) :: gast !! Greenwich apparent sidereal time (radians)
    gast = ANP ( GMST82 ( uta, utb ) + EQEQ94 ( uta, utb ) )
    end function GST94
Call graph
gst94 calls gmst82, anp, eqeq94
gmst82 calls anp
eqeq94 calls obl80, anpm, nut80
nut80 calls anpm