H2FK5 – astro-fortran
H2FK5 Subroutine
28 statements
Source File
public subroutine H2FK5(rh, dh, drh, ddh, pxh, rvh, r5, d5, dr5, dd5, px5, rv5)
Transform Hipparcos star data into the FK5 (J2000.0) system.
Status: support routine.
Notes
This routine transforms Hipparcos star positions and proper motions into FK5 J2000.0.
The proper motions in RA are dRA/dt rather than cos(Dec)*dRA/dt, and are per year rather than per century.
The FK5 to Hipparcos transformation is modeled as a pure rotation and spin; zonal errors in the FK5 catalog are not taken into account.
See also FK52H, FK5HZ, HFK5Z.
Reference
F. Mignard & M. Froeschle, Astron.Astrophys., 354, 732-739 (2000).
History
IAU SOFA revision: 2017 October 12
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: rh
RA (radians) [Hipparcos, epoch J2000.0]
real(kind=wp), intent(in) :: dh
Dec (radians) [Hipparcos, epoch J2000.0]
real(kind=wp), intent(in) :: drh
proper motion in RA (dRA/dt, rad/Jyear) [Hipparcos, epoch J2000.0]
real(kind=wp), intent(in) :: ddh
proper motion in Dec (dDec/dt, rad/Jyear) [Hipparcos, epoch J2000.0]
real(kind=wp), intent(in) :: pxh
parallax (arcsec) [Hipparcos, epoch J2000.0]
real(kind=wp), intent(in) :: rvh
radial velocity (km/s, positive = receding) [Hipparcos, epoch J2000.0]
real(kind=wp), intent(out) :: r5
RA (radians) [FK5, equinox J2000.0, epoch J2000.0]
real(kind=wp), intent(out) :: d5
Dec (radians) [FK5, equinox J2000.0, epoch J2000.0]
real(kind=wp), intent(out) :: dr5
proper motion in RA (dRA/dt, rad/Jyear) [FK5, equinox J2000.0, epoch J2000.0]
real(kind=wp), intent(out) :: dd5
proper motion in Dec (dDec/dt, rad/Jyear) [FK5, equinox J2000.0, epoch J2000.0]
real(kind=wp), intent(out) :: px5
parallax (arcsec) [FK5, equinox J2000.0, epoch J2000.0]
real(kind=wp), intent(out) :: rv5
radial velocity (km/s, positive = receding) [FK5, equinox J2000.0, epoch J2000.0]
Calls
Contents
Source Code
H2FK5
Source Code
    subroutine H2FK5 ( rh, dh, drh, ddh, pxh, rvh, &
                       r5, d5, dr5, dd5, px5, rv5 )
    implicit none
    real(wp),intent(in) :: rh !! RA (radians) [Hipparcos, epoch J2000.0]
    real(wp),intent(in) :: dh !! Dec (radians) [Hipparcos, epoch J2000.0]
    real(wp),intent(in) :: drh !! proper motion in RA (dRA/dt, rad/Jyear) [Hipparcos, epoch J2000.0]
    real(wp),intent(in) :: ddh !! proper motion in Dec (dDec/dt, rad/Jyear) [Hipparcos, epoch J2000.0]
    real(wp),intent(in) :: pxh !! parallax (arcsec) [Hipparcos, epoch J2000.0]
    real(wp),intent(in) :: rvh !! radial velocity (km/s, positive = receding) [Hipparcos, epoch J2000.0]
    real(wp),intent(out) :: r5 !! RA (radians) [FK5, equinox J2000.0, epoch J2000.0]
    real(wp),intent(out) :: d5 !! Dec (radians) [FK5, equinox J2000.0, epoch J2000.0]
    real(wp),intent(out) :: dr5 !! proper motion in RA (dRA/dt, rad/Jyear) [FK5, equinox J2000.0, epoch J2000.0]
    real(wp),intent(out) :: dd5 !! proper motion in Dec (dDec/dt, rad/Jyear) [FK5, equinox J2000.0, epoch J2000.0]
    real(wp),intent(out) :: px5 !! parallax (arcsec) [FK5, equinox J2000.0, epoch J2000.0]
    real(wp),intent(out) :: rv5 !! radial velocity (km/s, positive = receding) [FK5, equinox J2000.0, epoch J2000.0]
    real(wp) :: pvh(3,2), r5h(3,3), s5h(3), sh(3), wxp(3), &
                vv(3), pv5(3,2)
    integer :: j, i
    !  Hipparcos barycentric position/velocity pv-vector (normalized).
    call STARPV ( rh, dh, drh, ddh, pxh, rvh, pvh, j )
    !  FK5 to Hipparcos orientation matrix and spin vector.
    call FK5HIP ( r5h, s5h )
    !  Make spin units per day instead of per year.
    do i=1,3
       s5h(i) = s5h(i) / 365.25_wp
    end do
    !  Orient the spin into the Hipparcos system.
    call RXP ( r5h, s5h, sh )
    !  De-orient the Hipparcos position into the FK5 system.
    call TRXP ( r5h, pvh(1,1), pv5(1,1) )
    !  Apply spin to the position giving an extra space motion component.
    call PXP ( pvh(1,1), sh, wxp )
    !  Subtract this component from the Hipparcos space motion.
    call PMP ( pvh(1,2), wxp, vv )
    !  De-orient the Hipparcos space motion into the FK5 system.
    call TRXP ( r5h, vv, pv5(1,2) )
    !  FK5 pv-vector to spherical.
    call PVSTAR ( pv5, r5, d5, dr5, dd5, px5, rv5, j )
    end subroutine H2FK5
Call graph
h2fk5 calls starpv, rxp, fk5hip, trxp, pxp, pmp, pvstar
starpv calls pmp, pdp, sxp, zp, ppp, s2pv
fk5hip calls rv2m
trxp calls rxp, tr
pvstar calls pmp, pdp, sxp, ppp, pv2s, anp