IR – astro-fortran
IR Subroutine
13 statements
Source File
public subroutine IR(r)
Initialize an r-matrix to the identity matrix.
Status: vector/matrix support routine.
History
IAU SOFA revision: 2012 April 3
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(out), dimension(3,3) :: r
r-matrix
Called by
Contents
Source Code
IR
Source Code
    subroutine IR ( r )
    implicit none
    real(wp),dimension(3,3),intent(out) :: r !! r-matrix
    r(1,1) = 1.0_wp
    r(1,2) = 0.0_wp
    r(1,3) = 0.0_wp
    r(2,1) = 0.0_wp
    r(2,2) = 1.0_wp
    r(2,3) = 0.0_wp
    r(3,1) = 0.0_wp
    r(3,2) = 0.0_wp
    r(3,3) = 1.0_wp
    end subroutine IR
Call graph
c2ixys calls ir
numat calls ir
bp00 calls ir
fw2m calls ir
apcs calls ir
pom00 calls ir
ecm06 calls ir, pmat06
pmat76 calls ir
pn00 calls numat, bp00
c2i06a calls c2ixys, pnm06a
pnm80 calls pmat76, nutm80
apco calls c2ixys, apcs, pvtob
apcg calls apcs
pvtob calls pom00
c2ixy calls c2ixys
fw2xy calls fw2m
c2tpe calls pom00, pn00
nutm80 calls numat
pnm06a calls fw2m
pn06 calls fw2m
pmat06 calls fw2m
apci calls c2ixys, apcg
num06a calls numat
pmat00 calls bp00
c2t00b calls pom00, c2i00b
bp06 calls fw2m, pmat06
c2t00a calls pom00, c2i00a
c2txy calls pom00, c2ixy
eceq06 calls ecm06
apcs13 calls apcs
c2t06a calls pom00, c2i06a
eqec06 calls ecm06
pn00a calls pn00
apio calls pvtob
apco13 calls apco, pnm06a
c2ibpn calls c2ixy
gst06a calls pnm06a
s06a calls pnm06a
xys06a calls pnm06a
pn06a calls pn06
pn00b calls pn00
apcg13 calls apcg
apci13 calls pnm06a, apci
eo06a calls pnm06a
pb06 calls pmat06
atco13 calls apco13
num00a calls pn00a
atci13 calls apci13
atic13 calls apci13
pnm00a calls pn00a
apio13 calls apio
atoc13 calls apco13
c2i00a calls c2ibpn, pnm00a
c2i00b calls c2ibpn, pnm00b
ee06a calls gst06a
pnm00b calls pn00b
num00b calls pn00b
atoi13 calls apio13
xys00a calls pnm00a
atio13 calls apio13
s00a calls pnm00a
s00b calls pnm00b
xys00b calls pnm00b