LDSUN – astro-fortran
LDSUN Subroutine
10 statements
Source File
public subroutine LDSUN(p, e, em, p1)
Deflection of starlight by the Sun.
Status: support routine.
Notes
The source is presumed to be sufficiently distant that its directions seen from the Sun and the observer are essentially the same.
The deflection is restrained when the angle between the star and the center of the Sun is less than a threshold value, falling to zero deflection for zero separation. The chosen threshold value is within the solar limb for all solar-system applications, and is about 5 arcminutes for the case of a terrestrial observer.
History
IAU SOFA revision: 2016 June 16
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(3) :: p
direction from observer to star (unit vector)
real(kind=wp), intent(in), dimension(3) :: e
direction from Sun to observer (unit vector)
real(kind=wp), intent(in) :: em
distance from Sun to observer (au)
real(kind=wp), intent(out), dimension(3) :: p1
observer to deflected star (unit vector)
Calls
Called by
Contents
Source Code
LDSUN
Source Code
    subroutine LDSUN ( p, e, em, p1 )
    implicit none
    real(wp),dimension(3),intent(in) :: p !! direction from observer to star (unit vector)
    real(wp),dimension(3),intent(in) :: e !! direction from Sun to observer (unit vector)
    real(wp),intent(in) :: em !! distance from Sun to observer (au)
    real(wp),dimension(3),intent(out) :: p1 !! observer to deflected star (unit vector)
    real(wp) :: dlim
    !  Deflection limiter (smaller for distant observers).
    dlim = 1.0e-6_wp / max(em*em,1.0_wp)
    !  Apply the deflection.
    call LD ( 1.0_wp, p, p, e, em, dlim, p1 )
    end subroutine LDSUN
Call graph
ldsun calls ld
ld calls pdp, pxp
aticq calls ldsun
atciq calls ldsun
atciqz calls ldsun
atoc13 calls aticq
atic13 calls aticq
atci13 calls atciq
atco13 calls atciq