NUM06A – astro-fortran
NUM06A Subroutine
10 statements
Source File
public subroutine NUM06A(date1, date2, rmatn)
Form the matrix of nutation for a given date, IAU 2006/2000A model.
Status: support routine.
Notes
The TT date DATE1+DATE2 is a Julian Date, apportioned in any convenient way between the two arguments. For example, JD(TT)=2450123.7 could be expressed in any of these ways, among others:
    DATE1          DATE2
 2450123.7D0        0D0        (JD method)
  2451545D0      -1421.3D0     (J2000 method)
 2400000.5D0     50123.2D0     (MJD method)
 2450123.5D0       0.2D0       (date & time method)
The JD method is the most natural and convenient to use in cases where the loss of several decimal digits of resolution is acceptable. The J2000 method is best matched to the way the argument is handled internally and will deliver the optimum resolution. The MJD method and the date & time methods are both good compromises between resolution and convenience.
The matrix operates in the sense V(true) = RMATN * V(mean), where the p-vector V(true) is with respect to the true equatorial triad of date and the p-vector V(mean) is with respect to the mean equatorial triad of date.
References
Capitaine, N., Wallace, P.T. & Chapront, J., 2005, Astron. Astrophys. 432, 355
Wallace, P.T. & Capitaine, N., 2006, Astron.Astrophys. 459, 981
History
IAU SOFA revision: 2007 May 11
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: date1
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(in) :: date2
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(out), dimension(3,3) :: rmatn
nutation matrix
Calls
Contents
Source Code
NUM06A
Source Code
    subroutine NUM06A ( date1, date2, rmatn )
    implicit none
    real(wp),intent(in) :: date1 !! TT as a 2-part Julian Date (Note 1)
    real(wp),intent(in) :: date2 !! TT as a 2-part Julian Date (Note 1)
    real(wp),dimension(3,3),intent(out) :: rmatn !! nutation matrix
    real(wp) :: eps, dp, de
    !  Mean obliquity.
    eps = OBL06 ( date1, date2 )
    !  Nutation components.
    call NUT06A ( date1, date2, dp, de )
    !  Nutation matrix.
    call NUMAT ( eps, dp, de, rmatn )
    end subroutine NUM06A
Call graph
num06a calls obl06, nut06a, numat
nut06a calls nut00a
numat calls ir, rz, rx
nut00a calls faom03, faju03, fasa03, fae03, fame03, fal03, fapa03, faf03, fave03, fama03, faur03