NUM00A – astro-fortran
NUM00A Subroutine
8 statements
Source File
public subroutine NUM00A(date1, date2, rmatn)
Form the matrix of nutation for a given date, IAU 2000A model.
Status: support routine.
Notes
The TT date DATE1+DATE2 is a Julian Date, apportioned in any convenient way between the two arguments. For example, JD(TT)=2450123.7 could be expressed in any of these ways, among others:
    DATE1          DATE2
 2450123.7D0        0D0        (JD method)
  2451545D0      -1421.3D0     (J2000 method)
 2400000.5D0     50123.2D0     (MJD method)
 2450123.5D0       0.2D0       (date & time method)
The JD method is the most natural and convenient to use in cases where the loss of several decimal digits of resolution is acceptable. The J2000 method is best matched to the way the argument is handled internally and will deliver the optimum resolution. The MJD method and the date & time methods are both good compromises between resolution and convenience.
The matrix operates in the sense V(true) = RMATN * V(mean), where the p-vector V(true) is with respect to the true equatorial triad of date and the p-vector V(mean) is with respect to the mean equatorial triad of date.
A faster, but slightly less accurate result (about 1 mas), can be obtained by using instead the NUM00B routine.
Reference
Explanatory Supplement to the Astronomical Almanac, P. Kenneth Seidelmann (ed), University Science Books (1992), Section 3.222-3 (p114).
History
IAU SOFA revision: 2006 November 13
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: date1
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(in) :: date2
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(out), dimension(3,3) :: rmatn
nutation matrix
Calls
Contents
Source Code
NUM00A
Source Code
    subroutine NUM00A ( date1, date2, rmatn )
    implicit none
    real(wp),intent(in) :: date1 !! TT as a 2-part Julian Date (Note 1)
    real(wp),intent(in) :: date2 !! TT as a 2-part Julian Date (Note 1)
    real(wp),dimension(3,3),intent(out) :: rmatn !! nutation matrix
    real(wp) :: dpsi, deps, epsa, &
                rb(3,3), rp(3,3), rbp(3,3), rbpn(3,3)
    !  Obtain the required matrix (discarding other results).
    call PN00A ( date1, date2, &
                 dpsi, deps, epsa, rb, rp, rbp, rmatn, rbpn )
    end subroutine NUM00A
Call graph
num00a calls pn00a
pn00a calls nut00a, pn00
nut00a calls faom03, faju03, fasa03, fae03, fame03, fal03, fapa03, faf03, fave03, fama03, faur03
pn00 calls obl80, numat, bp00, pr00, rxr
numat calls rx, ir, rz
bp00 calls pr00, rxr, rx, ry, ir, rz, bi00