NUMAT – astro-fortran
NUMAT Subroutine
11 statements
Source File
public subroutine NUMAT(epsa, dpsi, deps, rmatn)
Form the matrix of nutation.
Status: support routine.
Notes
The supplied mean obliquity EPSA, must be consistent with the precession-nutation models from which DPSI and DEPS were obtained.
The caller is responsible for providing the nutation components; they are in longitude and obliquity, in radians and are with respect to the equinox and ecliptic of date.
The matrix operates in the sense V(true) = RMATN * V(mean), where the p-vector V(true) is with respect to the true equatorial triad of date and the p-vector V(mean) is with respect to the mean equatorial triad of date.
Reference
Explanatory Supplement to the Astronomical Almanac, P. Kenneth Seidelmann (ed), University Science Books (1992), Section 3.222-3 (p114).
History
IAU SOFA revision: 2006 November 13
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: epsa
mean obliquity of date (Note 1)
real(kind=wp), intent(in) :: dpsi
nutation (Note 2)
real(kind=wp), intent(in) :: deps
nutation (Note 2)
real(kind=wp), intent(out), dimension(3,3) :: rmatn
nutation matrix (Note 3)
Calls
Called by
Contents
Source Code
NUMAT
Source Code
    subroutine NUMAT ( epsa, dpsi, deps, rmatn )
    implicit none
    real(wp),intent(in) :: epsa !! mean obliquity of date (Note 1)
    real(wp),intent(in) :: dpsi !! nutation (Note 2)
    real(wp),intent(in) :: deps !! nutation (Note 2)
    real(wp),dimension(3,3),intent(out) :: rmatn !! nutation matrix (Note 3)
    !  Build the rotation matrix.
    call IR ( rmatn )
    call RX ( epsa, rmatn )
    call RZ ( -dpsi, rmatn )
    call RX ( -(epsa+deps), rmatn )
    end subroutine NUMAT
Call graph
numat calls ir, rz, rx
num06a calls numat
pn00 calls numat
nutm80 calls numat
pn00a calls pn00
pn00b calls pn00
pnm80 calls nutm80
c2tpe calls pn00
num00a calls pn00a
pnm00a calls pn00a
pnm00b calls pn00b
num00b calls pn00b
s00b calls pnm00b
c2i00a calls pnm00a
s00a calls pnm00a
xys00a calls pnm00a
xys00b calls pnm00b
c2i00b calls pnm00b
c2t00b calls c2i00b
c2t00a calls c2i00a