NUT00B – astro-fortran
NUT00B Subroutine
38 statements
Source File
public subroutine NUT00B(date1, date2, dpsi, deps)
Nutation, IAU 2000B model.
Status: canonical model.
Notes
The TT date DATE1+DATE2 is a Julian Date, apportioned in any convenient way between the two arguments. For example, JD(TT)=2450123.7 could be expressed in any of these ways, among others:
    DATE1          DATE2
 2450123.7D0        0D0        (JD method)
  2451545D0      -1421.3D0     (J2000 method)
 2400000.5D0     50123.2D0     (MJD method)
 2450123.5D0       0.2D0       (date & time method)
The JD method is the most natural and convenient to use in cases where the loss of several decimal digits of resolution is acceptable. The J2000 method is best matched to the way the argument is handled internally and will deliver the optimum resolution. The MJD method and the date & time methods are both good compromises between resolution and convenience.
The nutation components in longitude and obliquity are in radians and with respect to the equinox and ecliptic of date. The obliquity at J2000.0 is assumed to be the Lieske et al. (1977) value of 84381.448 arcsec. (The errors that result from using this routine with the IAU 2006 value of 84381.406 arcsec can be neglected.)
The nutation model consists only of luni-solar terms, but includes also a fixed offset which compensates for certain long-period planetary terms (Note 7).
This routine is an implementation of the IAU 2000B abridged nutation model formally adopted by the IAU General Assembly in
The routine computes the MHB_2000_SHORT luni-solar nutation series (Luzum 2001), but without the associated corrections for the precession rate adjustments and the offset between the GCRS and J2000.0 mean poles.
The full IAU 2000A (MHB2000) nutation model contains nearly 1400 terms. The IAU 2000B model (McCarthy & Luzum 2003) contains only 77 terms, plus additional simplifications, yet still delivers results of 1 mas accuracy at present epochs. This combination of accuracy and size makes the IAU 2000B abridged nutation model suitable for most practical applications.
The routine delivers a pole accurate to 1 mas from 1900 to 2100 (usually better than 1 mas, very occasionally just outside 1 mas). The full IAU 2000A model, which is implemented in the routine NUT00A (q.v.), delivers considerably greater accuracy at current epochs; however, to realize this improved accuracy, corrections for the essentially unpredictable free-core-nutation (FCN) must also be included.
The present routine provides classical nutation. The MHB_2000_SHORT algorithm, from which it is adapted, deals also with (i) the offsets between the GCRS and mean poles and (ii) the adjustments in longitude and obliquity due to the changed precession rates. These additional functions, namely frame bias and precession adjustments, are supported by the SOFA routines BI00 and PR00.
The MHB_2000_SHORT algorithm also provides "total" nutations, comprising the arithmetic sum of the frame bias, precession adjustments, and nutation (luni-solar + planetary). These total nutations can be used in combination with an existing IAU 1976 precession implementation, such as PMAT76, to deliver GCRS-to- true predictions of mas accuracy at current epochs. However, for symmetry with the NUT00A routine (q.v. for the reasons), the SOFA routines do not generate the "total nutations" directly. Should they be required, they could of course easily be generated by calling BI00, PR00 and the present routine and adding the results.
The IAU 2000B model includes "planetary bias" terms that are fixed in size but compensate for long-period nutations. The amplitudes quoted in McCarthy & Luzum (2003), namely Dpsi = -1.5835 mas and Depsilon = +1.6339 mas, are optimized for the "total nutations" method described in Note 6. The Luzum (2001) values used in this SOFA implementation, namely -0.135 mas and +0.388 mas, are optimized for the "rigorous" method, where frame bias, precession and nutation are applied separately and in that order. During the interval 1995-2050, the SOFA implementation delivers a maximum error of 1.001 mas (not including FCN).
References
Lieske, J.H., Lederle, T., Fricke, W., Morando, B., "Expressions for the precession quantities based upon the IAU /1976/ system of astronomical constants", Astron.Astrophys. 58, 1-2, 1-16. (1977)
Luzum, B., private communication, 2001 (Fortran code MHB_2000_SHORT)
McCarthy, D.D. & Luzum, B.J., "An abridged model of the precession-nutation of the celestial pole", Cel.Mech.Dyn.Astron. 85, 37-49 (2003)
Simon, J.-L., Bretagnon, P., Chapront, J., Chapront-Touze, M., Francou, G., Laskar, J., Astron.Astrophys. 282, 663-683 (1994)
History
IAU SOFA revision: 2009 December 15
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: date1
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(in) :: date2
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(out) :: dpsi
nutation, luni-solar + planetary (Note 2)
real(kind=wp), intent(out) :: deps
nutation, luni-solar + planetary (Note 2)
Called by
Contents
Source Code
NUT00B
Source Code
    subroutine NUT00B ( date1, date2, dpsi, deps )
    implicit none
    real(wp),intent(in) :: date1 !! TT as a 2-part Julian Date (Note 1)
    real(wp),intent(in) :: date2 !! TT as a 2-part Julian Date (Note 1)
    real(wp),intent(out) :: dpsi !! nutation, luni-solar + planetary (Note 2)
    real(wp),intent(out) :: deps !! nutation, luni-solar + planetary (Note 2)
    !  Milliarcseconds to radians
    real(wp),parameter :: dmas2r = das2r / 1.0e3_wp
    !  Arcseconds in a full circle
    real(wp),parameter :: turnas = 1296000.0_wp
    !  Units of 0.1 microarcsecond to radians
    real(wp),parameter :: u2r = das2r/1.0e7_wp
    !  Miscellaneous
    real(wp) :: t, el, elp, f, d, om, arg, dp, de, sarg, carg, &
                     dpsils, depsls, dpsipl, depspl
    integer :: i, j
    !  -------------------------
    !  Luni-Solar nutation model
    !  -------------------------
    !  Number of terms in the luni-solar nutation model
    integer,parameter :: nls = 77
    !  ---------------------------------------
    !  Fixed offset in lieu of planetary terms (radians)
    !  ---------------------------------------
    real(wp),parameter :: dpplan = - 0.135_wp * dmas2r
    real(wp),parameter :: deplan = + 0.388_wp * dmas2r
    !  ----------------------------------------
    !  Tables of argument and term coefficients
    !  ----------------------------------------
    !
    !  Luni-Solar argument multipliers:
    !
    !               L     L'    F     D     Om
    !  Coefficients for fundamental arguments
    integer,dimension(5,nls),parameter :: nals = reshape([ &
              0,    0,    0,    0,    1, &
              0,    0,    2,   -2,    2, &
              0,    0,    2,    0,    2, &
              0,    0,    0,    0,    2, &
              0,    1,    0,    0,    0, &
              0,    1,    2,   -2,    2, &
              1,    0,    0,    0,    0, &
              0,    0,    2,    0,    1, &
              1,    0,    2,    0,    2, &
              0,   -1,    2,   -2,    2, &
              0,    0,    2,   -2,    1, &
             -1,    0,    2,    0,    2, &
             -1,    0,    0,    2,    0, &
              1,    0,    0,    0,    1, &
             -1,    0,    0,    0,    1, &
             -1,    0,    2,    2,    2, &
              1,    0,    2,    0,    1, &
             -2,    0,    2,    0,    1, &
              0,    0,    0,    2,    0, &
              0,    0,    2,    2,    2, &
              0,   -2,    2,   -2,    2, &
             -2,    0,    0,    2,    0, &
              2,    0,    2,    0,    2, &
              1,    0,    2,   -2,    2, &
             -1,    0,    2,    0,    1, &
              2,    0,    0,    0,    0, &
              0,    0,    2,    0,    0, &
              0,    1,    0,    0,    1, &
             -1,    0,    0,    2,    1, &
              0,    2,    2,   -2,    2, &
              0,    0,   -2,    2,    0, &
              1,    0,    0,   -2,    1, &
              0,   -1,    0,    0,    1, &
             -1,    0,    2,    2,    1, &
              0,    2,    0,    0,    0, &
              1,    0,    2,    2,    2, &
             -2,    0,    2,    0,    0, &
              0,    1,    2,    0,    2, &
              0,    0,    2,    2,    1, &
              0,   -1,    2,    0,    2, &
              0,    0,    0,    2,    1, &
              1,    0,    2,   -2,    1, &
              2,    0,    2,   -2,    2, &
             -2,    0,    0,    2,    1, &
              2,    0,    2,    0,    1, &
              0,   -1,    2,   -2,    1, &
              0,    0,    0,   -2,    1, &
             -1,   -1,    0,    2,    0, &
              2,    0,    0,   -2,    1, &
              1,    0,    0,    2,    0, &
              0,    1,    2,   -2,    1, &
              1,   -1,    0,    0,    0, &
             -2,    0,    2,    0,    2, &
              3,    0,    2,    0,    2, &
              0,   -1,    0,    2,    0, &
              1,   -1,    2,    0,    2, &
              0,    0,    0,    1,    0, &
             -1,   -1,    2,    2,    2, &
             -1,    0,    2,    0,    0, &
              0,   -1,    2,    2,    2, &
             -2,    0,    0,    0,    1, &
              1,    1,    2,    0,    2, &
              2,    0,    0,    0,    1, &
             -1,    1,    0,    1,    0, &
              1,    1,    0,    0,    0, &
              1,    0,    2,    0,    0, &
             -1,    0,    2,   -2,    1, &
              1,    0,    0,    0,    2, &
             -1,    0,    0,    1,    0, &
              0,    0,    2,    1,    2, &
             -1,    0,    2,    4,    2, &
             -1,    1,    0,    1,    1, &
              0,   -2,    2,   -2,    1, &
              1,    0,    2,    2,    1, &
             -2,    0,    2,    2,    2, &
             -1,    0,    0,    0,    2, &
              1,    1,    2,   -2,    2 ], [5,nls])
    !
    !  Luni-Solar nutation coefficients, unit 1e-7 arcsec:
    !  longitude (sin, t*sin, cos), obliquity (cos, t*cos, sin)
    !
    !  Longitude and obliquity coefficients
    real(wp),dimension(6,nls),parameter :: cls = reshape([ &
     -172064161.0_wp, -174666.0_wp,  33386.0_wp, 92052331.0_wp,  9086.0_wp, 15377.0_wp, &
      -13170906.0_wp,   -1675.0_wp, -13696.0_wp,  5730336.0_wp, -3015.0_wp, -4587.0_wp, &
       -2276413.0_wp,    -234.0_wp,   2796.0_wp,   978459.0_wp,  -485.0_wp,  1374.0_wp, &
        2074554.0_wp,     207.0_wp,   -698.0_wp,  -897492.0_wp,   470.0_wp,  -291.0_wp, &
        1475877.0_wp,   -3633.0_wp,  11817.0_wp,    73871.0_wp,  -184.0_wp, -1924.0_wp, &
        -516821.0_wp,    1226.0_wp,   -524.0_wp,   224386.0_wp,  -677.0_wp,  -174.0_wp, &
         711159.0_wp,      73.0_wp,   -872.0_wp,    -6750.0_wp,     0.0_wp,   358.0_wp, &
        -387298.0_wp,    -367.0_wp,    380.0_wp,   200728.0_wp,    18.0_wp,   318.0_wp, &
        -301461.0_wp,     -36.0_wp,    816.0_wp,   129025.0_wp,   -63.0_wp,   367.0_wp, &
         215829.0_wp,    -494.0_wp,    111.0_wp,   -95929.0_wp,   299.0_wp,   132.0_wp, &
         128227.0_wp,     137.0_wp,    181.0_wp,   -68982.0_wp,    -9.0_wp,    39.0_wp, &
         123457.0_wp,      11.0_wp,     19.0_wp,   -53311.0_wp,    32.0_wp,    -4.0_wp, &
         156994.0_wp,      10.0_wp,   -168.0_wp,    -1235.0_wp,     0.0_wp,    82.0_wp, &
          63110.0_wp,      63.0_wp,     27.0_wp,   -33228.0_wp,     0.0_wp,    -9.0_wp, &
         -57976.0_wp,     -63.0_wp,   -189.0_wp,    31429.0_wp,     0.0_wp,   -75.0_wp, &
         -59641.0_wp,     -11.0_wp,    149.0_wp,    25543.0_wp,   -11.0_wp,    66.0_wp, &
         -51613.0_wp,     -42.0_wp,    129.0_wp,    26366.0_wp,     0.0_wp,    78.0_wp, &
          45893.0_wp,      50.0_wp,     31.0_wp,   -24236.0_wp,   -10.0_wp,    20.0_wp, &
          63384.0_wp,      11.0_wp,   -150.0_wp,    -1220.0_wp,     0.0_wp,    29.0_wp, &
         -38571.0_wp,      -1.0_wp,    158.0_wp,    16452.0_wp,   -11.0_wp,    68.0_wp, &
          32481.0_wp,       0.0_wp,      0.0_wp,   -13870.0_wp,     0.0_wp,     0.0_wp, &
         -47722.0_wp,       0.0_wp,    -18.0_wp,      477.0_wp,     0.0_wp,   -25.0_wp, &
         -31046.0_wp,      -1.0_wp,    131.0_wp,    13238.0_wp,   -11.0_wp,    59.0_wp, &
          28593.0_wp,       0.0_wp,     -1.0_wp,   -12338.0_wp,    10.0_wp,    -3.0_wp, &
          20441.0_wp,      21.0_wp,     10.0_wp,   -10758.0_wp,     0.0_wp,    -3.0_wp, &
          29243.0_wp,       0.0_wp,    -74.0_wp,     -609.0_wp,     0.0_wp,    13.0_wp, &
          25887.0_wp,       0.0_wp,    -66.0_wp,     -550.0_wp,     0.0_wp,    11.0_wp, &
         -14053.0_wp,     -25.0_wp,     79.0_wp,     8551.0_wp,    -2.0_wp,   -45.0_wp, &
          15164.0_wp,      10.0_wp,     11.0_wp,    -8001.0_wp,     0.0_wp,    -1.0_wp, &
         -15794.0_wp,      72.0_wp,    -16.0_wp,     6850.0_wp,   -42.0_wp,    -5.0_wp, &
          21783.0_wp,       0.0_wp,     13.0_wp,     -167.0_wp,     0.0_wp,    13.0_wp, &
         -12873.0_wp,     -10.0_wp,    -37.0_wp,     6953.0_wp,     0.0_wp,   -14.0_wp, &
         -12654.0_wp,      11.0_wp,     63.0_wp,     6415.0_wp,     0.0_wp,    26.0_wp, &
         -10204.0_wp,       0.0_wp,     25.0_wp,     5222.0_wp,     0.0_wp,    15.0_wp, &
          16707.0_wp,     -85.0_wp,    -10.0_wp,      168.0_wp,    -1.0_wp,    10.0_wp, &
          -7691.0_wp,       0.0_wp,     44.0_wp,     3268.0_wp,     0.0_wp,    19.0_wp, &
         -11024.0_wp,       0.0_wp,    -14.0_wp,      104.0_wp,     0.0_wp,     2.0_wp, &
           7566.0_wp,     -21.0_wp,    -11.0_wp,    -3250.0_wp,     0.0_wp,    -5.0_wp, &
          -6637.0_wp,     -11.0_wp,     25.0_wp,     3353.0_wp,     0.0_wp,    14.0_wp, &
          -7141.0_wp,      21.0_wp,      8.0_wp,     3070.0_wp,     0.0_wp,     4.0_wp, &
          -6302.0_wp,     -11.0_wp,      2.0_wp,     3272.0_wp,     0.0_wp,     4.0_wp, &
           5800.0_wp,      10.0_wp,      2.0_wp,    -3045.0_wp,     0.0_wp,    -1.0_wp, &
           6443.0_wp,       0.0_wp,     -7.0_wp,    -2768.0_wp,     0.0_wp,    -4.0_wp, &
          -5774.0_wp,     -11.0_wp,    -15.0_wp,     3041.0_wp,     0.0_wp,    -5.0_wp, &
          -5350.0_wp,       0.0_wp,     21.0_wp,     2695.0_wp,     0.0_wp,    12.0_wp, &
          -4752.0_wp,     -11.0_wp,     -3.0_wp,     2719.0_wp,     0.0_wp,    -3.0_wp, &
          -4940.0_wp,     -11.0_wp,    -21.0_wp,     2720.0_wp,     0.0_wp,    -9.0_wp, &
           7350.0_wp,       0.0_wp,     -8.0_wp,      -51.0_wp,     0.0_wp,     4.0_wp, &
           4065.0_wp,       0.0_wp,      6.0_wp,    -2206.0_wp,     0.0_wp,     1.0_wp, &
           6579.0_wp,       0.0_wp,    -24.0_wp,     -199.0_wp,     0.0_wp,     2.0_wp, &
           3579.0_wp,       0.0_wp,      5.0_wp,    -1900.0_wp,     0.0_wp,     1.0_wp, &
           4725.0_wp,       0.0_wp,     -6.0_wp,      -41.0_wp,     0.0_wp,     3.0_wp, &
          -3075.0_wp,       0.0_wp,     -2.0_wp,     1313.0_wp,     0.0_wp,    -1.0_wp, &
          -2904.0_wp,       0.0_wp,     15.0_wp,     1233.0_wp,     0.0_wp,     7.0_wp, &
           4348.0_wp,       0.0_wp,    -10.0_wp,      -81.0_wp,     0.0_wp,     2.0_wp, &
          -2878.0_wp,       0.0_wp,      8.0_wp,     1232.0_wp,     0.0_wp,     4.0_wp, &
          -4230.0_wp,       0.0_wp,      5.0_wp,      -20.0_wp,     0.0_wp,    -2.0_wp, &
          -2819.0_wp,       0.0_wp,      7.0_wp,     1207.0_wp,     0.0_wp,     3.0_wp, &
          -4056.0_wp,       0.0_wp,      5.0_wp,       40.0_wp,     0.0_wp,    -2.0_wp, &
          -2647.0_wp,       0.0_wp,     11.0_wp,     1129.0_wp,     0.0_wp,     5.0_wp, &
          -2294.0_wp,       0.0_wp,    -10.0_wp,     1266.0_wp,     0.0_wp,    -4.0_wp, &
           2481.0_wp,       0.0_wp,     -7.0_wp,    -1062.0_wp,     0.0_wp,    -3.0_wp, &
           2179.0_wp,       0.0_wp,     -2.0_wp,    -1129.0_wp,     0.0_wp,    -2.0_wp, &
           3276.0_wp,       0.0_wp,      1.0_wp,       -9.0_wp,     0.0_wp,     0.0_wp, &
          -3389.0_wp,       0.0_wp,      5.0_wp,       35.0_wp,     0.0_wp,    -2.0_wp, &
           3339.0_wp,       0.0_wp,    -13.0_wp,     -107.0_wp,     0.0_wp,     1.0_wp, &
          -1987.0_wp,       0.0_wp,     -6.0_wp,     1073.0_wp,     0.0_wp,    -2.0_wp, &
          -1981.0_wp,       0.0_wp,      0.0_wp,      854.0_wp,     0.0_wp,     0.0_wp, &
           4026.0_wp,       0.0_wp,   -353.0_wp,     -553.0_wp,     0.0_wp,  -139.0_wp, &
           1660.0_wp,       0.0_wp,     -5.0_wp,     -710.0_wp,     0.0_wp,    -2.0_wp, &
          -1521.0_wp,       0.0_wp,      9.0_wp,      647.0_wp,     0.0_wp,     4.0_wp, &
           1314.0_wp,       0.0_wp,      0.0_wp,     -700.0_wp,     0.0_wp,     0.0_wp, &
          -1283.0_wp,       0.0_wp,      0.0_wp,      672.0_wp,     0.0_wp,     0.0_wp, &
          -1331.0_wp,       0.0_wp,      8.0_wp,      663.0_wp,     0.0_wp,     4.0_wp, &
           1383.0_wp,       0.0_wp,     -2.0_wp,     -594.0_wp,     0.0_wp,    -2.0_wp, &
           1405.0_wp,       0.0_wp,      4.0_wp,     -610.0_wp,     0.0_wp,     2.0_wp, &
           1290.0_wp,       0.0_wp,      0.0_wp,     -556.0_wp,     0.0_wp,     0.0_wp ], [6,nls])
    !  Interval between fundamental epoch J2000.0 and given date (JC).
    t = ( ( date1-dj00 ) + date2 ) / djc
    !  -------------------
    !  LUNI-SOLAR NUTATION
    !  -------------------
    !
    !  Fundamental (Delaunay) arguments from Simon et al. (1994)
    !
    !  Mean anomaly of the Moon.
    el  = mod (         485868.249036_wp + &
                ( + 1717915923.2178_wp ) * t, turnas ) * das2r
    !  Mean anomaly of the Sun.
    elp = mod (        1287104.79305_wp + &
                (  + 129596581.0481_wp ) * t, turnas ) * das2r
    !  Mean argument of the latitude of the Moon.
    f   = mod (         335779.526232_wp + &
                ( + 1739527262.8478_wp ) * t, turnas ) * das2r
    !  Mean elongation of the Moon from the Sun.
    d   = mod (        1072260.70369_wp + &
                ( + 1602961601.2090_wp ) * t, turnas ) * das2r
    !  Mean longitude of the ascending node of the Moon.
    om  = mod (         450160.398036_wp + &
                (    - 6962890.5431_wp ) * t, turnas ) * das2r
    !  Initialize the nutation values.
    dp = 0.0_wp
    de = 0.0_wp
    !  Summation of luni-solar nutation series (in reverse order).
    do i = nls, 1, -1
    !     Argument and functions.
       arg = mod ( real ( nals(1,i), wp ) * el  + &
                   real ( nals(2,i), wp ) * elp + &
                   real ( nals(3,i), wp ) * f   + &
                   real ( nals(4,i), wp ) * d   + &
                   real ( nals(5,i), wp ) * om, d2pi )
       sarg = sin(arg)
       carg = cos(arg)
    !     Term.
       dp = dp + ( cls(1,i) + cls(2,i) * t ) * sarg &
               +   cls(3,i)                  * carg
       de = de + ( cls(4,i) + cls(5,i) * t ) * carg &
               +   cls(6,i)                  * sarg
    end do
    !  Convert from 0.1 microarcsec units to radians.
    dpsils = dp * u2r
    depsls = de * u2r
    !  -----------------------------
    !  IN LIEU OF PLANETARY NUTATION
    !  -----------------------------
    !  Fixed offset to correct for missing terms in truncated series.
    dpsipl = dpplan
    depspl = deplan
    !  -------
    !  RESULTS
    !  -------
    !  Add luni-solar and planetary components.
    dpsi = dpsils + dpsipl
    deps = depsls + depspl
    end subroutine NUT00B
Call graph
ee00b calls nut00b
pn00b calls nut00b
gst00b calls ee00b
pnm00b calls pn00b
num00b calls pn00b
s00b calls pnm00b
c2i00b calls pnm00b
xys00b calls pnm00b
c2t00b calls c2i00b