NUT06A – astro-fortran
NUT06A Subroutine
13 statements
Source File
public subroutine NUT06A(date1, date2, dpsi, deps)
IAU 2000A nutation with adjustments to match the IAU 2006 precession.
Status: canonical model.
Notes
The TT date DATE1+DATE2 is a Julian Date, apportioned in any convenient way between the two arguments. For example, JD(TT)=2450123.7 could be expressed in any of these ways, among others
    DATE1          DATE2
 2450123.7D0        0D0        (JD method)
  2451545D0      -1421.3D0     (J2000 method)
 2400000.5D0     50123.2D0     (MJD method)
 2450123.5D0       0.2D0       (date & time method)
The JD method is the most natural and convenient to use in cases where the loss of several decimal digits of resolution is acceptable. The J2000 method is best matched to the way the argument is handled internally and will deliver the optimum resolution. The MJD method and the date & time methods are both good compromises between resolution and convenience.
The nutation components in longitude and obliquity are in radians and with respect to the mean equinox and ecliptic of date, IAU 2006 precession model (Hilton et al. 2006, Capitaine et al. 2005).
The routine first computes the IAU 2000A nutation, then applies adjustments for (i) the consequences of the change in obliquity from the IAU 1980 ecliptic to the IAU 2006 ecliptic and (ii) the secular variation in the Earth's dynamical form factor J2.
The present routine provides classical nutation, complementing the IAU 2000 frame bias and IAU 2006 precession. It delivers a pole which is at current epochs accurate to a few tens of microarcseconds, apart from the free core nutation.
Reference
Wallace, P.T. & Capitaine, N., 2006, Astron.Astrophys. 459, 981
History
IAU SOFA revision: 2011 April 3
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: date1
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(in) :: date2
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(out) :: dpsi
nutation, luni-solar + planetary (Note 2)
real(kind=wp), intent(out) :: deps
nutation, luni-solar + planetary (Note 2)
Calls
Called by
Contents
Source Code
NUT06A
Source Code
    subroutine NUT06A ( date1, date2, dpsi, deps )
    implicit none
    real(wp),intent(in) :: date1 !! TT as a 2-part Julian Date (Note 1)
    real(wp),intent(in) :: date2 !! TT as a 2-part Julian Date (Note 1)
    real(wp),intent(out) :: dpsi !! nutation, luni-solar + planetary (Note 2)
    real(wp),intent(out) :: deps !! nutation, luni-solar + planetary (Note 2)
    !  Miscellaneous
    real(wp) :: t, fj2, dp, de
    !  Interval between fundamental date J2000.0 and given date (JC).
    t = ( ( date1-dj00 ) + date2 ) / djc
    !  Factor correcting for secular variation of J2.
    fj2 = -2.7774e-6_wp * t
    !  Obtain IAU 2000A nutation.
    call NUT00A ( date1, date2, dp, de )
    !  Apply P03 adjustments (Wallace & Capitaine, 2006, Eqs.5).
    dpsi = dp + dp * ( 0.4697e-6_wp + fj2 )
    deps = de + de * fj2
    end subroutine NUT06A
Call graph
nut06a calls nut00a
nut00a calls faom03, faju03, fasa03, fae03, fame03, fal03, fapa03, faf03, fave03, fama03, faur03
pnm06a calls nut06a
num06a calls nut06a
pn06a calls nut06a
gst06a calls pnm06a
s06a calls pnm06a
xys06a calls pnm06a
c2i06a calls pnm06a
apco13 calls pnm06a
apci13 calls pnm06a
eo06a calls pnm06a
atco13 calls apco13
atci13 calls apci13
atic13 calls apci13
ee06a calls gst06a
c2t06a calls c2i06a
atoc13 calls apco13