OBL06 – astro-fortran
OBL06 Function
9 statements
Source File
public function OBL06(date1, date2) result(obl)
Mean obliquity of the ecliptic, IAU 2006 precession model.
Status: canonical model.
Notes
The date DATE1+DATE2 is a Julian Date, apportioned in any convenient way between the two arguments. For example, JD(TT)=2450123.7 could be expressed in any of these ways, among others:
     DATE1         DATE2
 2450123.7D0        0D0        (JD method)
  2451545D0      -1421.3D0     (J2000 method)
 2400000.5D0     50123.2D0     (MJD method)
 2450123.5D0       0.2D0       (date & time method)
The JD method is the most natural and convenient to use in cases where the loss of several decimal digits of resolution is acceptable. The J2000 method is best matched to the way the argument is handled internally and will deliver the optimum resolution. The MJD method and the date & time methods are both good compromises between resolution and convenience.
The result is the angle between the ecliptic and mean equator of date DATE1+DATE2.
Reference
Hilton, J. et al., 2006, Celest.Mech.Dyn.Astron. 94, 351
History
IAU SOFA revision: 2009 December 15
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: date1
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(in) :: date2
TT as a 2-part Julian Date (Note 1)
Return Value real(kind=wp)
obliquity of the ecliptic (radians, Note 2)
Called by
Contents
Source Code
OBL06
Source Code
    function OBL06 ( date1, date2 ) result(obl)
    implicit none
    real(wp),intent(in) :: date1 !! TT as a 2-part Julian Date (Note 1)
    real(wp),intent(in) :: date2 !! TT as a 2-part Julian Date (Note 1)
    real(wp) :: obl !! obliquity of the ecliptic (radians, Note 2)
    real(wp) :: t
    !  Interval between fundamental date J2000.0 and given date (JC).
    t = ( ( date1-dj00 ) + date2 ) / djc
    !  Mean obliquity.
    obl = ( 84381.406_wp       + &
          (   -46.836769_wp    + &
          (    -0.0001831_wp   + &
          (     0.00200340_wp  + &
          (    -0.000000576_wp + &
          (    -0.0000000434_wp ) &
                      * t ) * t ) * t ) * t ) * t ) * das2r
    end function OBL06
Call graph
pfw06 calls obl06
ecm06 calls obl06, pmat06
num06a calls obl06
p06e calls obl06
pmat06 calls pfw06
pn06 calls pfw06
eceq06 calls ecm06
bp06 calls pfw06, pmat06
eqec06 calls ecm06
pnm06a calls pfw06
xys06a calls pnm06a
pn06a calls pn06
c2i06a calls pnm06a
apci13 calls pnm06a
gst06a calls pnm06a
eo06a calls pnm06a
apco13 calls pnm06a
pb06 calls pmat06
s06a calls pnm06a
ee06a calls gst06a
atic13 calls apci13
c2t06a calls c2i06a
atoc13 calls apco13
atci13 calls apci13
atco13 calls apco13