OBL80 – astro-fortran
OBL80 Function
9 statements
Source File
public function OBL80(date1, date2) result(obl)
Mean obliquity of the ecliptic, IAU 1980 model.
Status: canonical model.
Notes
The date DATE1+DATE2 is a Julian Date, apportioned in any convenient way between the two arguments. For example, JD(TDB)=2450123.7 could be expressed in any of these ways, among others:
     DATE1         DATE2
 2450123.7D0        0D0        (JD method)
  2451545D0      -1421.3D0     (J2000 method)
 2400000.5D0     50123.2D0     (MJD method)
 2450123.5D0       0.2D0       (date & time method)
The JD method is the most natural and convenient to use in cases where the loss of several decimal digits of resolution is acceptable. The J2000 method is best matched to the way the argument is handled internally and will deliver the optimum resolution. The MJD method and the date & time methods are both good compromises between resolution and convenience.
The result is the angle between the ecliptic and mean equator of date DATE1+DATE2.
Reference
Explanatory Supplement to the Astronomical Almanac, P. Kenneth Seidelmann (ed), University Science Books (1992), Expression 3.222-1 (p114).
History
IAU SOFA revision: 2009 December 15
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: date1
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(in) :: date2
TT as a 2-part Julian Date (Note 1)
Return Value real(kind=wp)
obliquity of the ecliptic (radians, Note 2)
Called by
Contents
Source Code
OBL80
Source Code
    function OBL80 ( date1, date2 ) result(obl)
    implicit none
    real(wp),intent(in) :: date1 !! TT as a 2-part Julian Date (Note 1)
    real(wp),intent(in) :: date2 !! TT as a 2-part Julian Date (Note 1)
    real(wp) :: obl !! obliquity of the ecliptic (radians, Note 2)
    real(wp) :: t
    !  Interval between fundamental epoch J2000.0 and given date (JC).
    t = ( ( date1-dj00 ) + date2 ) / djc
    !  Mean obliquity of date.
    obl = das2r * ( 84381.448_wp + &
                    ( -46.8150_wp + &
                     ( -0.00059_wp + &
                        0.001813_wp * t ) * t ) * t )
    end function OBL80
Call graph
pn00 calls obl80
ee00a calls obl80
eqeq94 calls obl80
nutm80 calls obl80
ee00b calls obl80
gst00a calls ee00a
pn00a calls pn00
gst94 calls eqeq94
pn00b calls pn00
c2tpe calls pn00
gst00b calls ee00b
pnm80 calls nutm80
num00a calls pn00a
pnm00a calls pn00a
pnm00b calls pn00b
num00b calls pn00b
s00b calls pnm00b
c2i00a calls pnm00a
s00a calls pnm00a
xys00a calls pnm00a
xys00b calls pnm00b
c2i00b calls pnm00b
c2t00b calls c2i00b
c2t00a calls c2i00a