PDP – astro-fortran
PDP Subroutine
13 statements
Source File
public subroutine PDP(a, b, adb)
p-vector inner (=scalar=dot) product.
Status: vector/matrix support routine.
History
IAU SOFA revision: 2000 November 25
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(3) :: a
first p-vector
real(kind=wp), intent(in), dimension(3) :: b
second p-vector
real(kind=wp), intent(out) :: adb
A . B
Called by
Contents
Source Code
PDP
Source Code
    subroutine PDP ( a, b, adb )
    implicit none
    real(wp),dimension(3),intent(in) :: a !! first p-vector
    real(wp),dimension(3),intent(in) :: b !! second p-vector
    real(wp),intent(out) :: adb !! A . B
    real(wp) :: w
    integer :: i
    w = 0.0_wp
    do i=1,3
       w = w + a(i)*b(i)
    end do
    adb = w
    end subroutine PDP
Call graph
pap calls pdp
ld calls pdp
fk45z calls pdp
fk425 calls pdp
sepp calls pdp
ldn calls pdp, ld
starpv calls pdp
ab calls pdp
pmpx calls pdp
pvstar calls pdp
starpm calls pdp, starpv, pvstar
pvdpv calls pdp
fk524 calls pdp
seps calls sepp
pmsafe calls starpm, seps
aticq calls ab, ldsun
atciqz calls ab, ldsun
fk52h calls starpv, pvstar
h2fk5 calls starpv, pvstar
fk54z calls fk524
ldsun calls ld
aticqn calls ldn, ab
atciqn calls ldn, ab, pmpx
atciq calls ab, pmpx, ldsun
atoc13 calls aticq
atic13 calls aticq
atci13 calls atciq
atco13 calls atciq