PFW06 – astro-fortran
PFW06 Subroutine
15 statements
Source File
public subroutine PFW06(date1, date2, gamb, phib, psib, epsa)
Precession angles, IAU 2006 (Fukushima-Williams 4-angle formulation).
Status: canonical model.
Notes
The TT date DATE1+DATE2 is a Julian Date, apportioned in any convenient way between the two arguments. For example, JD(TT)=2450123.7 could be expressed in any of these ways, among others
    DATE1          DATE2
 2450123.7D0        0D0        (JD method)
  2451545D0      -1421.3D0     (J2000 method)
 2400000.5D0     50123.2D0     (MJD method)
 2450123.5D0       0.2D0       (date & time method)
The JD method is the most natural and convenient to use in cases where the loss of several decimal digits of resolution is acceptable. The J2000 method is best matched to the way the argument is handled internally and will deliver the optimum resolution. The MJD method and the date & time methods are both good compromises between resolution and convenience.
Naming the following points:
   e = J2000.0 ecliptic pole,
   p = GCRS pole,
   E = mean ecliptic pole of date,
and P = mean pole of date,
the four Fukushima-Williams angles are as follows:
GAMB = gamma_bar = epE
PHIB = phi_bar = pE
PSIB = psi_bar = pEP
EPSA = epsilon_A = EP
The matrix representing the combined effects of frame bias and precession is:
PxB = R_1(-EPSA).R_3(-PSIB).R_1(PHIB).R_3(GAMB)
The matrix representing the combined effects of frame bias, precession and nutation is simply:
NxPxB = R_1(-EPSA-dE).R_3(-PSIB-dP).R_1(PHIB).R_3(GAMB)
where dP and dE are the nutation components with respect to the ecliptic of date.
Reference
Hilton, J. et al., 2006, Celest.Mech.Dyn.Astron. 94, 351
History
IAU SOFA revision: 2009 December 15
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: date1
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(in) :: date2
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(out) :: gamb
F-W angle gamma_bar (radians)
real(kind=wp), intent(out) :: phib
F-W angle phi_bar (radians)
real(kind=wp), intent(out) :: psib
F-W angle psi_bar (radians)
real(kind=wp), intent(out) :: epsa
F-W angle epsilon_A (radians)
Calls
Called by
Contents
Source Code
PFW06
Source Code
    subroutine PFW06 ( date1, date2, gamb, phib, psib, epsa )
    implicit none
    real(wp),intent(in) :: date1 !! TT as a 2-part Julian Date (Note 1)
    real(wp),intent(in) :: date2 !! TT as a 2-part Julian Date (Note 1)
    real(wp),intent(out) :: gamb !! F-W angle gamma_bar (radians)
    real(wp),intent(out) :: phib !! F-W angle phi_bar (radians)
    real(wp),intent(out) :: psib !! F-W angle psi_bar (radians)
    real(wp),intent(out) :: epsa !! F-W angle epsilon_A (radians)
    real(wp) :: t
    !  Interval between fundamental date J2000.0 and given date (JC).
    t = ( ( date1-dj00 ) + date2 ) / djc
    !  P03 bias+precession angles.
    gamb =        (    -0.052928_wp    + &
                  (    10.556378_wp    + &
                  (     0.4932044_wp   + &
                  (    -0.00031238_wp  + &
                  (    -0.000002788_wp + &
                  (     0.0000000260_wp ) &
                                 * t ) * t ) * t ) * t ) * t ) * das2r
    phib =        ( 84381.412819_wp    + &
                  (   -46.811016_wp    + &
                  (     0.0511268_wp   + &
                  (     0.00053289_wp  + &
                  (    -0.000000440_wp + &
                  (    -0.0000000176_wp ) &
                                 * t ) * t ) * t ) * t ) * t ) * das2r
    psib =        (    -0.041775_wp    + &
                  (  5038.481484_wp    + &
                  (     1.5584175_wp   + &
                  (    -0.00018522_wp  + &
                  (    -0.000026452_wp + &
                  (    -0.0000000148_wp ) &
                                 * t ) * t ) * t ) * t ) * t ) * das2r
    epsa = OBL06 ( date1, date2 )
    end subroutine PFW06
Call graph
pfw06 calls obl06
bp06 calls pfw06, pmat06
pn06 calls pfw06
pmat06 calls pfw06
pnm06a calls pfw06
xys06a calls pnm06a
pn06a calls pn06
c2i06a calls pnm06a
apci13 calls pnm06a
gst06a calls pnm06a
eo06a calls pnm06a
ecm06 calls pmat06
apco13 calls pnm06a
pb06 calls pmat06
s06a calls pnm06a
ee06a calls gst06a
eceq06 calls ecm06
atic13 calls apci13
c2t06a calls c2i06a
atoc13 calls apco13
atci13 calls apci13
atco13 calls apco13
eqec06 calls ecm06