PMAT06 – astro-fortran
PMAT06 Subroutine
9 statements
Source File
public subroutine PMAT06(date1, date2, rbp)
Precession matrix (including frame bias) from GCRS to a specified date, IAU 2006 model.
Status: support routine.
Notes
The TT date DATE1+DATE2 is a Julian Date, apportioned in any convenient way between the arguments DATE1 and DATE2. For example, JD(TT)=2450123.7 could be expressed in any of these ways, among others:
    DATE1          DATE2
 2450123.7D0        0D0        (JD method)
  2451545D0      -1421.3D0     (J2000 method)
 2400000.5D0     50123.2D0     (MJD method)
 2450123.5D0       0.2D0       (date & time method)
The JD method is the most natural and convenient to use in cases where the loss of several decimal digits of resolution is acceptable. The J2000 method is best matched to the way the argument is handled internally and will deliver the optimum resolution. The MJD method and the date & time methods are both good compromises between resolution and convenience.
The matrix operates in the sense V(date) = RBP * V(GCRS), where the p-vector V(GCRS) is with respect to the Geocentric Celestial Reference System (IAU, 2000) and the p-vector V(date) is with respect to the mean equatorial triad of the given date.
References
Capitaine, N. & Wallace, P.T., 2006, Astron.Astrophys. 450, 855
Wallace, P.T. & Capitaine, N., 2006, Astron.Astrophys. 459, 981
History
IAU SOFA revision: 2009 December 21
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: date1
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(in) :: date2
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(out), dimension(3,3) :: rbp
bias-precession matrix (Note 2)
Calls
Called by
Contents
Source Code
PMAT06
Source Code
    subroutine PMAT06 ( date1, date2, rbp )
    implicit none
    real(wp),intent(in) :: date1 !! TT as a 2-part Julian Date (Note 1)
    real(wp),intent(in) :: date2 !! TT as a 2-part Julian Date (Note 1)
    real(wp),dimension(3,3),intent(out) :: rbp !! bias-precession matrix (Note 2)
    real(wp) :: gamb, phib, psib, epsa
    !  Bias-precession Fukushima-Williams angles.
    call PFW06 ( date1, date2, gamb, phib, psib, epsa )
    !  Form the matrix.
    call FW2M ( gamb, phib, psib, epsa, rbp )
    end subroutine PMAT06
Call graph
pmat06 calls fw2m, pfw06
fw2m calls ir, rz, rx
pfw06 calls obl06
bp06 calls pmat06
pb06 calls pmat06
ecm06 calls pmat06
eqec06 calls ecm06
eceq06 calls ecm06