PMAT76 – astro-fortran
PMAT76 Subroutine
13 statements
Source File
public subroutine PMAT76(date1, date2, rmatp)
Precession matrix from J2000.0 to a specified date, IAU 1976 model.
Status: support routine.
Notes
The ending date DATE1+DATE2 is a Julian Date, apportioned in any convenient way between the arguments DATE1 and DATE2. For example, JD(TT)=2450123.7 could be expressed in any of these ways, among others:
    DATE1          DATE2
 2450123.7D0        0D0        (JD method)
  2451545D0      -1421.3D0     (J2000 method)
 2400000.5D0     50123.2D0     (MJD method)
 2450123.5D0       0.2D0       (date & time method)
The JD method is the most natural and convenient to use in cases where the loss of several decimal digits of resolution is acceptable. The J2000 method is best matched to the way the argument is handled internally and will deliver the optimum resolution. The MJD method and the date & time methods are both good compromises between resolution and convenience.
The matrix operates in the sense V(date) = RMATP * V(J2000), where the p-vector V(J2000) is with respect to the mean equatorial triad of epoch J2000.0 and the p-vector V(date) is with respect to the mean equatorial triad of the given date.
Though the matrix method itself is rigorous, the precession angles are expressed through canonical polynomials which are valid only for a limited time span. In addition, the IAU 1976 precession rate is known to be imperfect. The absolute accuracy of the present formulation is better than 0.1 arcsec from 1960AD to 2040AD, better than 1 arcsec from 1640AD to 2360AD, and remains below 3 arcsec for the whole of the period 500BC to 3000AD. The errors exceed 10 arcsec outside the range 1200BC to 3900AD, exceed 100 arcsec outside 4200BC to 5600AD and exceed 1000 arcsec outside 6800BC to 8200AD.
References
Lieske, J.H., 1979, Astron.Astrophys. 73, 282. equations (6) & (7), p283.
Kaplan, G.H., 1981, USNO circular no. 163, pA2.
History
IAU SOFA revision: 2009 December 18
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: date1
ending date, TT (Note 1)
real(kind=wp), intent(in) :: date2
ending date, TT (Note 1)
real(kind=wp), intent(out), dimension(3,3) :: rmatp
precession matrix, J2000.0 -> DATE1+DATE2
Calls
Called by
Contents
Source Code
PMAT76
Source Code
    subroutine PMAT76 ( date1, date2, rmatp )
    implicit none
    real(wp),intent(in) :: date1 !! ending date, TT (Note 1)
    real(wp),intent(in) :: date2 !! ending date, TT (Note 1)
    real(wp),dimension(3,3),intent(out) :: rmatp !! precession matrix, J2000.0 -> DATE1+DATE2
    real(wp) :: zeta, z, theta, wmat(3,3)
    !  Precession Euler angles, J2000.0 to specified date.
    call PREC76 ( dj00, 0.0_wp, date1, date2, zeta, z, theta )
    !  Form the rotation matrix.
    call IR ( wmat )
    call RZ ( -zeta, wmat )
    call RY ( theta, wmat )
    call RZ ( -z, wmat )
    call CR ( wmat, rmatp )
    end subroutine PMAT76
Call graph
pmat76 calls ir, prec76, rz, ry
pnm80 calls pmat76