PMP – astro-fortran
PMP Subroutine
10 statements
Source File
public subroutine PMP(a, b, amb)
P-vector subtraction.
Status: vector/matrix support routine.
History
IAU SOFA revision: 2000 November 25
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(3) :: a
first p-vector
real(kind=wp), intent(in), dimension(3) :: b
second p-vector
real(kind=wp), intent(out), dimension(3) :: amb
A - B
Called by
Contents
Source Code
PMP
Source Code
    subroutine PMP ( a, b, amb )
    implicit none
    real(wp),dimension(3),intent(in) :: a !! first p-vector
    real(wp),dimension(3),intent(in) :: b !! second p-vector
    real(wp),dimension(3),intent(out) :: amb !! A - B
    integer :: i
    do i=1,3
       amb(i) = a(i) - b(i)
    end do
    end subroutine PMP
Call graph
pap calls pmp
fk45z calls pmp
fk524 calls pmp
h2fk5 calls pmp, pvstar, starpv
pvstar calls pmp
starpv calls pmp
ldn calls pmp
pvmpv calls pmp
fk52h calls pvstar, starpv
fk425 calls pvmpv
fk54z calls fk524
aticqn calls ldn
starpm calls pvstar, starpv
atciqn calls ldn
pmsafe calls starpm