PN – astro-fortran
PN Subroutine
14 statements
Source File
public subroutine PN(p, r, u)
Convert a p-vector into modulus and unit vector.
Status: vector/matrix support routine.
Note
 If P is null, the result is null.  Otherwise the result is
 a unit vector.
History
IAU SOFA revision: 2006 November 13
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(3) :: p
p-vector
real(kind=wp), intent(out) :: r
modulus
real(kind=wp), intent(out), dimension(3) :: u
unit vector
Calls
Called by
Contents
Source Code
PN
Source Code
    subroutine PN ( p, r, u )
    implicit none
    real(wp),dimension(3),intent(in) :: p !! p-vector
    real(wp),intent(out) :: r !! modulus
    real(wp),dimension(3),intent(out) :: u !! unit vector
    real(wp) :: w
    !  Obtain the modulus and test for zero.
    call PM ( p, w )
    if ( w == 0.0_wp ) then
       !  Null vector.
       call ZP ( u )
    else
       !  Unit vector.
       call SXP ( 1.0_wp/w, p, u )
    end if
    !  Return the modulus.
    r = w
    end subroutine PN
Call graph
pn calls zp, sxp
apcs calls pn
apcg calls apcs
apcs13 calls apcs
apco calls apcs
apcg13 calls apcg
apci calls apcg
apco13 calls apco
apci13 calls apci
atco13 calls apco13
atoc13 calls apco13
atci13 calls apci13
atic13 calls apci13