PN00A – astro-fortran
PN00A Subroutine
15 statements
Source File
public subroutine PN00A(date1, date2, dpsi, deps, epsa, rb, rp, rbp, rn, rbpn)
Precession-nutation, IAU 2000A model: a multi-purpose routine, supporting classical (equinox-based) use directly and CIO-based use indirectly.
Status: support routine.
Notes
The TT date DATE1+DATE2 is a Julian Date, apportioned in any convenient way between the two arguments. For example, JD(TT)=2450123.7 could be expressed in any of these ways, among others:
    DATE1          DATE2
 2450123.7D0        0D0        (JD method)
  2451545D0      -1421.3D0     (J2000 method)
 2400000.5D0     50123.2D0     (MJD method)
 2450123.5D0       0.2D0       (date & time method)
The JD method is the most natural and convenient to use in cases where the loss of several decimal digits of resolution is acceptable. The J2000 method is best matched to the way the argument is handled internally and will deliver the optimum resolution. The MJD method and the date & time methods are both good compromises between resolution and convenience.
The nutation components (luni-solar + planetary, IAU 2000A) in longitude and obliquity are in radians and with respect to the equinox and ecliptic of date. Free core nutation is omitted; for the utmost accuracy, use the PN00 routine, where the nutation components are caller-specified. For faster but slightly less accurate results, use the PN00B routine.
The mean obliquity is consistent with the IAU 2000 precession.
The matrix RB transforms vectors from GCRS to J2000.0 mean equator and equinox by applying frame bias.
The matrix RP transforms vectors from J2000.0 mean equator and equinox to mean equator and equinox of date by applying precession.
The matrix RBP transforms vectors from GCRS to mean equator and equinox of date by applying frame bias then precession. It is the product RP x RB.
The matrix RN transforms vectors from mean equator and equinox of date to true equator and equinox of date by applying the nutation (luni-solar + planetary).
The matrix RBPN transforms vectors from GCRS to true equator and equinox of date. It is the product RN x RBP, applying frame bias, precession and nutation in that order.
The X,Y,Z coordinates of the IAU 2000A Celestial Intermediate Pole are elements (3,1-3) of the matrix RBPN.
Reference
Capitaine, N., Chapront, J., Lambert, S. and Wallace, P., "Expressions for the Celestial Intermediate Pole and Celestial Ephemeris Origin consistent with the IAU 2000A precession-nutation model", Astron.Astrophys. 400, 1145-1154 (2003).
n.b. The celestial ephemeris origin (CEO) was renamed "celestial intermediate origin" (CIO) by IAU 2006 Resolution 2.
History
IAU SOFA revision: 2010 January 18
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: date1
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(in) :: date2
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(out) :: dpsi
nutation (Note 2)
real(kind=wp), intent(out) :: deps
nutation (Note 2)
real(kind=wp), intent(out) :: epsa
mean obliquity (Note 3)
real(kind=wp), intent(out), dimension(3,3) :: rb
frame bias matrix (Note 4)
real(kind=wp), intent(out), dimension(3,3) :: rp
precession matrix (Note 5)
real(kind=wp), intent(out), dimension(3,3) :: rbp
bias-precession matrix (Note 6)
real(kind=wp), intent(out), dimension(3,3) :: rn
nutation matrix (Note 7)
real(kind=wp), intent(out), dimension(3,3) :: rbpn
GCRS-to-true matrix (Notes 8,9)
Calls
Called by
Contents
Source Code
PN00A
Source Code
    subroutine PN00A ( date1, date2, &
                       dpsi, deps, epsa, rb, rp, rbp, rn, rbpn )
    implicit none
    real(wp),intent(in) :: date1 !! TT as a 2-part Julian Date (Note 1)
    real(wp),intent(in) :: date2 !! TT as a 2-part Julian Date (Note 1)
    real(wp),intent(out) :: dpsi !! nutation (Note 2)
    real(wp),intent(out) :: deps !! nutation (Note 2)
    real(wp),intent(out) :: epsa !! mean obliquity (Note 3)
    real(wp),dimension(3,3),intent(out) :: rb !! frame bias matrix (Note 4)
    real(wp),dimension(3,3),intent(out) :: rp !! precession matrix (Note 5)
    real(wp),dimension(3,3),intent(out) :: rbp !! bias-precession matrix (Note 6)
    real(wp),dimension(3,3),intent(out) :: rn !! nutation matrix (Note 7)
    real(wp),dimension(3,3),intent(out) :: rbpn !! GCRS-to-true matrix (Notes 8,9)
    !  Nutation.
    call NUT00A ( date1, date2, dpsi, deps )
    !  Remaining results.
    call PN00 ( date1, date2, dpsi, deps, &
                    epsa, rb, rp, rbp, rn, rbpn )
    end subroutine PN00A
Call graph
pn00a calls nut00a, pn00
nut00a calls faom03, faju03, fasa03, fae03, fame03, fal03, fapa03, faf03, fave03, fama03, faur03
pn00 calls obl80, numat, bp00, pr00, rxr
numat calls rx, ir, rz
bp00 calls pr00, rxr, rx, ry, ir, rz, bi00
pnm00a calls pn00a
num00a calls pn00a
s00a calls pnm00a
c2i00a calls pnm00a
xys00a calls pnm00a
c2t00a calls c2i00a