PN00 – astro-fortran
PN00 Subroutine
19 statements
Source File
public subroutine PN00(date1, date2, dpsi, deps, epsa, rb, rp, rbp, rn, rbpn)
Precession-nutation, IAU 2000 model: a multi-purpose routine, supporting classical (equinox-based) use directly and CIO-based use indirectly.
Status: support routine.
Notes
The TT date DATE1+DATE2 is a Julian Date, apportioned in any convenient way between the two arguments. For example, JD(TT)=2450123.7 could be expressed in any of these ways, among others:
    DATE1          DATE2
 2450123.7D0        0D0        (JD method)
  2451545D0      -1421.3D0     (J2000 method)
 2400000.5D0     50123.2D0     (MJD method)
 2450123.5D0       0.2D0       (date & time method)
The JD method is the most natural and convenient to use in cases where the loss of several decimal digits of resolution is acceptable. The J2000 method is best matched to the way the argument is handled internally and will deliver the optimum resolution. The MJD method and the date & time methods are both good compromises between resolution and convenience.
The caller is responsible for providing the nutation components; they are in longitude and obliquity, in radians and are with respect to the equinox and ecliptic of date. For high-accuracy applications, free core nutation should be included as well as any other relevant corrections to the position of the CIP.
The returned mean obliquity is consistent with the IAU 2000 precession-nutation models.
The matrix RB transforms vectors from GCRS to J2000.0 mean equator and equinox by applying frame bias.
The matrix RP transforms vectors from J2000.0 mean equator and equinox to mean equator and equinox of date by applying precession.
The matrix RBP transforms vectors from GCRS to mean equator and equinox of date by applying frame bias then precession. It is the product RP x RB.
The matrix RN transforms vectors from mean equator and equinox of date to true equator and equinox of date by applying the nutation (luni-solar + planetary).
The matrix RBPN transforms vectors from GCRS to true equator and equinox of date. It is the product RN x RBP, applying frame bias, precession and nutation in that order.
Reference
Capitaine, N., Chapront, J., Lambert, S. and Wallace, P., "Expressions for the Celestial Intermediate Pole and Celestial Ephemeris Origin consistent with the IAU 2000A precession-nutation model", Astron.Astrophys. 400, 1145-1154 (2003)
n.b. The celestial ephemeris origin (CEO) was renamed "celestial intermediate origin" (CIO) by IAU 2006 Resolution 2.
History
IAU SOFA revision: 2010 January 18
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: date1
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(in) :: date2
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(in) :: dpsi
nutation (Note 2)
real(kind=wp), intent(in) :: deps
nutation (Note 2)
real(kind=wp), intent(out) :: epsa
mean obliquity (Note 3)
real(kind=wp), intent(out), dimension(3,3) :: rb
frame bias matrix (Note 4)
real(kind=wp), intent(out), dimension(3,3) :: rp
precession matrix (Note 5)
real(kind=wp), intent(out), dimension(3,3) :: rbp
bias-precession matrix (Note 6)
real(kind=wp), intent(out), dimension(3,3) :: rn
nutation matrix (Note 7)
real(kind=wp), intent(out), dimension(3,3) :: rbpn
GCRS-to-true matrix (Note 8)
Calls
Called by
Contents
Source Code
PN00
Source Code
    subroutine PN00 ( date1, date2, dpsi, deps, &
                      epsa, rb, rp, rbp, rn, rbpn )
    implicit none
    real(wp),intent(in) :: date1 !! TT as a 2-part Julian Date (Note 1)
    real(wp),intent(in) :: date2 !! TT as a 2-part Julian Date (Note 1)
    real(wp),intent(in) :: dpsi !! nutation (Note 2)
    real(wp),intent(in) :: deps !! nutation (Note 2)
    real(wp),intent(out) :: epsa !! mean obliquity (Note 3)
    real(wp),dimension(3,3),intent(out) :: rb !! frame bias matrix (Note 4)
    real(wp),dimension(3,3),intent(out) :: rp !! precession matrix (Note 5)
    real(wp),dimension(3,3),intent(out) :: rbp !! bias-precession matrix (Note 6)
    real(wp),dimension(3,3),intent(out) :: rn !! nutation matrix (Note 7)
    real(wp),dimension(3,3),intent(out) :: rbpn !! GCRS-to-true matrix (Note 8)
    real(wp) :: dpsipr, depspr
    !  IAU 2000 precession-rate adjustments.
    call PR00 ( date1, date2, dpsipr, depspr )
    !  Mean obliquity, consistent with IAU 2000 precession-nutation.
    epsa = OBL80 ( date1, date2 ) + depspr
    !  Frame bias and precession matrices and their product.
    call BP00 ( date1, date2, rb, rp, rbp )
    !  Nutation matrix.
    call NUMAT ( epsa, dpsi, deps, rn )
    !  Bias-precession-nutation matrix (classical).
    call RXR ( rn, rbp, rbpn )
    end subroutine PN00
Call graph
pn00 calls obl80, bp00, numat, rxr, pr00
bp00 calls rxr, pr00, bi00, rx, ir, ry, rz
numat calls rx, ir, rz
c2tpe calls pn00
pn00a calls pn00
pn00b calls pn00
pnm00a calls pn00a
num00b calls pn00b
num00a calls pn00a
pnm00b calls pn00b
c2i00b calls pnm00b
xys00b calls pnm00b
s00b calls pnm00b
c2i00a calls pnm00a
s00a calls pnm00a
xys00a calls pnm00a
c2t00a calls c2i00a
c2t00b calls c2i00b