PN06A – astro-fortran
PN06A Subroutine
15 statements
Source File
public subroutine PN06A(date1, date2, dpsi, deps, epsa, rb, rp, rbp, rn, rbpn)
Precession-nutation, IAU 2006/2000A models: a multi-purpose routine, supporting classical (equinox-based) use directly and CIO-based use indirectly.
Status: support routine.
Notes
The TT date DATE1+DATE2 is a Julian Date, apportioned in any convenient way between the two arguments. For example, JD(TT)=2450123.7 could be expressed in any of these ways, among others:
    DATE1          DATE2
 2450123.7D0        0D0        (JD method)
  2451545D0      -1421.3D0     (J2000 method)
 2400000.5D0     50123.2D0     (MJD method)
 2450123.5D0       0.2D0       (date & time method)
The JD method is the most natural and convenient to use in cases where the loss of several decimal digits of resolution is acceptable. The J2000 method is best matched to the way the argument is handled internally and will deliver the optimum resolution. The MJD method and the date & time methods are both good compromises between resolution and convenience.
The nutation components (luni-solar + planetary, IAU 2000A) in longitude and obliquity are in radians and with respect to the equinox and ecliptic of date. Free core nutation is omitted; for the utmost accuracy, use the PN06 routine, where the nutation components are caller-specified.
The mean obliquity is consistent with the IAU 2006 precession.
The matrix RB transforms vectors from GCRS to mean J2000.0 by applying frame bias.
The matrix RP transforms vectors from mean J2000.0 to mean of date by applying precession.
The matrix RBP transforms vectors from GCRS to mean of date by applying frame bias then precession. It is the product RP x RB.
The matrix RN transforms vectors from mean of date to true of date by applying the nutation (luni-solar + planetary).
The matrix RBPN transforms vectors from GCRS to true of date (CIP/equinox). It is the product RN x RBP, applying frame bias, precession and nutation in that order.
The X,Y,Z coordinates of the IAU 2006/2000A Celestial Intermediate Pole are elements (3,1-3) of the matrix RBPN.
Reference
Capitaine, N. & Wallace, P.T., 2006, Astron.Astrophys. 450, 855
History
IAU SOFA revision: 2009 December 15
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: date1
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(in) :: date2
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(out) :: dpsi
nutation (Note 2)
real(kind=wp), intent(out) :: deps
nutation (Note 2)
real(kind=wp), intent(out) :: epsa
mean obliquity (Note 3)
real(kind=wp), intent(out), dimension(3,3) :: rb
frame bias matrix (Note 4)
real(kind=wp), intent(out), dimension(3,3) :: rp
precession matrix (Note 5)
real(kind=wp), intent(out), dimension(3,3) :: rbp
bias-precession matrix (Note 6)
real(kind=wp), intent(out), dimension(3,3) :: rn
nutation matrix (Note 7)
real(kind=wp), intent(out), dimension(3,3) :: rbpn
GCRS-to-true matrix (Notes 8,9)
Calls
Contents
Source Code
PN06A
Source Code
    subroutine PN06A ( date1, date2, &
                       dpsi, deps, epsa, rb, rp, rbp, rn, rbpn )
    implicit none
    real(wp),intent(in) :: date1 !! TT as a 2-part Julian Date (Note 1)
    real(wp),intent(in) :: date2 !! TT as a 2-part Julian Date (Note 1)
    real(wp),intent(out) :: dpsi !! nutation (Note 2)
    real(wp),intent(out) :: deps !! nutation (Note 2)
    real(wp),intent(out) :: epsa !! mean obliquity (Note 3)
    real(wp),dimension(3,3),intent(out) :: rb !! frame bias matrix (Note 4)
    real(wp),dimension(3,3),intent(out) :: rp !! precession matrix (Note 5)
    real(wp),dimension(3,3),intent(out) :: rbp !! bias-precession matrix (Note 6)
    real(wp),dimension(3,3),intent(out) :: rn !! nutation matrix (Note 7)
    real(wp),dimension(3,3),intent(out) :: rbpn !! GCRS-to-true matrix (Notes 8,9)
    !  Nutation.
    call NUT06A ( date1, date2, dpsi, deps )
    !  Remaining results.
    call PN06 ( date1, date2, dpsi, deps, &
                epsa, rb, rp, rbp, rn, rbpn )
    end subroutine PN06A
Call graph
pn06a calls pn06, nut06a
pn06 calls fw2m, tr, pfw06, rxr
nut06a calls nut00a
fw2m calls ir, rz, rx
nut00a calls faom03, fama03, faf03, faju03, faur03, fae03, fave03, fame03, fapa03, fal03, fasa03
pfw06 calls obl06