PNM06A – astro-fortran
PNM06A Subroutine
10 statements
Source File
public subroutine PNM06A(date1, date2, rnpb)
Form the matrix of precession-nutation for a given date (including frame bias), IAU 2006 precession and IAU 2000A nutation models.
Status: support routine.
Notes
The TT date DATE1+DATE2 is a Julian Date, apportioned in any convenient way between the two arguments. For example, JD(TT)=2450123.7 could be expressed in any of these ways, among others:
    DATE1          DATE2
 2450123.7D0        0D0        (JD method)
  2451545D0      -1421.3D0     (J2000 method)
 2400000.5D0     50123.2D0     (MJD method)
 2450123.5D0       0.2D0       (date & time method)
The JD method is the most natural and convenient to use in cases where the loss of several decimal digits of resolution is acceptable. The J2000 method is best matched to the way the argument is handled internally and will deliver the optimum resolution. The MJD method and the date & time methods are both good compromises between resolution and convenience.
The matrix operates in the sense V(date) = RNPB * V(GCRS), where the p-vector V(date) is with respect to the true equatorial triad of date DATE1+DATE2 and the p-vector V(GCRS) is with respect to the Geocentric Celestial Reference System (IAU, 2000).
Reference
Capitaine, N. & Wallace, P.T., 2006, Astron.Astrophys. 450, 855.
History
IAU SOFA revision: 2009 December 21
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: date1
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(in) :: date2
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(out), dimension(3,3) :: rnpb
bias-precession-nutation matrix (Note 2)
Calls
Called by
Contents
Source Code
PNM06A
Source Code
    subroutine PNM06A ( date1, date2, rnpb )
    implicit none
    real(wp),intent(in) :: date1 !! TT as a 2-part Julian Date (Note 1)
    real(wp),intent(in) :: date2 !! TT as a 2-part Julian Date (Note 1)
    real(wp),dimension(3,3),intent(out) :: rnpb !! bias-precession-nutation matrix (Note 2)
    real(wp) :: gamb, phib, psib, epsa, dp, de
    !  Fukushima-Williams angles for frame bias and precession.
    call PFW06 ( date1, date2, gamb, phib, psib, epsa )
    !  Nutation components.
    call NUT06A ( date1, date2, dp, de )
    !  Equinox based nutation x precession x bias matrix.
    call FW2M ( gamb, phib, psib+dp, epsa+de, rnpb )
    end subroutine PNM06A
Call graph
pnm06a calls pfw06, nut06a, fw2m
pfw06 calls obl06
nut06a calls nut00a
fw2m calls rx, ir, rz
nut00a calls faom03, faju03, fasa03, fae03, fame03, fal03, fapa03, faf03, fave03, fama03, faur03
gst06a calls pnm06a
s06a calls pnm06a
xys06a calls pnm06a
c2i06a calls pnm06a
apco13 calls pnm06a
apci13 calls pnm06a
eo06a calls pnm06a
atco13 calls apco13
atci13 calls apci13
atic13 calls apci13
ee06a calls gst06a
c2t06a calls c2i06a
atoc13 calls apco13