PNM00A – astro-fortran
PNM00A Subroutine
8 statements
Source File
public subroutine PNM00A(date1, date2, rbpn)
Form the matrix of precession-nutation for a given date (including frame bias), equinox-based, IAU 2000A model.
Status: support routine.
Notes
The TT date DATE1+DATE2 is a Julian Date, apportioned in any convenient way between the two arguments. For example, JD(TT)=2450123.7 could be expressed in any of these ways, among others:
    DATE1          DATE2
 2450123.7D0        0D0        (JD method)
  2451545D0      -1421.3D0     (J2000 method)
 2400000.5D0     50123.2D0     (MJD method)
 2450123.5D0       0.2D0       (date & time method)
The JD method is the most natural and convenient to use in cases where the loss of several decimal digits of resolution is acceptable. The J2000 method is best matched to the way the argument is handled internally and will deliver the optimum resolution. The MJD method and the date & time methods are both good compromises between resolution and convenience.
The matrix operates in the sense V(date) = RBPN * V(GCRS), where the p-vector V(date) is with respect to the true equatorial triad of date DATE1+DATE2 and the p-vector V(GCRS) is with respect to the Geocentric Celestial Reference System (IAU, 2000).
A faster, but slightly less accurate result (about 1 mas), can be obtained by using instead the PNM00B routine.
Reference
IAU: Trans. International Astronomical Union, Vol. XXIVB; Proc. 24th General Assembly, Manchester, UK. Resolutions B1.3, B1.6. (2000)
History
IAU SOFA revision: 2009 December 21
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: date1
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(in) :: date2
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(out), dimension(3,3) :: rbpn
classical NPB matrix (Note 2)
Calls
Called by
Contents
Source Code
PNM00A
Source Code
    subroutine PNM00A ( date1, date2, rbpn )
    implicit none
    real(wp),intent(in) :: date1 !! TT as a 2-part Julian Date (Note 1)
    real(wp),intent(in) :: date2 !! TT as a 2-part Julian Date (Note 1)
    real(wp),dimension(3,3),intent(out) :: rbpn !! classical NPB matrix (Note 2)
    real(wp) :: dpsi, deps, epsa, rb(3,3), rp(3,3), rbp(3,3), &
                rn(3,3)
    !  Obtain the required matrix (discarding other results).
    call PN00A ( date1, date2, &
                 dpsi, deps, epsa, rb, rp, rbp, rn, rbpn )
    end subroutine PNM00A
Call graph
pnm00a calls pn00a
pn00a calls pn00, nut00a
pn00 calls obl80, bp00, numat, rxr, pr00
nut00a calls faom03, faur03, faju03, fame03, fasa03, fae03, fal03, fapa03, faf03, fave03, fama03
bp00 calls rxr, pr00, bi00, rx, ir, ry, rz
numat calls rx, ir, rz
c2i00a calls pnm00a
s00a calls pnm00a
xys00a calls pnm00a
c2t00a calls c2i00a