PNM80 – astro-fortran
PNM80 Subroutine
10 statements
Source File
public subroutine PNM80(date1, date2, rmatpn)
Form the matrix of precession/nutation for a given date, IAU 1976 precession model, IAU 1980 nutation model.
Status: support routine.
Notes
The TDB date DATE1+DATE2 is a Julian Date, apportioned in any convenient way between the two arguments. For example, JD(TDB)=2450123.7 could be expressed in any of these ways, among others:
    DATE1          DATE2
 2450123.7D0        0D0        (JD method)
  2451545D0      -1421.3D0     (J2000 method)
 2400000.5D0     50123.2D0     (MJD method)
 2450123.5D0       0.2D0       (date & time method)
The JD method is the most natural and convenient to use in cases where the loss of several decimal digits of resolution is acceptable. The J2000 method is best matched to the way the argument is handled internally and will deliver the optimum resolution. The MJD method and the date & time methods are both good compromises between resolution and convenience.
The matrix operates in the sense V(date) = RMATPN * V(J2000), where the p-vector V(date) is with respect to the true equatorial triad of date DATE1+DATE2 and the p-vector V(J2000) is with respect to the mean equatorial triad of epoch J2000.0.
Reference
Explanatory Supplement to the Astronomical Almanac, P. Kenneth Seidelmann (ed), University Science Books (1992), Section 3.3 (p145).
History
IAU SOFA revision: 2012 September 5
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: date1
TDB date (Note 1)
real(kind=wp), intent(in) :: date2
TDB date (Note 1)
real(kind=wp), intent(out), dimension(3,3) :: rmatpn
combined precession/nutation matrix
Calls
Contents
Source Code
PNM80
Source Code
    subroutine PNM80 ( date1, date2, rmatpn )
    implicit none
    real(wp),intent(in) :: date1 !! TDB date (Note 1)
    real(wp),intent(in) :: date2 !! TDB date (Note 1)
    real(wp),dimension(3,3),intent(out) :: rmatpn !! combined precession/nutation matrix
    real(wp) :: rmatp(3,3), rmatn(3,3)
    !  Precession matrix, J2000.0 to date.
    call PMAT76 ( date1, date2, rmatp )
    !  Nutation matrix.
    call NUTM80 ( date1, date2, rmatn )
    !  Combine the matrices:  PN = N x P.
    call RXR ( rmatn, rmatp, rmatpn )
    end subroutine PNM80
Call graph
pnm80 calls rxr, pmat76, nutm80
pmat76 calls ir, prec76, ry, rz
nutm80 calls obl80, nut80, numat
nut80 calls anpm
numat calls ir, rz, rx