POM00 – astro-fortran
POM00 Subroutine
11 statements
Source File
public subroutine POM00(xp, yp, sp, rpom)
Form the matrix of polar motion for a given date, IAU 2000.
Status: support routine.
Notes
XP and YP are the coordinates (in radians) of the Celestial Intermediate Pole with respect to the International Terrestrial Reference System (see IERS Conventions 2003), measured along the meridians to 0 and 90 deg west respectively.
SP is the TIO locator s', in radians, which positions the Terrestrial Intermediate Origin on the equator. It is obtained from polar motion observations by numerical integration, and so is in essence unpredictable. However, it is dominated by a secular drift of about 47 microarcseconds per century, and so can be taken into account by using s' = -47*t, where t is centuries since J2000.0. The routine SP00 implements this approximation.
The matrix operates in the sense V(TRS) = RPOM * V(CIP), meaning that it is the final rotation when computing the pointing direction to a celestial source.
Reference
McCarthy, D. D., Petit, G. (eds.), IERS Conventions (2003), IERS Technical Note No. 32, BKG (2004)
History
IAU SOFA revision: 2009 December 15
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: xp
coordinates of the pole (radians, Note 1)
real(kind=wp), intent(in) :: yp
coordinates of the pole (radians, Note 1)
real(kind=wp), intent(in) :: sp
the TIO locator s' (radians, Note 2)
real(kind=wp), intent(out), dimension(3,3) :: rpom
polar-motion matrix (Note 3)
Calls
Called by
Contents
Source Code
POM00
Source Code
    subroutine POM00 ( xp, yp, sp, rpom )
    implicit none
    real(wp),intent(in) :: xp !! coordinates of the pole (radians, Note 1)
    real(wp),intent(in) :: yp !! coordinates of the pole (radians, Note 1)
    real(wp),intent(in) :: sp !! the TIO locator s' (radians, Note 2)
    real(wp),dimension(3,3),intent(out) :: rpom !! polar-motion matrix (Note 3)
    !  Construct the matrix.
    call IR ( rpom )
    call RZ ( sp, rpom )
    call RY ( -xp, rpom )
    call RX ( -yp, rpom )
    end subroutine POM00
Call graph
pom00 calls ir, rz, rx, ry
pvtob calls pom00
c2t00a calls pom00
c2txy calls pom00
c2t06a calls pom00
c2tpe calls pom00
c2t00b calls pom00
apco calls pvtob
apio calls pvtob
apco13 calls apco
apio13 calls apio
atco13 calls apco13
atoi13 calls apio13
atio13 calls apio13
atoc13 calls apco13