PPP – astro-fortran
PPP Subroutine
10 statements
Source File
public subroutine PPP(a, b, apb)
P-vector addition.
Status: vector/matrix support routine.
History
IAU SOFA revision: 2000 November 25
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(3) :: a
first p-vector
real(kind=wp), intent(in), dimension(3) :: b
second p-vector
real(kind=wp), intent(out), dimension(3) :: apb
A + B
Called by
Contents
Source Code
PPP
Source Code
    subroutine PPP ( a, b, apb )
    implicit none
    real(wp),dimension(3),intent(in) :: a !! first p-vector
    real(wp),dimension(3),intent(in) :: b !! second p-vector
    real(wp),dimension(3),intent(out) :: apb !! A + B
    integer :: i
    do i=1,3
       apb(i) = a(i) + b(i)
    end do
    end subroutine PPP
Call graph
fk52h calls ppp, pvstar, starpv
pvxpv calls ppp
pvppv calls ppp
pvstar calls ppp
starpv calls ppp
fk524 calls ppp
h2fk5 calls pvstar, starpv
fk54z calls fk524
fk425 calls pvppv
starpm calls pvstar, starpv
pmsafe calls starpm