PPSP – astro-fortran
PPSP Subroutine
11 statements
Source File
public subroutine PPSP(a, s, b, apsb)
P-vector plus scaled p-vector.
Status: vector/matrix support routine.
History
IAU SOFA revision: 2007 August 18
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(3) :: a
first p-vector
real(kind=wp), intent(in) :: s
scalar (multiplier for B)
real(kind=wp), intent(in), dimension(3) :: b
second p-vector
real(kind=wp), intent(out), dimension(3) :: apsb
A + S*B
Called by
Contents
Source Code
PPSP
Source Code
    subroutine PPSP ( a, s, b, apsb )
    implicit none
    real(wp),dimension(3),intent(in) :: a !! first p-vector
    real(wp),intent(in) :: s !! scalar (multiplier for B)
    real(wp),dimension(3),intent(in) :: b !! second p-vector
    real(wp),dimension(3),intent(out) :: apsb !! A + S*B
    integer :: i
    do i=1,3
       apsb(i) = a(i) + s*b(i)
    end do
    end subroutine PPSP
Call graph
ldn calls ppsp
pvu calls ppsp
fk45z calls ppsp, pvu
aticqn calls ldn
starpm calls pvu
atciqn calls ldn
pmsafe calls starpm