PR00 – astro-fortran
PR00 Subroutine
13 statements
Source File
public subroutine PR00(date1, date2, dpsipr, depspr)
Precession-rate part of the IAU 2000 precession-nutation models (part of MHB2000).
Status: canonical model.
Notes
The TT date DATE1+DATE2 is a Julian Date, apportioned in any convenient way between the two arguments. For example, JD(TT)=2450123.7 could be expressed in any of these ways, among others
    DATE1          DATE2
 2450123.7D0        0D0        (JD method)
  2451545D0      -1421.3D0     (J2000 method)
 2400000.5D0     50123.2D0     (MJD method)
 2450123.5D0       0.2D0       (date & time method)
The JD method is the most natural and convenient to use in cases where the loss of several decimal digits of resolution is acceptable. The J2000 method is best matched to the way the argument is handled internally and will deliver the optimum resolution. The MJD method and the date & time methods are both good compromises between resolution and convenience.
The precession adjustments are expressed as "nutation components", corrections in longitude and obliquity with respect to the J2000.0 equinox and ecliptic.
Although the precession adjustments are stated to be with respect to Lieske et al. (1977), the MHB2000 model does not specify which set of Euler angles are to be used and how the adjustments are to be applied. The most literal and straightforward procedure is to adopt the 4-rotation epsilon_0, psi_A, omega_A, xi_A option, and to add DPSIPR to psi_A and DEPSPR to both omega_A and eps_A.
This is an implementation of one aspect of the IAU 2000A nutation model, formally adopted by the IAU General Assembly in 2000, namely MHB2000 (Mathews et al. 2002).
References
Lieske, J.H., Lederle, T., Fricke, W. & Morando, B., "Expressions for the precession quantities based upon the IAU (1976) System of Astronomical Constants", Astron.Astrophys., 58, 1-16 (1977)
Mathews, P.M., Herring, T.A., Buffet, B.A., "Modeling of nutation and precession New nutation series for nonrigid Earth and insights into the Earth's interior", J.Geophys.Res., 107, B4,
The MHB2000 code itself was obtained on 9th September 2002 from ftp://maia.usno.navy.mil/conv2000/chapter5/IAU2000A.
Wallace, P.T., "Software for Implementing the IAU 2000 Resolutions", in IERS Workshop 5.1 (2002).
History
IAU SOFA revision: 2009 December 15
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: date1
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(in) :: date2
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(out) :: dpsipr
precession corrections (Notes 2,3)
real(kind=wp), intent(out) :: depspr
precession corrections (Notes 2,3)
Called by
Contents
Source Code
PR00
Source Code
    subroutine PR00 ( date1, date2, dpsipr, depspr )
    implicit none
    real(wp),intent(in) :: date1 !! TT as a 2-part Julian Date (Note 1)
    real(wp),intent(in) :: date2 !! TT as a 2-part Julian Date (Note 1)
    real(wp),intent(out) :: dpsipr !! precession corrections (Notes 2,3)
    real(wp),intent(out) :: depspr !! precession corrections (Notes 2,3)
    real(wp) :: t
    !  ------------------------------------
    !  Precession and obliquity corrections (radians per century)
    !  ------------------------------------
    real(wp),parameter :: precor = -0.29965_wp * das2r
    real(wp),parameter :: oblcor = -0.02524_wp * das2r
    !  Interval between fundamental epoch J2000.0 and given date (JC).
    t = ( ( date1-dj00 ) + date2 ) / djc
    !  Precession rate contributions with respect to IAU 1976/80.
    dpsipr = precor * t
    depspr = oblcor * t
    end subroutine PR00
Call graph
ee00b calls pr00
bp00 calls pr00
ee00a calls pr00
pn00 calls pr00, bp00
gst00a calls ee00a
pn00a calls pn00
pn00b calls pn00
c2tpe calls pn00
gst00b calls ee00b
pmat00 calls bp00
num00a calls pn00a
pnm00a calls pn00a
pnm00b calls pn00b
num00b calls pn00b
s00b calls pnm00b
c2i00a calls pnm00a
s00a calls pnm00a
xys00a calls pnm00a
xys00b calls pnm00b
c2i00b calls pnm00b
c2t00b calls c2i00b
c2t00a calls c2i00a