PVTOB – astro-fortran
PVTOB Subroutine
28 statements
Source File
public subroutine PVTOB(elong, phi, hm, xp, yp, sp, theta, pv)
Position and velocity of a terrestrial observing station.
Status: support routine.
Notes
The terrestrial coordinates are with respect to the WGS84 reference ellipsoid.
XP and YP are the coordinates (in radians) of the Celestial Intermediate Pole with respect to the International Terrestrial Reference System (see IERS Conventions 2003), measured along the meridians 0 and 90 deg west respectively. SP is the TIO locator s', in radians, which positions the Terrestrial Intermediate Origin on the equator. For many applications, XP, YP and (especially) SP can be set to zero.
If THETA is Greenwich apparent sidereal time instead of Earth rotation angle, the result is with respect to the true equator and equinox of date, i.e. with the x-axis at the equinox rather than the celestial intermediate origin.
The velocity units are meters per UT1 second, not per SI second. This is unlikely to have any practical consequences in the modern era.
No validation is performed on the arguments. Error cases that could lead to arithmetic exceptions are trapped by the GD2GC routine, and the result set to zeros.
References
McCarthy, D. D., Petit, G. (eds.), IERS Conventions (2003), IERS Technical Note No. 32, BKG (2004)
Urban, S. & Seidelmann, P. K. (eds), Explanatory Supplement to the Astronomical Almanac, 3rd ed., University Science Books (2013), Section 7.4.3.3.
History
IAU SOFA revision: 2013 June 25
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: elong
longitude (radians, east +ve, Note 1)
real(kind=wp), intent(in) :: phi
latitude (geodetic, radians, Note 1)
real(kind=wp), intent(in) :: hm
height above reference ellipsoid (geodetic, m)
real(kind=wp), intent(in) :: xp
coordinates of the pole (radians, Note 2)
real(kind=wp), intent(in) :: yp
coordinates of the pole (radians, Note 2)
real(kind=wp), intent(in) :: sp
the TIO locator s' (radians, Note 2)
real(kind=wp), intent(in) :: theta
Earth rotation angle (radians, Note 3)
real(kind=wp), intent(out), dimension(3,2) :: pv
position/velocity vector (m, m/s, CIRS)
Calls
Called by
Contents
Source Code
PVTOB
Source Code
    subroutine PVTOB ( elong, phi, hm, xp, yp, sp, theta, pv )
    implicit none
    real(wp),intent(in) :: elong !! longitude (radians, east +ve, Note 1)
    real(wp),intent(in) :: phi !! latitude (geodetic, radians, Note 1)
    real(wp),intent(in) :: hm !! height above reference ellipsoid (geodetic, m)
    real(wp),intent(in) :: xp !! coordinates of the pole (radians, Note 2)
    real(wp),intent(in) :: yp !! coordinates of the pole (radians, Note 2)
    real(wp),intent(in) :: sp !! the TIO locator s' (radians, Note 2)
    real(wp),intent(in) :: theta !! Earth rotation angle (radians, Note 3)
    real(wp),dimension(3,2),intent(out) :: pv !! position/velocity vector (m, m/s, CIRS)
    !  Earth rotation rate in radians per UT1 second
    real(wp),parameter :: om = 1.00273781191135448_wp * d2pi / d2s
    integer :: j
    real(wp) :: xyzm(3), rpm(3,3), xyz(3), x, y, z, s, c
    !  Geodetic to geocentric transformation (WGS84).
    call GD2GC ( 1, elong, phi, hm, xyzm, j )
    !  Polar motion and TIO position.
    call POM00 ( xp, yp, sp, rpm )
    call TRXP ( rpm, xyzm, xyz )
    x = xyz(1)
    y = xyz(2)
    z = xyz(3)
    !  routines of ERA.
    s = sin(theta)
    c = cos(theta)
    !  Position.
    pv(1,1) = c*x - s*y
    pv(2,1) = s*x + c*y
    pv(3,1) = z
    !  Velocity.
    pv(1,2) = om * ( -s*x - c*y )
    pv(2,2) = om * (  c*x - s*y )
    pv(3,2) = 0.0_wp
    end subroutine PVTOB
Call graph
pvtob calls pom00, gd2gc, trxp
pom00 calls ry, ir, rz, rx
gd2gc calls eform, gd2gce
trxp calls rxp, tr
apco calls pvtob
apio calls pvtob
apio13 calls apio
apco13 calls apco
atio13 calls apio13
atoc13 calls apco13
atoi13 calls apio13
atco13 calls apco13