PXP – astro-fortran
PXP Subroutine
16 statements
Source File
public subroutine PXP(a, b, axb)
p-vector outer (=vector=cross) product.
Status: vector/matrix support routine.
History
IAU SOFA revision: 2000 November 25
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(3) :: a
first p-vector
real(kind=wp), intent(in), dimension(3) :: b
second p-vector
real(kind=wp), intent(out), dimension(3) :: axb
A x B
Called by
Contents
Source Code
PXP
Source Code
    subroutine PXP ( a, b, axb )
    implicit none
    real(wp),dimension(3),intent(in) :: a !! first p-vector
    real(wp),dimension(3),intent(in) :: b !! second p-vector
    real(wp),dimension(3),intent(out) :: axb !! A x B
    real(wp) :: xa, ya, za, xb, yb, zb
    xa = a(1)
    ya = a(2)
    za = a(3)
    xb = b(1)
    yb = b(2)
    zb = b(3)
    axb(1) = ya*zb - za*yb
    axb(2) = za*xb - xa*zb
    axb(3) = xa*yb - ya*xb
    end subroutine PXP
Call graph
pap calls pxp
ld calls pxp
ltecm calls pxp
fk52h calls pxp
sepp calls pxp
h2fk5 calls pxp
pvxpv calls pxp
hfk5z calls pxp
ltp calls pxp
seps calls sepp
lteceq calls ltecm
ltpb calls ltp
lteqec calls ltecm
ldsun calls ld
ldn calls ld
pmsafe calls seps
aticq calls ldsun
atciqn calls ldn
atciqz calls ldsun
aticqn calls ldn
atciq calls ldsun
atoc13 calls aticq
atic13 calls aticq
atci13 calls atciq
atco13 calls atciq