RX – astro-fortran
RX Subroutine
20 statements
Source File
public subroutine RX(phi, r)
Rotate an r-matrix about the x-axis.
Status: vector/matrix support routine.
Notes
Calling this routine with positive PHI incorporates in the supplied r-matrix R an additional rotation, about the x-axis, anticlockwise as seen looking towards the origin from positive x.
The additional rotation can be represented by this matrix:
         (  1        0            0      )
         (                               )
         (  0   + cos(PHI)   + sin(PHI)  )
         (                               )
         (  0   - sin(PHI)   + cos(PHI)  )
History
IAU SOFA revision: 2012 April 3
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: phi
angle (radians)
real(kind=wp), intent(out), dimension(3,3) :: r
r-matrix, rotated
Called by
Contents
Source Code
RX
Source Code
    subroutine RX ( phi, r )
    implicit none
    real(wp),intent(in) :: phi !! angle (radians)
    real(wp),dimension(3,3),intent(out) :: r !! r-matrix, rotated
    real(wp) :: s, c, a21, a22, a23, a31, a32, a33
    s = sin(phi)
    c = cos(phi)
    a21 =   c*r(2,1) + s*r(3,1)
    a22 =   c*r(2,2) + s*r(3,2)
    a23 =   c*r(2,3) + s*r(3,3)
    a31 = - s*r(2,1) + c*r(3,1)
    a32 = - s*r(2,2) + c*r(3,2)
    a33 = - s*r(2,3) + c*r(3,3)
    r(2,1) = a21
    r(2,2) = a22
    r(2,3) = a23
    r(3,1) = a31
    r(3,2) = a32
    r(3,3) = a33
    end subroutine RX
Call graph
pom00 calls rx
bp00 calls rx
numat calls rx
fw2m calls rx
ecm06 calls rx, pmat06
c2tpe calls pom00, pn00
pmat06 calls fw2m
pn00 calls bp00, numat
c2t00a calls pom00, c2i00a
fw2xy calls fw2m
c2txy calls pom00
eqec06 calls ecm06
pnm06a calls fw2m
num06a calls numat
c2t06a calls pom00, c2i06a
pmat00 calls bp00
c2t00b calls pom00, c2i00b
nutm80 calls numat
bp06 calls fw2m, pmat06
eceq06 calls ecm06
pvtob calls pom00
pn06 calls fw2m
apio calls pvtob
pn06a calls pn06
pn00a calls pn00
pnm80 calls nutm80
pn00b calls pn00
s06a calls pnm06a
apci13 calls pnm06a
eo06a calls pnm06a
apco13 calls pnm06a, apco
gst06a calls pnm06a
apco calls pvtob
xys06a calls pnm06a
pb06 calls pmat06
c2i06a calls pnm06a
atoc13 calls apco13
apio13 calls apio
pnm00a calls pn00a
num00b calls pn00b
atci13 calls apci13
ee06a calls gst06a
atic13 calls apci13
atco13 calls apco13
num00a calls pn00a
pnm00b calls pn00b
c2i00b calls pnm00b
xys00b calls pnm00b
s00b calls pnm00b
c2i00a calls pnm00a
s00a calls pnm00a
xys00a calls pnm00a
atio13 calls apio13
atoi13 calls apio13