RXP – astro-fortran
RXP Subroutine
16 statements
Source File
public subroutine RXP(r, p, rp)
Multiply a p-vector by an r-matrix.
Status: vector/matrix support routine.
History
IAU SOFA revision: 2006 November 13
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(3,3) :: r
r-matrix
real(kind=wp), intent(in), dimension(3) :: p
p-vector
real(kind=wp), intent(out), dimension(3) :: rp
R * P
Called by
Contents
Source Code
RXP
Source Code
    subroutine RXP ( r, p, rp )
    implicit none
    real(wp),dimension(3,3),intent(in) :: r !! r-matrix
    real(wp),dimension(3),intent(in) :: p !! p-vector
    real(wp),dimension(3),intent(out) :: rp !! R * P
    real(wp) :: w, wrp(3)
    integer :: i, j
    !  Matrix R * vector P.
    do j=1,3
       w = 0.0_wp
       do i=1,3
          w = w + r(j,i)*p(i)
       end do
       wrp(j) = w
    end do
    !  Return the result.
    call CP ( wrp, rp )
    end subroutine RXP
Call graph
atciq calls rxp
hfk5z calls rxp, trxp
lteqec calls rxp
fk52h calls rxp
rxpv calls rxp
trxp calls rxp
atciqn calls rxp
atciqz calls rxp
eqec06 calls rxp
fk5hz calls rxp, trxp
h2fk5 calls rxp, trxp
icrs2g calls rxp
atci13 calls atciq
atco13 calls atciq, apco13
pvtob calls trxp
aticqn calls trxp
eceq06 calls trxp
g2icrs calls trxp
trxpv calls rxpv
aticq calls trxp
lteceq calls trxp
apco calls pvtob, trxpv
atic13 calls aticq
atoc13 calls aticq, apco13
apio calls pvtob
apco13 calls apco
apio13 calls apio
atio13 calls apio13
atoi13 calls apio13