RXR – astro-fortran
RXR Subroutine
18 statements
Source File
public subroutine RXR(a, b, atb)
Multiply two r-matrices.
Status: vector/matrix support routine.
History
IAU SOFA revision: 2000 November 25
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(3,3) :: a
first r-matrix
real(kind=wp), intent(in), dimension(3,3) :: b
second r-matrix
real(kind=wp), intent(out), dimension(3,3) :: atb
A * B
Called by
Contents
Source Code
RXR
Source Code
    subroutine RXR ( a, b, atb )
    implicit none
    real(wp),dimension(3,3),intent(in) :: a !! first r-matrix
    real(wp),dimension(3,3),intent(in) :: b !! second r-matrix
    real(wp),dimension(3,3),intent(out) :: atb !! A * B
    integer :: i, j, k
    real(wp) :: w, wm(3,3)
    do i=1,3
       do j=1,3
          w = 0.0_wp
          do k=1,3
             w = w + a(i,k)*b(k,j)
          end do
          wm(i,j) = w
       end do
    end do
    call CR ( wm, atb )
    end subroutine RXR
Call graph
bp00 calls rxr
pn00 calls rxr, bp00
bp06 calls rxr
c2teqx calls rxr
hfk5z calls rxr
pn06 calls rxr
pnm80 calls rxr
c2tcio calls rxr
ecm06 calls rxr
pn06a calls pn06
pn00a calls pn00
c2t00a calls c2tcio, c2i00a
c2txy calls c2tcio
eceq06 calls ecm06
pmat00 calls bp00
pn00b calls pn00
c2tpe calls pn00, c2teqx
c2t06a calls c2tcio
c2tceo calls c2tcio
c2t00b calls c2tcio, c2i00b
eqec06 calls ecm06
pnm00a calls pn00a
num00a calls pn00a
num00b calls pn00b
pnm00b calls pn00b
xys00a calls pnm00a
s00a calls pnm00a
c2i00b calls pnm00b
c2i00a calls pnm00a
s00b calls pnm00b
xys00b calls pnm00b