RY – astro-fortran
RY Subroutine
20 statements
Source File
public subroutine RY(theta, r)
Rotate an r-matrix about the y-axis.
Status: vector/matrix support routine.
Notes
Calling this routine with positive THETA incorporates in the supplied r-matrix R an additional rotation, about the y-axis, anticlockwise as seen looking towards the origin from positive y.
The additional rotation can be represented by this matrix:
         (  + cos(THETA)     0      - sin(THETA)  )
         (                                        )
         (       0           1           0        )
         (                                        )
         (  + sin(THETA)     0      + cos(THETA)  )
History
IAU SOFA revision: 2012 April 3
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: theta
angle (radians)
real(kind=wp), intent(out), dimension(3,3) :: r
r-matrix, rotated
Called by
Contents
Source Code
RY
Source Code
    subroutine RY ( theta, r )
    implicit none
    real(wp),intent(in) :: theta !! angle (radians)
    real(wp),dimension(3,3),intent(out) :: r !! r-matrix, rotated
    real(wp) :: s, c, a11, a12, a13, a31, a32, a33
    s = sin(theta)
    c = cos(theta)
    a11 = c*r(1,1) - s*r(3,1)
    a12 = c*r(1,2) - s*r(3,2)
    a13 = c*r(1,3) - s*r(3,3)
    a31 = s*r(1,1) + c*r(3,1)
    a32 = s*r(1,2) + c*r(3,2)
    a33 = s*r(1,3) + c*r(3,3)
    r(1,1) = a11
    r(1,2) = a12
    r(1,3) = a13
    r(3,1) = a31
    r(3,2) = a32
    r(3,3) = a33
    end subroutine RY
Call graph
c2ixys calls ry
pom00 calls ry
bp00 calls ry
pmat76 calls ry
c2tpe calls pom00, pn00
pnm80 calls pmat76
pn00 calls bp00
c2t00a calls pom00, c2i00a
c2txy calls pom00, c2ixy
apco calls c2ixys, pvtob
c2t06a calls pom00, c2i06a
pmat00 calls bp00
pvtob calls pom00
c2t00b calls pom00, c2i00b
apci calls c2ixys
c2ixy calls c2ixys
c2i06a calls c2ixys
apio calls pvtob
pn00a calls pn00
pn00b calls pn00
apci13 calls apci
apco13 calls apco
c2ibpn calls c2ixy
atoc13 calls apco13
c2i00b calls c2ibpn, pnm00b
apio13 calls apio
pnm00a calls pn00a
num00b calls pn00b
atci13 calls apci13
atic13 calls apci13
atco13 calls apco13
c2i00a calls c2ibpn, pnm00a
num00a calls pn00a
pnm00b calls pn00b
xys00b calls pnm00b
s00b calls pnm00b
s00a calls pnm00a
xys00a calls pnm00a
atio13 calls apio13
atoi13 calls apio13