RZ – astro-fortran
RZ Subroutine
20 statements
Source File
public subroutine RZ(psi, r)
Rotate an r-matrix about the z-axis.
Status: vector/matrix support routine.
Notes
Calling this routine with positive PSI incorporates in the supplied r-matrix R an additional rotation, about the z-axis, anticlockwise as seen looking towards the origin from positive z.
The additional rotation can be represented by this matrix:
         (  + cos(PSI)   + sin(PSI)     0  )
         (                                 )
         (  - sin(PSI)   + cos(PSI)     0  )
         (                                 )
         (       0            0         1  )
History
IAU SOFA revision: 2012 April 3
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: psi
angle (radians)
real(kind=wp), intent(out), dimension(3,3) :: r
r-matrix, rotated
Called by
Contents
Source Code
RZ
Source Code
    subroutine RZ ( psi, r )
    implicit none
    real(wp),intent(in) :: psi !! angle (radians)
    real(wp),dimension(3,3),intent(out) :: r !! r-matrix, rotated
    real(wp) :: s, c, a11, a12, a13, a21, a22, a23
    s = sin(psi)
    c = cos(psi)
    a11 =   c*r(1,1) + s*r(2,1)
    a12 =   c*r(1,2) + s*r(2,2)
    a13 =   c*r(1,3) + s*r(2,3)
    a21 = - s*r(1,1) + c*r(2,1)
    a22 = - s*r(1,2) + c*r(2,2)
    a23 = - s*r(1,3) + c*r(2,3)
    r(1,1) = a11
    r(1,2) = a12
    r(1,3) = a13
    r(2,1) = a21
    r(2,2) = a22
    r(2,3) = a23
    end subroutine RZ
Call graph
c2teqx calls rz
pmat76 calls rz
c2tcio calls rz
pom00 calls rz
bp00 calls rz
pb06 calls rz, pmat06
numat calls rz
c2ixys calls rz
fw2m calls rz
c2t00b calls c2tcio, pom00, c2i00b
c2tpe calls c2teqx, pom00, pn00
pmat06 calls fw2m
apco calls c2ixys, pvtob
nutm80 calls numat
apci calls c2ixys
c2ixy calls c2ixys
pnm80 calls pmat76, nutm80
pn06 calls fw2m
pn00 calls bp00, numat
c2txy calls c2tcio, pom00, c2ixy
num06a calls numat
c2tceo calls c2tcio
bp06 calls fw2m, pmat06
pvtob calls pom00
pnm06a calls fw2m
c2t00a calls c2tcio, pom00, c2i00a
fw2xy calls fw2m
c2t06a calls c2tcio, pom00, c2i06a
pmat00 calls bp00
c2i06a calls c2ixys, pnm06a
apio calls pvtob
pn06a calls pn06
pn00a calls pn00
pn00b calls pn00
s06a calls pnm06a
c2ibpn calls c2ixy
apci13 calls apci, pnm06a
apco13 calls apco, pnm06a
eo06a calls pnm06a
gst06a calls pnm06a
xys06a calls pnm06a
ecm06 calls pmat06
atoc13 calls apco13
c2i00b calls c2ibpn, pnm00b
apio13 calls apio
pnm00a calls pn00a
num00b calls pn00b
atci13 calls apci13
eqec06 calls ecm06
eceq06 calls ecm06
ee06a calls gst06a
atic13 calls apci13
atco13 calls apco13
c2i00a calls c2ibpn, pnm00a
num00a calls pn00a
pnm00b calls pn00b
xys00b calls pnm00b
s00b calls pnm00b
s00a calls pnm00a
xys00a calls pnm00a
atio13 calls apio13
atoi13 calls apio13