S00A – astro-fortran
S00A Function
10 statements
Source File
public function S00A(date1, date2) result(s)
The CIO locator s, positioning the Celestial Intermediate Origin on the equator of the Celestial Intermediate Pole, using the IAU 2000A precession-nutation model.
Status: support routine.
Notes
The TT date DATE1+DATE2 is a Julian Date, apportioned in any convenient way between the two arguments. For example, JD(TT)=2450123.7 could be expressed in any of these ways, among others:
    DATE1          DATE2
 2450123.7D0        0D0        (JD method)
  2451545D0      -1421.3D0     (J2000 method)
 2400000.5D0     50123.2D0     (MJD method)
 2450123.5D0       0.2D0       (date & time method)
The JD method is the most natural and convenient to use in cases where the loss of several decimal digits of resolution is acceptable. The J2000 method is best matched to the way the argument is handled internally and will deliver the optimum resolution. The MJD method and the date & time methods are both good compromises between resolution and convenience.
The CIO locator s is the difference between the right ascensions of the same point in two systems. The two systems are the GCRS and the CIP,CIO, and the point is the ascending node of the CIP equator. The CIO locator s remains a small fraction of 1 arcsecond throughout 1900-2100.
The series used to compute s is in fact for s+XY/2, where X and Y are the x and y components of the CIP unit vector; this series is more compact than a direct series for s would be. The present routine uses the full IAU 2000A nutation model when predicting the CIP position. Faster results, with no significant loss of accuracy, can be obtained via the routine S00B, which uses instead the IAU 2000B truncated model.
References
Capitaine, N., Chapront, J., Lambert, S. and Wallace, P., "Expressions for the Celestial Intermediate Pole and Celestial Ephemeris Origin consistent with the IAU 2000A precession-nutation model", Astron.Astrophys. 400, 1145-1154 (2003)
n.b. The celestial ephemeris origin (CEO) was renamed "celestial intermediate origin" (CIO) by IAU 2006 Resolution 2.
McCarthy, D. D., Petit, G. (eds.), IERS Conventions (2003), IERS Technical Note No. 32, BKG (2004)
History
IAU SOFA revision: 2010 January 18
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: date1
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(in) :: date2
TT as a 2-part Julian Date (Note 1)
Return Value real(kind=wp)
the CIO locator s in radians (Note 2)
Calls
Contents
Source Code
S00A
Source Code
    function S00A ( date1, date2 ) result(s)
    implicit none
    real(wp),intent(in) :: date1 !! TT as a 2-part Julian Date (Note 1)
    real(wp),intent(in) :: date2 !! TT as a 2-part Julian Date (Note 1)
    real(wp) :: s !! the CIO locator s in radians (Note 2)
    real(wp) :: rbpn(3,3), x, y
    !  Bias-precession-nutation-matrix, IAU 2000A.
    call PNM00A ( date1, date2, rbpn )
    !  Extract the CIP coordinates.
    call BPN2XY ( rbpn, x, y )
    !  Compute the CIO locator s, given the CIP coordinates.
    s = S00 ( date1, date2, x, y )
    end function S00A
Call graph
s00a calls pnm00a, bpn2xy, s00
pnm00a calls pn00a
s00 calls faom03, fad03, falp03, fae03, fal03, fapa03, faf03, fave03
pn00a calls pn00, nut00a
pn00 calls obl80, bp00, numat, rxr, pr00
nut00a calls faom03, fae03, fal03, fapa03, faf03, fave03, faur03, faju03, fame03, fasa03, fama03
bp00 calls rxr, pr00, bi00, rx, ir, ry, rz
numat calls rx, ir, rz