S2C – astro-fortran
S2C Subroutine
11 statements
Source File
public subroutine S2C(theta, phi, c)
Convert spherical coordinates to Cartesian.
Status: vector/matrix support routine.
History
IAU SOFA revision: 2000 November 25
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: theta
longitude angle (radians)
real(kind=wp), intent(in) :: phi
latitude angle (radians)
real(kind=wp), intent(out), dimension(3) :: c
direction cosines
Called by
Contents
Source Code
S2C
Source Code
    subroutine S2C ( theta, phi, c )
    implicit none
    real(wp),intent(in) :: theta !!  longitude angle (radians)
    real(wp),intent(in) :: phi !!  latitude angle (radians)
    real(wp),dimension(3),intent(out) :: c !! direction cosines
    real(wp) :: cp
    cp = cos(phi)
    c(1) = cos(theta) * cp
    c(2) = sin(theta) * cp
    c(3) = sin(phi)
    end subroutine S2C
Call graph
aticqn calls s2c
fk54z calls s2c
g2icrs calls s2c
eceq06 calls s2c
fk45z calls s2c
hfk5z calls s2c
lteqec calls s2c
s2p calls s2c
atciqz calls s2c
atioq calls s2c
atoiq calls s2c
aticq calls s2c
eqec06 calls s2c
fk5hz calls s2c
icrs2g calls s2c
lteceq calls s2c
seps calls s2c
atco13 calls atioq
atoi13 calls atoiq
atic13 calls aticq
atio13 calls atioq
pmsafe calls seps
atoc13 calls atoiq, aticq