S2PV – astro-fortran
S2PV Subroutine
26 statements
Source File
public subroutine S2PV(theta, phi, r, td, pd, rd, pv)
Convert position/velocity from spherical to Cartesian coordinates.
Status: vector/matrix support routine.
History
IAU SOFA revision: 2000 November 25
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: theta
longitude angle (radians)
real(kind=wp), intent(in) :: phi
latitude angle (radians)
real(kind=wp), intent(in) :: r
radial distance
real(kind=wp), intent(in) :: td
rate of change of THETA
real(kind=wp), intent(in) :: pd
rate of change of PHI
real(kind=wp), intent(in) :: rd
rate of change of R
real(kind=wp), intent(out), dimension(3,2) :: pv
pv-vector
Called by
Contents
Source Code
S2PV
Source Code
    subroutine S2PV ( theta, phi, r, td, pd, rd, pv )
    implicit none
    real(wp),intent(in) :: theta !! longitude angle (radians)
    real(wp),intent(in) :: phi !! latitude angle (radians)
    real(wp),intent(in) :: r !! radial distance
    real(wp),intent(in) :: td !! rate of change of THETA
    real(wp),intent(in) :: pd !! rate of change of PHI
    real(wp),intent(in) :: rd !! rate of change of R
    real(wp),dimension(3,2),intent(out) :: pv !! pv-vector
    real(wp) :: st, ct, sp, cp, rcp, x, y, rpd, w
    st = sin(theta)
    ct = cos(theta)
    sp = sin(phi)
    cp = cos(phi)
    rcp = r*cp
    x = rcp*ct
    y = rcp*st
    rpd = r*pd
    w = rpd*sp - cp*rd
    pv(1,1) = x
    pv(2,1) = y
    pv(3,1) = r*sp
    pv(1,2) = - y*td - w*ct
    pv(2,2) =   x*td - w*st
    pv(3,2) = rpd*cp + sp*rd
    end subroutine S2PV
Call graph
fk425 calls s2pv
starpv calls s2pv
fk524 calls s2pv
fk52h calls starpv
starpm calls starpv
h2fk5 calls starpv
fk54z calls fk524
pmsafe calls starpm