SXP – astro-fortran
SXP Subroutine
10 statements
Source File
public subroutine SXP(s, p, sp)
Multiply a p-vector by a scalar.
Status: vector/matrix support routine.
History
IAU SOFA revision: 2000 November 25
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: s
scalar
real(kind=wp), intent(in), dimension(3) :: p
p-vector
real(kind=wp), intent(out), dimension(3) :: sp
S * P
Called by
Contents
Source Code
SXP
Source Code
    subroutine SXP ( s, p, sp )
    implicit none
    real(wp),intent(in) :: s !! scalar
    real(wp),dimension(3),intent(in) :: p !! p-vector
    real(wp),dimension(3),intent(out) :: sp !! S * P
    integer :: i
    do i=1,3
       sp(i) = s * p(i)
    end do
    end subroutine SXP
Call graph
pn calls sxp
starpv calls sxp
fk425 calls sxp
fk524 calls sxp
hfk5z calls sxp
s2p calls sxp
pvstar calls sxp
fk5hz calls sxp
s2xpv calls sxp
starpm calls starpv, pvstar
fk54z calls fk524
fk52h calls starpv, pvstar
apcs calls pn
h2fk5 calls starpv, pvstar
sxpv calls s2xpv
pmsafe calls starpm
apco calls apcs
apcs13 calls apcs
apcg calls apcs
apco13 calls apco
apci calls apcg
apcg13 calls apcg
atco13 calls apco13
apci13 calls apci
atoc13 calls apco13
atci13 calls apci13
atic13 calls apci13