TAIUTC – astro-fortran
TAIUTC Subroutine
38 statements
Source File
public subroutine TAIUTC(tai1, tai2, utc1, utc2, j)
Time scale transformation: International Atomic Time, TAI, to Coordinated Universal Time, UTC.
Status: canonical.
Notes
TAI1+TAI2 is Julian Date, apportioned in any convenient way between the two arguments, for example where TAI1 is the Julian Day Number and TAI2 is the fraction of a day. The returned UTC1 and UTC2 form an analogous pair, except that a special convention is used, to deal with the problem of leap seconds - see the next note.
JD cannot unambiguously represent UTC during a leap second unless special measures are taken. The convention in the present routine is that the JD day represents UTC days whether the length is 86399, 86400 or 86401 SI seconds. In the 1960-1972 era there were smaller jumps (in either direction) each time the linear UTC(TAI) expression was changed, and these "mini-leaps" are also included in the SOFA convention.
The routine D2DTF can be used to transform the UTC quasi-JD into calendar date and clock time, including UTC leap second handling.
The warning status "dubious year" flags UTCs that predate the introduction of the time scale or that are too far in the future to be trusted. See DAT for further details.
References
McCarthy, D. D., Petit, G. (eds.), IERS Conventions (2003), IERS Technical Note No. 32, BKG (2004)
Explanatory Supplement to the Astronomical Almanac, P. Kenneth Seidelmann (ed), University Science Books (1992)
History
IAU SOFA revision: 2019 June 20
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: tai1
TAI as a 2-part Julian Date (Note 1)
real(kind=wp), intent(in) :: tai2
TAI as a 2-part Julian Date (Note 1)
real(kind=wp), intent(out) :: utc1
UTC as a 2-part quasi Julian Date (Notes 1-3)
real(kind=wp), intent(out) :: utc2
UTC as a 2-part quasi Julian Date (Notes 1-3)
integer, intent(out) :: j
+1 = dubious year (Note 4)
0 = OK
-1 = unacceptable date
Calls
Contents
Source Code
TAIUTC
Source Code
    subroutine TAIUTC ( tai1, tai2, utc1, utc2, j )
    implicit none
    real(wp),intent(in) :: tai1 !! TAI as a 2-part Julian Date (Note 1)
    real(wp),intent(in) :: tai2 !! TAI as a 2-part Julian Date (Note 1)
    real(wp),intent(out) :: utc1 !! UTC as a 2-part quasi Julian Date (Notes 1-3)
    real(wp),intent(out) :: utc2 !! UTC as a 2-part quasi Julian Date (Notes 1-3)
    integer,intent(out) :: j !! status:
                             !! * +1 = dubious year (Note 4)
                             !! * 0 = OK
                             !! * -1 = unacceptable date
    logical :: big1
    integer :: i, js
    real(wp) :: a1, a2, u1, u2, g1, g2
    !  Put the two parts of the TAI into big-first order.
    big1 = abs(tai1) >= abs(tai2)
    if ( big1 ) then
       a1 = tai1
       a2 = tai2
    else
       a1 = tai2
       a2 = tai1
    end if
    !  Initial guess for UTC.
    u1 = a1
    u2 = a2
    !  Iterate (though in most cases just once is enough).
    do i=1,3
       !  Guessed UTC to TAI.
       call UTCTAI ( u1, u2, g1, g2, js )
       if ( js<0 ) then
        j = js
        return
       end if
       !  Adjust guessed UTC.
       u2 = u2 + (a1-g1)
       u2 = u2 + (a2-g2)
    end do
    !  Return the UTC result, preserving the TAI order.
    if ( big1 ) then
       utc1 = u1
       utc2 = u2
    else
       utc1 = u2
       utc2 = u1
    end if
    !  Status.
    j = js
    end subroutine TAIUTC
Call graph
taiutc calls utctai
utctai calls jd2cal, cal2jd, dat
dat calls cal2jd