TR – astro-fortran
TR Subroutine
13 statements
Source File
public subroutine TR(r, rt)
Transpose an r-matrix.
Status: vector/matrix support routine.
History
IAU SOFA revision: 2000 November 25
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(3,3) :: r
r-matrix
real(kind=wp), intent(out), dimension(3,3) :: rt
transpose
Called by
Contents
Source Code
TR
Source Code
    subroutine TR ( r, rt )
    implicit none
    real(wp),dimension(3,3),intent(in) :: r !! r-matrix
    real(wp),dimension(3,3),intent(out) :: rt !! transpose
    real(wp) :: wm(3,3)
    integer :: i, j
    do i=1,3
       do j=1,3
          wm(i,j) = r(j,i)
       end do
    end do
    call CR ( wm, rt )
    end subroutine TR
Call graph
trxpv calls tr
trxp calls tr
pn06 calls tr
bp06 calls tr
lteceq calls trxp
pn06a calls pn06
aticq calls trxp
fk5hz calls trxp
g2icrs calls trxp
h2fk5 calls trxp
apco calls trxpv, pvtob
hfk5z calls trxp
eceq06 calls trxp
aticqn calls trxp
pvtob calls trxp
atoc13 calls aticq, apco13
apio calls pvtob
atic13 calls aticq
apco13 calls apco
apio13 calls apio
atco13 calls apco13
atio13 calls apio13
atoi13 calls apio13