TRXP – astro-fortran
TRXP Subroutine
9 statements
Source File
public subroutine TRXP(r, p, trp)
Multiply a p-vector by the transpose of an r-matrix.
Status: vector/matrix support routine.
History
IAU SOFA revision: 2009 July 11
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(3,3) :: r
r-matrix
real(kind=wp), intent(in), dimension(3) :: p
p-vector
real(kind=wp), intent(out), dimension(3) :: trp
R * P
Calls
Called by
Contents
Source Code
TRXP
Source Code
    subroutine TRXP ( r, p, trp )
    implicit none
    real(wp),dimension(3,3),intent(in) :: r !! r-matrix
    real(wp),dimension(3),intent(in) :: p !! p-vector
    real(wp),dimension(3),intent(out) :: trp !! R * P
    real(wp) :: ri(3,3)
    !  Transpose of matrix R.
    call TR ( r, ri )
    !  Matrix RI * vector P -> vector TRP.
    call RXP ( ri, p, trp )
    end subroutine TRXP
Call graph
trxp calls tr, rxp
lteceq calls trxp
aticq calls trxp
fk5hz calls trxp
g2icrs calls trxp
h2fk5 calls trxp
hfk5z calls trxp
eceq06 calls trxp
aticqn calls trxp
pvtob calls trxp
atoc13 calls aticq, apco13
apio calls pvtob
atic13 calls aticq
apco calls pvtob
apio13 calls apio
apco13 calls apco
atio13 calls apio13
atoi13 calls apio13
atco13 calls apco13