UTCUT1 – astro-fortran
UTCUT1 Subroutine
25 statements
Source File
public subroutine UTCUT1(utc1, utc2, dut1, ut11, ut12, j)
Time scale transformation: Coordinated Universal Time, UTC, to Universal Time, UT1.
Status: canonical.
Notes
UTC1+UTC2 is quasi Julian Date (see Note 2), apportioned in any convenient way between the two arguments, for example where UTC1 is the Julian Day Number and UTC2 is the fraction of a day.
JD cannot unambiguously represent UTC during a leap second unless special measures are taken. The convention in the present routine is that the JD day represents UTC days whether the length is 86399, 86400 or 86401 SI seconds.
The warning status "dubious year" flags UTCs that predate the introduction of the time scale or that are too far in the future to be trusted. See DAT for further details.
The routine DTF2D converts from calendar date and time of day into 2-part Julian Date, and in the case of UTC implements the leap-second-ambiguity convention described above.
Delta UT1 can be obtained from tabulations provided by the International Earth Rotation and Reference Systems Service. It is the caller's responsibility to supply a DUT1 argument containing the UT1-UTC value that matches the given UTC.
The returned UT11,UT12 are such that their sum is the UT1 Julian Date.
References
McCarthy, D. D., Petit, G. (eds.), IERS Conventions (2003), IERS Technical Note No. 32, BKG (2004)
Explanatory Supplement to the Astronomical Almanac, P. Kenneth Seidelmann (ed), University Science Books (1992)
History
IAU SOFA revision: 2013 August 12
11/21/2019: for astro_module, renamed the local variable 'dat' to 'd' so as not to conflict with the subroutine DAT.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: utc1
UTC as a 2-part quasi Julian Date (Notes 1-4)
real(kind=wp), intent(in) :: utc2
UTC as a 2-part quasi Julian Date (Notes 1-4)
real(kind=wp), intent(in) :: dut1
Delta UT1 = UT1-UTC in seconds (Note 5)
real(kind=wp), intent(out) :: ut11
UT1 as a 2-part Julian Date (Note 6)
real(kind=wp), intent(out) :: ut12
UT1 as a 2-part Julian Date (Note 6)
integer, intent(out) :: j
+1 = dubious year (Note 3)
0 = OK
-1 = unacceptable date
Calls
Called by
Contents
Source Code
UTCUT1
Source Code
    subroutine UTCUT1 ( utc1, utc2, dut1, ut11, ut12, j )
    implicit none
    real(wp),intent(in) :: utc1 !! UTC as a 2-part quasi Julian Date (Notes 1-4)
    real(wp),intent(in) :: utc2 !! UTC as a 2-part quasi Julian Date (Notes 1-4)
    real(wp),intent(in) :: dut1 !! Delta UT1 = UT1-UTC in seconds (Note 5)
    real(wp),intent(out) :: ut11 !! UT1 as a 2-part Julian Date (Note 6)
    real(wp),intent(out) :: ut12 !! UT1 as a 2-part Julian Date (Note 6)
    integer,intent(out) :: j !! status:
                             !! * +1 = dubious year (Note 3)
                             !! * 0 = OK
                             !! * -1 = unacceptable date
    integer :: iy, im, id, js, jw
    real(wp) :: w, d, dta, tai1, tai2
    !  Look up TAI-UTC.
    call JD2CAL ( utc1, utc2, iy, im, id, w, js )
    if ( js==0 ) then
      call DAT ( iy, im, id, 0.0_wp, d, js )
      if ( js>=0 ) then
        !  Form UT1-TAI.
        dta = dut1 - d
        !  UTC to TAI to UT1.
        call UTCTAI ( utc1, utc2, tai1, tai2, jw )
        if ( jw<0 ) then
          js = jw
        else
          call TAIUT1 ( tai1, tai2, dta, ut11, ut12, jw )
        end if
      end if
    end if
    !  Return the status.
    j = js
    end subroutine UTCUT1
Call graph
utcut1 calls jd2cal, dat, utctai, taiut1
dat calls cal2jd
utctai calls jd2cal, dat, cal2jd
apco13 calls utcut1
apio13 calls utcut1
atco13 calls apco13
atoi13 calls apio13
atio13 calls apio13
atoc13 calls apco13