XY06 – astro-fortran
XY06 Subroutine
93 statements
Source File
public subroutine XY06(date1, date2, x, y)
X,Y coordinates of celestial intermediate pole from series based on IAU 2006 precession and IAU 2000A nutation.
Status: canonical model.
Notes
The TT date DATE1+DATE2 is a Julian Date, apportioned in any convenient way between the two arguments. For example, JD(TT)=2450123.7 could be expressed in any of these ways, among others:
    DATE1          DATE2
 2450123.7D0        0D0        (JD method)
  2451545D0      -1421.3D0     (J2000 method)
 2400000.5D0     50123.2D0     (MJD method)
 2450123.5D0       0.2D0       (date & time method)
The JD method is the most natural and convenient to use in cases where the loss of several decimal digits of resolution is acceptable. The J2000 method is best matched to the way the argument is handled internally and will deliver the optimum resolution. The MJD method and the date & time methods are both good compromises between resolution and convenience.
The X,Y coordinates are those of the unit vector towards the celestial intermediate pole. They represent the combined effects of frame bias, precession and nutation.
The fundamental arguments used are as adopted in IERS Conventions (2003) and are from Simon et al. (1994) and Souchay et al. (1999).
This is an alternative to the angles-based method, via the SOFA routine FW2XY and as used in XYS06A for example. The two methods agree at the 1 microarcsecond level (at present), a negligible amount compared with the intrinsic accuracy of the models. However, it would be unwise to mix the two methods (angles-based and series-based) in a single application.
References
Capitaine, N., Wallace, P.T. & Chapront, J., 2003, Astron.Astrophys., 412, 567
Capitaine, N. & Wallace, P.T., 2006, Astron.Astrophys. 450, 855
McCarthy, D. D., Petit, G. (eds.), 2004, IERS Conventions (2003), IERS Technical Note No. 32, BKG
Simon, J.L., Bretagnon, P., Chapront, J., Chapront-Touze, M., Francou, G. & Laskar, J., Astron.Astrophys., 1994, 282, 663
Souchay, J., Loysel, B., Kinoshita, H., Folgueira, M., 1999, Astron.Astrophys.Supp.Ser. 135, 111
Wallace, P.T. & Capitaine, N., 2006, Astron.Astrophys. 459, 981
History
IAU SOFA revision: 2013 December 2
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: date1
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(in) :: date2
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(out) :: x
CIP X coordinate (Note 2)
real(kind=wp), intent(out) :: y
CIP Y coordinate (Note 2)
Calls
Contents
Source Code
XY06
Source Code
    subroutine XY06 ( date1, date2, x, y )
    implicit none
    real(wp),intent(in) :: date1 !! TT as a 2-part Julian Date (Note 1)
    real(wp),intent(in) :: date2 !! TT as a 2-part Julian Date (Note 1)
    real(wp),intent(out) :: x !! CIP X coordinate (Note 2)
    real(wp),intent(out) :: y !! CIP Y coordinate (Note 2)
    !  Maximum power of T in the polynomials for X and Y
    integer,parameter :: maxpt = 5
    !  Numbers of frequencies:  luni-solar, planetary, total
    integer,parameter :: nfls = 653
    integer,parameter :: nfpl = 656
    integer,parameter :: nf = nfls+nfpl
    !  Number of amplitude coefficients
    integer,parameter :: na = 4755
    !  Polynomial coefficients (arcsec).
    real(wp),dimension(0:maxpt,0:1),parameter :: xyp = reshape([   -0.016617_wp, &
                                                                +2004.191898_wp, &
                                                                   -0.4297829_wp, &
                                                                   -0.19861834_wp, &
                                                                   +0.000007578_wp, &
                                                                   +0.0000059285_wp, &
                                                                   -0.006951_wp, &
                                                                   -0.025896_wp, &
                                                                   -22.4072747_wp, &
                                                                   +0.00190059_wp, &
                                                                   +0.001112526_wp, &
                                                                   +0.0000001358_wp ], [maxpt+1,2])
    !  Amplitude usage: X or Y, sin or cos, power of T.
    integer,dimension(0:maxpt*4-1),parameter :: jaxy = [ 0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1 ]
    integer,dimension(0:maxpt*4-1),parameter :: jasc = [ 0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0 ]
    integer,dimension(0:maxpt*4-1),parameter :: japt = [ 0,0,0,0,1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4 ]
    !  Miscellaneous
    real(wp) :: t, w, pt(0:maxpt), fa(14), xypr(0:1), xypl(0:1), &
                xyls(0:1), arg, sc(0:1)
    integer :: jpt, i, j, jxy, ialast, ifreq, m, ia, jsc
    !  Fundamental-argument multipliers:  luni-solar terms.
    integer,dimension(5,nfls),parameter :: mfals = reshape( &
                [   0,  0,  0,  0,  1, &
                    0,  0,  2, -2,  2, &
                    0,  0,  2,  0,  2, &
                    0,  0,  0,  0,  2, &
                    0,  1,  0,  0,  0, &
                    0,  1,  2, -2,  2, &
                    1,  0,  0,  0,  0, &
                    0,  0,  2,  0,  1, &
                    1,  0,  2,  0,  2, &
                    0,  1, -2,  2, -2, &
                    0,  0,  2, -2,  1, &
                    1,  0, -2,  0, -2, &
                    1,  0,  0, -2,  0, &
                    1,  0,  0,  0,  1, &
                    1,  0,  0,  0, -1, &
                    1,  0, -2, -2, -2, &
                    1,  0,  2,  0,  1, &
                    2,  0, -2,  0, -1, &
                    0,  0,  0,  2,  0, &
                    0,  0,  2,  2,  2, &
                    2,  0,  0, -2,  0, &
                    0,  2, -2,  2, -2, &
                    2,  0,  2,  0,  2, &
                    1,  0,  2, -2,  2, &
                    1,  0, -2,  0, -1, &
                    2,  0,  0,  0,  0, &
                    0,  0,  2,  0,  0, &
                    0,  1,  0,  0,  1, &
                    1,  0,  0, -2, -1, &
                    0,  2,  2, -2,  2, &
                    0,  0,  2, -2,  0, &
                    1,  0,  0, -2,  1, &
                    0,  1,  0,  0, -1, &
                    0,  2,  0,  0,  0, &
                    1,  0, -2, -2, -1, &
                    1,  0,  2,  2,  2, &
                    0,  1,  2,  0,  2, &
                    2,  0, -2,  0,  0, &
                    0,  0,  2,  2,  1, &
                    0,  1, -2,  0, -2, &
                    0,  0,  0,  2,  1, &
                    1,  0,  2, -2,  1, &
                    2,  0,  0, -2, -1, &
                    2,  0,  2, -2,  2, &
                    2,  0,  2,  0,  1, &
                    0,  0,  0,  2, -1, &
                    0,  1, -2,  2, -1, &
                    1,  1,  0, -2,  0, &
                    2,  0,  0, -2,  1, &
                    1,  0,  0,  2,  0, &
                    0,  1,  2, -2,  1, &
                    1, -1,  0,  0,  0, &
                    0,  1, -1,  1, -1, &
                    2,  0, -2,  0, -2, &
                    0,  1,  0, -2,  0, &
                    1,  0,  0, -1,  0, &
                    3,  0,  2,  0,  2, &
                    0,  0,  0,  1,  0, &
                    1, -1,  2,  0,  2, &
                    1,  1, -2, -2, -2, &
                    1,  0, -2,  0,  0, &
                    2,  0,  0,  0, -1, &
                    0,  1, -2, -2, -2, &
                    1,  1,  2,  0,  2, &
                    2,  0,  0,  0,  1, &
                    1,  1,  0,  0,  0, &
                    1,  0, -2,  2, -1, &
                    1,  0,  2,  0,  0, &
                    1, -1,  0, -1,  0, &
                    1,  0,  0,  0,  2, &
                    1,  0, -1,  0, -1, &
                    0,  0,  2,  1,  2, &
                    1,  0, -2, -4, -2, &
                    1, -1,  0, -1, -1, &
                    1,  0,  2,  2,  1, &
                    0,  2, -2,  2, -1, &
                    1,  0,  0,  0, -2, &
                    2,  0, -2, -2, -2, &
                    1,  1,  2, -2,  2, &
                    2,  0, -2, -4, -2, &
                    1,  0, -4,  0, -2, &
                    2,  0,  2, -2,  1, &
                    1,  0,  0, -1, -1, &
                    2,  0,  2,  2,  2, &
                    3,  0,  0,  0,  0, &
                    1,  0,  0,  2,  1, &
                    0,  0,  2, -2, -1, &
                    3,  0,  2, -2,  2, &
                    0,  0,  4, -2,  2, &
                    1,  0,  0, -4,  0, &
                    0,  1,  2,  0,  1, &
                    2,  0,  0, -4,  0, &
                    1,  1,  0, -2, -1, &
                    2,  0, -2,  0,  1, &
                    0,  0,  2,  0, -1, &
                    0,  1, -2,  0, -1, &
                    0,  1,  0,  0,  2, &
                    0,  0,  2, -1,  2, &
                    0,  0,  2,  4,  2, &
                    2,  1,  0, -2,  0, &
                    1,  1,  0, -2,  1, &
                    1, -1,  0, -2,  0, &
                    1, -1,  0, -1, -2, &
                    1, -1,  0,  0,  1, &
                    0,  1, -2,  2,  0, &
                    0,  1,  0,  0, -2, &
                    1, -1,  2,  2,  2, &
                    1,  0,  0,  2, -1, &
                    1, -1, -2, -2, -2, &
                    3,  0,  2,  0,  1, &
                    0,  1,  2,  2,  2, &
                    1,  0,  2, -2,  0, &
                    1,  1, -2, -2, -1, &
                    1,  0,  2, -4,  1, &
                    0,  1, -2, -2, -1, &
                    2, -1,  2,  0,  2, &
                    0,  0,  0,  2,  2, &
                    1, -1,  2,  0,  1, &
                    1, -1, -2,  0, -2, &
                    0,  1,  0,  2,  0, &
                    0,  1,  2, -2,  0, &
                    0,  0,  0,  1,  1, &
                    1,  0, -2, -2,  0, &
                    0,  3,  2, -2,  2, &
                    2,  1,  2,  0,  2, &
                    1,  1,  0,  0,  1, &
                    2,  0,  0,  2,  0, &
                    1,  1,  2,  0,  1, &
                    1,  0,  0, -2, -2, &
                    1,  0, -2,  2,  0, &
                    1,  0, -1,  0, -2, &
                    0,  1,  0, -2,  1, &
                    0,  1,  0,  1,  0, &
                    0,  0,  0,  1, -1, &
                    1,  0, -2,  2, -2, &
                    1, -1,  0,  0, -1, &
                    0,  0,  0,  4,  0, &
                    1, -1,  0,  2,  0, &
                    1,  0,  2,  1,  2, &
                    1,  0,  2, -1,  2, &
                    0,  0,  2,  1,  1, &
                    1,  0,  0, -2,  2, &
                    1,  0, -2,  0,  1, &
                    1,  0, -2, -4, -1, &
                    0,  0,  2,  2,  0, &
                    1,  1,  2, -2,  1, &
                    1,  0, -2,  1, -1, &
                    0,  0,  1,  0,  1, &
                    2,  0, -2, -2, -1, &
                    4,  0,  2,  0,  2, &
                    2, -1,  0,  0,  0, &
                    2,  1,  2, -2,  2, &
                    0,  1,  2,  1,  2, &
                    1,  0,  4, -2,  2, &
                    1,  1,  0,  0, -1, &
                    2,  0,  2,  0,  0, &
                    2,  0, -2, -4, -1, &
                    1,  0, -1,  0,  0, &
                    1,  0,  0,  1,  0, &
                    0,  1,  0,  2,  1, &
                    1,  0, -4,  0, -1, &
                    1,  0,  0, -4, -1, &
                    2,  0,  2,  2,  1, &
                    2,  1,  0,  0,  0, &
                    0,  0,  2, -3,  2, &
                    1,  2,  0, -2,  0, &
                    0,  3,  0,  0,  0, &
                    0,  0,  4,  0,  2, &
                    0,  0,  2, -4,  1, &
                    2,  0,  0, -2, -2, &
                    1,  1, -2, -4, -2, &
                    0,  1,  0, -2, -1, &
                    0,  0,  0,  4,  1, &
                    3,  0,  2, -2,  1, &
                    1,  0,  2,  4,  2, &
                    1,  1, -2,  0, -2, &
                    0,  0,  4, -2,  1, &
                    2, -2,  0, -2,  0, &
                    2,  1,  0, -2, -1, &
                    0,  2,  0, -2,  0, &
                    1,  0,  0, -1,  1, &
                    1,  1,  2,  2,  2, &
                    3,  0,  0,  0, -1, &
                    2,  0,  0, -4, -1, &
                    3,  0,  2,  2,  2, &
                    0,  0,  2,  4,  1, &
                    0,  2, -2, -2, -2, &
                    1, -1,  0, -2, -1, &
                    0,  0,  2, -1,  1, &
                    2,  0,  0,  2,  1, &
                    1, -1, -2,  2, -1, &
                    0,  0,  0,  2, -2, &
                    2,  0,  0, -4,  1, &
                    1,  0,  0, -4,  1, &
                    2,  0,  2, -4,  1, &
                    4,  0,  2, -2,  2, &
                    2,  1, -2,  0, -1, &
                    2,  1, -2, -4, -2, &
                    3,  0,  0, -4,  0, &
                    1, -1,  2,  2,  1, &
                    1, -1, -2,  0, -1, &
                    0,  2,  0,  0,  1, &
                    1,  2, -2, -2, -2, &
                    1,  1,  0, -4,  0, &
                    2,  0,  0, -2,  2, &
                    0,  2,  2, -2,  1, &
                    1,  0,  2,  0, -1, &
                    2,  1,  0, -2,  1, &
                    2, -1, -2,  0, -1, &
                    1, -1, -2, -2, -1, &
                    0,  1, -2,  1, -2, &
                    1,  0, -4,  2, -2, &
                    0,  1,  2,  2,  1, &
                    3,  0,  0,  0,  1, &
                    2, -1,  2,  2,  2, &
                    0,  1, -2, -4, -2, &
                    1,  0, -2, -3, -2, &
                    2,  0,  0,  0,  2, &
                    1, -1,  0, -2, -2, &
                    2,  0, -2,  2, -1, &
                    0,  2, -2,  0, -2, &
                    3,  0, -2,  0, -1, &
                    2, -1,  2,  0,  1, &
                    1,  0, -2, -1, -2, &
                    0,  0,  2,  0,  3, &
                    2,  0, -4,  0, -2, &
                    2,  1,  0, -4,  0, &
                    1,  1, -2,  1, -1, &
                    0,  2,  2,  0,  2, &
                    1, -1,  2, -2,  2, &
                    1, -1,  0, -2,  1, &
                    2,  1,  2,  0,  1, &
                    1,  0,  2, -4,  2, &
                    1,  1, -2,  0, -1, &
                    1,  1,  0,  2,  0, &
                    1,  0,  0, -3,  0, &
                    2,  0,  2, -1,  2, &
                    0,  2,  0,  0, -1, &
                    2, -1,  0, -2,  0, &
                    4,  0,  0,  0,  0, &
                    2,  1, -2, -2, -2, &
                    0,  2, -2,  2,  0, &
                    1,  0,  2,  1,  1, &
                    1,  0, -1,  0, -3, &
                    3, -1,  2,  0,  2, &
                    2,  0,  2, -2,  0, &
                    1, -2,  0,  0,  0, &
                    2,  0,  0,  0, -2, &
                    1,  0,  0,  4,  0, &
                    0,  1,  0,  1,  1, &
                    1,  0,  2,  2,  0, &
                    0,  1,  0,  2, -1, &
                    0,  1,  0,  1, -1, &
                    0,  0,  2, -2,  3, &
                    3,  1,  2,  0,  2, &
                    1,  1,  2,  1,  2, &
                    1,  1, -2,  2, -1, &
                    2, -1,  2, -2,  2, &
                    1, -2,  2,  0,  2, &
                    1,  0,  2, -4,  0, &
                    0,  0,  1,  0,  0, &
                    1,  0,  2, -3,  1, &
                    1, -2,  0, -2,  0, &
                    2,  0,  0,  2, -1, &
                    1,  1,  2, -4,  1, &
                    4,  0,  2,  0,  1, &
                    0,  1,  2,  1,  1, &
                    1,  2,  2, -2,  2, &
                    2,  0,  2,  1,  2, &
                    2,  1,  2, -2,  1, &
                    1,  0,  2, -1,  1, &
                    1,  0,  4, -2,  1, &
                    1, -1,  2, -2,  1, &
                    0,  1,  0, -4,  0, &
                    3,  0, -2, -2, -2, &
                    0,  0,  4, -4,  2, &
                    2,  0, -4, -2, -2, &
                    2, -2,  0, -2, -1, &
                    1,  0,  2, -2, -1, &
                    2,  0, -2, -6, -2, &
                    1,  0, -2,  1, -2, &
                    1,  0, -2,  2,  1, &
                    1, -1,  0,  2, -1, &
                    1,  0, -2,  1,  0, &
                    2, -1,  0, -2,  1, &
                    1, -1,  0,  2,  1, &
                    2,  0, -2, -2,  0, &
                    1,  0,  2, -3,  2, &
                    0,  0,  0,  4, -1, &
                    2, -1,  0,  0,  1, &
                    2,  0,  4, -2,  2, &
                    0,  0,  2,  3,  2, &
                    0,  1,  4, -2,  2, &
                    0,  1, -2,  2,  1, &
                    1,  1,  0,  2,  1, &
                    1,  0,  0,  4,  1, &
                    0,  0,  4,  0,  1, &
                    2,  0,  0, -3,  0, &
                    1,  0,  0, -1, -2, &
                    1, -2, -2, -2, -2, &
                    3,  0,  0,  2,  0, &
                    2,  0,  2, -4,  2, &
                    1,  1, -2, -4, -1, &
                    1,  0, -2, -6, -2, &
                    2, -1,  0,  0, -1, &
                    2, -1,  0,  2,  0, &
                    0,  1,  2, -2, -1, &
                    1,  1,  0,  1,  0, &
                    1,  2,  0, -2, -1, &
                    1,  0,  0,  1, -1, &
                    0,  0,  1,  0,  2, &
                    3,  1,  2, -2,  2, &
                    1,  0, -4, -2, -2, &
                    1,  0,  2,  4,  1, &
                    1, -2,  2,  2,  2, &
                    1, -1, -2, -4, -2, &
                    0,  0,  2, -4,  2, &
                    0,  0,  2, -3,  1, &
                    2,  1, -2,  0,  0, &
                    3,  0, -2, -2, -1, &
                    2,  0,  2,  4,  2, &
                    0,  0,  0,  0,  3, &
                    2, -1, -2, -2, -2, &
                    2,  0,  0, -1,  0, &
                    3,  0,  2, -4,  2, &
                    2,  1,  2,  2,  2, &
                    0,  0,  3,  0,  3, &
                    1,  1,  2,  2,  1, &
                    2,  1,  0,  0, -1, &
                    1,  2,  0, -2,  1, &
                    3,  0,  2,  2,  1, &
                    1, -1, -2,  2, -2, &
                    1,  1,  0, -1,  0, &
                    1,  2,  0,  0,  0, &
                    1,  0,  4,  0,  2, &
                    1, -1,  2,  4,  2, &
                    2,  1,  0,  0,  1, &
                    1,  0,  0,  2,  2, &
                    1, -1, -2,  2,  0, &
                    0,  2, -2, -2, -1, &
                    2,  0, -2,  0,  2, &
                    5,  0,  2,  0,  2, &
                    3,  0, -2, -6, -2, &
                    1, -1,  2, -1,  2, &
                    3,  0,  0, -4, -1, &
                    1,  0,  0,  1,  1, &
                    1,  0, -4,  2, -1, &
                    0,  1,  2, -4,  1, &
                    1,  2,  2,  0,  2, &
                    0,  1,  0, -2, -2, &
                    0,  0,  2, -1,  0, &
                    1,  0,  1,  0,  1, &
                    0,  2,  0, -2,  1, &
                    3,  0,  2,  0,  0, &
                    1,  1, -2,  1,  0, &
                    2,  1, -2, -4, -1, &
                    3, -1,  0,  0,  0, &
                    2, -1, -2,  0,  0, &
                    4,  0,  2, -2,  1, &
                    2,  0, -2,  2,  0, &
                    1,  1,  2, -2,  0, &
                    1,  0, -2,  4, -1, &
                    1,  0, -2, -2,  1, &
                    2,  0,  2, -4,  0, &
                    1,  1,  0, -2, -2, &
                    1,  1, -2, -2,  0, &
                    1,  0,  1, -2,  1, &
                    2, -1, -2, -4, -2, &
                    3,  0, -2,  0, -2, &
                    0,  1, -2, -2,  0, &
                    3,  0,  0, -2, -1, &
                    1,  0, -2, -3, -1, &
                    0,  1,  0, -4, -1, &
                    1, -2,  2, -2,  1, &
                    0,  1, -2,  1, -1, &
                    1, -1,  0,  0,  2, &
                    2,  0,  0,  1,  0, &
                    1, -2,  0,  2,  0, &
                    1,  2, -2, -2, -1, &
                    0,  0,  4, -4,  1, &
                    0,  1,  2,  4,  2, &
                    0,  1, -4,  2, -2, &
                    3,  0, -2,  0,  0, &
                    2, -1,  2,  2,  1, &
                    0,  1, -2, -4, -1, &
                    4,  0,  2,  2,  2, &
                    2,  0, -2, -3, -2, &
                    2,  0,  0, -6,  0, &
                    1,  0,  2,  0,  3, &
                    3,  1,  0,  0,  0, &
                    3,  0,  0, -4,  1, &
                    1, -1,  2,  0,  0, &
                    1, -1,  0, -4,  0, &
                    2,  0, -2,  2, -2, &
                    1,  1,  0, -2,  2, &
                    4,  0,  0, -2,  0, &
                    2,  2,  0, -2,  0, &
                    0,  1,  2,  0,  0, &
                    1,  1,  0, -4,  1, &
                    1,  0,  0, -4, -2, &
                    0,  0,  0,  1,  2, &
                    3,  0,  0,  2,  1, &
                    1,  1,  0, -4, -1, &
                    0,  0,  2,  2, -1, &
                    1,  1,  2,  0,  0, &
                    1, -1,  2, -4,  1, &
                    1,  1,  0,  0,  2, &
                    0,  0,  2,  6,  2, &
                    4,  0, -2, -2, -1, &
                    2,  1,  0, -4, -1, &
                    0,  0,  0,  3,  1, &
                    1, -1, -2,  0,  0, &
                    0,  0,  2,  1,  0, &
                    1,  0,  0,  2, -2, &
                    3, -1,  2,  2,  2, &
                    3, -1,  2, -2,  2, &
                    1,  0,  0, -1,  2, &
                    1, -2,  2, -2,  2, &
                    0,  1,  0,  2,  2, &
                    0,  1, -2, -1, -2, &
                    1,  1, -2,  0,  0, &
                    0,  2,  2, -2,  0, &
                    3, -1, -2, -1, -2, &
                    1,  0,  0, -6,  0, &
                    1,  0, -2, -4,  0, &
                    2,  1,  0, -4,  1, &
                    2,  0,  2,  0, -1, &
                    2,  0, -4,  0, -1, &
                    0,  0,  3,  0,  2, &
                    2,  1, -2, -2, -1, &
                    1, -2,  0,  0,  1, &
                    2, -1,  0, -4,  0, &
                    0,  0,  0,  3,  0, &
                    5,  0,  2, -2,  2, &
                    1,  2, -2, -4, -2, &
                    1,  0,  4, -4,  2, &
                    0,  0,  4, -1,  2, &
                    3,  1,  0, -4,  0, &
                    3,  0,  0, -6,  0, &
                    2,  0,  0,  2,  2, &
                    2, -2,  2,  0,  2, &
                    1,  0,  0, -3,  1, &
                    1, -2, -2,  0, -2, &
                    1, -1, -2, -3, -2, &
                    0,  0,  2, -2, -2, &
                    2,  0, -2, -4,  0, &
                    1,  0, -4,  0,  0, &
                    0,  1,  0, -1,  0, &
                    4,  0,  0,  0, -1, &
                    3,  0,  2, -1,  2, &
                    3, -1,  2,  0,  1, &
                    2,  0,  2, -1,  1, &
                    1,  2,  2, -2,  1, &
                    1,  1,  0,  2, -1, &
                    0,  2,  2,  0,  1, &
                    3,  1,  2,  0,  1, &
                    1,  1,  2,  1,  1, &
                    1,  1,  0, -1,  1, &
                    1, -2,  0, -2, -1, &
                    4,  0,  0, -4,  0, &
                    2,  1,  0,  2,  0, &
                    1, -1,  0,  4,  0, &
                    0,  1,  0, -2,  2, &
                    0,  0,  2,  0, -2, &
                    1,  0, -1,  0,  1, &
                    3,  0,  2, -2,  0, &
                    2,  0,  2,  2,  0, &
                    1,  2,  0, -4,  0, &
                    1, -1,  0, -3,  0, &
                    0,  1,  0,  4,  0, &
                    0,  1, -2,  0,  0, &
                    2,  2,  2, -2,  2, &
                    0,  0,  0,  1, -2, &
                    0,  2, -2,  0, -1, &
                    4,  0,  2, -4,  2, &
                    2,  0, -4,  2, -2, &
                    2, -1, -2,  0, -2, &
                    1,  1,  4, -2,  2, &
                    1,  1,  2, -4,  2, &
                    1,  0,  2,  3,  2, &
                    1,  0,  0,  4, -1, &
                    0,  0,  0,  4,  2, &
                    2,  0,  0,  4,  0, &
                    1,  1, -2,  2,  0, &
                    2,  1,  2,  1,  2, &
                    2,  1,  2, -4,  1, &
                    2,  0,  2,  1,  1, &
                    2,  0, -4, -2, -1, &
                    2,  0, -2, -6, -1, &
                    2, -1,  2, -1,  2, &
                    1, -2,  2,  0,  1, &
                    1, -2,  0, -2,  1, &
                    1, -1,  0, -4, -1, &
                    0,  2,  2,  2,  2, &
                    0,  2, -2, -4, -2, &
                    0,  1,  2,  3,  2, &
                    0,  1,  0, -4,  1, &
                    3,  0,  0, -2,  1, &
                    2,  1, -2,  0,  1, &
                    2,  0,  4, -2,  1, &
                    2,  0,  0, -3, -1, &
                    2, -2,  0, -2,  1, &
                    2, -1,  2, -2,  1, &
                    1,  0,  0, -6, -1, &
                    1, -2,  0,  0, -1, &
                    1, -2, -2, -2, -1, &
                    0,  1,  4, -2,  1, &
                    0,  0,  2,  3,  1, &
                    2, -1,  0, -1,  0, &
                    1,  3,  0, -2,  0, &
                    0,  3,  0, -2,  0, &
                    2, -2,  2, -2,  2, &
                    0,  0,  4, -2,  0, &
                    4, -1,  2,  0,  2, &
                    2,  2, -2, -4, -2, &
                    4,  1,  2,  0,  2, &
                    4, -1, -2, -2, -2, &
                    2,  1,  0, -2, -2, &
                    2,  1, -2, -6, -2, &
                    2,  0,  0, -1,  1, &
                    2, -1, -2,  2, -1, &
                    1,  1, -2,  2, -2, &
                    1,  1, -2, -3, -2, &
                    1,  0,  3,  0,  3, &
                    1,  0, -2,  1,  1, &
                    1,  0, -2,  0,  2, &
                    1, -1,  2,  1,  2, &
                    1, -1,  0,  0, -2, &
                    1, -1, -4,  2, -2, &
                    0,  3, -2, -2, -2, &
                    0,  1,  0,  4,  1, &
                    0,  0,  4,  2,  2, &
                    3,  0, -2, -2,  0, &
                    2, -2,  0,  0,  0, &
                    1,  1,  2, -4,  0, &
                    1,  1,  0, -3,  0, &
                    1,  0,  2, -3,  0, &
                    1, -1,  2, -2,  0, &
                    0,  2,  0,  2,  0, &
                    0,  0,  2,  4,  0, &
                    1,  0,  1,  0,  0, &
                    3,  1,  2, -2,  1, &
                    3,  0,  4, -2,  2, &
                    3,  0,  2,  1,  2, &
                    3,  0,  0,  2, -1, &
                    3,  0,  0,  0,  2, &
                    3,  0, -2,  2, -1, &
                    2,  0,  4, -4,  2, &
                    2,  0,  2, -3,  2, &
                    2,  0,  0,  4,  1, &
                    2,  0,  0, -3,  1, &
                    2,  0, -4,  2, -1, &
                    2,  0, -2, -2,  1, &
                    2, -2,  2,  2,  2, &
                    2, -2,  0, -2, -2, &
                    2, -1,  0,  2,  1, &
                    2, -1,  0,  2, -1, &
                    1,  1,  2,  4,  2, &
                    1,  1,  0,  1,  1, &
                    1,  1,  0,  1, -1, &
                    1,  1, -2, -6, -2, &
                    1,  0,  0, -3, -1, &
                    1,  0, -4, -2, -1, &
                    1,  0, -2, -6, -1, &
                    1, -2,  2,  2,  1, &
                    1, -2, -2,  2, -1, &
                    1, -1, -2, -4, -1, &
                    0,  2,  0,  0,  2, &
                    0,  1,  2, -4,  2, &
                    0,  1, -2,  4, -1, &
                    5,  0,  0,  0,  0, &
                    3,  0,  0, -3,  0, &
                    2,  2,  0, -4,  0, &
                    1, -1,  2,  2,  0, &
                    0,  1,  0,  3,  0, &
                    4,  0, -2,  0, -1, &
                    3,  0, -2, -6, -1, &
                    3,  0, -2, -1, -1, &
                    2,  1,  2,  2,  1, &
                    2,  1,  0,  2,  1, &
                    2,  0,  2,  4,  1, &
                    2,  0,  2, -6,  1, &
                    2,  0,  2, -2, -1, &
                    2,  0,  0, -6, -1, &
                    2, -1, -2, -2, -1, &
                    1,  2,  2,  0,  1, &
                    1,  2,  0,  0,  1, &
                    1,  0,  4,  0,  1, &
                    1,  0,  2, -6,  1, &
                    1,  0,  2, -4, -1, &
                    1,  0, -1, -2, -1, &
                    1, -1,  2,  4,  1, &
                    1, -1,  2, -3,  1, &
                    1, -1,  0,  4,  1, &
                    1, -1, -2,  1, -1, &
                    0,  1,  2, -2,  3, &
                    3,  0,  0, -2,  0, &
                    1,  0,  1, -2,  0, &
                    0,  2,  0, -4,  0, &
                    0,  0,  2, -4,  0, &
                    0,  0,  1, -1,  0, &
                    0,  0,  0,  6,  0, &
                    0,  2,  0,  0, -2, &
                    0,  1, -2,  2, -3, &
                    4,  0,  0,  2,  0, &
                    3,  0,  0, -1,  0, &
                    3, -1,  0,  2,  0, &
                    2,  1,  0,  1,  0, &
                    2,  1,  0, -6,  0, &
                    2, -1,  2,  0,  0, &
                    1,  0,  2, -1,  0, &
                    1, -1,  0,  1,  0, &
                    1, -1, -2, -2,  0, &
                    0,  1,  2,  2,  0, &
                    0,  0,  2, -3,  0, &
                    2,  2,  0, -2, -1, &
                    2, -1, -2,  0,  1, &
                    1,  2,  2, -4,  1, &
                    0,  1,  4, -4,  2, &
                    0,  0,  0,  3,  2, &
                    5,  0,  2,  0,  1, &
                    4,  1,  2, -2,  2, &
                    4,  0, -2, -2,  0, &
                    3,  1,  2,  2,  2, &
                    3,  1,  0, -2,  0, &
                    3,  1, -2, -6, -2, &
                    3,  0,  0,  0, -2, &
                    3,  0, -2, -4, -2, &
                    3, -1,  0, -3,  0, &
                    3, -1,  0, -2,  0, &
                    2,  1,  2,  0,  0, &
                    2,  1,  2, -4,  2, &
                    2,  1,  2, -2,  0, &
                    2,  1,  0, -3,  0, &
                    2,  1, -2,  0, -2, &
                    2,  0,  0, -4,  2, &
                    2,  0,  0, -4, -2, &
                    2,  0, -2, -5, -2, &
                    2, -1,  2,  4,  2, &
                    2, -1,  0, -2,  2, &
                    1,  3, -2, -2, -2, &
                    1,  1,  0,  0, -2, &
                    1,  1,  0, -6,  0, &
                    1,  1, -2,  1, -2, &
                    1,  1, -2, -1, -2, &
                    1,  0,  2,  1,  0, &
                    1,  0,  0,  3,  0, &
                    1,  0,  0, -4,  2, &
                    1,  0, -2,  4, -2, &
                    1, -2,  0, -1,  0, &
                    0,  1, -4,  2, -1, &
                    1,  0, -2,  0, -3, &
                    0,  0,  4, -4,  4  ], [5,nfls])
    !  Fundamental-argument multipliers:  planetary terms.
    integer,dimension(14,nfpl),parameter :: mfapl = reshape( [ &
       0,  0,  1, -1,  1,  0,  0, -1,  0, -2,  5,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  0,  0,  2, -5,  0,  0, -1, &
       0,  0,  0,  0,  0,  0,  3, -5,  0,  0,  0,  0,  0, -2, &
       0,  0,  1, -1,  1,  0, -8, 12,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  0,  4, -8,  3,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  1, -1,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  8,-16,  4,  5,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  1,  0, -1,  0,  0,  0,  0, &
       0,  0,  0,  0,  1,  0,  0, -1,  2,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  8,-13,  0,  0,  0,  0,  0, -1, &
       0,  0,  1, -1,  1,  0,  0, -1,  0,  2, -5,  0,  0,  0, &
       0,  0,  2, -2,  1,  0, -5,  6,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  4, -6,  0,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  0,  3,  0, -1,  0,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  0,  2, -8,  3,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  2, -4,  0,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  0,  6, -8,  3,  0,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  0,  1, -2,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  2, -3,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  2, -2,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  2,  0,  0,  0,  0,  0,  0,  2, &
       0,  0,  0,  0,  1,  0,  0, -4,  8, -3,  0,  0,  0,  0, &
       0,  0,  0,  0,  1,  0,  0,  4, -8,  3,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  0,  0,  2, -5,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  1,  1,  0,  0,  0,  0,  0,  2, &
       0,  0,  1, -1,  1,  0,  0,  0, -2,  0,  0,  0,  0,  0, &
       2,  0,  0, -2, -1,  0,  0, -2,  0,  2,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0,  0,  1, &
       2,  0,  0, -2,  0,  0,  0, -2,  0,  2,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  2,  0, -2,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  8,-13,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  1,  0,  1,  0,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  5, -8,  0,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  0,  2, -2,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  0,  0,  2, -5,  0,  0,  1, &
       2,  0,  0, -2,  0,  0,  0, -2,  0,  3,  0,  0,  0,  0, &
       0,  0,  1, -1,  1,  0,  0, -1,  0, -1,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  3, -4,  0,  0,  0,  0,  0,  0, &
       0,  0,  1, -1,  1,  0,  0, -1,  0,  0, -1,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  1,  0, -2,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  5, -7,  0,  0,  0,  0,  0, -2, &
       0,  0,  1, -1,  0,  0,  0,  0, -2,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  4,  0, -2,  0,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  8,-13,  0,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  2, -1,  0,  0,  0,  0,  0,  2, &
       1,  0,  0,  0,  0,  0,-18, 16,  0,  0,  0,  0,  0,  0, &
       0,  0,  1, -1,  1,  0,  0, -1,  0,  2,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  2,  0,  1,  0,  0,  0,  2, &
       0,  0,  1, -1,  1,  0, -5,  7,  0,  0,  0,  0,  0,  0, &
       1,  0,  0,  0,  0,  0,-10,  3,  0,  0,  0,  0,  0,  0, &
       0,  0,  2, -2,  0,  0, -5,  6,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  2,  0, -1,  0,  0,  0,  2, &
       1,  0,  2,  0,  2,  0,  0,  1,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  4, -2,  0,  0,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0,  1, &
       1,  0, -2,  0, -2,  0,  0,  4, -8,  3,  0,  0,  0,  0, &
       0,  0,  1, -1,  1,  0,  0, -1,  0,  0,  2,  0,  0,  0, &
       0,  0,  2, -2,  1,  0, -3,  3,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  0,  8,-16,  4,  5,  0,  0, -2, &
       0,  0,  1, -1,  1,  0,  0,  3, -8,  3,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  8,-11,  0,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  0,  0,  0,  3,  0,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  0,  8,-16,  4,  5,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  1, -1,  0,  0,  0,  0,  0, -1, &
       0,  0,  0,  0,  0,  0,  4, -6,  0,  0,  0,  0,  0, -1, &
       0,  0,  0,  0,  0,  0,  0,  1,  0, -3,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  0,  2, -4,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  6, -8,  0,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  3, -2,  0,  0,  0,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  8,-15,  0,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  2, -5,  0,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  1, -3,  0,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  0,  3,  0, -2,  0,  0,  0,  2, &
       0,  0,  1, -1,  1,  0,  0, -5,  8, -3,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  1,  2,  0,  0,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  0,  3, -2,  0,  0,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  3, -5,  0,  0,  0,  0,  0,  0, &
       2,  0,  0, -2,  1,  0,  0, -2,  0,  3,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  5, -8,  0,  0,  0,  0,  0, -1, &
       2,  0,  0, -2,  0,  0, -3,  3,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  1,  0,  8,-13,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  1,  0,  0,  0,  0, -2,  5,  0,  0,  0, &
       1,  0,  0, -1,  0,  0, -3,  4,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  2,  0,  0,  0,  0,  0,  2, &
       1,  0,  0,  0, -1,  0,-18, 16,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  1,  0,  0,  0,  0,  2, -5,  0,  0,  0, &
       0,  0,  0,  0,  1,  0,  0,  0,  0,  1,  0,  0,  0,  0, &
       1,  0,  0, -2,  0,  0, 19,-21,  3,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  1,  0, -8, 13,  0,  0,  0,  0,  0,  0, &
       0,  0,  1, -1,  1,  0,  0, -1,  0,  0,  1,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  7, -9,  0,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0,  0,  0,  2, &
       1,  0,  0,  0,  1,  0,-18, 16,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  2, -4,  0,  0,  0,  0,  0, -1, &
       0,  0,  0,  0,  0,  0,  0,  6,-16,  4,  5,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  4, -7,  0,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  3, -7,  0,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  2, -2,  0,  0,  0,  0,  0, -1, &
       0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  1, &
       2,  0,  0, -2,  1,  0,  0, -2,  0,  2,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0, -1, &
       0,  0,  0,  0,  0,  0,  0,  3, -4,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  1, -2,  0,  0,  0,  0,  0,  0, &
       2,  0,  0, -2, -1,  0,  0, -2,  0,  3,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  3, -3,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  2,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  1,  0,  2,  0,  0,  0,  2, &
       0,  0,  0,  0,  1,  0,  0,  1, -2,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  2, &
       0,  0,  2, -2,  1,  0,  0, -2,  0,  2,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  2,  0, -3,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  3, -5,  0,  0,  0,  0,  0, -1, &
       0,  0,  0,  0,  0,  0,  3, -3,  0,  0,  0,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  4, -4,  0,  0,  0,  0,  0,  0, &
       0,  0,  1, -1,  0,  0,  0, -1,  0, -1,  0,  0,  0,  0, &
       2,  0,  0, -2,  0,  0, -6,  8,  0,  0,  0,  0,  0,  0, &
       0,  0,  1, -1,  1,  0,  0, -2,  2,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  1, &
       0,  0,  1, -1,  1,  0,  0, -1,  0,  1,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  1, -2,  0,  0,  0,  0, -1, &
       0,  0,  0,  0,  0,  0,  0,  2, -3,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  2, -4,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  0,  1,  0,  0, -1,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  8,-10,  0,  0,  0,  0,  0, -2, &
       0,  0,  1, -1,  1,  0, -3,  4,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  6, -9,  0,  0,  0,  0,  0, -2, &
       1,  0,  0, -1,  1,  0,  0, -1,  0,  2,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  5, -7,  0,  0,  0,  0,  0, -1, &
       0,  0,  0,  0,  0,  0,  5, -5,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0, -1, &
       0,  0,  0,  0,  0,  0,  3, -3,  0,  0,  0,  0,  0, -1, &
       0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  0,  4,  0,  0,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  0,  4,  0, -3,  0,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  1, -1,  0,  0,  0,  0,  0,  1, &
       0,  0,  0,  0,  0,  0,  0,  2,  0,  0,  0,  0,  0,  1, &
       0,  0,  0,  0,  1,  0,  2, -3,  0,  0,  0,  0,  0,  0, &
       1,  0,  0, -1,  0,  0,  0, -1,  0,  1,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  1, -3,  0,  0,  0,  0,  0, -1, &
       0,  0,  0,  0,  0,  0,  0,  5, -4,  0,  0,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  0,  4, -4,  0,  0,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  9,-11,  0,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  2, -3,  0,  0,  0,  0,  0, -1, &
       0,  0,  0,  0,  0,  0,  0,  8,-15,  0,  0,  0,  0,  0, &
       0,  0,  1, -1,  1,  0, -4,  5,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  4, -6,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  4,  0, -1,  0,  0,  0,  2, &
       1,  0,  0, -1,  1,  0, -3,  4,  0,  0,  0,  0,  0,  0, &
       0,  0,  1,  1,  1,  0,  0,  1,  0,  0,  0,  0,  0,  0, &
       0,  0,  1, -1,  1,  0,  0, -1,  0, -4, 10,  0,  0,  0, &
       0,  0,  0,  0,  1,  0,  1, -1,  0,  0,  0,  0,  0,  0, &
       0,  0,  1, -1,  0,  0,  0, -1,  0,  0, -1,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  1,  0, -3,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  3, -1,  0,  0,  0,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  0,  1,  0, -4,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  0,  0,  0,  2, -5,  0,  0, -2, &
       0,  0,  2, -2,  1,  0, -4,  4,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  3,  0,  0, -1,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  0,  4, -3,  0,  0,  0,  0,  2, &
       0,  0,  1, -1,  1,  0,  0, -1,  0,  0,  0,  0,  2,  0, &
       0,  0,  0,  0,  0,  0,  4, -4,  0,  0,  0,  0,  0, -1, &
       0,  0,  0,  0,  0,  0,  0,  2, -4,  0,  0,  0,  0, -1, &
       0,  0,  0,  0,  0,  0,  5, -8,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  1, -2,  0,  0,  0,  0,  1, &
       0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  1,  0,  0,  0, &
       0,  0,  2, -2,  1,  0,  0, -9, 13,  0,  0,  0,  0,  0, &
       2,  0,  2,  0,  2,  0,  0,  2,  0, -3,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  3, -6,  0,  0,  0,  0,  0, -2, &
       0,  0,  1, -1,  2,  0,  0, -1,  0,  0,  2,  0,  0,  0, &
       1,  0,  0, -1, -1,  0, -3,  4,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  3, -6,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  6, -6,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  0,  0,  3,  0,  0,  0,  1, &
       1,  0,  2,  0,  1,  0,  0, -2,  0,  3,  0,  0,  0,  0, &
       1,  0, -2,  0, -1,  0,  0, -1,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  1,  0,  0, -2,  4,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  3, -5,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  2,  1,  0,  0,  0,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  1,  1,  0,  0,  0,  0,  0,  1, &
       0,  0,  2,  0,  2,  0,  0,  1,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  1, -8,  3,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  6,-10,  0,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  0,  7, -8,  3,  0,  0,  0,  2, &
       0,  0,  0,  0,  1,  0, -3,  5,  0,  0,  0,  0,  0,  0, &
       0,  0,  1, -1,  1,  0, -1,  0,  0,  0,  0,  0,  0,  0, &
       0,  0,  1, -1,  0,  0, -5,  7,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  2,  0, -2,  0,  0,  0,  1, &
       0,  0,  0,  0,  0,  0,  0,  2,  0, -1,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  7,-10,  0,  0,  0,  0,  0, -2, &
       1,  0,  0, -2,  0,  0,  0, -2,  0,  2,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  1,  0,  2, -5,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  6, -8,  0,  0,  0,  0,  0, -1, &
       0,  0,  1, -1,  1,  0,  0, -9, 15,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  1,  0, -2,  3,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  1,  0, -1,  1,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  3, -6,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  1, -4,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  0,  0,  3,  0,  0,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  0,  2,  0,  0, -1,  0,  0,  2, &
       2,  0,  0, -2,  1,  0, -6,  8,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  5, -5,  0,  0,  0,  0,  0, -1, &
       0,  0,  1, -1,  1,  0,  3, -6,  0,  0,  0,  0,  0,  0, &
       0,  0,  1, -1,  1,  0, -2,  2,  0,  0,  0,  0,  0,  0, &
       0,  0,  1, -1,  1,  0,  8,-14,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  1,  0,  0,  8,-15,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  4, -6,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  7, -7,  0,  0,  0,  0,  0,  0, &
       2,  0,  0, -2,  1,  0, -3,  3,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  3, -1,  0,  0,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  0,  2,  0,  0,  1,  0,  0,  2, &
       2,  0, -1, -1,  0,  0,  0,  3, -7,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  4, -7,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  0,  3, -3,  0,  0,  0,  0,  0, &
       0,  0,  1, -1,  1,  0,  0, -3,  4,  0,  0,  0,  0,  0, &
       2,  0,  0, -2,  0,  0,  0, -6,  8,  0,  0,  0,  0,  0, &
       2,  0,  0, -2,  0,  0,  0, -5,  6,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  1,  0,  0,  0,  0, -1,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  2,  0,  0,  0,  0,  0,  0,  1, &
       0,  0,  0,  0,  0,  0,  2,  1,  0,  0,  0,  0,  0,  1, &
       0,  0,  0,  0,  0,  0,  1,  2,  0,  0,  0,  0,  0,  2, &
       0,  0,  0,  0,  1,  0,  0,  1,  0, -1,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  1, -1,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  3, -9,  4,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  0,  3, -5,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  0,  2,  0, -4,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  1, &
       0,  0,  0,  0,  0,  0,  7,-11,  0,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  3, -5,  4,  0,  0,  0,  0,  2, &
       0,  0,  1, -1,  0,  0,  0, -1,  0, -1,  1,  0,  0,  0, &
       2,  0,  0,  0,  0,  0,  0, -2,  0,  3,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  8,-15,  0,  0,  0,  0, -2, &
       0,  0,  1, -1,  2,  0,  0, -2,  2,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  3,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  6, -6,  0,  0,  0,  0,  0, -1, &
       0,  0,  1, -1,  1,  0,  0, -1,  0, -1,  1,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  2, -2,  0,  0,  0,  0,  0,  1, &
       0,  0,  0,  0,  0,  0,  0,  4, -7,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  3, -8,  3,  0,  0,  0,  0, &
       0,  0,  1, -1,  1,  0,  2, -4,  0, -3,  0,  0,  0,  0, &
       0,  0,  0,  0,  1,  0,  3, -5,  0,  2,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  3,  0, -3,  0,  0,  0,  2, &
       0,  0,  2, -2,  2,  0, -8, 11,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  5, -8,  3,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  1,  0,  0, -2,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  1,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  0,  5, -9,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  0,  5, -5,  0,  0,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  7, -9,  0,  0,  0,  0,  0, -1, &
       0,  0,  0,  0,  0,  0,  4, -7,  0,  0,  0,  0,  0, -1, &
       0,  0,  0,  0,  0,  0,  2, -1,  0,  0,  0,  0,  0,  0, &
       1,  0, -2, -2, -2,  0,  0, -2,  0,  2,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  1,  1,  0,  0,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  0,  2,  0, -2,  5,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  3, -3,  0,  0,  0,  0,  0,  1, &
       0,  0,  0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  0,  2,  0,  2, -5,  0,  0,  2, &
       2,  0,  0, -2, -1,  0,  0, -2,  0,  0,  5,  0,  0,  0, &
       2,  0,  0, -2, -1,  0, -6,  8,  0,  0,  0,  0,  0,  0, &
       1,  0,  0, -2,  0,  0, -3,  3,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  8, -8,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  3,  0,  2, -5,  0,  0,  2, &
       0,  0,  0,  0,  1,  0,  3, -7,  4,  0,  0,  0,  0,  0, &
       0,  0,  2, -2,  1,  0, -2,  2,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  1,  0,  0, -1,  0,  1,  0,  0,  0,  0, &
       0,  0,  1, -1,  0,  0,  0, -1,  0, -2,  5,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  3,  0, -3,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  3, -1,  0,  0,  0,  0,  0,  1, &
       0,  0,  0,  0,  0,  0,  2, -3,  0,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  0, 11,  0,  0,  0,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  0,  6,-15,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  0,  3,  0,  1,  0,  0,  0,  2, &
       1,  0,  0, -1,  0,  0,  0, -3,  4,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  1,  0, -3,  7, -4,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  5,  0, -2,  0,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  3, -5,  0,  0,  0,  0,  0,  1, &
       0,  0,  2, -2,  2,  0, -5,  6,  0,  0,  0,  0,  0,  0, &
       0,  0,  2, -2,  2,  0, -3,  3,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  3,  0,  0,  0,  0,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  4, -4,  0,  0,  0,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  0,  4, -8,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  0,  4, -5,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  5, -7,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  6,-11,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  0,  1, -3,  0,  0,  0,  0, -2, &
       0,  0,  1, -1,  1,  0,  0, -1,  0,  3,  0,  0,  0,  0, &
       0,  0,  1, -1,  0,  0,  0, -1,  0,  2,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  1, -2,  0,  0,  0,  0,  0,  1, &
       0,  0,  0,  0,  0,  0,  9,-12,  0,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  4, -4,  0,  0,  0,  0,  0,  1, &
       0,  0,  1, -1,  0,  0, -8, 12,  0,  0,  0,  0,  0,  0, &
       0,  0,  1, -1,  1,  0, -2,  3,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  7, -7,  0,  0,  0,  0,  0, -1, &
       0,  0,  0,  0,  0,  0,  0,  3, -6,  0,  0,  0,  0, -1, &
       0,  0,  0,  0,  0,  0,  0,  6, -6,  0,  0,  0,  0,  2, &
       0,  0,  0,  0,  0,  1,  0, -4,  0,  0,  0,  0,  0, -2, &
       0,  0,  1, -1,  1,  0,  0,  1,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  6, -9,  0,  0,  0,  0,  0, -1, &
       0,  0,  1, -1, -1,  0,  0,  0, -2,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  1, -5,  0,  0,  0,  0, -2, &
       2,  0,  0, -2,  0,  0,  0, -2,  0,  3, -1,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  2,  0,  0, -2,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  5, -9,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  5, -6,  0,  0,  0,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  9, -9,  0,  0,  0,  0,  0, -1, &
       0,  0,  1, -1,  1,  0,  0, -1,  0,  0,  3,  0,  0,  0, &
       0,  0,  0,  0,  1,  0,  0,  2, -4,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  5, -3,  0,  0,  0,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  3,  0,  0,  1, &
       0,  0,  1, -1,  2,  0,  0, -1,  0,  2,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  5, -9,  0,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  0,  5, -3,  0,  0,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  0,  0,  0,  4,  0,  0,  0,  2, &
       0,  0,  2,  0,  2,  0,  0,  4, -8,  3,  0,  0,  0,  0, &
       0,  0,  2,  0,  2,  0,  0, -4,  8, -3,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  5,  0, -3,  0,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  0,  1,  0,  1,  0,  0,  0,  0, &
       2,  0, -1, -1, -1,  0,  0, -1,  0,  3,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  4, -3,  0,  0,  0,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  4, -2,  0,  0,  0,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  5,-10,  0,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  8,-13,  0,  0,  0,  0,  0,  1, &
       0,  0,  2, -2,  1, -1,  0,  2,  0,  0,  0,  0,  0,  0, &
       0,  0,  1, -1,  1,  0,  0, -1,  0,  0,  0,  2,  0,  0, &
       0,  0,  0,  0,  1,  0,  3, -5,  0,  0,  0,  0,  0,  0, &
       1,  0,  0, -2,  0,  0,  0, -2,  0,  3,  0,  0,  0,  0, &
       0,  0,  2, -2,  0,  0, -3,  3,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  9, -9,  0,  0,  0,  0,  0,  0, &
       0,  0,  2,  0,  2,  0,  1, -1,  0,  0,  0,  0,  0,  0, &
       0,  0,  2, -2,  1,  0,  0, -8, 11,  0,  0,  0,  0,  0, &
       0,  0,  2, -2,  1,  0,  0, -2,  0,  0,  2,  0,  0,  0, &
       0,  0,  1, -1,  1,  0,  0, -1,  0, -1,  2,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  5, -5,  0,  0,  0,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  2, -6,  0,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  0,  8,-15,  0,  0,  0,  0, -1, &
       0,  0,  0,  0,  0,  0,  0,  5, -2,  0,  0,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  0,  7,-13,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  0,  3,  0, -2,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  1,  0,  3,  0,  0,  0,  2, &
       0,  0,  2, -2,  1,  0,  0, -2,  0,  3,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  8, -8,  0,  0,  0,  0,  0, -1, &
       0,  0,  0,  0,  0,  0,  8,-10,  0,  0,  0,  0,  0, -1, &
       0,  0,  0,  0,  0,  0,  4, -2,  0,  0,  0,  0,  0,  1, &
       0,  0,  0,  0,  0,  0,  3, -6,  0,  0,  0,  0,  0, -1, &
       0,  0,  0,  0,  0,  0,  3, -4,  0,  0,  0,  0,  0, -1, &
       0,  0,  0,  0,  0,  0,  0,  0,  0,  2, -5,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  0,  2,  0, -4,  0,  0,  0,  0, &
       2,  0,  0, -2, -1,  0,  0, -5,  6,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  2, -5,  0,  0,  0,  0, -2, &
       2,  0, -1, -1, -1,  0,  0,  3, -7,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  5, -8,  0,  0,  0,  0,  0, &
       0,  0,  2,  0,  2,  0, -1,  1,  0,  0,  0,  0,  0,  0, &
       2,  0,  0, -2,  0,  0,  0, -2,  0,  4, -3,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  6,-11,  0,  0,  0,  0,  0, &
       2,  0,  0, -2,  1,  0,  0, -6,  8,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  4, -8,  1,  5,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  0,  6, -5,  0,  0,  0,  0,  2, &
       1,  0, -2, -2, -2,  0, -3,  3,  0,  0,  0,  0,  0,  0, &
       0,  0,  1, -1,  2,  0,  0,  0, -2,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  2,  0,  0,  4, -8,  3,  0,  0,  0,  0, &
       0,  0,  0,  0,  2,  0,  0, -4,  8, -3,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  1, &
       0,  0,  0,  0,  0,  0,  0,  6, -7,  0,  0,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  0,  4,  0,  0, -2,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  0,  3,  0,  0, -2,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  0,  1,  0, -1,  0,  0,  0,  1, &
       0,  0,  0,  0,  0,  0,  0,  1, -6,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  0,  0,  0,  4, -5,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  2, &
       0,  0,  0,  0,  0,  0,  3, -5,  0,  2,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  7,-13,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  2,  0, -2,  0,  0,  0,  2, &
       0,  0,  1, -1,  0,  0,  0, -1,  0,  0,  2,  0,  0,  0, &
       0,  0,  0,  0,  1,  0,  0, -8, 15,  0,  0,  0,  0,  0, &
       2,  0,  0, -2, -2,  0, -3,  3,  0,  0,  0,  0,  0,  0, &
       2,  0, -1, -1, -1,  0,  0, -1,  0,  2,  0,  0,  0,  0, &
       1,  0,  2, -2,  2,  0,  0, -2,  0,  2,  0,  0,  0,  0, &
       1,  0, -1,  1, -1,  0,-18, 17,  0,  0,  0,  0,  0,  0, &
       0,  0,  2,  0,  2,  0,  0,  1,  0, -1,  0,  0,  0,  0, &
       0,  0,  2,  0,  2,  0,  0, -1,  0,  1,  0,  0,  0,  0, &
       0,  0,  2, -2, -1,  0, -5,  6,  0,  0,  0,  0,  0,  0, &
       0,  0,  1, -1,  2,  0,  0, -1,  0,  1,  0,  0,  0,  0, &
       0,  0,  0,  0,  1,  0,  2, -2,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  8,-16,  0,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  5,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  2, &
       0,  0,  0,  0,  2,  0,  0, -1,  2,  0,  0,  0,  0,  0, &
       2,  0, -1, -1, -2,  0,  0, -1,  0,  2,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  6,-10,  0,  0,  0,  0,  0, -1, &
       0,  0,  1, -1,  1,  0,  0, -1,  0, -2,  4,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  2,  2,  0,  0,  0,  0,  2, &
       2,  0,  0, -2, -1,  0,  0, -2,  0,  4, -5,  0,  0,  0, &
       2,  0,  0, -2, -1,  0, -3,  3,  0,  0,  0,  0,  0,  0, &
       2,  0, -1, -1, -1,  0,  0, -1,  0,  0,  0,  0,  0,  0, &
       1,  0,  1, -1,  1,  0,  0, -1,  0,  0,  0,  0,  0,  0, &
       1,  0,  0, -1, -1,  0,  0, -2,  2,  0,  0,  0,  0,  0, &
       1,  0, -1, -1, -1,  0, 20,-20,  0,  0,  0,  0,  0,  0, &
       0,  0,  2, -2,  1,  0,  0, -1,  0,  1,  0,  0,  0,  0, &
       0,  0,  1, -1,  1,  0,  1, -2,  0,  0,  0,  0,  0,  0, &
       0,  0,  1, -1,  1,  0, -2,  1,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  1,  0,  5, -8,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  1,  0,  0,  0,  0,  0, -1,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  9,-11,  0,  0,  0,  0,  0, -1, &
       0,  0,  0,  0,  0,  0,  5, -3,  0,  0,  0,  0,  0,  1, &
       0,  0,  0,  0,  0,  0,  0,  1,  0, -3,  0,  0,  0, -1, &
       0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  1, &
       0,  0,  0,  0,  0,  0,  6, -7,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  3, -2,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  1, -2,  0,  0,  0,  0,  0, -2, &
       0,  0,  1, -1,  1,  0,  0, -1,  0,  0, -2,  0,  0,  0, &
       0,  0,  1, -1,  2,  0,  0, -1,  0, -2,  5,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  5, -7,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  1, -3,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  5, -8,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  0,  2, -6,  0,  0,  0,  0, -2, &
       1,  0,  0, -2,  0,  0, 20,-21,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  8,-12,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  5, -6,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  4, -4,  0,  0,  0,  0,  0, &
       0,  0,  1, -1,  2,  0,  0, -1,  0, -1,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  8,-12,  0,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  0,  9,-17,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  5, -6,  0,  0,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  0,  4, -8,  1,  5,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  0,  4, -6,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  0,  2, -7,  0,  0,  0,  0, -2, &
       1,  0,  0, -1,  1,  0,  0, -3,  4,  0,  0,  0,  0,  0, &
       1,  0, -2,  0, -2,  0,-10,  3,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  1,  0,  0, -9, 17,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  1, -4,  0,  0,  0,  0,  0, -2, &
       1,  0, -2, -2, -2,  0,  0, -2,  0,  3,  0,  0,  0,  0, &
       1,  0, -1,  1, -1,  0,  0,  1,  0,  0,  0,  0,  0,  0, &
       0,  0,  2, -2,  2,  0,  0, -2,  0,  2,  0,  0,  0,  0, &
       0,  0,  1, -1,  2,  0,  0, -1,  0,  0,  1,  0,  0,  0, &
       0,  0,  1, -1,  2,  0, -5,  7,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  1,  0,  0,  2, -2,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  4, -5,  0,  0,  0,  0,  0, -1, &
       0,  0,  0,  0,  0,  0,  3, -4,  0,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  2, -4,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  5,-10,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  0,  4,  0, -4,  0,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  0,  2,  0, -5,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  0,  1,  0, -5,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  0,  1,  0, -2,  5,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  0,  1,  0, -2,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  2, -3,  0,  0,  0,  0,  0,  1, &
       1,  0,  0, -2,  0,  0,  0,  1,  0, -1,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  3, -7,  4,  0,  0,  0,  0,  0, &
       2,  0,  2,  0,  1,  0,  0,  1,  0,  0,  0,  0,  0,  0, &
       0,  0,  1, -1, -1,  0,  0, -1,  0, -1,  0,  0,  0,  0, &
       0,  0,  0,  0,  1,  0,  0,  1,  0, -2,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  6,-10,  0,  0,  0,  0, -2, &
       1,  0,  0, -1,  1,  0,  0, -1,  0,  1,  0,  0,  0,  0, &
       0,  0,  2, -2,  1,  0,  0,  4, -8,  3,  0,  0,  0,  0, &
       0,  0,  2, -2,  1,  0,  0,  1,  0, -1,  0,  0,  0,  0, &
       0,  0,  2, -2,  1,  0,  0, -4,  8, -3,  0,  0,  0,  0, &
       0,  0,  2, -2,  1,  0,  0, -3,  0,  3,  0,  0,  0,  0, &
       0,  0,  2, -2,  1,  0, -5,  5,  0,  0,  0,  0,  0,  0, &
       0,  0,  1, -1,  1,  0,  1, -3,  0,  0,  0,  0,  0,  0, &
       0,  0,  1, -1,  1,  0,  0, -4,  6,  0,  0,  0,  0,  0, &
       0,  0,  1, -1,  1,  0,  0, -1,  0,  0,  0, -1,  0,  0, &
       0,  0,  1, -1,  1,  0, -5,  6,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  1,  0,  3, -4,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  1,  0, -2,  2,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  7,-10,  0,  0,  0,  0,  0, -1, &
       0,  0,  0,  0,  0,  0,  5, -5,  0,  0,  0,  0,  0,  1, &
       0,  0,  0,  0,  0,  0,  4, -5,  0,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  3, -8,  0,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  2, -5,  0,  0,  0,  0,  0, -1, &
       0,  0,  0,  0,  0,  0,  1, -2,  0,  0,  0,  0,  0, -1, &
       0,  0,  0,  0,  0,  0,  0,  7, -9,  0,  0,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  0,  7, -8,  0,  0,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  0,  3,  0,  0,  0,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  0,  3, -8,  3,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  0,  2,  0,  0, -2,  0,  0,  1, &
       0,  0,  0,  0,  0,  0,  0,  2, -4,  0,  0,  0,  0,  1, &
       0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0, -1, &
       0,  0,  0,  0,  0,  0,  0,  1,  0, -1,  0,  0,  0, -1, &
       2,  0,  0, -2, -1,  0,  0, -6,  8,  0,  0,  0,  0,  0, &
       2,  0, -1, -1,  1,  0,  0,  3, -7,  0,  0,  0,  0,  0, &
       0,  0,  2, -2,  1,  0,  0, -7,  9,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  3, -5,  0,  0,  0,  0, -1, &
       0,  0,  1, -1,  2,  0, -8, 12,  0,  0,  0,  0,  0,  0, &
       1,  0,  0,  0,  0,  0,  0, -2,  0,  2,  0,  0,  0,  0, &
       1,  0,  0, -2,  0,  0,  2, -2,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  7, -8,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0,  0,  0,  0, &
       2,  0,  0, -2,  1,  0,  0, -5,  6,  0,  0,  0,  0,  0, &
       2,  0,  0, -2, -1,  0,  0, -2,  0,  3, -1,  0,  0,  0, &
       1,  0,  1,  1,  1,  0,  0,  1,  0,  0,  0,  0,  0,  0, &
       1,  0,  0, -2,  1,  0,  0, -2,  0,  2,  0,  0,  0,  0, &
       1,  0,  0, -2, -1,  0,  0, -2,  0,  2,  0,  0,  0,  0, &
       1,  0,  0, -1, -1,  0,  0, -3,  4,  0,  0,  0,  0,  0, &
       1,  0, -1,  0, -1,  0, -3,  5,  0,  0,  0,  0,  0,  0, &
       0,  0,  2, -2,  1,  0,  0, -4,  4,  0,  0,  0,  0,  0, &
       0,  0,  2, -2,  1,  0,  0, -2,  0,  0,  0,  0,  0,  0, &
       0,  0,  2, -2,  1,  0, -8, 11,  0,  0,  0,  0,  0,  0, &
       0,  0,  2, -2,  0,  0,  0, -9, 13,  0,  0,  0,  0,  0, &
       0,  0,  1,  1,  2,  0,  0,  1,  0,  0,  0,  0,  0,  0, &
       0,  0,  1, -1,  1,  0,  0,  1, -4,  0,  0,  0,  0,  0, &
       0,  0,  1, -1,  1,  0,  0, -1,  0,  1, -3,  0,  0,  0, &
       0,  0,  0,  0,  1,  0,  0,  7,-13,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  1,  0,  0,  2,  0, -2,  0,  0,  0,  0, &
       0,  0,  0,  0,  1,  0,  0, -2,  2,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  1,  0, -3,  4,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  1,  0, -4,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  7,-11,  0,  0,  0,  0,  0, -1, &
       0,  0,  0,  0,  0,  0,  6, -6,  0,  0,  0,  0,  0,  1, &
       0,  0,  0,  0,  0,  0,  6, -4,  0,  0,  0,  0,  0,  1, &
       0,  0,  0,  0,  0,  0,  5, -6,  0,  0,  0,  0,  0, -1, &
       0,  0,  0,  0,  0,  0,  4, -2,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  3, -4,  0,  0,  0,  0,  0,  1, &
       0,  0,  0,  0,  0,  0,  1, -4,  0,  0,  0,  0,  0, -1, &
       0,  0,  0,  0,  0,  0,  0,  9,-17,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  0,  7, -7,  0,  0,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  0,  4, -8,  3,  0,  0,  0,  1, &
       0,  0,  0,  0,  0,  0,  0,  4, -8,  3,  0,  0,  0, -1, &
       0,  0,  0,  0,  0,  0,  0,  4, -8,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  4, -7,  0,  0,  0,  0, -1, &
       0,  0,  0,  0,  0,  0,  0,  1,  0,  1,  0,  0,  0,  1, &
       0,  0,  0,  0,  0,  0,  0,  1,  0, -4,  0,  0,  0,  0, &
       2,  0,  0, -2,  0,  0,  0, -4,  8, -3,  0,  0,  0,  0, &
       2,  0,  0, -2,  0,  0, -2,  2,  0,  0,  0,  0,  0,  0, &
       1,  0,  0,  0,  0,  0,  0,  4, -8,  3,  0,  0,  0,  0, &
       1,  0,  0,  0,  0,  0,  0, -4,  8, -3,  0,  0,  0,  0, &
       1,  0,  0,  0,  0,  0, -1,  1,  0,  0,  0,  0,  0,  0, &
       1,  0,  0, -2,  0,  0, 17,-16,  0, -2,  0,  0,  0,  0, &
       1,  0,  0, -1,  0,  0,  0, -2,  2,  0,  0,  0,  0,  0, &
       0,  0,  2, -2,  0,  0,  0, -2,  0,  2,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  6, -9,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  4,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  3,  0, -4,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1, -2, -2, &
       0,  0,  0,  0,  0,  0,  0,  2,  1,  0,  0,  0,  0,  2, &
       2,  0,  0, -2,  0,  0,  0, -4,  4,  0,  0,  0,  0,  0, &
       2,  0,  0, -2,  0,  0,  0, -2,  0,  2,  2,  0,  0,  0, &
       1,  0,  0,  0,  0,  0,  1, -1,  0,  0,  0,  0,  0,  0, &
       1,  0,  0,  0,  0,  0,  0, -1,  0,  1,  0,  0,  0,  0, &
       1,  0,  0,  0,  0,  0, -3,  3,  0,  0,  0,  0,  0,  0, &
       1,  0,  0, -2,  0,  0,  1, -1,  0,  0,  0,  0,  0,  0, &
       1,  0,  0, -2,  0,  0,  0,  4, -8,  3,  0,  0,  0,  0, &
       1,  0,  0, -2,  0,  0,  0, -4,  8, -3,  0,  0,  0,  0, &
       1,  0,  0, -2,  0,  0, -2,  2,  0,  0,  0,  0,  0,  0, &
       0,  0,  2, -2,  0,  0, -4,  4,  0,  0,  0,  0,  0,  0, &
       0,  0,  1,  1,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0, &
       0,  0,  1, -1,  0,  0,  3, -6,  0,  0,  0,  0,  0,  0, &
       0,  0,  1, -1,  0,  0,  0, -2,  2,  0,  0,  0,  0,  0, &
       0,  0,  1, -1,  0,  0,  0, -1,  0,  1,  0,  0,  0,  0, &
       0,  0,  1, -1,  0,  0,  0, -1,  0,  0,  1,  0,  0,  0, &
       0,  0,  1, -1,  0,  0, -4,  5,  0,  0,  0,  0,  0,  0, &
       0,  0,  1, -1,  0,  0, -3,  4,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  2,  0,  0,  0, -1,  0,  1,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  8, -9,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  3, -6,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  1,  1,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  0,  0,  3, -5,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  0,  0,  2, -2,  0,  0,  0, &
       2,  0, -2, -2, -2,  0,  0, -2,  0,  2,  0,  0,  0,  0, &
       1,  0,  0,  0,  1,  0,-10,  3,  0,  0,  0,  0,  0,  0, &
       1,  0,  0,  0, -1,  0,-10,  3,  0,  0,  0,  0,  0,  0, &
       0,  0,  2,  0,  2,  0,  2, -3,  0,  0,  0,  0,  0,  0, &
       0,  0,  2,  0,  2,  0,  2, -2,  0,  0,  0,  0,  0,  0, &
       0,  0,  2,  0,  2,  0, -2,  3,  0,  0,  0,  0,  0,  0, &
       0,  0,  2,  0,  2,  0, -2,  2,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  2,  0,  0,  0,  0,  1,  0,  0,  0,  0, &
       0,  0,  0,  0,  1,  0,  0, -1,  0,  2,  0,  0,  0,  0, &
       2,  0,  2, -2,  2,  0,  0, -2,  0,  3,  0,  0,  0,  0, &
       2,  0,  1, -3,  1,  0, -6,  7,  0,  0,  0,  0,  0,  0, &
       2,  0,  0, -2,  0,  0,  2, -5,  0,  0,  0,  0,  0,  0, &
       2,  0,  0, -2,  0,  0,  0, -2,  0,  5, -5,  0,  0,  0, &
       2,  0,  0, -2,  0,  0,  0, -2,  0,  1,  5,  0,  0,  0, &
       2,  0,  0, -2,  0,  0,  0, -2,  0,  0,  5,  0,  0,  0, &
       2,  0,  0, -2,  0,  0,  0, -2,  0,  0,  2,  0,  0,  0, &
       2,  0,  0, -2,  0,  0, -4,  4,  0,  0,  0,  0,  0,  0, &
       2,  0, -2,  0, -2,  0,  0,  5, -9,  0,  0,  0,  0,  0, &
       2,  0, -1, -1,  0,  0,  0, -1,  0,  3,  0,  0,  0,  0, &
       1,  0,  2,  0,  2,  0,  1, -1,  0,  0,  0,  0,  0,  0, &
       1,  0,  2,  0,  2,  0,  0,  4, -8,  3,  0,  0,  0,  0, &
       1,  0,  2,  0,  2,  0,  0, -4,  8, -3,  0,  0,  0,  0, &
       1,  0,  2,  0,  2,  0, -1,  1,  0,  0,  0,  0,  0,  0, &
       1,  0,  2, -2,  2,  0, -3,  3,  0,  0,  0,  0,  0,  0, &
       1,  0,  0,  0,  0,  0,  0,  1,  0, -1,  0,  0,  0,  0, &
       1,  0,  0,  0,  0,  0,  0, -2,  0,  3,  0,  0,  0,  0, &
       1,  0,  0, -2,  0,  0,  0,  2,  0, -2,  0,  0,  0,  0, &
       1,  0, -2, -2, -2,  0,  0,  1,  0, -1,  0,  0,  0,  0, &
       1,  0, -1,  1,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0, &
       1,  0, -1, -1,  0,  0,  0,  8,-15,  0,  0,  0,  0,  0, &
       0,  0,  2,  2,  2,  0,  0,  2,  0, -2,  0,  0,  0,  0, &
       0,  0,  2, -2,  1,  0,  1, -1,  0,  0,  0,  0,  0,  0, &
       0,  0,  2, -2,  1,  0,  0, -2,  0,  1,  0,  0,  0,  0, &
       0,  0,  2, -2,  1,  0,  0,-10, 15,  0,  0,  0,  0,  0, &
       0,  0,  2, -2,  0, -1,  0,  2,  0,  0,  0,  0,  0,  0, &
       0,  0,  1, -1,  2,  0,  0, -1,  0,  0, -1,  0,  0,  0, &
       0,  0,  1, -1,  2,  0, -3,  4,  0,  0,  0,  0,  0,  0, &
       0,  0,  1, -1,  1,  0, -4,  6,  0,  0,  0,  0,  0,  0, &
       0,  0,  1, -1,  1,  0, -1,  2,  0,  0,  0,  0,  0,  0, &
       0,  0,  1, -1,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0, &
       0,  0,  1, -1,  0,  0,  0, -1,  0,  0, -2,  0,  0,  0, &
       0,  0,  1, -1,  0,  0, -2,  2,  0,  0,  0,  0,  0,  0, &
       0,  0,  1, -1,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0, &
       0,  0,  1, -1, -1,  0, -5,  7,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  2,  0,  0,  0,  2,  0, -2,  0,  0,  0,  0, &
       0,  0,  0,  2,  0,  0, -2,  2,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  2,  0, -3,  5,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  1,  0, -1,  2,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  9,-13,  0,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  8,-14,  0,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  8,-11,  0,  0,  0,  0,  0, -1, &
       0,  0,  0,  0,  0,  0,  6, -9,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  6, -8,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  6, -7,  0,  0,  0,  0,  0, -1, &
       0,  0,  0,  0,  0,  0,  5, -6,  0,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  5, -6, -4,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  5, -4,  0,  0,  0,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  4, -8,  0,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  4, -5,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  3, -3,  0,  2,  0,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  3, -1,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  2,  0,  0,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  1, -1,  0,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  0,  7,-12,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  0,  6, -9,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  0,  6, -8,  1,  5,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  0,  6, -4,  0,  0,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  0,  6,-10,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  5,  0, -4,  0,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  0,  5, -9,  0,  0,  0,  0, -1, &
       0,  0,  0,  0,  0,  0,  0,  5, -8,  3,  0,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  0,  5, -7,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  0,  5, -6,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  5,-16,  4,  5,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  0,  5,-13,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  0,  3,  0, -5,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  0,  3, -9,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  0,  3, -7,  0,  0,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  0,  2,  0,  2,  0,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  0,  2,  0,  0, -3,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  2, -8,  1,  5,  0,  0, -2, &
       0,  0,  0,  0,  0,  0,  0,  1,  0,  1, -5,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  2,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  0,  1,  0,  0, -3,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  1,  0, -3,  5,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  1, -3,  0,  0,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  0,  0,  2, -6,  3,  0, -2, &
       0,  0,  0,  0,  0,  0,  0,  0,  0,  1, -2,  0,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0, &
       0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  2, &
       0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0 ], [14,nfpl])
    !  Pointers into amplitudes array, one pointer per frequency.
    integer,dimension(nf),parameter :: nc = [ &
        1,   21,   37,   51,   65,   79,   91,  103,  115,  127, &
      139,  151,  163,  172,  184,  196,  207,  219,  231,  240, &
      252,  261,  273,  285,  297,  309,  318,  327,  339,  351, &
      363,  372,  384,  396,  405,  415,  423,  435,  444,  452, &
      460,  467,  474,  482,  490,  498,  506,  513,  521,  528, &
      536,  543,  551,  559,  566,  574,  582,  590,  597,  605, &
      613,  620,  628,  636,  644,  651,  658,  666,  674,  680, &
      687,  695,  702,  710,  717,  725,  732,  739,  746,  753, &
      760,  767,  774,  782,  790,  798,  805,  812,  819,  826, &
      833,  840,  846,  853,  860,  867,  874,  881,  888,  895, &
      901,  908,  914,  921,  928,  934,  941,  948,  955,  962, &
      969,  976,  982,  989,  996, 1003, 1010, 1017, 1024, 1031, &
     1037, 1043, 1050, 1057, 1064, 1071, 1078, 1084, 1091, 1098, &
     1104, 1112, 1118, 1124, 1131, 1138, 1145, 1151, 1157, 1164, &
     1171, 1178, 1185, 1192, 1199, 1205, 1212, 1218, 1226, 1232, &
     1239, 1245, 1252, 1259, 1266, 1272, 1278, 1284, 1292, 1298, &
     1304, 1310, 1316, 1323, 1329, 1335, 1341, 1347, 1353, 1359, &
     1365, 1371, 1377, 1383, 1389, 1396, 1402, 1408, 1414, 1420, &
     1426, 1434, 1440, 1446, 1452, 1459, 1465, 1471, 1477, 1482, &
     1488, 1493, 1499, 1504, 1509, 1514, 1520, 1527, 1532, 1538, &
     1543, 1548, 1553, 1558, 1564, 1569, 1574, 1579, 1584, 1589, &
     1594, 1596, 1598, 1600, 1602, 1605, 1608, 1610, 1612, 1617, &
     1619, 1623, 1625, 1627, 1629, 1632, 1634, 1640, 1642, 1644, &
     1646, 1648, 1650, 1652, 1654, 1658, 1660, 1662, 1664, 1668, &
     1670, 1672, 1673, 1675, 1679, 1681, 1683, 1684, 1686, 1688, &
     1690, 1693, 1695, 1697, 1701, 1703, 1705, 1707, 1709, 1711, &
     1712, 1715, 1717, 1721, 1723, 1725, 1727, 1729, 1731, 1733, &
     1735, 1737, 1739, 1741, 1743, 1745, 1747, 1749, 1751, 1753, &
     1755, 1757, 1759, 1761, 1762, 1764, 1766, 1768, 1769, 1771, &
     1773, 1775, 1777, 1779, 1781, 1783, 1785, 1787, 1788, 1790, &
     1792, 1794, 1796, 1798, 1800, 1802, 1804, 1806, 1807, 1809, &
     1811, 1815, 1817, 1819, 1821, 1823, 1825, 1827, 1829, 1831, &
     1833, 1835, 1837, 1839, 1840, 1842, 1844, 1848, 1850, 1852, &
     1854, 1856, 1858, 1859, 1860, 1862, 1864, 1866, 1868, 1869, &
     1871, 1873, 1875, 1877, 1879, 1881, 1883, 1885, 1887, 1889, &
     1891, 1892, 1896, 1898, 1900, 1901, 1903, 1905, 1907, 1909, &
     1910, 1911, 1913, 1915, 1919, 1921, 1923, 1927, 1929, 1931, &
     1933, 1935, 1937, 1939, 1943, 1945, 1947, 1948, 1949, 1951, &
     1953, 1955, 1957, 1958, 1960, 1962, 1964, 1966, 1968, 1970, &
     1971, 1973, 1974, 1975, 1977, 1979, 1980, 1981, 1982, 1984, &
     1986, 1988, 1990, 1992, 1994, 1995, 1997, 1999, 2001, 2003, &
     2005, 2007, 2008, 2009, 2011, 2013, 2015, 2017, 2019, 2021, &
     2023, 2024, 2025, 2027, 2029, 2031, 2033, 2035, 2037, 2041, &
     2043, 2045, 2046, 2047, 2049, 2051, 2053, 2055, 2056, 2057, &
     2059, 2061, 2063, 2065, 2067, 2069, 2070, 2071, 2072, 2074, &
     2076, 2078, 2080, 2082, 2084, 2086, 2088, 2090, 2092, 2094, &
     2095, 2096, 2097, 2099, 2101, 2105, 2106, 2107, 2108, 2109, &
     2110, 2111, 2113, 2115, 2119, 2121, 2123, 2125, 2127, 2129, &
     2131, 2133, 2135, 2136, 2137, 2139, 2141, 2143, 2145, 2147, &
     2149, 2151, 2153, 2155, 2157, 2159, 2161, 2163, 2165, 2167, &
     2169, 2171, 2173, 2175, 2177, 2179, 2181, 2183, 2185, 2186, &
     2187, 2188, 2192, 2193, 2195, 2197, 2199, 2201, 2203, 2205, &
     2207, 2209, 2211, 2213, 2217, 2219, 2221, 2223, 2225, 2227, &
     2229, 2231, 2233, 2234, 2235, 2236, 2237, 2238, 2239, 2240, &
     2241, 2244, 2246, 2248, 2250, 2252, 2254, 2256, 2258, 2260, &
     2262, 2264, 2266, 2268, 2270, 2272, 2274, 2276, 2278, 2280, &
     2282, 2284, 2286, 2288, 2290, 2292, 2294, 2296, 2298, 2300, &
     2302, 2303, 2304, 2305, 2306, 2307, 2309, 2311, 2313, 2315, &
     2317, 2319, 2321, 2323, 2325, 2327, 2329, 2331, 2333, 2335, &
     2337, 2341, 2343, 2345, 2347, 2349, 2351, 2352, 2355, 2356, &
     2357, 2358, 2359, 2361, 2363, 2364, 2365, 2366, 2367, 2368, &
     2369, 2370, 2371, 2372, 2373, 2374, 2376, 2378, 2380, 2382, &
     2384, 2385, 2386, 2387, 2388, 2389, 2390, 2391, 2392, 2393, &
     2394, 2395, 2396, 2397, 2398, 2399, 2400, 2401, 2402, 2403, &
     2404, 2405, 2406, 2407, 2408, 2409, 2410, 2411, 2412, 2413, &
     2414, 2415, 2417, 2418, 2430, 2438, 2445, 2453, 2460, 2468, &
     2474, 2480, 2488, 2496, 2504, 2512, 2520, 2527, 2535, 2543, &
     2550, 2558, 2566, 2574, 2580, 2588, 2596, 2604, 2612, 2619, &
     2627, 2634, 2642, 2648, 2656, 2664, 2671, 2679, 2685, 2693, &
     2701, 2709, 2717, 2725, 2733, 2739, 2747, 2753, 2761, 2769, &
     2777, 2785, 2793, 2801, 2809, 2817, 2825, 2833, 2841, 2848, &
     2856, 2864, 2872, 2878, 2884, 2892, 2898, 2906, 2914, 2922, &
     2930, 2938, 2944, 2952, 2958, 2966, 2974, 2982, 2988, 2996, &
     3001, 3009, 3017, 3025, 3032, 3039, 3045, 3052, 3059, 3067, &
     3069, 3076, 3083, 3090, 3098, 3105, 3109, 3111, 3113, 3120, &
     3124, 3128, 3132, 3136, 3140, 3144, 3146, 3150, 3158, 3161, &
     3165, 3166, 3168, 3172, 3176, 3180, 3182, 3185, 3189, 3193, &
     3194, 3197, 3200, 3204, 3208, 3212, 3216, 3219, 3221, 3222, &
     3226, 3230, 3234, 3238, 3242, 3243, 3247, 3251, 3254, 3258, &
     3262, 3266, 3270, 3274, 3275, 3279, 3283, 3287, 3289, 3293, &
     3296, 3300, 3303, 3307, 3311, 3315, 3319, 3321, 3324, 3327, &
     3330, 3334, 3338, 3340, 3342, 3346, 3350, 3354, 3358, 3361, &
     3365, 3369, 3373, 3377, 3381, 3385, 3389, 3393, 3394, 3398, &
     3402, 3406, 3410, 3413, 3417, 3421, 3425, 3429, 3433, 3435, &
     3439, 3443, 3446, 3450, 3453, 3457, 3458, 3461, 3464, 3468, &
     3472, 3476, 3478, 3481, 3485, 3489, 3493, 3497, 3501, 3505, &
     3507, 3511, 3514, 3517, 3521, 3524, 3525, 3527, 3529, 3533, &
     3536, 3540, 3541, 3545, 3548, 3551, 3555, 3559, 3563, 3567, &
     3569, 3570, 3574, 3576, 3578, 3582, 3586, 3590, 3593, 3596, &
     3600, 3604, 3608, 3612, 3616, 3620, 3623, 3626, 3630, 3632, &
     3636, 3640, 3643, 3646, 3648, 3652, 3656, 3660, 3664, 3667, &
     3669, 3671, 3675, 3679, 3683, 3687, 3689, 3693, 3694, 3695, &
     3699, 3703, 3705, 3707, 3710, 3713, 3717, 3721, 3725, 3729, &
     3733, 3736, 3740, 3744, 3748, 3752, 3754, 3757, 3759, 3763, &
     3767, 3770, 3773, 3777, 3779, 3783, 3786, 3790, 3794, 3798, &
     3801, 3805, 3809, 3813, 3817, 3821, 3825, 3827, 3831, 3835, &
     3836, 3837, 3840, 3844, 3848, 3852, 3856, 3859, 3863, 3867, &
     3869, 3871, 3875, 3879, 3883, 3887, 3890, 3894, 3898, 3901, &
     3905, 3909, 3913, 3917, 3921, 3922, 3923, 3924, 3926, 3930, &
     3932, 3936, 3938, 3940, 3944, 3948, 3952, 3956, 3959, 3963, &
     3965, 3969, 3973, 3977, 3979, 3981, 3982, 3986, 3989, 3993, &
     3997, 4001, 4004, 4006, 4009, 4012, 4016, 4020, 4024, 4026, &
     4028, 4032, 4036, 4040, 4044, 4046, 4050, 4054, 4058, 4060, &
     4062, 4063, 4064, 4068, 4071, 4075, 4077, 4081, 4083, 4087, &
     4089, 4091, 4095, 4099, 4101, 4103, 4105, 4107, 4111, 4115, &
     4119, 4123, 4127, 4129, 4131, 4135, 4139, 4141, 4143, 4145, &
     4149, 4153, 4157, 4161, 4165, 4169, 4173, 4177, 4180, 4183, &
     4187, 4191, 4195, 4198, 4201, 4205, 4209, 4212, 4213, 4216, &
     4217, 4221, 4223, 4226, 4230, 4234, 4236, 4240, 4244, 4248, &
     4252, 4256, 4258, 4262, 4264, 4266, 4268, 4270, 4272, 4276, &
     4279, 4283, 4285, 4287, 4289, 4293, 4295, 4299, 4300, 4301, &
     4305, 4309, 4313, 4317, 4319, 4323, 4325, 4329, 4331, 4333, &
     4335, 4337, 4341, 4345, 4349, 4351, 4353, 4357, 4361, 4365, &
     4367, 4369, 4373, 4377, 4381, 4383, 4387, 4389, 4391, 4395, &
     4399, 4403, 4407, 4411, 4413, 4414, 4415, 4418, 4419, 4421, &
     4423, 4427, 4429, 4431, 4433, 4435, 4437, 4439, 4443, 4446, &
     4450, 4452, 4456, 4458, 4460, 4462, 4466, 4469, 4473, 4477, &
     4481, 4483, 4487, 4489, 4491, 4493, 4497, 4499, 4501, 4504, &
     4506, 4510, 4513, 4514, 4515, 4518, 4521, 4522, 4525, 4526, &
     4527, 4530, 4533, 4534, 4537, 4541, 4542, 4543, 4544, 4545, &
     4546, 4547, 4550, 4553, 4554, 4555, 4558, 4561, 4564, 4567, &
     4568, 4571, 4574, 4575, 4578, 4581, 4582, 4585, 4586, 4588, &
     4590, 4592, 4596, 4598, 4602, 4604, 4608, 4612, 4613, 4616, &
     4619, 4622, 4623, 4624, 4625, 4626, 4629, 4632, 4633, 4636, &
     4639, 4640, 4641, 4642, 4643, 4644, 4645, 4648, 4649, 4650, &
     4651, 4652, 4653, 4656, 4657, 4660, 4661, 4664, 4667, 4670, &
     4671, 4674, 4675, 4676, 4677, 4678, 4681, 4682, 4683, 4684, &
     4687, 4688, 4689, 4692, 4693, 4696, 4697, 4700, 4701, 4702, &
     4703, 4704, 4707, 4708, 4711, 4712, 4715, 4716, 4717, 4718, &
     4719, 4720, 4721, 4722, 4723, 4726, 4729, 4730, 4733, 4736, &
     4737, 4740, 4741, 4742, 4745, 4746, 4749, 4752, 4753]
    !  Amplitude coefficients (microarcsec);  indexed using the NC array
    real(wp), dimension(na), parameter :: a = [ &
        -6844318.44_wp, 9205236.26_wp, 1328.67_wp, 1538.18_wp, 205833.11_wp, &
        153041.79_wp, -3309.73_wp, 853.32_wp, 2037.98_wp, -2301.27_wp, 81.46_wp, &
        120.56_wp, -20.39_wp, -15.22_wp, 1.73_wp, -1.61_wp, -0.1_wp, 0.11_wp, -0.02_wp, &
        -0.02_wp, -523908.04_wp, 573033.42_wp, -544.75_wp, -458.66_wp, 12814.01_wp, &
        11714.49_wp, 198.97_wp, -290.91_wp, 155.74_wp, -143.27_wp, -2.75_wp, -1.03_wp, &
        -1.27_wp, -1.16_wp, 0.0_wp, -0.01_wp, -90552.22_wp, 97846.69_wp, 111.23_wp, &
        137.41_wp, 2187.91_wp, 2024.68_wp, 41.44_wp, -51.26_wp, 26.92_wp, -24.46_wp, &
        -0.46_wp, -0.28_wp, -0.22_wp, -0.2_wp, 82168.76_wp, -89618.24_wp, -27.64_wp, &
        -29.05_wp, -2004.36_wp, -1837.32_wp, -36.07_wp, 48.0_wp, -24.43_wp, 22.41_wp, &
        0.47_wp, 0.24_wp, 0.2_wp, 0.18_wp, 58707.02_wp, 7387.02_wp, 470.05_wp, &
        -192.4_wp, 164.33_wp, -1312.21_wp, -179.73_wp, -28.93_wp, -17.36_wp, -1.83_wp, &
        -0.5_wp, 3.57_wp, 0.0_wp, 0.13_wp, -20557.78_wp, 22438.42_wp, -20.84_wp, &
        -17.4_wp, 501.82_wp, 459.68_wp, 59.2_wp, -67.3_wp, 6.08_wp, -5.61_wp, -1.36_wp, &
        -1.19_wp, 28288.28_wp, -674.99_wp, -34.69_wp, 35.8_wp, -15.07_wp, -632.54_wp, &
        -11.19_wp, 0.78_wp, -8.41_wp, 0.17_wp, 0.01_wp, 0.07_wp, -15406.85_wp, &
        20069.5_wp, 15.12_wp, 31.8_wp, 448.76_wp, 344.5_wp, -5.77_wp, 1.41_wp, 4.59_wp, &
        -5.02_wp, 0.17_wp, 0.24_wp, -11991.74_wp, 12902.66_wp, 32.46_wp, 36.7_wp, &
        288.49_wp, 268.14_wp, 5.7_wp, -7.06_wp, 3.57_wp, -3.23_wp, -0.06_wp, -0.04_wp, &
        -8584.95_wp, -9592.72_wp, 4.42_wp, -13.2_wp, -214.5_wp, 192.06_wp, 23.87_wp, &
        29.83_wp, 2.54_wp, 2.4_wp, 0.6_wp, -0.48_wp, 5095.5_wp, -6918.22_wp, &
        7.19_wp, 3.92_wp, -154.91_wp, -113.94_wp, 2.86_wp, -1.04_wp, -1.52_wp, &
        1.73_wp, -0.07_wp, -0.1_wp, -4910.93_wp, -5331.13_wp, 0.76_wp, 0.4_wp, &
        -119.21_wp, 109.81_wp, 2.16_wp, 3.2_wp, 1.46_wp, 1.33_wp, 0.04_wp, -0.02_wp, &
        -6245.02_wp, -123.48_wp, -6.68_wp, -8.2_wp, -2.76_wp, 139.64_wp, 2.71_wp, &
        0.15_wp, 1.86_wp, 2511.85_wp, -3323.89_wp, 1.07_wp, -0.9_wp, -74.33_wp, &
        -56.17_wp, 1.16_wp, -0.01_wp, -0.75_wp, 0.83_wp, -0.02_wp, -0.04_wp, &
        2307.58_wp, 3143.98_wp, -7.52_wp, 7.5_wp, 70.31_wp, -51.6_wp, 1.46_wp, 0.16_wp, &
        -0.69_wp, -0.79_wp, 0.02_wp, -0.05_wp, 2372.58_wp, 2554.51_wp, 5.93_wp, &
        -6.6_wp, 57.12_wp, -53.05_wp, -0.96_wp, -1.24_wp, -0.71_wp, -0.64_wp, -0.01_wp, &
        -2053.16_wp, 2636.13_wp, 5.13_wp, 7.8_wp, 58.94_wp, 45.91_wp, -0.42_wp, &
        -0.12_wp, 0.61_wp, -0.66_wp, 0.02_wp, 0.03_wp, -1825.49_wp, -2423.59_wp, &
        1.23_wp, -2.0_wp, -54.19_wp, 40.82_wp, -1.07_wp, -1.02_wp, 0.54_wp, 0.61_wp, &
        -0.04_wp, 0.04_wp, 2521.07_wp, -122.28_wp, -5.97_wp, 2.9_wp, -2.73_wp, &
        -56.37_wp, -0.82_wp, 0.13_wp, -0.75_wp, -1534.09_wp, 1645.01_wp, 6.29_wp, &
        6.8_wp, 36.78_wp, 34.3_wp, 0.92_wp, -1.25_wp, 0.46_wp, -0.41_wp, -0.02_wp, &
        -0.01_wp, 1898.27_wp, 47.7_wp, -0.72_wp, 2.5_wp, 1.07_wp, -42.45_wp, -0.94_wp, &
        0.02_wp, -0.56_wp, -1292.02_wp, -1387.0_wp, 0.0_wp, 0.0_wp, -31.01_wp, 28.89_wp, &
        0.68_wp, 0.0_wp, 0.38_wp, 0.35_wp, -0.01_wp, -0.01_wp, -1234.96_wp, &
        1323.81_wp, 5.21_wp, 5.9_wp, 29.6_wp, 27.61_wp, 0.74_wp, -1.22_wp, 0.37_wp, &
        -0.33_wp, -0.02_wp, -0.01_wp, 1137.48_wp, -1233.89_wp, -0.04_wp, -0.3_wp, &
        -27.59_wp, -25.43_wp, -0.61_wp, 1.0_wp, -0.34_wp, 0.31_wp, 0.01_wp, 0.01_wp, &
        -813.13_wp, -1075.6_wp, 0.4_wp, 0.3_wp, -24.05_wp, 18.18_wp, -0.4_wp, -0.01_wp, &
        0.24_wp, 0.27_wp, -0.01_wp, 0.01_wp, 1163.22_wp, -60.9_wp, -2.94_wp, 1.3_wp, &
        -1.36_wp, -26.01_wp, -0.58_wp, 0.07_wp, -0.35_wp, 1029.7_wp, -55.55_wp, &
        -2.63_wp, 1.1_wp, -1.25_wp, -23.02_wp, -0.52_wp, 0.06_wp, -0.31_wp, &
        -556.26_wp, 852.85_wp, 3.16_wp, -4.48_wp, 19.06_wp, 12.44_wp, -0.81_wp, &
        -0.27_wp, 0.17_wp, -0.21_wp, 0.0_wp, 0.02_wp, -603.52_wp, -800.34_wp, &
        0.44_wp, 0.1_wp, -17.9_wp, 13.49_wp, -0.08_wp, -0.01_wp, 0.18_wp, 0.2_wp, &
        -0.01_wp, 0.01_wp, -628.24_wp, 684.99_wp, -0.64_wp, -0.5_wp, 15.32_wp, &
        14.05_wp, 3.18_wp, -4.19_wp, 0.19_wp, -0.17_wp, -0.09_wp, -0.07_wp, &
        -866.48_wp, -16.26_wp, 0.52_wp, -1.3_wp, -0.36_wp, 19.37_wp, 0.43_wp, -0.01_wp, &
        0.26_wp, -512.37_wp, 695.54_wp, -1.47_wp, -1.4_wp, 15.55_wp, 11.46_wp, &
        -0.16_wp, 0.03_wp, 0.15_wp, -0.17_wp, 0.01_wp, 0.01_wp, 506.65_wp, &
        643.75_wp, 2.54_wp, -2.62_wp, 14.4_wp, -11.33_wp, -0.77_wp, -0.06_wp, -0.15_wp, &
        -0.16_wp, 0.0_wp, 0.01_wp, 664.57_wp, 16.81_wp, -0.4_wp, 1.0_wp, 0.38_wp, &
        -14.86_wp, -3.71_wp, -0.09_wp, -0.2_wp, 405.91_wp, 522.11_wp, 0.99_wp, -1.5_wp, &
        11.67_wp, -9.08_wp, -0.25_wp, -0.02_wp, -0.12_wp, -0.13_wp, -305.78_wp, &
        326.6_wp, 1.75_wp, 1.9_wp, 7.3_wp, 6.84_wp, 0.2_wp, -0.04_wp, 300.99_wp, &
        -325.03_wp, -0.44_wp, -0.5_wp, -7.27_wp, -6.73_wp, -1.01_wp, 0.01_wp, 0.0_wp, &
        0.08_wp, 0.0_wp, 0.02_wp, 438.51_wp, 10.47_wp, -0.56_wp, -0.2_wp, 0.24_wp, &
        -9.81_wp, -0.24_wp, 0.01_wp, -0.13_wp, -264.02_wp, 335.24_wp, 0.99_wp, 1.4_wp, &
        7.49_wp, 5.9_wp, -0.27_wp, -0.02_wp, 284.09_wp, 307.03_wp, 0.32_wp, -0.4_wp, &
        6.87_wp, -6.35_wp, -0.99_wp, -0.01_wp, -250.54_wp, 327.11_wp, 0.08_wp, 0.4_wp, &
        7.31_wp, 5.6_wp, -0.3_wp, 230.72_wp, -304.46_wp, 0.08_wp, -0.1_wp, -6.81_wp, &
        -5.16_wp, 0.27_wp, 229.78_wp, 304.17_wp, -0.6_wp, 0.5_wp, 6.8_wp, -5.14_wp, &
        0.33_wp, 0.01_wp, 256.3_wp, -276.81_wp, -0.28_wp, -0.4_wp, -6.19_wp, -5.73_wp, &
        -0.14_wp, 0.01_wp, -212.82_wp, 269.45_wp, 0.84_wp, 1.2_wp, 6.02_wp, 4.76_wp, &
        0.14_wp, -0.02_wp, 196.64_wp, 272.05_wp, -0.84_wp, 0.9_wp, 6.08_wp, -4.4_wp, &
        0.35_wp, 0.02_wp, 188.95_wp, 272.22_wp, -0.12_wp, 0.3_wp, 6.09_wp, -4.22_wp, &
        0.34_wp, -292.37_wp, -5.1_wp, -0.32_wp, -0.4_wp, -0.11_wp, 6.54_wp, 0.14_wp, &
        0.01_wp, 161.79_wp, -220.67_wp, 0.24_wp, 0.1_wp, -4.93_wp, -3.62_wp, -0.08_wp, &
        261.54_wp, -19.94_wp, -0.95_wp, 0.2_wp, -0.45_wp, -5.85_wp, -0.13_wp, 0.02_wp, &
        142.16_wp, -190.79_wp, 0.2_wp, 0.1_wp, -4.27_wp, -3.18_wp, -0.07_wp, 187.95_wp, &
        -4.11_wp, -0.24_wp, 0.3_wp, -0.09_wp, -4.2_wp, -0.09_wp, 0.01_wp, 0.0_wp, &
        0.0_wp, -79.08_wp, 167.9_wp, 0.04_wp, 0.0_wp, 3.75_wp, 1.77_wp, 121.98_wp, &
        131.04_wp, -0.08_wp, 0.1_wp, 2.93_wp, -2.73_wp, -0.06_wp, -172.95_wp, &
        -8.11_wp, -0.4_wp, -0.2_wp, -0.18_wp, 3.87_wp, 0.09_wp, 0.01_wp, &
        -160.15_wp, -55.3_wp, -14.04_wp, 13.9_wp, -1.23_wp, 3.58_wp, 0.4_wp, 0.31_wp, &
        -115.4_wp, 123.2_wp, 0.6_wp, 0.7_wp, 2.75_wp, 2.58_wp, 0.08_wp, -0.01_wp, &
        -168.26_wp, -2.0_wp, 0.2_wp, -0.2_wp, -0.04_wp, 3.76_wp, 0.08_wp, &
        -114.49_wp, 123.2_wp, 0.32_wp, 0.4_wp, 2.75_wp, 2.56_wp, 0.07_wp, -0.01_wp, &
        112.14_wp, 120.7_wp, 0.28_wp, -0.3_wp, 2.7_wp, -2.51_wp, -0.07_wp, -0.01_wp, &
        161.34_wp, 4.03_wp, 0.2_wp, 0.2_wp, 0.09_wp, -3.61_wp, -0.08_wp, 91.31_wp, &
        126.64_wp, -0.4_wp, 0.4_wp, 2.83_wp, -2.04_wp, -0.04_wp, 0.01_wp, 105.29_wp, &
        112.9_wp, 0.44_wp, -0.5_wp, 2.52_wp, -2.35_wp, -0.07_wp, -0.01_wp, 98.69_wp, &
        -106.2_wp, -0.28_wp, -0.3_wp, -2.37_wp, -2.21_wp, -0.06_wp, 0.01_wp, 86.74_wp, &
        -112.94_wp, -0.08_wp, -0.2_wp, -2.53_wp, -1.94_wp, -0.05_wp, -134.81_wp, &
        3.51_wp, 0.2_wp, -0.2_wp, 0.08_wp, 3.01_wp, 0.07_wp, 79.03_wp, 107.31_wp, &
        -0.24_wp, 0.2_wp, 2.4_wp, -1.77_wp, -0.04_wp, 0.01_wp, 132.81_wp, &
        -10.77_wp, -0.52_wp, 0.1_wp, -0.24_wp, -2.97_wp, -0.07_wp, 0.01_wp, &
        -130.31_wp, -0.9_wp, 0.04_wp, 0.0_wp, 0.0_wp, 2.91_wp, -78.56_wp, 85.32_wp, &
        0.0_wp, 0.0_wp, 1.91_wp, 1.76_wp, 0.04_wp, 0.0_wp, 0.0_wp, -41.53_wp, &
        89.1_wp, 0.02_wp, 0.0_wp, 1.99_wp, 0.93_wp, 66.03_wp, -71.0_wp, -0.2_wp, &
        -0.2_wp, -1.59_wp, -1.48_wp, -0.04_wp, 60.5_wp, 64.7_wp, 0.36_wp, -0.4_wp, &
        1.45_wp, -1.35_wp, -0.04_wp, -0.01_wp, -52.27_wp, -70.01_wp, 0.0_wp, 0.0_wp, &
        -1.57_wp, 1.17_wp, 0.03_wp, -52.95_wp, 66.29_wp, 0.32_wp, 0.4_wp, 1.48_wp, &
        1.18_wp, 0.04_wp, -0.01_wp, 51.02_wp, 67.25_wp, 0.0_wp, 0.0_wp, 1.5_wp, &
        -1.14_wp, -0.03_wp, -55.66_wp, -60.92_wp, 0.16_wp, -0.2_wp, -1.36_wp, 1.24_wp, &
        0.03_wp, -54.81_wp, -59.2_wp, -0.08_wp, 0.2_wp, -1.32_wp, 1.23_wp, 0.03_wp, &
        51.32_wp, -55.6_wp, 0.0_wp, 0.0_wp, -1.24_wp, -1.15_wp, -0.03_wp, 48.29_wp, &
        51.8_wp, 0.2_wp, -0.2_wp, 1.16_wp, -1.08_wp, -0.03_wp, -45.59_wp, -49.0_wp, &
        -0.12_wp, 0.1_wp, -1.1_wp, 1.02_wp, 0.03_wp, 40.54_wp, -52.69_wp, -0.04_wp, &
        -0.1_wp, -1.18_wp, -0.91_wp, -0.02_wp, -40.58_wp, -49.51_wp, -1.0_wp, 1.0_wp, &
        -1.11_wp, 0.91_wp, 0.04_wp, 0.02_wp, -43.76_wp, 46.5_wp, 0.36_wp, 0.4_wp, &
        1.04_wp, 0.98_wp, 0.03_wp, -0.01_wp, 62.65_wp, -5.0_wp, -0.24_wp, 0.0_wp, &
        -0.11_wp, -1.4_wp, -0.03_wp, 0.01_wp, -38.57_wp, 49.59_wp, 0.08_wp, 0.1_wp, &
        1.11_wp, 0.86_wp, 0.02_wp, -33.22_wp, -44.04_wp, 0.08_wp, -0.1_wp, -0.98_wp, &
        0.74_wp, 0.02_wp, 37.15_wp, -39.9_wp, -0.12_wp, -0.1_wp, -0.89_wp, -0.83_wp, &
        -0.02_wp, 36.68_wp, -39.5_wp, -0.04_wp, -0.1_wp, -0.88_wp, -0.82_wp, -0.02_wp, &
        -53.22_wp, -3.91_wp, -0.2_wp, 0.0_wp, -0.09_wp, 1.19_wp, 0.03_wp, 32.43_wp, &
        -42.19_wp, -0.04_wp, -0.1_wp, -0.94_wp, -0.73_wp, -0.02_wp, -51.0_wp, -2.3_wp, &
        -0.12_wp, -0.1_wp, 0.0_wp, 1.14_wp, -29.53_wp, -39.11_wp, 0.04_wp, 0.0_wp, &
        -0.87_wp, 0.66_wp, 0.02_wp, 28.5_wp, -38.92_wp, -0.08_wp, -0.1_wp, -0.87_wp, &
        -0.64_wp, -0.02_wp, 26.54_wp, 36.95_wp, -0.12_wp, 0.1_wp, 0.83_wp, -0.59_wp, &
        -0.01_wp, 26.54_wp, 34.59_wp, 0.04_wp, -0.1_wp, 0.77_wp, -0.59_wp, -0.02_wp, &
        28.35_wp, -32.55_wp, -0.16_wp, 0.2_wp, -0.73_wp, -0.63_wp, -0.01_wp, -28.0_wp, &
        30.4_wp, 0.0_wp, 0.0_wp, 0.68_wp, 0.63_wp, 0.01_wp, -27.61_wp, 29.4_wp, &
        0.2_wp, 0.2_wp, 0.66_wp, 0.62_wp, 0.02_wp, 40.33_wp, 0.4_wp, -0.04_wp, &
        0.1_wp, 0.0_wp, -0.9_wp, -23.28_wp, 31.61_wp, -0.08_wp, -0.1_wp, 0.71_wp, &
        0.52_wp, 0.01_wp, 37.75_wp, 0.8_wp, 0.04_wp, 0.1_wp, 0.0_wp, -0.84_wp, &
        23.66_wp, 25.8_wp, 0.0_wp, 0.0_wp, 0.58_wp, -0.53_wp, -0.01_wp, 21.01_wp, &
        -27.91_wp, 0.0_wp, 0.0_wp, -0.62_wp, -0.47_wp, -0.01_wp, -34.81_wp, 2.89_wp, &
        0.04_wp, 0.0_wp, 0.0_wp, 0.78_wp, -23.49_wp, -25.31_wp, 0.0_wp, 0.0_wp, &
        -0.57_wp, 0.53_wp, 0.01_wp, -23.47_wp, 25.2_wp, 0.16_wp, 0.2_wp, 0.56_wp, &
        0.52_wp, 0.02_wp, 19.58_wp, 27.5_wp, -0.12_wp, 0.1_wp, 0.62_wp, -0.44_wp, &
        -0.01_wp, -22.67_wp, -24.4_wp, -0.08_wp, 0.1_wp, -0.55_wp, 0.51_wp, 0.01_wp, &
        -19.97_wp, 25.0_wp, 0.12_wp, 0.2_wp, 0.56_wp, 0.45_wp, 0.01_wp, 21.28_wp, &
        -22.8_wp, -0.08_wp, -0.1_wp, -0.51_wp, -0.48_wp, -0.01_wp, -30.47_wp, 0.91_wp, &
        0.04_wp, 0.0_wp, 0.0_wp, 0.68_wp, 18.58_wp, 24.0_wp, 0.04_wp, -0.1_wp, &
        0.54_wp, -0.42_wp, -0.01_wp, -18.02_wp, 24.4_wp, -0.04_wp, -0.1_wp, 0.55_wp, &
        0.4_wp, 0.01_wp, 17.74_wp, 22.5_wp, 0.08_wp, -0.1_wp, 0.5_wp, -0.4_wp, &
        -0.01_wp, -19.41_wp, 20.7_wp, 0.08_wp, 0.1_wp, 0.46_wp, 0.43_wp, 0.01_wp, &
        -18.64_wp, 20.11_wp, 0.0_wp, 0.0_wp, 0.45_wp, 0.42_wp, 0.01_wp, -16.75_wp, &
        21.6_wp, 0.04_wp, 0.1_wp, 0.48_wp, 0.37_wp, 0.01_wp, -18.42_wp, -20.0_wp, &
        0.0_wp, 0.0_wp, -0.45_wp, 0.41_wp, 0.01_wp, -26.77_wp, 1.41_wp, 0.08_wp, &
        0.0_wp, 0.0_wp, 0.6_wp, -26.17_wp, -0.19_wp, 0.0_wp, 0.0_wp, 0.0_wp, &
        0.59_wp, -15.52_wp, 20.51_wp, 0.0_wp, 0.0_wp, 0.46_wp, 0.35_wp, 0.01_wp, &
        -25.42_wp, -1.91_wp, -0.08_wp, 0.0_wp, -0.04_wp, 0.57_wp, 0.45_wp, -17.42_wp, &
        18.1_wp, 0.0_wp, 0.0_wp, 0.4_wp, 0.39_wp, 0.01_wp, 16.39_wp, -17.6_wp, &
        -0.08_wp, -0.1_wp, -0.39_wp, -0.37_wp, -0.01_wp, -14.37_wp, 18.91_wp, 0.0_wp, &
        0.0_wp, 0.42_wp, 0.32_wp, 0.01_wp, 23.39_wp, -2.4_wp, -0.12_wp, 0.0_wp, &
        0.0_wp, -0.52_wp, 14.32_wp, -18.5_wp, -0.04_wp, -0.1_wp, -0.41_wp, -0.32_wp, &
        -0.01_wp, 15.69_wp, 17.08_wp, 0.0_wp, 0.0_wp, 0.38_wp, -0.35_wp, -0.01_wp, &
        -22.99_wp, 0.5_wp, 0.04_wp, 0.0_wp, 0.0_wp, 0.51_wp, 0.0_wp, 0.0_wp, &
        14.47_wp, -17.6_wp, -0.01_wp, 0.0_wp, -0.39_wp, -0.32_wp, -13.33_wp, 18.4_wp, &
        -0.04_wp, -0.1_wp, 0.41_wp, 0.3_wp, 22.47_wp, -0.6_wp, -0.04_wp, 0.0_wp, &
        0.0_wp, -0.5_wp, -12.78_wp, -17.41_wp, 0.04_wp, 0.0_wp, -0.39_wp, 0.29_wp, &
        0.01_wp, -14.1_wp, -15.31_wp, 0.04_wp, 0.0_wp, -0.34_wp, 0.32_wp, 0.01_wp, &
        11.98_wp, 16.21_wp, -0.04_wp, 0.0_wp, 0.36_wp, -0.27_wp, -0.01_wp, 19.65_wp, &
        -1.9_wp, -0.08_wp, 0.0_wp, 0.0_wp, -0.44_wp, 19.61_wp, -1.5_wp, -0.08_wp, &
        0.0_wp, 0.0_wp, -0.44_wp, 13.41_wp, -14.3_wp, -0.04_wp, -0.1_wp, -0.32_wp, &
        -0.3_wp, -0.01_wp, -13.29_wp, 14.4_wp, 0.0_wp, 0.0_wp, 0.32_wp, 0.3_wp, &
        0.01_wp, 11.14_wp, -14.4_wp, -0.04_wp, 0.0_wp, -0.32_wp, -0.25_wp, -0.01_wp, &
        12.24_wp, -13.38_wp, 0.04_wp, 0.0_wp, -0.3_wp, -0.27_wp, -0.01_wp, 10.07_wp, &
        -13.81_wp, 0.04_wp, 0.0_wp, -0.31_wp, -0.23_wp, -0.01_wp, 10.46_wp, 13.1_wp, &
        0.08_wp, -0.1_wp, 0.29_wp, -0.23_wp, -0.01_wp, 16.55_wp, -1.71_wp, -0.08_wp, &
        0.0_wp, 0.0_wp, -0.37_wp, 9.75_wp, -12.8_wp, 0.0_wp, 0.0_wp, -0.29_wp, &
        -0.22_wp, -0.01_wp, 9.11_wp, 12.8_wp, 0.0_wp, 0.0_wp, 0.29_wp, -0.2_wp, &
        0.0_wp, 0.0_wp, -6.44_wp, -13.8_wp, 0.0_wp, 0.0_wp, -0.31_wp, 0.14_wp, &
        -9.19_wp, -12.0_wp, 0.0_wp, 0.0_wp, -0.27_wp, 0.21_wp, -10.3_wp, 10.9_wp, &
        0.08_wp, 0.1_wp, 0.24_wp, 0.23_wp, 0.01_wp, 14.92_wp, -0.8_wp, -0.04_wp, &
        0.0_wp, 0.0_wp, -0.33_wp, 10.02_wp, -10.8_wp, 0.0_wp, 0.0_wp, -0.24_wp, &
        -0.22_wp, -0.01_wp, -9.75_wp, 10.4_wp, 0.04_wp, 0.0_wp, 0.23_wp, 0.22_wp, &
        0.01_wp, 9.67_wp, -10.4_wp, -0.04_wp, 0.0_wp, -0.23_wp, -0.22_wp, -0.01_wp, &
        -8.28_wp, -11.2_wp, 0.04_wp, 0.0_wp, -0.25_wp, 0.19_wp, 13.32_wp, -1.41_wp, &
        -0.08_wp, 0.0_wp, 0.0_wp, -0.3_wp, 8.27_wp, 10.5_wp, 0.04_wp, 0.0_wp, &
        0.23_wp, -0.19_wp, 0.0_wp, 0.0_wp, 13.13_wp, 0.0_wp, 0.0_wp, 0.0_wp, &
        0.0_wp, -0.29_wp, -12.93_wp, 0.7_wp, 0.04_wp, 0.0_wp, 0.0_wp, 0.29_wp, &
        7.91_wp, -10.2_wp, 0.0_wp, 0.0_wp, -0.23_wp, -0.18_wp, -7.84_wp, -10.0_wp, &
        -0.04_wp, 0.0_wp, -0.22_wp, 0.18_wp, 7.44_wp, 9.6_wp, 0.0_wp, 0.0_wp, &
        0.21_wp, -0.17_wp, -7.64_wp, 9.4_wp, 0.08_wp, 0.1_wp, 0.21_wp, 0.17_wp, &
        0.01_wp, -11.38_wp, 0.6_wp, 0.04_wp, 0.0_wp, 0.0_wp, 0.25_wp, -7.48_wp, &
        8.3_wp, 0.0_wp, 0.0_wp, 0.19_wp, 0.17_wp, -10.98_wp, -0.2_wp, 0.0_wp, &
        0.0_wp, 0.0_wp, 0.25_wp, 10.98_wp, 0.2_wp, 0.0_wp, 0.0_wp, 0.0_wp, &
        -0.25_wp, 7.4_wp, -7.9_wp, -0.04_wp, 0.0_wp, -0.18_wp, -0.17_wp, -6.09_wp, &
        8.4_wp, -0.04_wp, 0.0_wp, 0.19_wp, 0.14_wp, -6.94_wp, -7.49_wp, 0.0_wp, &
        0.0_wp, -0.17_wp, 0.16_wp, 6.92_wp, 7.5_wp, 0.04_wp, 0.0_wp, 0.17_wp, &
        -0.15_wp, 6.2_wp, 8.09_wp, 0.0_wp, 0.0_wp, 0.18_wp, -0.14_wp, -6.12_wp, &
        7.8_wp, 0.04_wp, 0.0_wp, 0.17_wp, 0.14_wp, 5.85_wp, -7.5_wp, 0.0_wp, &
        0.0_wp, -0.17_wp, -0.13_wp, -6.48_wp, 6.9_wp, 0.08_wp, 0.1_wp, 0.15_wp, &
        0.14_wp, 0.01_wp, 6.32_wp, 6.9_wp, 0.0_wp, 0.0_wp, 0.15_wp, -0.14_wp, &
        5.61_wp, -7.2_wp, 0.0_wp, 0.0_wp, -0.16_wp, -0.13_wp, 9.07_wp, 0.0_wp, &
        0.0_wp, 0.0_wp, 0.0_wp, -0.2_wp, 5.25_wp, 6.9_wp, 0.0_wp, 0.0_wp, &
        0.15_wp, -0.12_wp, -8.47_wp, -0.4_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.19_wp, &
        6.32_wp, -5.39_wp, -1.11_wp, 1.1_wp, -0.12_wp, -0.14_wp, 0.02_wp, 0.02_wp, &
        5.73_wp, -6.1_wp, -0.04_wp, 0.0_wp, -0.14_wp, -0.13_wp, 4.7_wp, 6.6_wp, &
        -0.04_wp, 0.0_wp, 0.15_wp, -0.11_wp, -4.9_wp, -6.4_wp, 0.0_wp, 0.0_wp, &
        -0.14_wp, 0.11_wp, -5.33_wp, 5.6_wp, 0.04_wp, 0.1_wp, 0.13_wp, 0.12_wp, &
        0.01_wp, -4.81_wp, 6.0_wp, 0.04_wp, 0.0_wp, 0.13_wp, 0.11_wp, 5.13_wp, &
        5.5_wp, 0.04_wp, 0.0_wp, 0.12_wp, -0.11_wp, 4.5_wp, 5.9_wp, 0.0_wp, &
        0.0_wp, 0.13_wp, -0.1_wp, -4.22_wp, 6.1_wp, 0.0_wp, 0.0_wp, 0.14_wp, &
        -4.53_wp, 5.7_wp, 0.0_wp, 0.0_wp, 0.13_wp, 0.1_wp, 4.18_wp, 5.7_wp, &
        0.0_wp, 0.0_wp, 0.13_wp, -4.75_wp, -5.19_wp, 0.0_wp, 0.0_wp, -0.12_wp, &
        0.11_wp, -4.06_wp, 5.6_wp, 0.0_wp, 0.0_wp, 0.13_wp, -3.98_wp, 5.6_wp, &
        -0.04_wp, 0.0_wp, 0.13_wp, 4.02_wp, -5.4_wp, 0.0_wp, 0.0_wp, -0.12_wp, &
        4.49_wp, -4.9_wp, -0.04_wp, 0.0_wp, -0.11_wp, -0.1_wp, -3.62_wp, -5.4_wp, &
        -0.16_wp, 0.2_wp, -0.12_wp, 0.0_wp, 0.01_wp, 4.38_wp, 4.8_wp, 0.0_wp, &
        0.0_wp, 0.11_wp, -6.4_wp, -0.1_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.14_wp, &
        -3.98_wp, 5.0_wp, 0.04_wp, 0.0_wp, 0.11_wp, -3.82_wp, -5.0_wp, 0.0_wp, &
        0.0_wp, -0.11_wp, -3.71_wp, 5.07_wp, 0.0_wp, 0.0_wp, 0.11_wp, 4.14_wp, &
        4.4_wp, 0.0_wp, 0.0_wp, 0.1_wp, -6.01_wp, -0.5_wp, -0.04_wp, 0.0_wp, &
        0.0_wp, 0.13_wp, -4.04_wp, 4.39_wp, 0.0_wp, 0.0_wp, 0.1_wp, 3.45_wp, &
        -4.72_wp, 0.0_wp, 0.0_wp, -0.11_wp, 3.31_wp, 4.71_wp, 0.0_wp, 0.0_wp, &
        0.11_wp, 3.26_wp, -4.5_wp, 0.0_wp, 0.0_wp, -0.1_wp, -3.26_wp, -4.5_wp, &
        0.0_wp, 0.0_wp, -0.1_wp, -3.34_wp, -4.4_wp, 0.0_wp, 0.0_wp, -0.1_wp, &
        -3.74_wp, -4.0_wp, 3.7_wp, 4.0_wp, 3.34_wp, -4.3_wp, 3.3_wp, -4.3_wp, &
        -3.66_wp, 3.9_wp, 0.04_wp, 3.66_wp, 3.9_wp, 0.04_wp, -3.62_wp, -3.9_wp, &
        -3.61_wp, 3.9_wp, -0.2_wp, 5.3_wp, 0.0_wp, 0.0_wp, 0.12_wp, 3.06_wp, &
        4.3_wp, 3.3_wp, 4.0_wp, 0.4_wp, 0.2_wp, 3.1_wp, 4.1_wp, -3.06_wp, &
        3.9_wp, -3.3_wp, -3.6_wp, -3.3_wp, 3.36_wp, 0.01_wp, 3.14_wp, 3.4_wp, &
        -4.57_wp, -0.2_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.1_wp, -2.7_wp, -3.6_wp, &
        2.94_wp, -3.2_wp, -2.9_wp, 3.2_wp, 2.47_wp, -3.4_wp, 2.55_wp, -3.3_wp, &
        2.8_wp, -3.08_wp, 2.51_wp, 3.3_wp, -4.1_wp, 0.3_wp, -0.12_wp, -0.1_wp, &
        4.1_wp, 0.2_wp, -2.74_wp, 3.0_wp, 2.46_wp, 3.23_wp, -3.66_wp, 1.2_wp, &
        -0.2_wp, 0.2_wp, 3.74_wp, -0.4_wp, -2.51_wp, -2.8_wp, -3.74_wp, 2.27_wp, &
        -2.9_wp, 0.0_wp, 0.0_wp, -2.5_wp, 2.7_wp, -2.51_wp, 2.6_wp, -3.5_wp, &
        0.2_wp, 3.38_wp, -2.22_wp, -2.5_wp, 3.26_wp, -0.4_wp, 1.95_wp, -2.6_wp, &
        3.22_wp, -0.4_wp, -0.04_wp, -1.79_wp, -2.6_wp, 1.91_wp, 2.5_wp, 0.74_wp, &
        3.05_wp, -0.04_wp, 0.08_wp, 2.11_wp, -2.3_wp, -2.11_wp, 2.2_wp, -1.87_wp, &
        -2.4_wp, 2.03_wp, -2.2_wp, -2.03_wp, 2.2_wp, 2.98_wp, 0.0_wp, 0.0_wp, &
        2.98_wp, -1.71_wp, 2.4_wp, 2.94_wp, -0.1_wp, -0.12_wp, 0.1_wp, 1.67_wp, &
        2.4_wp, -1.79_wp, 2.3_wp, -1.79_wp, 2.2_wp, -1.67_wp, 2.2_wp, 1.79_wp, &
        -2.0_wp, 1.87_wp, -1.9_wp, 1.63_wp, -2.1_wp, -1.59_wp, 2.1_wp, 1.55_wp, &
        -2.1_wp, -1.55_wp, 2.1_wp, -2.59_wp, -0.2_wp, -1.75_wp, -1.9_wp, -1.75_wp, &
        1.9_wp, -1.83_wp, -1.8_wp, 1.51_wp, 2.0_wp, -1.51_wp, -2.0_wp, 1.71_wp, &
        1.8_wp, 1.31_wp, 2.1_wp, -1.43_wp, 2.0_wp, 1.43_wp, 2.0_wp, -2.43_wp, &
        -1.51_wp, 1.9_wp, -1.47_wp, 1.9_wp, 2.39_wp, 0.2_wp, -2.39_wp, 1.39_wp, &
        1.9_wp, 1.39_wp, -1.8_wp, 1.47_wp, -1.6_wp, 1.47_wp, -1.6_wp, 1.43_wp, &
        -1.5_wp, -1.31_wp, 1.6_wp, 1.27_wp, -1.6_wp, -1.27_wp, 1.6_wp, 1.27_wp, &
        -1.6_wp, 2.03_wp, 1.35_wp, 1.5_wp, -1.39_wp, -1.4_wp, 1.95_wp, -0.2_wp, &
        -1.27_wp, 1.49_wp, 1.19_wp, 1.5_wp, 1.27_wp, 1.4_wp, 1.15_wp, 1.5_wp, &
        1.87_wp, -0.1_wp, -1.12_wp, -1.5_wp, 1.87_wp, -1.11_wp, -1.5_wp, -1.11_wp, &
        -1.5_wp, 0.0_wp, 0.0_wp, 1.19_wp, 1.4_wp, 1.27_wp, -1.3_wp, -1.27_wp, &
        -1.3_wp, -1.15_wp, 1.4_wp, -1.23_wp, 1.3_wp, -1.23_wp, -1.3_wp, 1.22_wp, &
        -1.29_wp, 1.07_wp, -1.4_wp, 1.75_wp, -0.2_wp, -1.03_wp, -1.4_wp, -1.07_wp, &
        1.2_wp, -1.03_wp, 1.15_wp, 1.07_wp, 1.1_wp, 1.51_wp, -1.03_wp, 1.1_wp, &
        1.03_wp, -1.1_wp, 0.0_wp, 0.0_wp, -1.03_wp, -1.1_wp, 0.91_wp, -1.2_wp, &
        -0.88_wp, -1.2_wp, -0.88_wp, 1.2_wp, -0.95_wp, 1.1_wp, -0.95_wp, -1.1_wp, &
        1.43_wp, -1.39_wp, 0.95_wp, -1.0_wp, -0.95_wp, 1.0_wp, -0.8_wp, 1.1_wp, &
        0.91_wp, -1.0_wp, -1.35_wp, 0.88_wp, 1.0_wp, -0.83_wp, 1.0_wp, -0.91_wp, &
        0.9_wp, 0.91_wp, 0.9_wp, 0.88_wp, -0.9_wp, -0.76_wp, -1.0_wp, -0.76_wp, &
        1.0_wp, 0.76_wp, 1.0_wp, -0.72_wp, 1.0_wp, 0.84_wp, -0.9_wp, 0.84_wp, &
        0.9_wp, 1.23_wp, 0.0_wp, 0.0_wp, -0.52_wp, -1.1_wp, -0.68_wp, 1.0_wp, &
        1.19_wp, -0.2_wp, 1.19_wp, 0.76_wp, 0.9_wp, 1.15_wp, -0.1_wp, 1.15_wp, &
        -0.1_wp, 0.72_wp, -0.9_wp, -1.15_wp, -1.15_wp, 0.68_wp, 0.9_wp, -0.68_wp, &
        0.9_wp, -1.11_wp, 0.0_wp, 0.0_wp, 0.2_wp, 0.79_wp, 0.8_wp, -1.11_wp, &
        -0.1_wp, 0.0_wp, 0.0_wp, -0.48_wp, -1.0_wp, -0.76_wp, -0.8_wp, -0.72_wp, &
        -0.8_wp, -1.07_wp, -0.1_wp, 0.64_wp, 0.8_wp, -0.64_wp, -0.8_wp, 0.64_wp, &
        0.8_wp, 0.4_wp, 0.6_wp, 0.52_wp, -0.5_wp, -0.6_wp, -0.8_wp, -0.71_wp, &
        0.7_wp, -0.99_wp, 0.99_wp, 0.56_wp, 0.8_wp, -0.56_wp, 0.8_wp, 0.68_wp, &
        -0.7_wp, 0.68_wp, 0.7_wp, -0.95_wp, -0.64_wp, 0.7_wp, 0.64_wp, 0.7_wp, &
        -0.6_wp, 0.7_wp, -0.6_wp, -0.7_wp, -0.91_wp, -0.1_wp, -0.51_wp, 0.76_wp, &
        -0.91_wp, -0.56_wp, 0.7_wp, 0.88_wp, 0.88_wp, -0.63_wp, -0.6_wp, 0.55_wp, &
        -0.6_wp, -0.8_wp, 0.8_wp, -0.8_wp, -0.52_wp, 0.6_wp, 0.52_wp, 0.6_wp, &
        0.52_wp, -0.6_wp, -0.48_wp, 0.6_wp, 0.48_wp, 0.6_wp, 0.48_wp, 0.6_wp, &
        -0.76_wp, 0.44_wp, -0.6_wp, 0.52_wp, -0.5_wp, -0.52_wp, 0.5_wp, 0.4_wp, &
        0.6_wp, -0.4_wp, -0.6_wp, 0.4_wp, -0.6_wp, 0.72_wp, -0.72_wp, -0.51_wp, &
        -0.5_wp, -0.48_wp, 0.5_wp, 0.48_wp, -0.5_wp, -0.48_wp, 0.5_wp, -0.48_wp, &
        0.5_wp, 0.48_wp, -0.5_wp, -0.48_wp, -0.5_wp, -0.68_wp, -0.68_wp, 0.44_wp, &
        0.5_wp, -0.64_wp, -0.1_wp, -0.64_wp, -0.1_wp, -0.4_wp, 0.5_wp, 0.4_wp, &
        0.5_wp, 0.4_wp, 0.5_wp, 0.0_wp, 0.0_wp, -0.4_wp, -0.5_wp, -0.36_wp, &
        -0.5_wp, 0.36_wp, -0.5_wp, 0.6_wp, -0.6_wp, 0.4_wp, -0.4_wp, 0.4_wp, &
        0.4_wp, -0.4_wp, 0.4_wp, -0.4_wp, 0.4_wp, -0.56_wp, -0.56_wp, 0.36_wp, &
        -0.4_wp, -0.36_wp, 0.4_wp, 0.36_wp, -0.4_wp, -0.36_wp, -0.4_wp, 0.36_wp, &
        0.4_wp, 0.36_wp, 0.4_wp, -0.52_wp, 0.52_wp, 0.52_wp, 0.32_wp, 0.4_wp, &
        -0.32_wp, 0.4_wp, -0.32_wp, 0.4_wp, -0.32_wp, 0.4_wp, 0.32_wp, -0.4_wp, &
        -0.32_wp, -0.4_wp, 0.32_wp, -0.4_wp, 0.28_wp, -0.4_wp, -0.28_wp, 0.4_wp, &
        0.28_wp, -0.4_wp, 0.28_wp, 0.4_wp, 0.48_wp, -0.48_wp, 0.48_wp, 0.36_wp, &
        -0.3_wp, -0.36_wp, -0.3_wp, 0.0_wp, 0.0_wp, 0.2_wp, 0.4_wp, -0.44_wp, &
        0.44_wp, -0.44_wp, -0.44_wp, -0.44_wp, -0.44_wp, 0.32_wp, -0.3_wp, 0.32_wp, &
        0.3_wp, 0.24_wp, 0.3_wp, -0.12_wp, -0.1_wp, -0.28_wp, 0.3_wp, 0.28_wp, &
        0.3_wp, 0.28_wp, 0.3_wp, 0.28_wp, -0.3_wp, 0.28_wp, -0.3_wp, 0.28_wp, &
        -0.3_wp, 0.28_wp, 0.3_wp, -0.28_wp, 0.3_wp, 0.4_wp, 0.4_wp, -0.24_wp, &
        0.3_wp, 0.24_wp, -0.3_wp, 0.24_wp, -0.3_wp, -0.24_wp, -0.3_wp, 0.24_wp, &
        0.3_wp, 0.24_wp, -0.3_wp, -0.24_wp, 0.3_wp, 0.24_wp, -0.3_wp, -0.24_wp, &
        -0.3_wp, 0.24_wp, -0.3_wp, 0.24_wp, 0.3_wp, -0.24_wp, 0.3_wp, -0.24_wp, &
        0.3_wp, 0.2_wp, -0.3_wp, 0.2_wp, -0.3_wp, 0.2_wp, -0.3_wp, 0.2_wp, &
        0.3_wp, 0.2_wp, -0.3_wp, 0.2_wp, -0.3_wp, 0.2_wp, 0.3_wp, 0.2_wp, &
        0.3_wp, -0.2_wp, -0.3_wp, 0.2_wp, -0.3_wp, 0.2_wp, -0.3_wp, -0.36_wp, &
        -0.36_wp, -0.36_wp, -0.04_wp, 0.3_wp, 0.12_wp, -0.1_wp, -0.32_wp, -0.24_wp, &
        0.2_wp, 0.24_wp, 0.2_wp, 0.2_wp, -0.2_wp, -0.2_wp, -0.2_wp, -0.2_wp, &
        -0.2_wp, 0.2_wp, 0.2_wp, 0.2_wp, -0.2_wp, 0.2_wp, 0.2_wp, 0.2_wp, &
        0.2_wp, -0.2_wp, -0.2_wp, 0.0_wp, 0.0_wp, -0.2_wp, -0.2_wp, -0.2_wp, &
        0.2_wp, -0.2_wp, 0.2_wp, 0.2_wp, -0.2_wp, -0.2_wp, -0.2_wp, 0.2_wp, &
        0.2_wp, 0.2_wp, 0.2_wp, 0.2_wp, -0.2_wp, 0.2_wp, -0.2_wp, 0.28_wp, &
        0.28_wp, 0.28_wp, 0.28_wp, 0.28_wp, 0.28_wp, -0.28_wp, 0.28_wp, 0.12_wp, &
        0.0_wp, 0.24_wp, 0.16_wp, -0.2_wp, 0.16_wp, -0.2_wp, 0.16_wp, -0.2_wp, &
        0.16_wp, 0.2_wp, -0.16_wp, 0.2_wp, 0.16_wp, 0.2_wp, -0.16_wp, 0.2_wp, &
        -0.16_wp, 0.2_wp, -0.16_wp, 0.2_wp, 0.16_wp, -0.2_wp, 0.16_wp, 0.2_wp, &
        0.16_wp, -0.2_wp, -0.16_wp, 0.2_wp, -0.16_wp, -0.2_wp, -0.16_wp, 0.2_wp, &
        0.16_wp, 0.2_wp, 0.16_wp, -0.2_wp, 0.16_wp, -0.2_wp, 0.16_wp, 0.2_wp, &
        0.16_wp, 0.2_wp, 0.16_wp, 0.2_wp, -0.16_wp, -0.2_wp, 0.16_wp, 0.2_wp, &
        -0.16_wp, 0.2_wp, 0.16_wp, 0.2_wp, -0.16_wp, -0.2_wp, 0.16_wp, -0.2_wp, &
        0.16_wp, -0.2_wp, -0.16_wp, -0.2_wp, 0.24_wp, -0.24_wp, -0.24_wp, 0.24_wp, &
        0.24_wp, 0.12_wp, 0.2_wp, 0.12_wp, 0.2_wp, -0.12_wp, -0.2_wp, 0.12_wp, &
        -0.2_wp, 0.12_wp, -0.2_wp, -0.12_wp, 0.2_wp, -0.12_wp, 0.2_wp, -0.12_wp, &
        -0.2_wp, 0.12_wp, 0.2_wp, 0.12_wp, 0.2_wp, 0.12_wp, -0.2_wp, -0.12_wp, &
        0.2_wp, 0.12_wp, -0.2_wp, -0.12_wp, 0.2_wp, 0.12_wp, 0.2_wp, 0.0_wp, &
        0.0_wp, -0.12_wp, 0.2_wp, -0.12_wp, 0.2_wp, 0.12_wp, -0.2_wp, -0.12_wp, &
        0.2_wp, 0.12_wp, 0.2_wp, 0.0_wp, -0.21_wp, -0.2_wp, 0.0_wp, 0.0_wp, &
        0.2_wp, -0.2_wp, -0.2_wp, -0.2_wp, 0.2_wp, -0.16_wp, -0.1_wp, 0.0_wp, &
        0.17_wp, 0.16_wp, 0.16_wp, 0.16_wp, 0.16_wp, -0.16_wp, 0.16_wp, 0.16_wp, &
        -0.16_wp, 0.16_wp, -0.16_wp, 0.16_wp, 0.12_wp, 0.1_wp, 0.12_wp, -0.1_wp, &
        -0.12_wp, 0.1_wp, -0.12_wp, 0.1_wp, 0.12_wp, -0.1_wp, -0.12_wp, 0.12_wp, &
        -0.12_wp, 0.12_wp, -0.12_wp, 0.12_wp, -0.12_wp, -0.12_wp, -0.12_wp, -0.12_wp, &
        -0.12_wp, -0.12_wp, -0.12_wp, 0.12_wp, 0.12_wp, 0.12_wp, 0.12_wp, -0.12_wp, &
        -0.12_wp, 0.12_wp, 0.12_wp, 0.12_wp, -0.12_wp, 0.12_wp, -0.12_wp, -0.12_wp, &
        -0.12_wp, 0.12_wp, -0.12_wp, -0.12_wp, 0.12_wp, 0.0_wp, 0.11_wp, 0.11_wp, &
        -122.67_wp, 164.7_wp, 203.78_wp, 273.5_wp, 3.58_wp, 2.74_wp, 6.18_wp, -4.56_wp, &
        0.0_wp, -0.04_wp, 0.0_wp, -0.07_wp, 57.44_wp, -77.1_wp, 95.82_wp, 128.6_wp, &
        -1.77_wp, -1.28_wp, 2.85_wp, -2.14_wp, 82.14_wp, 89.5_wp, 0.0_wp, 0.0_wp, &
        2.0_wp, -1.84_wp, -0.04_wp, 47.73_wp, -64.1_wp, 23.79_wp, 31.9_wp, -1.45_wp, &
        -1.07_wp, 0.69_wp, -0.53_wp, -46.38_wp, 50.5_wp, 0.0_wp, 0.0_wp, 1.13_wp, &
        1.04_wp, 0.02_wp, -18.38_wp, 0.0_wp, 63.8_wp, 0.0_wp, 0.0_wp, 0.41_wp, &
        0.0_wp, -1.43_wp, 59.07_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, -1.32_wp, &
        57.28_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, -1.28_wp, -48.65_wp, 0.0_wp, &
        -1.15_wp, 0.0_wp, 0.0_wp, 1.09_wp, 0.0_wp, 0.03_wp, -18.3_wp, 24.6_wp, &
        -17.3_wp, -23.2_wp, 0.56_wp, 0.41_wp, -0.51_wp, 0.39_wp, -16.91_wp, 26.9_wp, &
        8.43_wp, 13.3_wp, 0.6_wp, 0.38_wp, 0.31_wp, -0.19_wp, 1.23_wp, -1.7_wp, &
        -19.13_wp, -25.7_wp, -0.03_wp, -0.03_wp, -0.58_wp, 0.43_wp, -0.72_wp, 0.9_wp, &
        -17.34_wp, -23.3_wp, 0.03_wp, 0.02_wp, -0.52_wp, 0.39_wp, -19.49_wp, -21.3_wp, &
        0.0_wp, 0.0_wp, -0.48_wp, 0.44_wp, 0.01_wp, 20.57_wp, -20.1_wp, 0.64_wp, &
        0.7_wp, -0.45_wp, -0.46_wp, 0.0_wp, -0.01_wp, 4.89_wp, 5.9_wp, -16.55_wp, &
        19.9_wp, 0.14_wp, -0.11_wp, 0.44_wp, 0.37_wp, 18.22_wp, 19.8_wp, 0.0_wp, &
        0.0_wp, 0.44_wp, -0.41_wp, -0.01_wp, 4.89_wp, -5.3_wp, -16.51_wp, -18.0_wp, &
        -0.11_wp, -0.11_wp, -0.41_wp, 0.37_wp, -17.86_wp, 0.0_wp, 17.1_wp, 0.0_wp, &
        0.0_wp, 0.4_wp, 0.0_wp, -0.38_wp, 0.32_wp, 0.0_wp, 24.42_wp, 0.0_wp, &
        0.0_wp, -0.01_wp, 0.0_wp, -0.55_wp, -23.79_wp, 0.0_wp, 0.0_wp, 0.0_wp, &
        0.0_wp, 0.53_wp, 14.72_wp, -16.0_wp, -0.32_wp, 0.0_wp, -0.36_wp, -0.33_wp, &
        -0.01_wp, 0.01_wp, 3.34_wp, -4.5_wp, 11.86_wp, 15.9_wp, -0.11_wp, -0.07_wp, &
        0.35_wp, -0.27_wp, -3.26_wp, 4.4_wp, 11.62_wp, 15.6_wp, 0.09_wp, 0.07_wp, &
        0.35_wp, -0.26_wp, -19.53_wp, 0.0_wp, 5.09_wp, 0.0_wp, 0.0_wp, 0.44_wp, &
        0.0_wp, -0.11_wp, -13.48_wp, 14.7_wp, 0.0_wp, 0.0_wp, 0.33_wp, 0.3_wp, &
        0.01_wp, 10.86_wp, -14.6_wp, 3.18_wp, 4.3_wp, -0.33_wp, -0.24_wp, 0.09_wp, &
        -0.07_wp, -11.3_wp, -15.1_wp, 0.0_wp, 0.0_wp, -0.34_wp, 0.25_wp, 0.01_wp, &
        2.03_wp, -2.7_wp, 10.82_wp, 14.5_wp, -0.07_wp, -0.05_wp, 0.32_wp, -0.24_wp, &
        17.46_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, -0.39_wp, 16.43_wp, 0.0_wp, &
        0.52_wp, 0.0_wp, 0.0_wp, -0.37_wp, 0.0_wp, -0.01_wp, 9.35_wp, 0.0_wp, &
        13.29_wp, 0.0_wp, 0.0_wp, -0.21_wp, 0.0_wp, -0.3_wp, -10.42_wp, 11.4_wp, &
        0.0_wp, 0.0_wp, 0.25_wp, 0.23_wp, 0.01_wp, 0.44_wp, 0.5_wp, -10.38_wp, &
        11.3_wp, 0.02_wp, -0.01_wp, 0.25_wp, 0.23_wp, -14.64_wp, 0.0_wp, 0.0_wp, &
        0.0_wp, 0.0_wp, 0.33_wp, 0.56_wp, 0.8_wp, -8.67_wp, 11.7_wp, 0.02_wp, &
        -0.01_wp, 0.26_wp, 0.19_wp, 13.88_wp, 0.0_wp, -2.47_wp, 0.0_wp, 0.0_wp, &
        -0.31_wp, 0.0_wp, 0.06_wp, -1.99_wp, 2.7_wp, 7.72_wp, 10.3_wp, 0.06_wp, &
        0.04_wp, 0.23_wp, -0.17_wp, -0.2_wp, 0.0_wp, 13.05_wp, 0.0_wp, 0.0_wp, &
        0.0_wp, 0.0_wp, -0.29_wp, 6.92_wp, -9.3_wp, 3.34_wp, 4.5_wp, -0.21_wp, &
        -0.15_wp, 0.1_wp, -0.07_wp, -6.6_wp, 0.0_wp, 10.7_wp, 0.0_wp, 0.0_wp, &
        0.15_wp, 0.0_wp, -0.24_wp, -8.04_wp, -8.7_wp, 0.0_wp, 0.0_wp, -0.19_wp, &
        0.18_wp, -10.58_wp, 0.0_wp, -3.1_wp, 0.0_wp, 0.0_wp, 0.24_wp, 0.0_wp, &
        0.07_wp, -7.32_wp, 8.0_wp, -0.12_wp, -0.1_wp, 0.18_wp, 0.16_wp, 1.63_wp, &
        1.7_wp, 6.96_wp, -7.6_wp, 0.03_wp, -0.04_wp, -0.17_wp, -0.16_wp, -3.62_wp, &
        0.0_wp, 9.86_wp, 0.0_wp, 0.0_wp, 0.08_wp, 0.0_wp, -0.22_wp, 0.2_wp, &
        -0.2_wp, -6.88_wp, -7.5_wp, 0.0_wp, 0.0_wp, -0.17_wp, 0.15_wp, -8.99_wp, &
        0.0_wp, 4.02_wp, 0.0_wp, 0.0_wp, 0.2_wp, 0.0_wp, -0.09_wp, -1.07_wp, &
        1.4_wp, -5.69_wp, -7.7_wp, 0.03_wp, 0.02_wp, -0.17_wp, 0.13_wp, 6.48_wp, &
        -7.2_wp, -0.48_wp, -0.5_wp, -0.16_wp, -0.14_wp, -0.01_wp, 0.01_wp, 5.57_wp, &
        -7.5_wp, 1.07_wp, 1.4_wp, -0.17_wp, -0.12_wp, 0.03_wp, -0.02_wp, 8.71_wp, &
        0.0_wp, 3.54_wp, 0.0_wp, 0.0_wp, -0.19_wp, 0.0_wp, -0.08_wp, 0.4_wp, &
        0.0_wp, 9.27_wp, 0.0_wp, 0.0_wp, -0.01_wp, 0.0_wp, -0.21_wp, -6.13_wp, &
        6.7_wp, -1.19_wp, -1.3_wp, 0.15_wp, 0.14_wp, -0.03_wp, 0.03_wp, 5.21_wp, &
        -5.7_wp, -2.51_wp, -2.6_wp, -0.13_wp, -0.12_wp, -0.06_wp, 0.06_wp, 5.69_wp, &
        -6.2_wp, -0.12_wp, -0.1_wp, -0.14_wp, -0.13_wp, -0.01_wp, 2.03_wp, -2.7_wp, &
        4.53_wp, 6.1_wp, -0.06_wp, -0.05_wp, 0.14_wp, -0.1_wp, 5.01_wp, 5.5_wp, &
        -2.51_wp, 2.7_wp, 0.12_wp, -0.11_wp, 0.06_wp, 0.06_wp, -1.91_wp, 2.6_wp, &
        -4.38_wp, -5.9_wp, 0.06_wp, 0.04_wp, -0.13_wp, 0.1_wp, 4.65_wp, -6.3_wp, &
        0.0_wp, 0.0_wp, -0.14_wp, -0.1_wp, -5.29_wp, 5.7_wp, 0.0_wp, 0.0_wp, &
        0.13_wp, 0.12_wp, -2.23_wp, -4.0_wp, -4.65_wp, 4.2_wp, -0.09_wp, 0.05_wp, &
        0.1_wp, 0.1_wp, -4.53_wp, 6.1_wp, 0.0_wp, 0.0_wp, 0.14_wp, 0.1_wp, &
        2.47_wp, 2.7_wp, -4.46_wp, 4.9_wp, 0.06_wp, -0.06_wp, 0.11_wp, 0.1_wp, &
        -5.05_wp, 5.5_wp, 0.84_wp, 0.9_wp, 0.12_wp, 0.11_wp, 0.02_wp, -0.02_wp, &
        4.97_wp, -5.4_wp, -1.71_wp, 0.0_wp, -0.12_wp, -0.11_wp, 0.0_wp, 0.04_wp, &
        -0.99_wp, -1.3_wp, 4.22_wp, -5.7_wp, -0.03_wp, 0.02_wp, -0.13_wp, -0.09_wp, &
        0.99_wp, 1.4_wp, 4.22_wp, -5.6_wp, 0.03_wp, -0.02_wp, -0.13_wp, -0.09_wp, &
        -4.69_wp, -5.2_wp, 0.0_wp, 0.0_wp, -0.12_wp, 0.1_wp, -3.42_wp, 0.0_wp, &
        6.09_wp, 0.0_wp, 0.0_wp, 0.08_wp, 0.0_wp, -0.14_wp, -4.65_wp, -5.1_wp, &
        0.0_wp, 0.0_wp, -0.11_wp, 0.1_wp, 0.0_wp, 0.0_wp, -4.53_wp, -5.0_wp, &
        0.0_wp, 0.0_wp, -0.11_wp, 0.1_wp, -2.43_wp, -2.7_wp, -3.82_wp, 4.2_wp, &
        -0.06_wp, 0.05_wp, 0.1_wp, 0.09_wp, 0.0_wp, 0.0_wp, -4.53_wp, 4.9_wp, &
        0.0_wp, 0.0_wp, 0.11_wp, 0.1_wp, -4.49_wp, -4.9_wp, 0.0_wp, 0.0_wp, &
        -0.11_wp, 0.1_wp, 2.67_wp, -2.9_wp, -3.62_wp, -3.9_wp, -0.06_wp, -0.06_wp, &
        -0.09_wp, 0.08_wp, 3.94_wp, -5.3_wp, 0.0_wp, 0.0_wp, -0.12_wp, -3.38_wp, &
        3.7_wp, -2.78_wp, -3.1_wp, 0.08_wp, 0.08_wp, -0.07_wp, 0.06_wp, 3.18_wp, &
        -3.5_wp, -2.82_wp, -3.1_wp, -0.08_wp, -0.07_wp, -0.07_wp, 0.06_wp, -5.77_wp, &
        0.0_wp, 1.87_wp, 0.0_wp, 0.0_wp, 0.13_wp, 0.0_wp, -0.04_wp, 3.54_wp, &
        -4.8_wp, -0.64_wp, -0.9_wp, -0.11_wp, 0.0_wp, -0.02_wp, -3.5_wp, -4.7_wp, &
        0.68_wp, -0.9_wp, -0.11_wp, 0.0_wp, -0.02_wp, 5.49_wp, 0.0_wp, 0.0_wp, &
        0.0_wp, 0.0_wp, -0.12_wp, 1.83_wp, -2.5_wp, 2.63_wp, 3.5_wp, -0.06_wp, &
        0.0_wp, 0.08_wp, 3.02_wp, -4.1_wp, 0.68_wp, 0.9_wp, -0.09_wp, 0.0_wp, &
        0.02_wp, 0.0_wp, 0.0_wp, 5.21_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, &
        -0.12_wp, -3.54_wp, 3.8_wp, 2.7_wp, 3.6_wp, -1.35_wp, 1.8_wp, 0.08_wp, &
        0.0_wp, 0.04_wp, -2.9_wp, 3.9_wp, 0.68_wp, 0.9_wp, 0.09_wp, 0.0_wp, &
        0.02_wp, 0.8_wp, -1.1_wp, -2.78_wp, -3.7_wp, -0.02_wp, 0.0_wp, -0.08_wp, &
        4.1_wp, 0.0_wp, -2.39_wp, 0.0_wp, 0.0_wp, -0.09_wp, 0.0_wp, 0.05_wp, &
        -1.59_wp, 2.1_wp, 2.27_wp, 3.0_wp, 0.05_wp, 0.0_wp, 0.07_wp, -2.63_wp, &
        3.5_wp, -0.48_wp, -0.6_wp, -2.94_wp, -3.2_wp, -2.94_wp, 3.2_wp, 2.27_wp, &
        -3.0_wp, -1.11_wp, -1.5_wp, -0.07_wp, 0.0_wp, -0.03_wp, -0.56_wp, -0.8_wp, &
        -2.35_wp, 3.1_wp, 0.0_wp, -0.6_wp, -3.42_wp, 1.9_wp, -0.12_wp, -0.1_wp, &
        2.63_wp, -2.9_wp, 2.51_wp, 2.8_wp, -0.64_wp, 0.7_wp, -0.48_wp, -0.6_wp, &
        2.19_wp, -2.9_wp, 0.24_wp, -0.3_wp, 2.15_wp, 2.9_wp, 2.15_wp, -2.9_wp, &
        0.52_wp, 0.7_wp, 2.07_wp, -2.8_wp, -3.1_wp, 0.0_wp, 1.79_wp, 0.0_wp, &
        0.0_wp, 0.07_wp, 0.0_wp, -0.04_wp, 0.88_wp, 0.0_wp, -3.46_wp, 2.11_wp, &
        2.8_wp, -0.36_wp, 0.5_wp, 3.54_wp, -0.2_wp, -3.5_wp, -1.39_wp, 1.5_wp, &
        -1.91_wp, -2.1_wp, -1.47_wp, 2.0_wp, 1.39_wp, 1.9_wp, 2.07_wp, -2.3_wp, &
        0.91_wp, 1.0_wp, 1.99_wp, -2.7_wp, 3.3_wp, 0.0_wp, 0.6_wp, -0.44_wp, &
        -0.7_wp, -1.95_wp, 2.6_wp, 2.15_wp, -2.4_wp, -0.6_wp, -0.7_wp, 3.3_wp, &
        0.84_wp, 0.0_wp, -3.1_wp, -3.1_wp, 0.0_wp, -0.72_wp, -0.32_wp, 0.4_wp, &
        -1.87_wp, -2.5_wp, 1.87_wp, -2.5_wp, 0.32_wp, 0.4_wp, -0.24_wp, 0.3_wp, &
        -1.87_wp, -2.5_wp, -0.24_wp, -0.3_wp, 1.87_wp, -2.5_wp, -2.7_wp, 0.0_wp, &
        1.55_wp, 2.03_wp, 2.2_wp, -2.98_wp, -1.99_wp, -2.2_wp, 0.12_wp, -0.1_wp, &
        -0.4_wp, 0.5_wp, 1.59_wp, 2.1_wp, 0.0_wp, 0.0_wp, -1.79_wp, 2.0_wp, &
        -1.03_wp, 1.4_wp, -1.15_wp, -1.6_wp, 0.32_wp, 0.5_wp, 1.39_wp, -1.9_wp, &
        2.35_wp, -1.27_wp, 1.7_wp, 0.6_wp, 0.8_wp, -0.32_wp, -0.4_wp, 1.35_wp, &
        -1.8_wp, 0.44_wp, 0.0_wp, 2.23_wp, -0.84_wp, 0.9_wp, -1.27_wp, -1.4_wp, &
        -1.47_wp, 1.6_wp, -0.28_wp, -0.3_wp, -0.28_wp, 0.4_wp, -1.27_wp, -1.7_wp, &
        0.28_wp, -0.4_wp, -1.43_wp, -1.5_wp, 0.0_wp, 0.0_wp, -1.27_wp, -1.7_wp, &
        2.11_wp, -0.32_wp, -0.4_wp, -1.23_wp, 1.6_wp, 1.19_wp, -1.3_wp, -0.72_wp, &
        -0.8_wp, 0.72_wp, -0.8_wp, -1.15_wp, -1.3_wp, -1.35_wp, -1.5_wp, -1.19_wp, &
        -1.6_wp, -0.12_wp, 0.2_wp, 1.79_wp, 0.0_wp, -0.88_wp, -0.28_wp, 0.4_wp, &
        1.11_wp, 1.5_wp, -1.83_wp, 0.0_wp, 0.56_wp, -0.12_wp, 0.1_wp, -1.27_wp, &
        -1.4_wp, 0.0_wp, 0.0_wp, 1.15_wp, 1.5_wp, -0.12_wp, 0.2_wp, 1.11_wp, &
        1.5_wp, 0.36_wp, -0.5_wp, -1.07_wp, -1.4_wp, -1.11_wp, 1.5_wp, 1.67_wp, &
        0.0_wp, 0.8_wp, -1.11_wp, 0.0_wp, 1.43_wp, 1.23_wp, -1.3_wp, -0.24_wp, &
        -1.19_wp, -1.3_wp, -0.24_wp, 0.2_wp, -0.44_wp, -0.9_wp, -0.95_wp, 1.1_wp, &
        1.07_wp, -1.4_wp, 1.15_wp, -1.3_wp, 1.03_wp, -1.1_wp, -0.56_wp, -0.6_wp, &
        -0.68_wp, 0.9_wp, -0.76_wp, -1.0_wp, -0.24_wp, -0.3_wp, 0.95_wp, -1.3_wp, &
        0.56_wp, 0.7_wp, 0.84_wp, -1.1_wp, -0.56_wp, 0.0_wp, -1.55_wp, 0.91_wp, &
        -1.3_wp, 0.28_wp, 0.3_wp, 0.16_wp, -0.2_wp, 0.95_wp, 1.3_wp, 0.4_wp, &
        -0.5_wp, -0.88_wp, -1.2_wp, 0.95_wp, -1.1_wp, -0.48_wp, -0.5_wp, 0.0_wp, &
        0.0_wp, -1.07_wp, 1.2_wp, 0.44_wp, -0.5_wp, 0.95_wp, 1.1_wp, 0.0_wp, &
        0.0_wp, 0.92_wp, -1.3_wp, 0.95_wp, 1.0_wp, -0.52_wp, 0.6_wp, 1.59_wp, &
        0.24_wp, -0.4_wp, 0.91_wp, 1.2_wp, 0.84_wp, -1.1_wp, -0.44_wp, -0.6_wp, &
        0.84_wp, 1.1_wp, -0.44_wp, 0.6_wp, -0.44_wp, 0.6_wp, -0.84_wp, -1.1_wp, &
        -0.8_wp, 0.0_wp, 1.35_wp, 0.76_wp, 0.2_wp, -0.91_wp, -1.0_wp, 0.2_wp, &
        -0.3_wp, -0.91_wp, -1.2_wp, -0.95_wp, 1.0_wp, -0.48_wp, -0.5_wp, 0.88_wp, &
        1.0_wp, 0.48_wp, -0.5_wp, -0.95_wp, -1.1_wp, 0.2_wp, -0.2_wp, -0.99_wp, &
        1.1_wp, -0.84_wp, 1.1_wp, -0.24_wp, -0.3_wp, 0.2_wp, -0.3_wp, 0.84_wp, &
        1.1_wp, -1.39_wp, 0.0_wp, -0.28_wp, -0.16_wp, 0.2_wp, 0.84_wp, 1.1_wp, &
        0.0_wp, 0.0_wp, 1.39_wp, 0.0_wp, 0.0_wp, -0.95_wp, 1.0_wp, 1.35_wp, &
        -0.99_wp, 0.0_wp, 0.88_wp, -0.52_wp, 0.0_wp, -1.19_wp, 0.2_wp, 0.2_wp, &
        0.76_wp, -1.0_wp, 0.0_wp, 0.0_wp, 0.76_wp, 1.0_wp, 0.0_wp, 0.0_wp, &
        0.76_wp, 1.0_wp, -0.76_wp, 1.0_wp, 0.0_wp, 0.0_wp, 1.23_wp, 0.76_wp, &
        0.8_wp, -0.32_wp, 0.4_wp, -0.72_wp, 0.8_wp, -0.4_wp, -0.4_wp, 0.0_wp, &
        0.0_wp, -0.8_wp, -0.9_wp, -0.68_wp, 0.9_wp, -0.16_wp, -0.2_wp, -0.16_wp, &
        -0.2_wp, 0.68_wp, -0.9_wp, -0.36_wp, 0.5_wp, -0.56_wp, -0.8_wp, 0.72_wp, &
        -0.9_wp, 0.44_wp, -0.6_wp, -0.48_wp, -0.7_wp, -0.16_wp, 0.0_wp, -1.11_wp, &
        0.32_wp, 0.0_wp, -1.07_wp, 0.6_wp, -0.8_wp, -0.28_wp, -0.4_wp, -0.64_wp, &
        0.0_wp, 0.91_wp, 1.11_wp, 0.64_wp, -0.9_wp, 0.76_wp, -0.8_wp, 0.0_wp, &
        0.0_wp, -0.76_wp, -0.8_wp, 1.03_wp, 0.0_wp, -0.36_wp, -0.64_wp, -0.7_wp, &
        0.36_wp, -0.4_wp, 1.07_wp, 0.36_wp, -0.5_wp, -0.52_wp, -0.7_wp, 0.6_wp, &
        0.0_wp, 0.88_wp, 0.95_wp, 0.0_wp, 0.48_wp, 0.16_wp, -0.2_wp, 0.6_wp, &
        0.8_wp, 0.16_wp, -0.2_wp, -0.6_wp, -0.8_wp, 0.0_wp, -1.0_wp, 0.12_wp, &
        0.2_wp, 0.16_wp, -0.2_wp, 0.68_wp, 0.7_wp, 0.59_wp, -0.8_wp, -0.99_wp, &
        -0.56_wp, -0.6_wp, 0.36_wp, -0.4_wp, -0.68_wp, -0.7_wp, -0.68_wp, -0.7_wp, &
        -0.36_wp, -0.5_wp, -0.44_wp, 0.6_wp, 0.64_wp, 0.7_wp, -0.12_wp, 0.1_wp, &
        -0.52_wp, 0.6_wp, 0.36_wp, 0.4_wp, 0.0_wp, 0.0_wp, 0.95_wp, -0.84_wp, &
        0.0_wp, 0.44_wp, 0.56_wp, 0.6_wp, 0.32_wp, -0.3_wp, 0.0_wp, 0.0_wp, &
        0.6_wp, 0.7_wp, 0.0_wp, 0.0_wp, 0.6_wp, 0.7_wp, -0.12_wp, -0.2_wp, &
        0.52_wp, -0.7_wp, 0.0_wp, 0.0_wp, 0.56_wp, 0.7_wp, -0.12_wp, 0.1_wp, &
        -0.52_wp, -0.7_wp, 0.0_wp, 0.0_wp, 0.88_wp, -0.76_wp, 0.0_wp, -0.44_wp, &
        0.0_wp, 0.0_wp, -0.52_wp, -0.7_wp, 0.52_wp, -0.7_wp, 0.36_wp, -0.4_wp, &
        -0.44_wp, -0.5_wp, 0.0_wp, 0.0_wp, 0.6_wp, 0.6_wp, 0.84_wp, 0.0_wp, &
        0.12_wp, -0.24_wp, 0.0_wp, 0.8_wp, -0.56_wp, 0.6_wp, -0.32_wp, -0.3_wp, &
        0.48_wp, -0.5_wp, 0.28_wp, -0.3_wp, -0.48_wp, -0.5_wp, 0.12_wp, 0.2_wp, &
        0.48_wp, -0.6_wp, 0.48_wp, 0.6_wp, -0.12_wp, 0.2_wp, 0.24_wp, 0.0_wp, &
        0.76_wp, -0.52_wp, -0.6_wp, -0.52_wp, 0.6_wp, 0.48_wp, -0.5_wp, -0.24_wp, &
        -0.3_wp, 0.12_wp, -0.1_wp, 0.48_wp, 0.6_wp, 0.52_wp, -0.2_wp, 0.36_wp, &
        0.4_wp, -0.44_wp, 0.5_wp, -0.24_wp, -0.3_wp, -0.48_wp, -0.6_wp, -0.44_wp, &
        -0.6_wp, -0.12_wp, 0.1_wp, 0.76_wp, 0.76_wp, 0.2_wp, -0.2_wp, 0.48_wp, &
        0.5_wp, 0.4_wp, -0.5_wp, -0.24_wp, -0.3_wp, 0.44_wp, -0.6_wp, 0.44_wp, &
        -0.6_wp, 0.36_wp, 0.0_wp, -0.64_wp, 0.72_wp, 0.0_wp, -0.12_wp, 0.0_wp, &
        -0.1_wp, -0.4_wp, -0.6_wp, -0.2_wp, -0.2_wp, -0.44_wp, 0.5_wp, -0.44_wp, &
        0.5_wp, 0.2_wp, 0.2_wp, -0.44_wp, -0.5_wp, 0.2_wp, -0.2_wp, -0.2_wp, &
        0.2_wp, -0.44_wp, -0.5_wp, 0.64_wp, 0.0_wp, 0.32_wp, -0.36_wp, 0.5_wp, &
        -0.2_wp, -0.3_wp, 0.12_wp, -0.1_wp, 0.48_wp, 0.5_wp, -0.12_wp, 0.3_wp, &
        -0.36_wp, -0.5_wp, 0.0_wp, 0.0_wp, 0.48_wp, 0.5_wp, -0.48_wp, 0.5_wp, &
        0.68_wp, 0.0_wp, -0.12_wp, 0.56_wp, -0.4_wp, 0.44_wp, -0.5_wp, -0.12_wp, &
        -0.1_wp, 0.24_wp, 0.3_wp, -0.4_wp, 0.4_wp, 0.64_wp, 0.0_wp, -0.24_wp, &
        0.64_wp, 0.0_wp, -0.2_wp, 0.0_wp, 0.0_wp, 0.44_wp, -0.5_wp, 0.44_wp, &
        0.5_wp, -0.12_wp, 0.2_wp, -0.36_wp, -0.5_wp, 0.12_wp, 0.0_wp, 0.64_wp, &
        -0.4_wp, 0.5_wp, 0.0_wp, 0.1_wp, 0.0_wp, 0.0_wp, -0.4_wp, 0.5_wp, &
        0.0_wp, 0.0_wp, -0.4_wp, -0.5_wp, 0.56_wp, 0.0_wp, 0.28_wp, 0.0_wp, &
        0.1_wp, 0.36_wp, 0.5_wp, 0.0_wp, -0.1_wp, 0.36_wp, -0.5_wp, 0.36_wp, &
        0.5_wp, 0.0_wp, -0.1_wp, 0.24_wp, -0.2_wp, -0.36_wp, -0.4_wp, 0.16_wp, &
        0.2_wp, 0.4_wp, -0.4_wp, 0.0_wp, 0.0_wp, -0.36_wp, -0.5_wp, -0.36_wp, &
        -0.5_wp, -0.32_wp, -0.5_wp, -0.12_wp, 0.1_wp, 0.2_wp, 0.2_wp, -0.36_wp, &
        0.4_wp, -0.6_wp, 0.6_wp, 0.28_wp, 0.0_wp, 0.52_wp, 0.12_wp, -0.1_wp, &
        0.4_wp, 0.4_wp, 0.0_wp, -0.5_wp, 0.2_wp, -0.2_wp, -0.32_wp, 0.4_wp, &
        0.16_wp, 0.2_wp, -0.16_wp, 0.2_wp, 0.32_wp, 0.4_wp, 0.56_wp, 0.0_wp, &
        -0.12_wp, 0.32_wp, -0.4_wp, -0.16_wp, -0.2_wp, 0.0_wp, 0.0_wp, 0.4_wp, &
        0.4_wp, -0.4_wp, -0.4_wp, -0.4_wp, 0.4_wp, -0.36_wp, 0.4_wp, 0.12_wp, &
        0.1_wp, 0.0_wp, 0.1_wp, 0.36_wp, 0.4_wp, 0.0_wp, -0.1_wp, 0.36_wp, &
        0.4_wp, -0.36_wp, 0.4_wp, 0.0_wp, 0.1_wp, 0.32_wp, 0.0_wp, 0.44_wp, &
        0.12_wp, 0.2_wp, 0.28_wp, -0.4_wp, 0.0_wp, 0.0_wp, 0.36_wp, 0.4_wp, &
        0.32_wp, -0.4_wp, -0.16_wp, 0.12_wp, 0.1_wp, 0.32_wp, -0.4_wp, 0.2_wp, &
        0.3_wp, -0.24_wp, 0.3_wp, 0.0_wp, 0.1_wp, 0.32_wp, 0.4_wp, 0.0_wp, &
        -0.1_wp, -0.32_wp, -0.4_wp, -0.32_wp, 0.4_wp, 0.0_wp, 0.1_wp, -0.52_wp, &
        -0.52_wp, 0.52_wp, 0.32_wp, -0.4_wp, 0.0_wp, 0.0_wp, 0.32_wp, 0.4_wp, &
        0.32_wp, -0.4_wp, 0.0_wp, 0.0_wp, -0.32_wp, -0.4_wp, -0.32_wp, 0.4_wp, &
        0.32_wp, 0.4_wp, 0.0_wp, 0.0_wp, 0.32_wp, 0.4_wp, 0.0_wp, 0.0_wp, &
        -0.32_wp, -0.4_wp, 0.0_wp, 0.0_wp, 0.32_wp, 0.4_wp, 0.16_wp, 0.2_wp, &
        0.32_wp, -0.3_wp, -0.16_wp, 0.0_wp, -0.48_wp, -0.2_wp, 0.2_wp, -0.28_wp, &
        -0.3_wp, 0.28_wp, -0.4_wp, 0.0_wp, 0.0_wp, 0.28_wp, -0.4_wp, 0.0_wp, &
        0.0_wp, 0.28_wp, -0.4_wp, 0.0_wp, 0.0_wp, -0.28_wp, -0.4_wp, 0.28_wp, &
        0.4_wp, -0.28_wp, -0.4_wp, -0.48_wp, -0.2_wp, 0.2_wp, 0.24_wp, 0.3_wp, &
        0.44_wp, 0.0_wp, 0.16_wp, 0.24_wp, 0.3_wp, 0.16_wp, -0.2_wp, 0.24_wp, &
        0.3_wp, -0.12_wp, 0.2_wp, 0.2_wp, 0.3_wp, -0.16_wp, 0.2_wp, 0.0_wp, &
        0.0_wp, 0.44_wp, -0.32_wp, 0.3_wp, 0.24_wp, 0.0_wp, -0.36_wp, 0.36_wp, &
        0.0_wp, 0.24_wp, 0.12_wp, -0.2_wp, 0.2_wp, 0.3_wp, -0.12_wp, 0.0_wp, &
        -0.28_wp, 0.3_wp, -0.24_wp, 0.3_wp, 0.12_wp, 0.1_wp, -0.28_wp, -0.3_wp, &
        -0.28_wp, 0.3_wp, 0.0_wp, 0.0_wp, -0.28_wp, -0.3_wp, 0.0_wp, 0.0_wp, &
        -0.28_wp, -0.3_wp, 0.0_wp, 0.0_wp, 0.28_wp, 0.3_wp, 0.0_wp, 0.0_wp, &
        -0.28_wp, -0.3_wp, -0.28_wp, 0.3_wp, 0.0_wp, 0.0_wp, -0.28_wp, -0.3_wp, &
        0.0_wp, 0.0_wp, 0.28_wp, 0.3_wp, 0.0_wp, 0.0_wp, -0.28_wp, 0.3_wp, &
        0.28_wp, -0.3_wp, -0.28_wp, 0.3_wp, 0.4_wp, 0.4_wp, -0.24_wp, 0.3_wp, &
        0.0_wp, -0.1_wp, 0.16_wp, 0.0_wp, 0.36_wp, -0.2_wp, 0.3_wp, -0.12_wp, &
        -0.1_wp, -0.24_wp, -0.3_wp, 0.0_wp, 0.0_wp, -0.24_wp, 0.3_wp, -0.24_wp, &
        0.3_wp, 0.0_wp, 0.0_wp, -0.24_wp, 0.3_wp, -0.24_wp, 0.3_wp, 0.24_wp, &
        -0.3_wp, 0.0_wp, 0.0_wp, 0.24_wp, -0.3_wp, 0.0_wp, 0.0_wp, 0.24_wp, &
        0.3_wp, 0.24_wp, -0.3_wp, 0.24_wp, 0.3_wp, -0.24_wp, 0.3_wp, -0.24_wp, &
        0.3_wp, -0.2_wp, 0.2_wp, -0.16_wp, -0.2_wp, 0.0_wp, 0.0_wp, -0.32_wp, &
        0.2_wp, 0.0_wp, 0.1_wp, 0.2_wp, -0.3_wp, 0.2_wp, -0.2_wp, 0.12_wp, &
        0.2_wp, -0.16_wp, 0.2_wp, 0.16_wp, 0.2_wp, 0.2_wp, 0.3_wp, 0.2_wp, &
        0.3_wp, 0.0_wp, 0.0_wp, -0.2_wp, 0.3_wp, 0.0_wp, 0.0_wp, 0.2_wp, &
        0.3_wp, -0.2_wp, -0.3_wp, -0.2_wp, -0.3_wp, 0.2_wp, -0.3_wp, 0.0_wp, &
        0.0_wp, 0.2_wp, 0.3_wp, 0.0_wp, 0.0_wp, 0.2_wp, 0.3_wp, 0.0_wp, &
        0.0_wp, 0.2_wp, 0.3_wp, 0.0_wp, 0.0_wp, 0.2_wp, 0.3_wp, 0.0_wp, &
        0.0_wp, 0.2_wp, -0.3_wp, 0.0_wp, 0.0_wp, -0.2_wp, -0.3_wp, 0.0_wp, &
        0.0_wp, -0.2_wp, 0.3_wp, 0.0_wp, 0.0_wp, -0.2_wp, 0.3_wp, 0.0_wp, &
        0.0_wp, 0.36_wp, 0.0_wp, 0.0_wp, 0.36_wp, 0.12_wp, 0.1_wp, -0.24_wp, &
        0.2_wp, 0.12_wp, -0.2_wp, -0.16_wp, -0.2_wp, -0.13_wp, 0.1_wp, 0.22_wp, &
        0.21_wp, 0.2_wp, 0.0_wp, -0.28_wp, 0.32_wp, 0.0_wp, -0.12_wp, -0.2_wp, &
        -0.2_wp, 0.12_wp, -0.1_wp, 0.12_wp, 0.1_wp, -0.2_wp, 0.2_wp, 0.0_wp, &
        0.0_wp, -0.32_wp, 0.32_wp, 0.0_wp, 0.0_wp, 0.32_wp, 0.32_wp, 0.0_wp, &
        0.0_wp, -0.24_wp, -0.2_wp, 0.24_wp, 0.2_wp, 0.2_wp, 0.0_wp, -0.24_wp, &
        0.0_wp, 0.0_wp, -0.24_wp, -0.2_wp, 0.0_wp, 0.0_wp, 0.24_wp, 0.2_wp, &
        -0.24_wp, -0.2_wp, 0.0_wp, 0.0_wp, -0.24_wp, 0.2_wp, 0.16_wp, -0.2_wp, &
        0.12_wp, 0.1_wp, 0.2_wp, 0.2_wp, 0.0_wp, -0.1_wp, -0.12_wp, 0.1_wp, &
        -0.16_wp, -0.2_wp, -0.12_wp, -0.1_wp, -0.16_wp, 0.2_wp, 0.2_wp, 0.2_wp, &
        0.0_wp, 0.0_wp, -0.2_wp, 0.2_wp, -0.2_wp, 0.2_wp, -0.2_wp, 0.2_wp, &
        -0.2_wp, 0.2_wp, 0.2_wp, -0.2_wp, -0.2_wp, -0.2_wp, 0.0_wp, 0.0_wp, &
        -0.2_wp, 0.2_wp, 0.2_wp, 0.0_wp, -0.2_wp, 0.0_wp, 0.0_wp, -0.2_wp, &
        0.2_wp, -0.2_wp, 0.2_wp, -0.2_wp, -0.2_wp, -0.2_wp, -0.2_wp, 0.0_wp, &
        0.0_wp, 0.2_wp, 0.2_wp, 0.2_wp, 0.2_wp, 0.12_wp, -0.2_wp, -0.12_wp, &
        -0.1_wp, 0.28_wp, -0.28_wp, 0.16_wp, -0.2_wp, 0.0_wp, -0.1_wp, 0.0_wp, &
        0.1_wp, -0.16_wp, 0.2_wp, 0.0_wp, -0.1_wp, -0.16_wp, -0.2_wp, 0.0_wp, &
        -0.1_wp, 0.16_wp, -0.2_wp, 0.16_wp, -0.2_wp, 0.0_wp, 0.0_wp, 0.16_wp, &
        0.2_wp, -0.16_wp, 0.2_wp, 0.0_wp, 0.0_wp, 0.16_wp, 0.2_wp, 0.16_wp, &
        -0.2_wp, 0.16_wp, -0.2_wp, -0.16_wp, 0.2_wp, 0.16_wp, -0.2_wp, 0.0_wp, &
        0.0_wp, 0.16_wp, 0.2_wp, 0.0_wp, 0.0_wp, 0.16_wp, 0.2_wp, 0.0_wp, &
        0.0_wp, -0.16_wp, -0.2_wp, 0.16_wp, -0.2_wp, -0.16_wp, -0.2_wp, 0.0_wp, &
        0.0_wp, -0.16_wp, -0.2_wp, 0.0_wp, 0.0_wp, -0.16_wp, 0.2_wp, 0.0_wp, &
        0.0_wp, 0.16_wp, -0.2_wp, 0.16_wp, 0.2_wp, 0.16_wp, 0.2_wp, 0.0_wp, &
        0.0_wp, -0.16_wp, -0.2_wp, 0.0_wp, 0.0_wp, -0.16_wp, -0.2_wp, 0.0_wp, &
        0.0_wp, 0.16_wp, 0.2_wp, 0.16_wp, 0.2_wp, 0.0_wp, 0.0_wp, 0.16_wp, &
        0.2_wp, 0.16_wp, -0.2_wp, 0.16_wp, 0.2_wp, 0.0_wp, 0.0_wp, -0.16_wp, &
        0.2_wp, 0.0_wp, 0.1_wp, 0.12_wp, -0.2_wp, 0.12_wp, -0.2_wp, 0.0_wp, &
        -0.1_wp, 0.0_wp, -0.1_wp, 0.12_wp, 0.2_wp, 0.0_wp, -0.1_wp, -0.12_wp, &
        0.2_wp, -0.15_wp, 0.2_wp, -0.24_wp, 0.24_wp, 0.0_wp, 0.0_wp, 0.24_wp, &
        0.24_wp, 0.12_wp, -0.2_wp, -0.12_wp, -0.2_wp, 0.0_wp, 0.0_wp, 0.12_wp, &
        0.2_wp, 0.12_wp, -0.2_wp, 0.12_wp, 0.2_wp, 0.12_wp, 0.2_wp, 0.12_wp, &
        0.2_wp, 0.12_wp, -0.2_wp, -0.12_wp, 0.2_wp, 0.0_wp, 0.0_wp, 0.12_wp, &
        0.2_wp, 0.12_wp, 0.0_wp, -0.2_wp, 0.0_wp, 0.0_wp, -0.12_wp, -0.2_wp, &
        0.12_wp, -0.2_wp, 0.0_wp, 0.0_wp, 0.12_wp, 0.2_wp, -0.12_wp, 0.2_wp, &
        -0.12_wp, 0.2_wp, 0.12_wp, -0.2_wp, 0.0_wp, 0.0_wp, 0.12_wp, 0.2_wp, &
        0.2_wp, 0.0_wp, 0.12_wp, 0.0_wp, 0.0_wp, -0.12_wp, 0.2_wp, 0.0_wp, &
        0.0_wp, -0.12_wp, -0.2_wp, 0.0_wp, 0.0_wp, -0.12_wp, -0.2_wp, -0.12_wp, &
        -0.2_wp, 0.0_wp, 0.0_wp, 0.12_wp, -0.2_wp, 0.12_wp, -0.2_wp, 0.12_wp, &
        0.2_wp, -0.12_wp, -0.2_wp, 0.0_wp, 0.0_wp, 0.12_wp, -0.2_wp, 0.12_wp, &
        -0.2_wp, 0.12_wp, 0.2_wp, 0.12_wp, 0.0_wp, 0.2_wp, -0.12_wp, -0.2_wp, &
        0.0_wp, 0.0_wp, 0.12_wp, 0.2_wp, -0.16_wp, 0.0_wp, 0.16_wp, -0.2_wp, &
        0.2_wp, 0.0_wp, 0.0_wp, -0.2_wp, 0.0_wp, 0.0_wp, -0.2_wp, 0.2_wp, &
        0.0_wp, 0.0_wp, 0.2_wp, 0.2_wp, -0.2_wp, 0.0_wp, 0.0_wp, -0.2_wp, &
        0.12_wp, 0.0_wp, -0.16_wp, 0.2_wp, 0.0_wp, 0.0_wp, 0.2_wp, 0.12_wp, &
        -0.1_wp, 0.0_wp, 0.1_wp, 0.16_wp, -0.16_wp, -0.16_wp, -0.16_wp, -0.16_wp, &
        -0.16_wp, 0.0_wp, 0.0_wp, -0.16_wp, 0.0_wp, 0.0_wp, -0.16_wp, -0.16_wp, &
        -0.16_wp, 0.0_wp, 0.0_wp, -0.16_wp, 0.0_wp, 0.0_wp, 0.16_wp, 0.0_wp, &
        0.0_wp, 0.16_wp, 0.0_wp, 0.0_wp, 0.16_wp, 0.16_wp, 0.0_wp, 0.0_wp, &
        -0.16_wp, 0.0_wp, 0.0_wp, -0.16_wp, -0.16_wp, 0.0_wp, 0.0_wp, 0.16_wp, &
        0.0_wp, 0.0_wp, -0.16_wp, -0.16_wp, 0.0_wp, 0.0_wp, -0.16_wp, -0.16_wp, &
        0.12_wp, 0.1_wp, 0.12_wp, -0.1_wp, 0.12_wp, 0.1_wp, 0.0_wp, 0.0_wp, &
        0.12_wp, 0.1_wp, -0.12_wp, 0.1_wp, 0.0_wp, 0.0_wp, 0.12_wp, 0.1_wp, &
        0.12_wp, -0.1_wp, 0.0_wp, 0.0_wp, -0.12_wp, -0.1_wp, 0.0_wp, 0.0_wp, &
        0.12_wp, 0.1_wp, 0.12_wp, 0.0_wp, 0.0_wp, 0.12_wp, 0.0_wp, 0.0_wp, &
        -0.12_wp, 0.0_wp, 0.0_wp, 0.12_wp, 0.12_wp, 0.12_wp, 0.12_wp, 0.12_wp, &
        0.0_wp, 0.0_wp, 0.12_wp, 0.0_wp, 0.0_wp, 0.12_wp, 0.12_wp, 0.0_wp, &
        0.0_wp, 0.12_wp, 0.0_wp, 0.0_wp, 0.12_wp, -0.12_wp, -0.12_wp, 0.12_wp, &
        0.12_wp, -0.12_wp, -0.12_wp, 0.0_wp, 0.0_wp, 0.12_wp, -0.12_wp, 0.12_wp, &
        0.12_wp, -0.12_wp, -0.12_wp, 0.0_wp, 0.0_wp, -0.12_wp, -0.12_wp, 0.0_wp, &
        0.0_wp, -0.12_wp, 0.12_wp, 0.0_wp, 0.0_wp, 0.12_wp, 0.0_wp, 0.0_wp, &
        0.12_wp, 0.0_wp, 0.0_wp, 0.12_wp, -0.12_wp, 0.0_wp, 0.0_wp, -0.12_wp, &
        0.12_wp, -0.12_wp, -0.12_wp, 0.12_wp, 0.0_wp, 0.0_wp, 0.12_wp, 0.12_wp, &
        0.12_wp, -0.12_wp, 0.0_wp, 0.0_wp, -0.12_wp, -0.12_wp, -0.12_wp, 0.0_wp, &
        0.0_wp, -0.12_wp, -0.12_wp, 0.0_wp, 0.0_wp, 0.12_wp, 0.12_wp, 0.0_wp, &
        0.0_wp, -0.12_wp, -0.12_wp, -0.12_wp, -0.12_wp, 0.12_wp, 0.0_wp, 0.0_wp, &
        0.12_wp, -0.12_wp, 0.0_wp, 0.0_wp, -0.12_wp, -0.12_wp, 0.0_wp, 0.0_wp, &
        0.12_wp, -0.12_wp, -0.12_wp, -0.12_wp, -0.12_wp, 0.12_wp, 0.12_wp, -0.12_wp, &
        -0.12_wp, 0.0_wp, 0.0_wp, -0.12_wp, 0.0_wp, 0.0_wp, -0.12_wp, 0.12_wp, &
        0.0_wp, 0.0_wp, 0.12_wp, 0.0_wp, 0.0_wp, -0.12_wp, -0.12_wp, 0.0_wp, &
        0.0_wp, -0.12_wp, -0.12_wp, 0.12_wp, 0.0_wp, 0.0_wp, 0.12_wp, 0.12_wp, &
        0.0_wp, 0.0_wp, 0.12_wp, 0.0_wp, 0.0_wp, 0.12_wp, 0.12_wp, 0.08_wp, &
        0.0_wp, 0.04_wp]
    !  Interval between fundamental date J2000.0 and given date (JC).
    t = ( ( date1-dj00 ) + date2 ) / djc
    !  Powers of T.
    w = 1.0_wp
    do jpt=0,maxpt
       pt(jpt) = w
       w = w*t
    end do
    !
    !  Luni-solar fundamental (Delaunay) arguments (IERS 2003)
    !
    !  Mean anomaly of the Moon.
    fa(1) = FAL03 ( t )
    !  Mean anomaly of the Sun.
    fa(2) = FALP03 ( t )
    !  Mean argument of the latitude of the Moon.
    fa(3) = FAF03 ( t )
    !  Mean elongation of the Moon from the Sun.
    fa(4) = FAD03 ( t )
    !  Mean longitude of the ascending node of the Moon.
    fa(5) = FAOM03 ( t )
    !  Planetary longitudes, Mercury through Neptune.
    fa(6)  = FAME03 ( t )
    fa(7)  = FAVE03 ( t )
    fa(8)  = FAE03 ( t )
    fa(9)  = FAMA03 ( t )
    fa(10) = FAJU03 ( t )
    fa(11) = FASA03 ( t )
    fa(12) = FAUR03 ( t )
    fa(13) = FANE03 ( t )
    !  General accumulated precession in longitude.
    fa(14) = FAPA03 ( t )
    !  --------------------------------------
    !  Polynomial part of precession-nutation
    !  --------------------------------------
    do jxy=0,1
       xypr(jxy) = 0.0_wp
       do j=maxpt,0,-1
          xypr(jxy) = xypr(jxy) + xyp(j,jxy)*pt(j)
       end do
    end do
    !  ----------------------------------
    !  Nutation periodic terms, planetary
    !  ----------------------------------
    !  Initialize totals in X and Y.
    do jxy=0,1
       xypl(jxy) = 0.0_wp
    end do
    !  Work backwards through the coefficients per frequency list.
    ialast = na
    do ifreq=nfpl,1,-1
       !  Obtain the argument functions.
       arg = 0.0_wp
       do i=1,14
          m = mfapl(i,ifreq)
          if ( m/=0 ) arg = arg + real(m,wp)*fa(i)
       end do
       sc(0) = sin(arg)
       sc(1) = cos(arg)
       !  Work backwards through the amplitudes at this frequency.
       ia = nc(ifreq+nfls)
       do i=ialast,ia,-1
          !  Coefficient number (0 = 1st).
          j = i-ia
          !  X or Y.
          jxy = jaxy(j)
          !  Sin or cos.
          jsc = jasc(j)
          !  Power of T.
          jpt = japt(j)
          !  Accumulate the component.
          xypl(jxy) = xypl(jxy) + a(i)*sc(jsc)*pt(jpt)
       end do
       ialast = ia-1
    end do
    !  -----------------------------------
    !  Nutation periodic terms, luni-solar
    !  -----------------------------------
    !  Initialize totals in X and Y.
    do jxy=0,1
       xyls(jxy) = 0.0_wp
    end do
    !  Continue working backwards through the number of coefficients list.
    do ifreq=nfls,1,-1
       !  Obtain the argument functions.
       arg = 0.0_wp
       do i=1,5
          m = mfals(i,ifreq)
          if ( m/=0 ) arg = arg + real(m,wp)*fa(i)
       end do
       sc(0) = sin(arg)
       sc(1) = cos(arg)
       !  Work backwards through the amplitudes at this frequency.
       ia = nc(ifreq)
       do i=ialast,ia,-1
          !  Coefficient number (0 = 1st).
          j = i-ia
          !  X or Y.
          jxy = jaxy(j)
          !  Sin or cos.
          jsc = jasc(j)
          !  Power of T.
          jpt = japt(j)
          !  Accumulate the component.
          xyls(jxy) = xyls(jxy) + a(i)*sc(jsc)*pt(jpt)
       end do
       ialast = ia-1
    end do
    !  -------
    !  Results
    !  -------
    !  CIP unit vector components.
    x = das2r * ( xypr(0) + ( xyls(0) + xypl(0) )/1.0e6_wp )
    y = das2r * ( xypr(1) + ( xyls(1) + xypl(1) )/1.0e6_wp )
    end subroutine XY06
Call graph
xy06 calls faom03, falp03, fad03, fama03, faf03, faju03, faur03, fane03, fae03, fave03, fame03, fapa03, fal03, fasa03