XYS00A – astro-fortran
XYS00A Subroutine
12 statements
Source File
public subroutine XYS00A(date1, date2, x, y, s)
For a given TT date, compute the X,Y coordinates of the Celestial Intermediate Pole and the CIO locator s, using the IAU 2000A precession-nutation model.
Status: support routine.
Notes
The TT date DATE1+DATE2 is a Julian Date, apportioned in any convenient way between the two arguments. For example, JD(TT)=2450123.7 could be expressed in any of these ways, among others:
    DATE1          DATE2
 2450123.7D0        0D0        (JD method)
  2451545D0      -1421.3D0     (J2000 method)
 2400000.5D0     50123.2D0     (MJD method)
 2450123.5D0       0.2D0       (date & time method)
The JD method is the most natural and convenient to use in cases where the loss of several decimal digits of resolution is acceptable. The J2000 method is best matched to the way the argument is handled internally and will deliver the optimum resolution. The MJD method and the date & time methods are both good compromises between resolution and convenience.
The Celestial Intermediate Pole coordinates are the x,y components of the unit vector in the Geocentric Celestial Reference System.
The CIO locator s (in radians) positions the Celestial Intermediate Origin on the equator of the CIP.
A faster, but slightly less accurate result (about 1 mas for X,Y), can be obtained by using instead the XYS00B routine.
Reference
McCarthy, D. D., Petit, G. (eds.), IERS Conventions (2003), IERS Technical Note No. 32, BKG (2004)
History
IAU SOFA revision: 2006 November 13
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: date1
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(in) :: date2
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(out) :: x
Celestial Intermediate Pole (Note 2)
real(kind=wp), intent(out) :: y
Celestial Intermediate Pole (Note 2)
real(kind=wp), intent(out) :: s
the CIO locator s (Note 2)
Calls
Contents
Source Code
XYS00A
Source Code
    subroutine XYS00A ( date1, date2, x, y, s )
    implicit none
    real(wp),intent(in) :: date1 !! TT as a 2-part Julian Date (Note 1)
    real(wp),intent(in) :: date2 !! TT as a 2-part Julian Date (Note 1)
    real(wp),intent(out) :: x !! Celestial Intermediate Pole (Note 2)
    real(wp),intent(out) :: y !! Celestial Intermediate Pole (Note 2)
    real(wp),intent(out) :: s !! the CIO locator s (Note 2)
    real(wp) :: rbpn(3,3)
    !  Form the bias-precession-nutation matrix, IAU 2000A.
    call PNM00A ( date1, date2, rbpn )
    !  Extract X,Y.
    call BPN2XY ( rbpn, x, y )
    !  Obtain s.
    s = S00 ( date1, date2, x, y )
    end subroutine XYS00A
Call graph
xys00a calls pnm00a, s00, bpn2xy
pnm00a calls pn00a
s00 calls faom03, falp03, fae03, fal03, faf03, fad03, fave03, fapa03
pn00a calls nut00a, pn00
nut00a calls faom03, fae03, fal03, faf03, fave03, fapa03, fame03, fasa03, faju03, fama03, faur03
pn00 calls obl80, numat, bp00, pr00, rxr
numat calls rx, ir, rz
bp00 calls pr00, rxr, rx, ry, ir, rz, bi00