XYS00B – astro-fortran
XYS00B Subroutine
12 statements
Source File
public subroutine XYS00B(date1, date2, x, y, s)
For a given TT date, compute the X,Y coordinates of the Celestial Intermediate Pole and the CIO locator s, using the IAU 2000B precession-nutation model.
Status: support routine.
Notes
The TT date DATE1+DATE2 is a Julian Date, apportioned in any convenient way between the two arguments. For example, JD(TT)=2450123.7 could be expressed in any of these ways, among others:
    DATE1          DATE2
 2450123.7D0        0D0        (JD method)
  2451545D0      -1421.3D0     (J2000 method)
 2400000.5D0     50123.2D0     (MJD method)
 2450123.5D0       0.2D0       (date & time method)
The JD method is the most natural and convenient to use in cases where the loss of several decimal digits of resolution is acceptable. The J2000 method is best matched to the way the argument is handled internally and will deliver the optimum resolution. The MJD method and the date & time methods are both good compromises between resolution and convenience.
The Celestial Intermediate Pole coordinates are the x,y components of the unit vector in the Geocentric Celestial Reference System.
The CIO locator s (in radians) positions the Celestial Intermediate Origin on the equator of the CIP.
The present routine is faster, but slightly less accurate (about 1 mas in X,Y), than the XYS00A routine.
Reference
McCarthy, D. D., Petit, G. (eds.), IERS Conventions (2003), IERS Technical Note No. 32, BKG (2004)
History
IAU SOFA revision: 2006 November 13
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: date1
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(in) :: date2
TT as a 2-part Julian Date (Note 1)
real(kind=wp), intent(out) :: x
Celestial Intermediate Pole (Note 2)
real(kind=wp), intent(out) :: y
Celestial Intermediate Pole (Note 2)
real(kind=wp), intent(out) :: s
the CIO locator s (Note 2)
Calls
Contents
Source Code
XYS00B
Source Code
    subroutine XYS00B ( date1, date2, x, y, s )
    implicit none
    real(wp),intent(in) :: date1 !! TT as a 2-part Julian Date (Note 1)
    real(wp),intent(in) :: date2 !! TT as a 2-part Julian Date (Note 1)
    real(wp),intent(out) :: x !! Celestial Intermediate Pole (Note 2)
    real(wp),intent(out) :: y !! Celestial Intermediate Pole (Note 2)
    real(wp),intent(out) :: s !! the CIO locator s (Note 2)
    real(wp) :: rbpn(3,3)
    !  Form the bias-precession-nutation matrix, IAU 2000A.
    call PNM00B ( date1, date2, rbpn )
    !  Extract X,Y.
    call BPN2XY ( rbpn, x, y )
    !  Obtain s.
    s = S00 ( date1, date2, x, y )
    end subroutine XYS00B
Call graph
xys00b calls s00, bpn2xy, pnm00b
s00 calls faom03, fad03, falp03, fae03, fal03, fapa03, faf03, fave03
pnm00b calls pn00b
pn00b calls pn00, nut00b
pn00 calls obl80, bp00, numat, rxr, pr00
bp00 calls rxr, pr00, bi00, rx, ir, ry, rz
numat calls rx, ir, rz