ZP – astro-fortran
ZP Subroutine
8 statements
Source File
public subroutine ZP(p)
Zero a p-vector.
Status: vector/matrix support routine.
History
IAU SOFA revision: 2000 November 25
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(out), dimension(3) :: p
p-vector
Called by
Contents
Source Code
ZP
Source Code
    subroutine ZP ( p )
    implicit none
    real(wp),dimension(3),intent(out) :: p !! p-vector
    integer :: i
    do i=1,3
       p(i) = 0.0_wp
    end do
    end subroutine ZP
Call graph
zpv calls zp
gd2gc calls zp
starpv calls zp
aticqn calls zp
pn calls zp
p2pv calls zp
aticq calls zp
pvtob calls gd2gc
fk52h calls starpv
starpm calls starpv
atic13 calls aticq, apci13
apcg calls zpv, apcs
h2fk5 calls starpv
apcs calls pn
atoc13 calls aticq, apco13
pmsafe calls starpm
apio calls pvtob
apco calls pvtob, apcs
apci calls apcg
apcg13 calls apcg
apcs13 calls apcs
apio13 calls apio
apci13 calls apci
apco13 calls apco
atio13 calls apio13
atoi13 calls apio13
atci13 calls apci13
atco13 calls apco13